### ISSUE TITLE
Please update release 2.3.0 on pypi

### ISSUE THREAD

**Issue by robertpro** [graphql-python/graphene#1000]

**Comment by dvndrsn** [comment]
Hi @robertpro, we are not currently planning a 2.3.0 release for Graphene.

Thanks to efforts from a bunch of folks, we have recently released 2.1.5. The next major release will be 3.0.0 (date TBD).

https://pypi.org/project/graphene/#history

I'm going to mark this as resolved, but feel free to follow up!

**Comment by robertpro** [comment]
Hi @dvndrsn, I am sorry I meant to open this issue on https://github.com/graphql-python/graphene-django
