### ISSUE TITLE
Create branch for Read The Docs-themed documentation.

### ISSUE THREAD

**Issue by changeling** [graphql-python/graphene#1001]
Please create two branches to be used for un-themed documentation for Read The Docs presentation.

- Based off `next/master`
- - Requested branch name: `read-the-docs-theme-3`
- Based off `master`
- - Requested branch name: `read-the-docs-theme-2`

This will allow us to have the following:

For ecosystem site integration:
https://changeling-graphene-themed.readthedocs.io/en/latest/

And generic Read The Docs:
https://changeling-graphene-unthemed.readthedocs.io/en/latest/

**Comment by jkimbo** [comment]
Branches created: 
https://github.com/graphql-python/graphene/tree/read-the-docs-theme-2
https://github.com/graphql-python/graphene/tree/read-the-docs-theme-3
