### ISSUE TITLE
Version conflict `aniso8601`

### ISSUE THREAD

**Issue by szakitibi** [graphql-python/graphene#1008]
While built out  my site with current latest `graphene = 2.1.5` version, I got the following version conflict:

```
...
Got relativetimebuilder 2.0.0.
Version and requirements information containing aniso8601:
  Requirement of graphene: aniso8601<=6.0.*,>=3
  Requirement of aniso8601<=6.0.*,>=3: relativetimebuilder>=0.2.0
  Requirement of relativetimebuilder>=0.2.0: aniso8601<8.0.0,>=7.0.0
While:
  Updating test.
Error: There is a version conflict.
We already have: aniso8601 5.1.0
but relativetimebuilder 2.0.0 requires 'aniso8601<8.0.0,>=7.0.0'.
```

Seems like I got `aniso8601` version `5.1.0` which still has the [circular dependency issue](https://bitbucket.org/nielsenb/aniso8601/issues/23/circular-dependency-on-relativetimebuilder).

**Note:**
For me pinning version to `aniso8601 = 6.0.0` and `relatvietimebuilder = 1.0.0` solved it. As you can see in the above traceback,  `relativetimebuilder` already has version is `2.0.0`, which requires `aniso8601 >= 7.0.0`, that is why both package had to be pinned.

**Comment by eelkevdbos** [comment]
Might be related to this commit: https://github.com/graphql-python/graphene/commit/431e93cd68b9f720be1cb1165f0a202a6388ed74

**Comment by Keats** [comment]
You would still get a conflict even with that commit since `relativetimebuilder` is asking for `>=7.0.0` and graphene wants `<6`. I've made https://github.com/graphql-python/graphene/pull/1009 to relax a bit that version.

**Comment by dwsutherland** [comment]
Yes this is an internal conflict of `2.1.5` ... clean env produces this with `pip install 'graphene==2.1.5'`

**Comment by jkimbo** [comment]
v2.1.6 is ready to be released and it contains a fix for this: https://github.com/graphql-python/graphene/pull/1005

@eelkevdbos that commit actually *fixes* the error as described in the issue.

**Comment by elcho** [comment]
Pinning ```relativetimebuilder``` to a version ```< 2.0.0`` resolved the issue for me. Since the issue is only because ``` relativetimebuilder v2.0.0``` requires ```aniso8610 >=7.0.0``` but a version ```<=2.0.0``` resolves fine with ```aniso8610 <=7.0.0```, ```graphene```'s requirement of ```aniso8610 <=6.0.0`` is satisfied.

**Comment by eelkevdbos** [comment]
@jkimbo sorry, I meant to say that, but reading it again I see it can be interpreted both ways

**Comment by jkimbo** [comment]
v2.1.6 has been released to PyPi which fixes this issue: https://pypi.org/project/graphene/2.1.6/

Release notes: https://github.com/graphql-python/graphene/releases/tag/v2.1.6
