### ISSUE TITLE
Calculated fields

### ISSUE THREAD

**Issue by sgtsquiggs** [graphql-python/graphene#101]
How do we access calculated fields? In a serializer I would do something like
```python
class ArtworkSerializer(serializers.ModelSerializer):
    url = serializers.URLField(source='get_absolute_url')

    class Meta:
        model = Artwork
        fields = ('id', 'title', 'url')
```

I assume I need to specify this somehow in `class ArtworkNode(DjangoNode):` but I've been unable to discover how.

**Comment by sgtsquiggs** [comment]
Figured it out.

```python
class ArtworkNode(DjangoNode):
    url = graphene.String()

    class Meta:
        model = Artwork
        filter_fields = ['id', 'title']

    def resolve_url(self, args, info):
        return self.instance.url
```


Is it possible to retrieve via `pk`?

**Comment by syrusakbary** [comment]
Great! However I'm going to add the source option to fields! It makes it much more pleasant to develop!

So you can do something like

```python
class ArtworkNode(DjangoNode):
    url = graphene.String(source='get_absolute_url')

    class Meta:
        model = Artwork
        filter_fields = ['id', 'title']
```

**Comment by syrusakbary** [comment]
@sgtsquiggs You can retrieve an Artwork Node doing:
```
{
  node(id:"SOME_STRING") {
    id
  }
}
```

In this case `SOME_STRING` will be the value of `ArtworkNode.global_id(1)`.

**Comment by sgtsquiggs** [comment]
Is it possible to get a single item via a field other than id? for instance I have a `slug` field on Artwork and in my django endpoint I use Artwork.get_by_slug(slug).

`source=` would be perfect, I use it extensively in my serializers

**Comment by syrusakbary** [comment]
Sure. You can do is using arguments.

```python
class Query(graphene.ObjectType):
    artwork = graphene.Field(ArtworkNode, slug=graphene.String())
    
    def resolve_artwork(self, args, info):
        return Artwork.get_by_slug(args.get('slug', None))
```

Then you can query it with the following query:
```
{
  artwork(slug:"my_slug") {
    id
    title
  }
}
```
Hope it helps!

**Comment by paymog** [comment]
How do I resolve a django object along with an extra, calculated field like below during a query?

```python
class ProjectType(DjangoObjectType):
    class Meta:
        model = Project

    extra_field = graphene.String()


class Query(ObjectType):
    project = graphene.Field(ProjectType,
                             name=graphene.String())

    def resolve_project(self, info, name):

        if id is not None:
            return Project.objects.get(pk=id) # how do I populate `extra_field` here?


        return None
```

**Comment by fescobar** [comment]
@paymog 

Small example:

**Brand** model
```sh
class Brand(models.Model):
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.name
```

BrandNode
```sh
class BrandNode(DjangoObjectType):
    # extra field INT
    extra_field_real_id_plus_one = graphene.Int()

    def resolve_extra_field_real_id_plus_one(parent, info, **kwargs):
        value = parent.id + 1
        print(f'Real Id: {parent.id}')
        print(f'Id ++: {value}')
        return value

    class Meta:
        model = Brand
        filter_fields = {
            'name': ['icontains', 'exact']
        }
        interfaces = (relay.Node,)
```

`extra_field_real_id_plus_one ` is the extra field. You can get any value from the original model, exactly from the `parent` parameter. You can calculate or format whatever you want and just you need to return the value.
You can get the extra field calculated value in queries, mutations, etc.
