### ISSUE TITLE
How to work with elasticsearch

### ISSUE THREAD

**Issue by rjsnh1522** [graphql-python/graphene#1013]
Can you please tell me how can I connect and prepare a schema to work with elastic search which is having a very large json docuemnt.
I am not able to find any reference regarding that.

**Comment by jkimbo** [comment]
@rjsnh1522 there is nothing special about working with elastic search in Graphene, you would use it just like you would implement any other resolver. You can find out more about defining your resolvers here: https://docs.graphene-python.org/en/latest/types/objecttypes/#resolvers

**Comment by barseghyanartur** [comment]
@jkimbo:

You could give [graphene-elastic](https://graphene-elastic.readthedocs.io) a try.
