### ISSUE TITLE
Buggy example in quickstart document

### ISSUE THREAD

**Issue by shivam05011996** [graphql-python/graphene#1014]
The quick start document explains how to define scheme and to query the same. But it has described a buggy example - 
![Screenshot 2019-06-19 at 10 14 49 AM](https://user-images.githubusercontent.com/33828942/59737389-17d55380-927b-11e9-8952-f5c8af946b3a.png)

`query_with_argument` is not defined anywhere, hence errors while trying out graphene. 
I am getting a permission denied while performing git push.

![Screenshot 2019-06-19 at 10 21 38 AM](https://user-images.githubusercontent.com/33828942/59737647-122c3d80-927c-11e9-9087-3b6fd14d4532.png)

**Comment by jkimbo** [comment]
Ah good spot @shivam05011996 , `query_string_with_argument` should be `query_with_argument`. I've created a PR to fix it: https://github.com/graphql-python/graphene/pull/1015

Also if you would like to propose code changes in future you will need to fork the repo and create a pull request. You can read more about how to do that here: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by shivam05011996** [comment]
@jkimbo Thank You. 
Please go ahead and close the issue, once #1015 is merged.

**Comment by jkimbo** [comment]
All fixed. Thanks @shivam05011996
