### ISSUE TITLE
Invite to slack

### ISSUE THREAD

**Issue by cherls** [graphql-python/graphene#1016]
Hi, can I get an invite to https://graphenetools.slack.com please? My email is charleshche@gmail.com

**Comment by jkimbo** [comment]
Invite sent

**Comment by juancarlosjr97** [comment]
Hello, can I get an invite to https://graphenetools.slack.com please?

**Comment by jkimbo** [comment]
@juancarlosjr97 you should be able to use the link in the README to join the group
