### ISSUE TITLE
regression: DateTime should accept valid ISO8601 date without time

### ISSUE THREAD

**Issue by brubbel** [graphql-python/graphene#1017]
Currently an input field with type `graphene.types.datetime.DateTime` does accept a string with format `2019-06-18T00:00:00` but rejects (`GraphQL error Expected type DateTime`) a valid ISO8601 date without time, e.g. `2019-06-18`

If I remember correctly an ISO8601 date without time was accepted before the switch to the aniso8601 package. cfr. https://github.com/graphql-python/graphene/pull/701

Imho it is acceptable to try a fallback to `parse_date(value)` before returning None in the following code.

https://github.com/graphql-python/graphene/blob/0e8a3c506302d59776a78b7c92f5cb8c602c9fcc/graphene/types/datetime.py#L63-L71

**Comment by jkimbo** [comment]
@brubbel I think that behaviour is correct. If you're passing a value as a `DateTime` type then it should be an actual datetime string otherwise it should error. I'm sorry that a minor version release changed that behaviour but the current behaviour is what I would expect.
