### ISSUE TITLE
bulk version of get_node_from_global_id ?

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/graphene#1018]
I want to get the nodes from a type but i have many nodes to get.
I would like to implement a bulk version of get_node maybe something like 
get_nodes .. there i could use something like a dataloader or use the get_queryset method of a django-graphene type mixin to optimize the retrieval of many node by id.

**Comment by jkimbo** [comment]
@japrogramer I’m not sure I understand what you want to implement. Do you mean something like this?

```
query {
  getNodes(ids: [ID!]!) {
    ...MyType
  }
}
```

Also when you mean nodes do you mean the Relay Node interface?

**Comment by japrogramer** [comment]
thats cool, I think i would implement that with an union.
But I was actually talking about something like this.

```
    @classmethod
    def get_many_nodes(cls, info, ids):
        plain_ids = []
        for i in ids:
            plain_ids += relay.node.from_global_id(i)[1]
        return cls.get_queryset(info).filter(pk__in= plain_ids)

# than on your type:
SomeType.get_many_nodes(info, list_of_global_ids)
```

**Comment by jkimbo** [comment]
Ok well the code you’ve included looks like it would work. What would you like to see in graphene?

**Comment by japrogramer** [comment]
maybe a build in method that gets many nodes from ids,
that way, there is one standard method that can be optimized for those specific use cases.
I know that dataloaders can be used for that, but to me it doesn't feel like all use cases would require the extra code that a dataloader would require.  

aside from a loop of 
```
        inst = relay\
            .Node\
            .get_node_from_global_id(info, gid)
```

**Comment by jkimbo** [comment]
@japrogramer I'm not sure there is much value in adding a new method that just wraps the underlying `from_global_id` or `get_node_from_global_id` methods since it's pretty trivial to implement in userspace (as you've shown). Also you would then have to make decisions like whether to return sparse arrays or not which are better decided in userspace IMO.
