### ISSUE TITLE
Document: Adding custom directives

### ISSUE THREAD

**Issue by jkimbo** [graphql-python/graphene#1021]
It is possible to pass custom directives to graphql-core but it's not documented anywhere. It should be.

```python
from graphql.types.directives import specified_directives  # <== default directives
from graphene import Schema

schema = Schema(query=Query, directives=specified_directives + [MyDirective])
```

`@skip` and `@include` and defined here: https://github.com/graphql-python/graphql-core/blob/8f7c8f3351dd0a4580b87f293aed7bfcf9126bc4/graphql/type/directives.py#L69-L98

Originally raised in https://github.com/graphql-python/graphene/issues/1006

**Comment by thebenwaters** [comment]
Also is there anyway to add a directive to a field via field argument? in an ObjectType definition

**Comment by thebenwaters** [comment]
This looks like directives are only supported client side and not server/query side

**Comment by thebenwaters** [comment]
Sorry for being an idiot, this was already discussed #1006

**Comment by karlosss** [comment]
Is it possible that the documentation on writing custom directives is still missing, or I am just unable to find it?
