### ISSUE TITLE
Interfaces lead to circular imports when splitting type definitions across files

### ISSUE THREAD

**Issue by klairetan** [graphql-python/graphene#1025]
I'm not sure if this issue has been raised before. Did a quick search through issues and didn't find anything. But I was wondering if anyone had run into this issue before and there's an existing Python solution I'm not thinking about or if this is an existing issue.

Basically, when defining a type that implements an interface, we specify the interface class that is being implemented by this new type in the Meta interface option.

```
class Character(graphene.Interface): 
    id = graphene.ID(required=True)
    name = graphene.String(required=True)
    friends = graphene.List(lambda: Character)

class Human(graphene.ObjectType):
    class Meta:
        interfaces = (Character, ) # <----- here

    starships = graphene.List(Starship)
    home_planet = graphene.String()

```

But if we would like to split the class definitions across two files:

```
#schema.py 

import graphene
from human import Human
from droid import Droid


class Character(graphene.Interface):
    id = graphene.ID(required=True)
    name = graphene.String(required=True)
    friends = graphene.List(lambda: Character)

   def resolve_type(cls, instance, info):
        if instance.type == 'DROID':
            return Droid
        return Human # <----- here we need to import Human




....


schema = graphene.Schema(query=Query, mutation=Mutation, types=[Human])
```

and

```
#human.py
class Human(graphene.ObjectType):
    class Meta:
        interfaces = (Character, ) # <--- would require us to import Character

    starships = graphene.List(Starship)
    home_planet = graphene.String()
```

then how would the `Human` class be able to import the `Character` class it needs to specify in the interfaces it implements without introducing circular imports?

**Comment by ekampf** [comment]
Your problem is the `schema` line just define it in a separate file..
```
# interfaces.py
import graphene
from droid import Droid

class Character(graphene.Interface):
    id = graphene.ID(required=True)
    name = graphene.String(required=True)
    friends = graphene.List(lambda: Character)

   def resolve_type(cls, instance, info):
        if instance.type == 'DROID':
            return Droid
        return Human
```

```
#human.py
from interfaces import Character

class Human(graphene.ObjectType):
    class Meta:
        interfaces = (Character, )

    starships = graphene.List(Starship)
    home_planet = graphene.String()
```

```
#schema.py
from human import Human

schema = graphene.Schema(query=Query, mutation=Mutation, types=[Human])
```

**Comment by ekampf** [comment]
Closing issue please re-open if you feel necessary....

**Comment by klairetan** [comment]
But in the `resolve_type` of `Character` we also are returning the class, are we not?

**Comment by ekampf** [comment]
@klairetan I missed that one. 
So in my solution you now have a problem of circular dependency between `interfaces.py` and `human.py` and `droid.py`.
Solving this problem is simple - lazy import. In `interfaces.py` move the import station events for `Droid` and `Human` into the `resolve_type`.

**Comment by ekampf** [comment]
```
# interfaces.py

import graphene

class Character(graphene.Interface):
    id = graphene.ID(required=True)
    name = graphene.String(required=True)
    friends = graphene.List(lambda: Character)

   def resolve_type(cls, instance, info):
        from droid import Droid
        from human import Human
        if instance.type == 'DROID':
            return Droid
        return Human

```

**Comment by jkimbo** [comment]
That is the way I've had to implement interfaces in the past as well @ekampf . It might make sense to allow string references to ObjectTypes in the interfaces list. What do you think?

**Comment by klairetan** [comment]
apparently, resolve_type can actually return Strings, so you can return 'Droid' and 'Human' instead of the classes themselves
