### ISSUE TITLE
How to do `search and filter` over the `JSONField`?

### ISSUE THREAD

**Issue by elcolie** [graphql-python/graphene#1027]
I comes from `django-restframework`. I would like to use `filter, search` over the `JSONField`

I had gone through the tutorial, but I have not found any section related to `JSONField`.
Is it possible to query by using `GraphQL`?

**Comment by timkindberg** [comment]
I also needed this and it doesn't seem supported out of the box. This is what I came up with. I'm using a custom FilterSet and in that I'm using the `method` kwarg of the CharFilter to run my own logic. The method takes in the queryset, name and value so it's flexible. I can't flexibly control the name, so I though I could hide some "sub-filtering" in the value, see the part `fields: "__code=12345"`. I split on the '=' sign and construct the query in the method. It's a bit hacky but it works!

```graphql
{
  allRecords(
    fields: "__code=12345",
  ) {
    edges{
      node{
        fields
      }
    }
  }
}
```

```python
class RecordFilter(django_filters.FilterSet):
    fields = django_filters.CharFilter(field_name='fields', method='filter_fields')

    def filter_fields(self, queryset, name, _value):
        subfilter, value = _value.split('=') if '=' in _value else ('', _value)
        lookup = name + subfilter
        return queryset.filter(**{lookup: value})

    class Meta:
        model = Record
        fields = ['fields']


class RecordNode(DjangoObjectType):
    fields = GenericScalar() # This also returns the JSON as actual JSON instead of a String

    class Meta:
        model = Record
        filterset_class = RecordFilter
        interfaces = (relay.Node,)
```

**Comment by esteban-diaz** [comment]
I'am also looking for this. .. just starting learning GraphQL but  I'm using Flask instead of Django
