### ISSUE TITLE
No way to subclass Mutation type for customization

### ISSUE THREAD

**Issue by thejcannon** [graphql-python/graphene#1029]
Let's say I wanted to add some custom logic to `__init_subclass_with_meta__` for my own mutation types. I would subclass `Mutation` and then define my `__init_subclass_with_meta__`. Everything _should_ work out just fine.

Unfortunately `Mutation`'s `__init_subclass_with_meta__` fires for my custom mutation type. (This should be fine. After all `ObjectType`'s `__init_subclass_with_meta__` fires for the declaration of `Mutation`). The bug is that in `Mutation`'s `__init_subclass_with_meta__`, it asserts there is a resolver or mutate function (which isn't true for my base mutation).

Consider removing the check, or making it smarter so that user can customize the mutation initialization.

P.S. validating user input with asserts is bad practice, since they can be turned off 😉

**Comment by KaySackey** [comment]
Two things. 

First from your `` you need to call the graphene.Mutation method.

Secondly, you need to pass a `resolver` because your new class subclasses Mutation but of course does not have a `mutate` method, since its intended to be subclassed itself.

Example from my codebase:

```
        super(HydraMutation, cls).__init_subclass_with_meta__(
            arguments=arguments, output=output, resolver=resolver, **options
        )
```

**Comment by p7g** [comment]
You can subclass the `Mutation` class by declaring it as abstract like so:

```python
import graphene


class MyMutation(graphene.Mutation, abstract=True):
    @classmethod
    def __init_subclass_with_meta__(cls, message, **kwargs):
        print('message:', message)
        super(MyMutation, cls).__init_subclass_with_meta__(**kwargs)


class MyConcreteMutation(MyMutation):
    class Meta:
        message = 'hello world'

    @classmethod
    def mutate(cls, root, info):
        pass
```

The abstract option can either be passed as a keyword argument to the class definition as above, or as a property of the `class Meta` property like so:

```python
class MyMutation(graphene.Mutation):
    class Meta:
        abstract = True
```

The `__init_subclass_with_meta__` method is only called for a declared class if it is not abstract (see [here][1].

[1]: https://github.com/graphql-python/graphene/blob/8e7d76bbce3eb8755bf4f3beba8b9d8b026c6424/graphene/utils/subclass_with_meta.py#L42
