### ISSUE TITLE
Accessing other class variables in resolve methods?

### ISSUE THREAD

**Issue by vangalamaheshh** [graphql-python/graphene#1034]
Hi, I have a use case where I need to access other class variable in the resolve method. For example,

```
class Test(graphene.ObjectType):
  one = graphene.List(lambda: graphene.String())
  two = graphene.List(lambda: graphene.Int())

  def resolve_one(self, info):
    return ["1", "2", "3"]

  def resolve_two(self, info):
    return [int(i) for i in self.one]

```

In the second resolver method, self.one always results in empty array. Let me know how I can solve this issue.

Thanks much,
Mahesh

**Comment by svanburen** [comment]
not super experienced with graphene, but presumably if you wanted to get the results from another resolver, you'd need to use the resolver's method?

```python
  def resolve_two(self, info):
    return [int(i) for i in self.resolve_one(info)]
```

**Comment by ProjectCheshire** [comment]
self.one is not a property, which is defined by @property decorator.  @svanburen is correct in that you need to use the method signature

**Comment by vangalamaheshh** [comment]
Sorry, this has slipped from my mind. Thanks, for the solution, @svanburen, @ProjectCheshire. Closing this as solved.
