### ISSUE TITLE
relay.NodeField does not propagate arguments to Field

### ISSUE THREAD

**Issue by tdiam** [graphql-python/graphene#1035]
The [current implementation](https://github.com/graphql-python/graphene/blob/167c8c203cc2607fd3b80359de4b6064ac2e5234/graphene/relay/node.py#L51) of `NodeField`'s constructor does not propagate `name`, `deprecation_reason` or `**kwargs` to its parent `Field` constructor.
This would be useful, for example, when the field has a name that is reserved in Python:
```python
klass = Node.Field(name='class', ...)
```

Is this expected behavior or is a fix needed?

<details>
<summary>Test code</summary>

```python
from graphene import Node, ObjectType, Schema, String

droids = {1: {'name': 'R2-D2'}}

class DroidNode(ObjectType):
    class Meta:
        interfaces = (Node,)

    name = String()

    @classmethod
    def get_node(cls, info, id):
        return DroidNode(**droids[id])

class Query(ObjectType):
    droid = Node.Field(DroidNode, name='robot')

schema = Schema(query=Query)


def test_field_name_is_robot():
    r = schema.execute(
        """
        {
            __type(name: "Query") {
                fields { name }
            }
        }
        """
    )
    assert r.data['__type']['fields'][0]['name'] == 'robot'
```
</details>

**Comment by chason** [comment]
I am currently running into this issue passing `description` to the constructor so that the automatically generated documentation in GraphiQL says something besides "The ID of the object".

**Comment by mattaustin** [comment]
I don't believe this issue to be stale. I am encountering the same problem today, and it would be great to see the related pull request merged.
