### ISSUE TITLE
Some clarity on how to define abstract types

### ISSUE THREAD

**Issue by fhennig** [graphql-python/graphene#1039]
I have different entities in my project, and want to split up my Query ObjectType into multiple classes.

How should I do that?

There seem to be three ways of doing it:

1. Just use inheritance as usual:

```
class UserQueries(graphene.ObjectType):
    ...

class OtherQueries(graphene.ObjectType):
    ...

class Queries(UserQueries, OtherQueries):
    pass
```

2. Using the `AbstractType`:

```
class UserQueries(graphene.AbstractType):
    ...

class OtherQueries(graphene.AbstractType):
    ...

class Queries(graphene.ObjectType, UserQueries, OtherQueries):
    pass
```

3. Using the `abstract = True` attribute:

```
class UserQueries(graphene.ObjectType):
    class Meta:
        abstract = True
    ...

class OtherQueries(graphene.ObjectType):
    class Meta:
        abstract = True
    ...

class Queries(UserQueries, OtherQueries):
    pass
```

And this can apparently also be given as a class argument like so:

```
class UserQueries(graphene.ObjectType, abstract=True):
    ...
```

The [documentation](https://docs.graphene-python.org/en/latest/types/abstracttypes/#abstracttypes) says to use 2., but in the [v2 release notes](https://github.com/graphql-python/graphene/blob/master/UPGRADE-v2.0.md) it says that `AbstractType` is deprecated.  In the same document it uses method 3., but I couldn't find any documentation for that.

I started to just use normal inheritance and it seems to work.

How should it be done?

Probably related to #823

**Comment by KaySackey** [comment]
If you are on Python3, you can use `abstract=True` without any problems. I believe `AbstractType` is your only option on Python2.

**Comment by odigity** [comment]
I'm confused.  "abstract = True" isn't mentioned anywhere in the Graphene docs.  Is that an official object option, and what behavior does it result in?
