### ISSUE TITLE
Prevent multiple repeats of a single query

### ISSUE THREAD

**Issue by preppypiet** [graphql-python/graphene#1040]
Apologies if this is something obvious, as I'm not all that used to graphql and django etc. 

I've currently got a simple app, with an Item model that references a User. If I currently query all of the items like this:

`query {
  items{
    edges{
      node{
        user {
          id,
          firstName
        }
      }
    }
  }
}
`

I get these sql queries being executed:

(0.001) SELECT COUNT(*) AS "__count" FROM "items_item"; args=()
(0.000) SELECT "items_item"."id", "items_item"."title", "items_item"."description", "items_item"."image_url", "items_item"."user_id" FROM "items_item"  LIMIT 6; args=()
(0.000) SELECT "items_itemuser"."id", "items_itemuser"."password", "items_itemuser"."last_login", "items_itemuser"."is_superuser", "items_itemuser"."is_staff", "items_itemuser"."is_active", "items_itemuser"."date_joined", "items_itemuser"."email", "items_itemuser"."first_name", "items_itemuser"."last_name" FROM "items_itemuser" WHERE "items_itemuser"."id" = 4; args=(4,)
(0.000) SELECT "items_itemuser"."id", "items_itemuser"."password", "items_itemuser"."last_login", "items_itemuser"."is_superuser", "items_itemuser"."is_staff", "items_itemuser"."is_active", "items_itemuser"."date_joined", "items_itemuser"."email", "items_itemuser"."first_name", "items_itemuser"."last_name" FROM "items_itemuser" WHERE "items_itemuser"."id" = 2; args=(2,)
(0.000) SELECT "items_itemuser"."id", "items_itemuser"."password", "items_itemuser"."last_login", "items_itemuser"."is_superuser", "items_itemuser"."is_staff", "items_itemuser"."is_active", "items_itemuser"."date_joined", "items_itemuser"."email", "items_itemuser"."first_name", "items_itemuser"."last_name" FROM "items_itemuser" WHERE **"items_itemuser"."id" = 3; args=(3,)**
(0.000) SELECT "items_itemuser"."id", "items_itemuser"."password", "items_itemuser"."last_login", "items_itemuser"."is_superuser", "items_itemuser"."is_staff", "items_itemuser"."is_active", "items_itemuser"."date_joined", "items_itemuser"."email", "items_itemuser"."first_name", "items_itemuser"."last_name" FROM "items_itemuser" WHERE "**items_itemuser"."id" = 3; args=(3,)**
(0.000) SELECT "items_itemuser"."id", "items_itemuser"."password", "items_itemuser"."last_login", "items_itemuser"."is_superuser", "items_itemuser"."is_staff", "items_itemuser"."is_active", "items_itemuser"."date_joined", "items_itemuser"."email", "items_itemuser"."first_name", "items_itemuser"."last_name" FROM "items_itemuser" WHERE "**items_itemuser"."id" = 3; args=(3,)**
(0.000) SELECT "items_itemuser"."id", "items_itemuser"."password", "items_itemuser"."last_login", "items_itemuser"."is_superuser", "items_itemuser"."is_staff", "items_itemuser"."is_active", "items_itemuser"."date_joined", "items_itemuser"."email", "items_itemuser"."first_name", "items_itemuser"."last_name" FROM "items_itemuser" WHERE "items_itemuser"."id" = 4; args=(4,)
[19/Jul/2019 17:45:01] "POST /graphql/ HTTP/1.1" 200 312

Notice above, the bolded bits. A list of items are fetched, which is correct, but for each item, the corresponding user record is fetched regardless if it was fetched before.

How can I prevent this behaviour so that, in the above case, user with id 3 is only queried once? It seems like the sort of thing that should be handled by graphene?

**Comment by preppypiet** [comment]
Ah, it was actually pretty simple [using dataloader](https://docs.graphene-python.org/en/latest/execution/dataloader/):

```
from promise.dataloader import DataLoader

class UserLoader(DataLoader):                                                                                                                             
     def batch_load_fn(self, keys):                                                                                                                          
         return Promise.resolve([ItemUser.objects.get(id=key) for key in keys])                                                                            
                                                                                                                                                         
user_loader = UserLoader()

class ItemType(DjangoObjectType):
    def resolve_user(root, info):                                                                                                                         
        return user_loader.load(root.user_id)
```                     
I'll close this now, sorry. Graphene is awesome stuff btw, thanks!

**Comment by jkimbo** [comment]
Glad you found dataloader!

**Comment by reginalin** [comment]
In this example, what type is `ItemUser`? Is it a graphene.ObjectType or a sqlalchemy model? 

I am following the graphene documentation below: 
```
class UserLoader(DataLoader):
    def batch_load_fn(self, keys):
        users = {user.id: user for user in User.objects.filter(id__in=keys)}
        return Promise.resolve([users.get(user_id) for user_id in keys])
```
An error is given when I attempt to call `.objects` on either a graphene ObjectType or sqlalchemy model, and I can't seem to find documentation about it. Would appreciate help understanding this.
