### ISSUE TITLE
Problem with Implementing Custom Directives 

### ISSUE THREAD

**Issue by frank2411** [graphql-python/graphene#1041]
Hi,

I've have read all the issues in your repo regarding this argument.
I've also checked your source code and the graphql-core source code.

And still I can't find a satisfying answer to my problem.

I have to implement custom directives like the ones implemented in this package (https://github.com/ekampf/graphene-custom-directives).

The question is: since the graphql-core apparently only supports the logic for the skip and include ones, and it seems quite hardcoded ( since it strictly supports only those two ), which is the correct way to implement custom directives ?

Is the way in the package I mentioned the only one possible to achieve my goal ?

Thanks

**Comment by jkimbo** [comment]
@frank2411 you should be able to pass directives when you define your schema like so:

```python
from graphql.types.directives import specified_directives  # <== default directives
from graphene import Schema
from graphene-custom-directives.directives.string import CurrencyDirective

schema = Schema(query=Query, directives=specified_directives + [CurrencyDirective])
```
