### ISSUE TITLE
Schema generation in alphabetical order

### ISSUE THREAD

**Issue by dan-klasson** [graphql-python/graphene#1043]
Is there anyway I can get the queries and mutations be sorted in alphabetical order so that they show up sorted in GraphiQL browser?

**Comment by jkimbo** [comment]
@dan-klasson not that I'm aware of sorry. The way GraphiQL gets the schema data is just by executing the introspection query on the GraphQL server. If you want GraphiQL to order the types then it might be worth creating a PR with that project. Looks like there might be an issue open already: https://github.com/graphql/graphiql/issues/631
