### ISSUE TITLE
External call to graphene API

### ISSUE THREAD

**Issue by graforlock** [graphql-python/graphene#1057]
I don't see the example anywhere but I assume it should be pretty basic functionality.

In the microservice architecture, if I have multiple python servers talking to graphene API, how do I accomplish this basic scenario? Is there any graphene client for this?

**Comment by manesioz** [comment]
Graphene is a library that enables you to make GraphQl APIs in Python. I'm not sure what you're asking.

**Comment by graforlock** [comment]
I was asking whether you have a working graphene client library for Python, but I think i found it already.
