### ISSUE TITLE
StarWars example (edges/node?)

### ISSUE THREAD

**Issue by sgtsquiggs** [graphql-python/graphene#106]
Is the `edges { node {` nesting an artifact of the connection between film and character? I am confused as to why it isn't simply

```
  myFavoriteFilm: film(id:"RmlsbToz") {
    id
    title
    episodeId
    characters(first:5) {
      name
    }
  }
```

with the result

```json
{
  "data": {
    "myFavoriteFilm": {
      "id": "RmlsbToz",
      "title": "Return of the Jedi",
      "episodeId": 6,
      "characters": [
          {
              "name": "Luke Skywalker"
          },
          {
              "name": "C-3PO"
          },
          {
              "name": "R2-D2"
          },
          {
              "name": "Darth Vader"
          },
          {
              "name": "Leia Organa"
          }
        ]
    }
  }
}
```

**Comment by Globegitter** [comment]
@sgtsquiggs That is the difference between a `graphene.List` and a `graphene.ConnectionField`. A ConnectionField is basically a list on steroids with information about pagination. See here for some more info on it: https://facebook.github.io/relay/docs/graphql-connections.html#content

**Comment by sgtsquiggs** [comment]
I see! I'll have to read up on Relay.

**Comment by tobych** [comment]
Looks like the link @Globegitter includes above has [moved](https://facebook.github.io/relay/graphql/connections.htm).
