### ISSUE TITLE
Including self-referential fields in InputObjectType subclass

### ISSUE THREAD

**Issue by seandavi** [graphql-python/graphene#1063]
I am trying to create an InputObjectType that has dynamic fields that is meant for complex filtering of fields but that also contains a couple of self-referencing fields to allow boolean operations (AND, OR). Here is a concrete example of what I am trying to do, taken from [here](https://www.contentful.com/developers/docs/references/graphql/#/reference/collection-filters):

```
input FriendlyUserFilter {
  sys: SysFilter
  name: String
  name_not: String
  name_exists: Boolean
  name_contains: String
  # ... more name filters
  age: Number
  age_gt: Number
  age_lt: Number
  # ... more age filters
  AND: [FriendlyUserFilter]
  OR: [FriendlyUserFilter]
}
```

I am using the technique described [here](https://github.com/graphql-python/graphene/issues/945#issuecomment-484588866) to do so. I'm curious how to implement the `AND` and `OR` functionality that includes a reference to the class itself.

**Comment by art1415926535** [comment]
Hi, do you need something like that?

```python

class UserFilters(graphene.InputObjectType):
    name = graphene.String()
    or_ = graphene.Field(graphene.List(lambda: UserFilters), name='or')
    and_ = graphene.Field(graphene.List(lambda: UserFilters), name='and')


class Query(ObjectType):
    all_users = ConnectionField(
        UserConnection, filters=UserFilters()
    )

```
Result (graphiql):
![image](https://user-images.githubusercontent.com/5222234/64191471-3f52ba00-ce81-11e9-9fec-98a2ef9ea275.png)

**Comment by seandavi** [comment]
Thanks, @art1415926535. That is pretty close and inspired the solution below. Here is roughly what seems to work for me for the time being. 

```
# example field for dynamic filtering class....
fields = {"name": graphene.String())
TmpFilter = type("TmpFilter", (graphene.InputObjectType,), fields)
class UserFilters(TmpFilter):
    or_ = graphene.Field(graphene.List(lambda: TmpFilter), name='or')
    and_ = graphene.Field(graphene.List(lambda: TmpFilter), name='and')
```

The inheritance approach seems to work since I seem to need an existing class for the lambda and using `type` to create the class dynamically doesn't give me that option, I don't think. 

Any other suggestions appreciated. In particular, since I am a little new to graphene, let me know if there are unforeseen problems with the approach I am outlining here.

**Comment by seandavi** [comment]
Since I have something that works for me, I'll close this. Thanks again, @art1415926535.

**Comment by art1415926535** [comment]
Hmm... Maybe like this?

```python
class BaseFilter(graphene.InputObjectType):
    @classmethod
    def __init_subclass_with_meta__(cls, *args, **kwargs):
        super().__init_subclass_with_meta__(*args, **kwargs)
        field = graphene.InputField(graphene.List(graphene.NonNull(cls)))
        cls._meta.fields.update({'or': field, 'and': field})

    class Meta:
        abstract = True


class UserFilter(BaseFilter):
    name = graphene.String()
```


Same result as https://github.com/graphql-python/graphene/issues/1063#issuecomment-527537653 (+NonNull)

**Comment by seandavi** [comment]
Nice, @art1415926535. I had forgotten about `__init_subclass_with_meta__`. Much cleaner than my approach.... Thanks again.
