### ISSUE TITLE
Directives

### ISSUE THREAD

**Issue by adrianschneider94** [graphql-python/graphene#1069]
Hi,

I'm currently writing a code generator for graphene as plugin to https://graphql-code-generator.com. I would like to implement directives as well.

I see that one can define directives:
https://github.com/graphql-python/graphene/issues/1006

However, the types used there are from the core library. Are those interchangeable with the graphene types or must I use the core types?

**Comment by jkimbo** [comment]
@adrianschneider94 you need to use the core types from graphql-core to define custom directives. Graphene runs on top of graphql-core and just provides a wrapper to help you define a schema in code.

https://github.com/ekampf/graphene-custom-directives provides some custom directives that you can use for inspiration.
