### ISSUE TITLE
turn off pagination (get rid of edges)

### ISSUE THREAD

**Issue by squarewave24** [graphql-python/graphene#1073]
is it possible to turn off pagination? 

i'd like to just get the data back, instead of edges/node 

on my new setup, it appears by default and i can't figure out how to get rid of it

```
{ allRecords {
  edges {
    node {
      id
    }
  }
} }
```

the issue im facing is that it adds unnecessary complexity in React Apollo client 

graphql-python code: 
```
class MyClass(SQLAlchemyObjectType):
    class Meta:
        model = MyClassModel
        interfaces = (relay.Node, )

class MyClassConnection(relay.Connection):
    class Meta:
        node = MyClass

class Query(graphene.ObjectType):
    node = relay.Node.Field()
    all_records = SQLAlchemyConnectionField(MyClassConnection, sort=None)
```

**Comment by jkimbo** [comment]
@squarewave24 the `edges` and `node` types appear because you are using a `Connection` field which conforms to the relay Connection spec: https://facebook.github.io/relay/graphql/connections.htm

If you don't want that then you can use a plain `List` type to just return an array of objects ([documentation](https://docs.graphene-python.org/en/latest/types/list-and-nonnull/#list))

**Comment by squarewave24** [comment]
> @squarewave24 the `edges` and `node` types appear because you are using a `Connection` field which conforms to the relay Connection spec: https://facebook.github.io/relay/graphql/connections.htm
> 
> If you don't want that then you can use a plain `List` type to just return an array of objects ([documentation](https://docs.graphene-python.org/en/latest/types/list-and-nonnull/#list))

thank you 
is it possible to use List while also using graphene_sqlalchemy for ORM? 

i was using `SQLAlchemyConnectionField` after following this example: https://docs.graphene-python.org/projects/sqlalchemy/en/latest/tutorial/

in the tutorial i see this bit, maybe its related ? 

```
             backref=backref('employees',
                        uselist=True,
                        cascade='delete,all'))```

**Comment by jkimbo** [comment]
I'm not that familiar with the sqlalchemy integration unfortunately so you would have to raise the issue there. If it's of use I did recently update the graphene-django list integration so the the `DjangoList` field would fetch models from the queryset if a resolver isn't defined: https://github.com/graphql-python/graphene-django/pull/732
