### ISSUE TITLE
Improve the DataLoader batching documentation

### ISSUE THREAD

**Issue by wojcikstefan** [graphql-python/graphene#1075]
If you follow the [documentation on batching](https://github.com/graphql-python/graphene/blob/5cb7d91aaad028ad186f9453c6d7cc7c1e63e8a1/docs/execution/dataloader.rst#batching) directly, you might easily come to a conclusion that the `DataLoader` is not working as advertised.

To make this more concrete, see this script, which is directly following the documentation:
```py
from promise import Promise
from promise.dataloader import DataLoader

class UserLoader(DataLoader):
    def batch_load_fn(self, keys):
        print("Batch loading", keys)
        return Promise.resolve(keys)

user_loader = UserLoader()
user_loader.load(1)
user_loader.load(2)
```

This results in the following output:
```
Batch loading [1]
Batch loading [2]
```
instead of `Batch loading [1, 2]`.

The only way (that I've found) to make this work correctly is to run this:
```
def test(res):
    user_loader.load(1)
    user_loader.load(2)

Promise.resolve(None).then(test)
```

**Comment by pollaro** [comment]
What's the update on this? I'm still trying to figure it out

**Comment by tazimmerman** [comment]
@pollaro you may want to give my comment on issue [#42](https://github.com/syrusakbary/promise/issues/42#issuecomment-589092209) a try.
