### ISSUE TITLE
AttributeError: Type "execute_async" not found in the Schema.

### ISSUE THREAD

**Issue by JacobMillner** [graphql-python/graphene#1077]
Hi there, 
I am using graphene 2.1.8 with the tornado framework. I am trying to setup an async graphene mutation and it appears to not think the function exists on the graphene Schema class. My code is roughly setup like this:

```python
graphql = graphene.Schema(query=Query, mutation=Mutations, subscription=Subscriptions)
async def query_async(self, query, queueLayer, variables, context):
        return await graphql.execute_async(query, variables=variables, context=context)
```

And I get this error:

```
| 2019-10-02 20:16:48,976 tornado.application ERROR    Uncaught exception POST /async (192.168.80.1)
 HTTPServerRequest(protocol='http', host='localhost:8081', method='POST', uri='/async', version='HTTP/1.1', remote_ip='192.168.80.1')
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
   File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/work/server/handlers.py", line 152, in post
     response = yield asyncio.ensure_future(self.session.exec_query_async(self.get_request_token(), query, variables, self.queueLayer))
   File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
     value = future.result()
File "/work/datastore/session/sessions.py", line 52, in exec_query_async
esult = await Schema.query_async(session, query, queueLayer, variables, dict(session=session, auth=token))
File "/work/schema/__init__.py", line 22, in query_async
 return await graphql.execute_async(query, variables=variables, context=context, middleware=[QueueLayerMiddleware(queueLayer)])
File "/usr/local/lib/python3.7/site-packages/graphene/types/schema.py", line 98, in __getattr__
raise AttributeError('Type "{}" not found in the Schema'.format(type_name))
AttributeError: Type "execute_async" not found in the Schema
```
EDIT: I tried setting up a very basic example of execute_async using the example in graphene/tests_asyncio/test_relay_mutation.py and it is still giving me a similar error.

**Comment by mariaines** [comment]
I'm getting the same error. @JacobMillner have you found any alternative for executing a query asynchronously?

**Comment by JacobMillner** [comment]
@mariaines I ended up having to create a separate route that is completely async. It parses the incoming graphql request manually (yuck I know), runs the async tasks needed,  stuffs the information in a middleware function and calls the original schema.execute() passing in the middleware. It's a super hacky solution I know but the only one I could think of without avoiding graphene completely.

**Comment by uSpike** [comment]
This is only available in graphene v3 (alpha still), see https://github.com/graphql-python/graphene/commit/8e7d76bbce3eb8755bf4f3beba8b9d8b026c6424

**Comment by JacobMillner** [comment]
@uSpike hmmm then why is it listed in their current docs? https://docs.graphene-python.org/en/latest/api/

**Comment by uSpike** [comment]
@JacobMillner that's docs for `latest`.  Look at https://docs.graphene-python.org/en/v2.1.8/api/#schema for `2.1.8`.

**Comment by JacobMillner** [comment]
@uSpike whelp that will do it! Thanks so much for the info.
