### ISSUE TITLE
Is Graphene being actively developed?

### ISSUE THREAD

**Issue by ztolley** [graphql-python/graphene#1091]
Looking at options for a GraphQL library and have found Graphene to be easy to use and gets the job done but I have one question. Is the library being actively developed? Recent commit history seems to be extremely quiet.

**Comment by denizdogan** [comment]
Last release was just in August and work on v3 is in alpha, doesn't seem extremely quiet to me :)

**Comment by henrythor** [comment]
Issues and PRs go unanswered and get pruned by stalebot. So I'd say it's not super active either
