### ISSUE TITLE
How to pass unknown fields to Graphene mutation?

### ISSUE THREAD

**Issue by prabhupant** [graphql-python/graphene#1096]
As per the GraphQL spec https://graphql.github.io/graphql-spec/draft/#sec-Input-Objects

> the input object literal or unordered map must not contain any entries with names not defined by a field of this input object type, otherwise an error must be thrown.

Let's say I have a project which has a user called `buyer`, the schema for which is as follows
```
type Buyer {
     id: ID!
     name: String!
     address: String!
     email: String!
}
```
Now I can write a graphene schema for it

```python
class BuyerType(DjangoObjectType):
    class Meta:
        model = Buyer
```

and make a mutation for this

```python
class BuyerInput(graphene.InputObjectType):
    name = graphene.String(required=False, default_value='')
    address = graphene.String(required=False, default_value='')
    email = graphene.String(required=False, default_value='')


class BuyerMutation(graphene.Mutation):
    """
    API to create applicant
    """
    class Arguments:
        buyer_data = BuyerInput(required=True)
        

    buyer = graphene.Field(BuyerType)
    ok = graphene.Boolean()

    def mutate(self, info, buyer_data=None):
           buyer = Buyer(name=buyer.name, address=buyer.address, email=buyer.email)
           buyer.save()
           return BuyerMutation(buyer=buyer, ok=True)
```

and write the resolvers functions and query and mutation class. Pretty basic stuff so far.

And now to create a new buyer, I just call the mutation 

```
mutation {
   createBuyer(
           name: "New Buyer"
           address: "Earth"
           email: "abc@example.com"
  ) {
      ok
  }
}
```

I pass some undefined argument to the mutation, it throws an error for Unknown Field, which is completely fine. But I want to make process for frontend devs easier. Rather than mentioning each field in the argument of mutation, they can just pass a dict which contains these three fields and also other arguments that might originate from a form submission, and then read the dict in the backend and only extract the fields that I need, much like it is done with REST APIs. 

If this is possible, then how can I implement this?

**Comment by BossGrand** [comment]
JSONField might be what you're looking for
