### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by imranolas** [graphql-python/graphene#110]
Python is not able to resolve circular dependencies for schemas with recursive types.

e.g
```py
  # category_type.py
  from .post_type import Post
  class Category(graphene.ObjectType):
    Post = graphene.List(Post)

  # post_type.py
  from .category_type import Category
  class Post(graphene.ObjectType):
    category = graphene.Field(Category)
```

At runtime, the above fails as the types haven't yet loaded before being used in field definitions. A better option would be to wrap the field definitions in a lambda to be called at resolve time and after the types have been declared.

e.g
```diff
  # category_type.py
-  from .post_type import Post
  class Category(graphene.ObjectType):
-   Post = graphene.List(Post)
+   Post = lambda: graphene.List(Post)

+ from .post_type import Post

  # post_type.py
- from .category_type import Category
  class Post(graphene.ObjectType):
-   category = graphene.Field(Category)
+   category = lambda: graphene.Field(Category)

+ from .category_type import Category
```

cc @Globegitter

**Comment by Globegitter** [comment]
Or looking at Graphql-core another syntax option could be

```py
    class Post(graphene.ObjectType):
        fields = lambda: dict(
            category = graphene.Field(Category)
        )
```

But of course that would mean that graphene would either have to break backwards-compatibility to a quite substantial degree, or support two different syntaxes.

**Comment by syrusakbary** [comment]
Hi @imranolas,

You can achieve this by using String references (ala Django):

```python
# category_type.py
@schema.register
class Category(graphene.ObjectType):
    Post = graphene.List('Post')

# post_type.py
@schema.register
class Post(graphene.ObjectType):
    category = graphene.Field('Category')
```

**Comment by syrusakbary** [comment]
As posted in the pull request #111, there is already another "undocumented" way for doing solving this if you don't want to use string references.

```python

class Category(graphene.ObjectType):
    Post = graphene.LazyType(lambda _: Post)

from .post_type import Post

# post_type.py
class Post(graphene.ObjectType):
    category = graphene.LazyType(lambda _: Category)
```

**Comment by syrusakbary** [comment]
Please feel free to reopen if you have any other suggestion of how to achieve it! :)

**Comment by Lucretiel** [comment]
Hey guys– I've seen a lot of similar issues and pull requests, all of which are closed as being fixed; is any of this documented anywhere? I can't find any reference to it in the main page documentation.

**Comment by joetempleman** [comment]
I agree, what's the way to do this in graphene 2.0? Neither the string or the LazyType seem to work for me...

**Comment by Lucretiel** [comment]
I think, based on reading through the source code, that graphene.Dynamic is intended to be the solution. It looks like this:

    graph.List(graph.Dynamic(lambda: CircularType))

But there's sadly no documentation for this class at all. For instance, would this be more appropriate?

    graph.Dynamic(lambda: graph.List(CircularType))

**Comment by sanfilippopablo** [comment]
Looking at some unrelated docs [here](http://docs.graphene-python.org/en/latest/execution/dataloader/) it seems like you can do this:
```py
graph.List(lambda: MyCircularType)
graph.Field(lambda: MyCircularType)
```
I just tested it and it works.

**Comment by Lucretiel** [comment]
Confirmed that the lambda thing works pretty much everywhere. Seems like that's the thing to do.

**Comment by seansay** [comment]
@syrusakbary 
anyway to do this just using `graphql-core`? thanks

**Comment by matt-dalton** [comment]
@sanfilippopablo How did you actually import the types? I'm still struggling to get this working without an error

**Comment by mekhami** [comment]
the lambda option doesn't solve the problem of circular imports, just circular dependencies. Is there a supported solution for the problem of circular imports?

**Comment by mfrlin** [comment]
> Hi @imranolas,
> 
> You can achieve this by using String references (ala Django):
> 
> ```python
> # category_type.py
> @schema.register
> class Category(graphene.ObjectType):
>     Post = graphene.List('Post')
> 
> # post_type.py
> @schema.register
> class Post(graphene.ObjectType):
>     category = graphene.Field('Category')
> ```

This does not work anymore. Just tested like this:

```
class Webhook(ModelObjectType):
  triggered_by = graphene.Field('WebhookEventType')

class WebhookEventType(ModelObjectType):
  ...
```

This raises ImportError from here: https://github.com/graphql-python/graphene/blame/master/graphene/utils/module_loading.py#L39

If I change string to `mymodule.WebhookEventType` then it works but this is not ideal.

**Comment by amaksymov** [comment]
> Using string references does not appear to be support in Connection.Meta.Node
> 
> ```
> class A(graphene.Connection):
>     class Meta:
>         node = 'B'
> ```
> 
> Any solutions. Ive also tried lazy_import and import_string, but it doesnt seem to be finding the class in the module.

I faced the same problem. Did you find any solutions?

**Comment by stan-sack** [comment]
@McPo  @amaksymov did you manage to solve this?

**Comment by alexrintt** [comment]
I tried the solutions above and none worked for me, so I read the source code I saw they're parsing dotted Strings:

```py
# graphene/types/utils.py
def get_type(_type):
    if isinstance(_type, string_types):
        return import_string(_type)
    if inspect.isfunction(_type) or isinstance(_type, partial):
        return _type()
    return _type
```

And the comment docs of `import_string` says:

    Import a dotted module path and return the attribute/class designated by the
    last name in the path. When a dotted attribute path is also provided, the
    dotted attribute path would be applied to the attribute/class retrieved from
    the first step, and return the corresponding value designated by the
    attribute path. Raise ImportError if the import failed.

It means we can declare the type  the field like that:

```py
class MyModelType(DjangoObjectType):
    class Meta:
        model = MyModel

    # Full module path to class of yours
    mymodel_field = graphene.ConnectionField('api.graphql.types.connection.MyModelTypeConnection')

    # Instead of:
    # from api.graphql.types.connection import MyModelTypeConnection
    # mymodel_field = graphene.ConnectionField(MyModelTypeConnection)
```

My env:

```
graphene==2.1.9
graphene-django==2.15.0
```

**Comment by odigity** [comment]
re: dotted-strings

I only discovered this feature because I inherited code from a contractor who used it in the code.  Don't know how they discovered it.

So... why isn't this documented?  And how are people handling the circular-import problem without that knowledge?  Surely this is a very common problem.  Having A refer to B and B refer to A is as normal as anything.
