### ISSUE TITLE
Edit data Query using graphene

### ISSUE THREAD

**Issue by Olivier-Metzinger** [graphql-python/graphene#1103]
Hello I am very new to GraphQl !

I would like to edit data with a query (GraphQL) using graphene

Group Model:

```
class GroupEntity(models.Model):

id = models.CharField(max_length=100, primary_key='true')
uuid = models.TextField()
namegroup = models.CharField(max_length=100)
description = models.TextField()
profilimage = models.TextField()
```

I have a query to getall groups and their data

```
class Query(object):
all_entitygroup = graphene.List(EntityType)

def resolve_all_entitygroup(self, info, **kwargs):
    return GroupEntity.objects.all()
```

And I can get the data with a query this by:

```
{
  "data": {
    "allEntitygroup": [
      {
        "id": "1",
        "description": "descrlol",
        "uuid": "11112",
        "namegroup": "nom",
        "profilimage": "img"
      }
}
```

How can I modify this data, for example if I want to change the 'uuid' of this specific user ?

Thank you in advance !

**Comment by KingDarBoja** [comment]
[GraphQL Mutations](https://docs.graphene-python.org/en/latest/types/mutations/) is what you looking for.
