### ISSUE TITLE
examples are added to site-packages

### ISSUE THREAD

**Issue by marnixlenoble** [graphql-python/graphene#1110]
When installing graphene using pip it creates an examples directory in site-packages with the star wars example schema.

I feel like it's improper to add a base examples directory. Either it should not be added or placed inside the graphene directory.

Steps to reproduce:

Start empty pipenv project

Run `pipenv install graphene`

In a python file: `from examples.starwars.schema import schema`

**Comment by radekwlsk** [comment]
@marnixlenoble @jkimbo I've found that issue cause in `setup.py` and I could fix it.  Unfortunately there seems to be no easy way to make package `examples` an optional dependency when it is in the same repository. 
Maybe it will be a good idea to separate examples from main package and then it could be added as `extras_require={"examples": ["graphene-examples"]}`? Is it even necessary to allow installation of examples or are they here only for documentation purposes?

**Comment by Mc01** [comment]
Seems like good starting point for `cleanup package content and setup.py` PR 😉 
@radekwlsk maybe you should provide solution proposal as new pull request with label `enhancement`?

**Comment by radekwlsk** [comment]
@jkimbo #1187 resolved this issue, you may link the two together and close it.

**Comment by jkimbo** [comment]
Yep this can be closed now.
