### ISSUE TITLE
DataLoader doesn't work

### ISSUE THREAD

**Issue by pollaro** [graphql-python/graphene#1113]
I've tried to implement the DataLoader in my schema. I've attempted a very simple implementation before I go more complex. It's very very similar to the documentation. Unfortunately, it goes through and creates all the Promises, but it doesn't batch them all together. It just runs them sequentially.

**Comment by slopeofhope81** [comment]
could I see an example please?

**Comment by pollaro** [comment]
Here's the part of the schema:
```   
def resolve_billing(self, _info):
        loader = PatientStatementsByPatientIdLoader()
        statements = loader.load(self.id)

        return PatientBillingType(
            statement_balance_timestamp=self.statement_balance_timestamp,
            statement_balance=self.statement_balance,
            cashpayments=CashPayment.objects.filter(
                patient=self, doctor_id=_info.context.effectiveUserProfile.doctor_id
            ),
            patient_billing_statements=statements,
        )```

and here's the loader:
```
set_default_scheduler(GeventScheduler())

class PatientStatementsByPatientIdLoader(DataLoader):

    def batch_load_fn(self, patient_ids):
        stmts = {}
        for statement in PatientBillingStatement.objects.filter(patient_id__in=patient_ids):
            if statement.patient_id not in stmts:
                stmts[statement.patient_id] = [statement]
            else:
                stmts[statement.patient_id].append(statement)
        return Promise.resolve([stmts.get(id, []) for id in patient_ids])
```

And here's the painful part: Python2.7, graphene 2.1.6

**Comment by syrusakbary** [comment]
@pollaro the loaders needs to be declared outside the resolver, otherwise it will not be able to batch.

You can do it by setting the loader globally (not recommended), or in the `info.context` (recommended)


```python
loader = PatientStatementsByPatientIdLoader()

def resolve_billing(self, _info):
        statements = loader.load(self.id)

        return PatientBillingType(
            statement_balance_timestamp=self.statement_balance_timestamp,
            statement_balance=self.statement_balance,
            cashpayments=CashPayment.objects.filter(
                patient=self, doctor_id=_info.context.effectiveUserProfile.doctor_id
            ),
            patient_billing_statements=statements,
        )
```

Hope this helps!

**Comment by pollaro** [comment]
This still doesn't work.

Does it not work on Python 2.7? Is there something special I need to do?
