### ISSUE TITLE
How can I add comparison operators to filter data using Graphene?

### ISSUE THREAD

**Issue by jrajak10** [graphql-python/graphene#1114]
I am trying to find a way to create comparison operators for a GraphQL query. I have come across an example website, where you are able to filter the results based on whether an item is less than a certain value.The query is below:

  ```
all_product (where: {size_lt: 20}){
    items {
      title
      price_in_usd
      color
        size

    }
  }
}
```
And the full url is here: https://www.contentstack.com/docs/apis/graphql-content-delivery-api/explorer/?api_key=blt20962a819b57e233&access_token=cscd5a86465a89929407f8fd9c&environment=production&query=query%20%7B%0A%20%20all_product%20(where%3A%20%7Bsize_lt%3A%2020%7D)%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20title%0A%20%20%20%20%20%20price_in_usd%0A%20%20%20%20%20%20color%0A%20%20%20%20%20%09size%0A%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

What I want to know is how you can resolve the 'where' (in all_products when you click on Docs) filter using graphene/python. I can't figure it out, and the documentation for Graphene is so vague I don't know where to start...

**Comment by jkimbo** [comment]
@jrajak10 Graphene doesn't provide anything out of the box for this because doing filtering well depends on the underlying data source. You might want to check out Graphene Django and it's integration with the Django filter library: http://docs.graphene-python.org/projects/django/en/latest/filtering/
