### ISSUE TITLE
Add support for `NullValue`

### ISSUE THREAD

**Issue by staticfox** [graphql-python/graphene#1121]
Hello,

I'm running in to the following error when trying to use the `null` keyword:

```
Syntax Error GraphQL (2:29) Unexpected Name "null"
```

I seem to recall a PR opened years ago that added support for null, but it looks like all development focus has shifted towards v3 of this library. Unfortunately, v3 will not be compatible for me as there seems to be no progress for v3 compatibility towards graphene-sqlalchemy and flask-graphql. Are there any plans to support `null` for the current version of this library?

**Comment by jkimbo** [comment]
Unfortunately graphql-core v2 is no longer under active development so it’s unlikely that support for null will be implemented in that version. V3 does have support for null (plus lots of other improvements) and work is on going to release v3 of graphene which supports it. 

Any help with updating graphene-sqlalchemey and flask-graphql to use graphene v3 would be most appreciated! Work has already started to update graphene-django: https://github.com/graphql-python/graphene-django/pull/812
