### ISSUE TITLE
Login Required for specific group of queries and mutations

### ISSUE THREAD

**Issue by viperfx** [graphql-python/graphene#1122]
The docs show that LoginRequired can be applied to the whole graphql layer. 

Using http://docs.graphene-python.org/projects/django/en/latest/authorization/#adding-login-required

What I am looking to have is a group of graphql mutations and queries that are required to be login required. 

Here are some common use cases why a group of non-login required mutations and queries may be needed:
- Password forget
- Login required
- Fetching data (that is not tied to a user)

How can this be achieved with graphene?

**Comment by dudanogueira** [comment]
Hi! If using django-graphql-jwt, you have a @login_required decorator and can restrict the access as a per query/mutation manner:

https://django-graphql-jwt.domake.io/en/latest/decorators.html

I am not an expert on graphql nor graphene, but hope I have helped :)
