### ISSUE TITLE
Graphiql Offline *.js Support

### ISSUE THREAD

**Issue by usmcamp0811** [graphql-python/graphene#1125]
I just tried to spin up an API at work on an offline server and found out that Graphene is using CDNs for Graphiql. How can I use Graphiql without being able to get to the CDNs? Can we include the *.js files with the Graphene install?

**Comment by usmcamp0811** [comment]
I just got it to work in my environment after some slight modifications.. I'm going to do a fork and make a pull request with my results as I think this is something that is important. Not everyone can trust to have CDNs always available in their environment.

**Comment by usmcamp0811** [comment]
My pull request is [here](https://github.com/graphql-python/flask-graphql/pull/69)

**Comment by jkimbo** [comment]
@usmcamp0811 if you need offline access to graphiql then I would recommend using a desktop client like [insomnia](https://insomnia.rest/) or [graphql-playground](https://github.com/prisma-labs/graphql-playground) or [altair](https://altair.sirmuel.design/)
