### ISSUE TITLE
how to use distinct?

### ISSUE THREAD

**Issue by YankeeTube** [graphql-python/graphene#1131]
i use flask and sqlalchemy.
and i have hashtag table

but i want to hashtag distinct and count.

```sql
select distinct count(hashtag) from tag_table;
```

**Comment by Cito** [comment]
You probably want `select count(distinct  hashtag) from tag_table` instead.

But this question is a about SQLAlchemy or SQL in general, it has nothing to do with graphene.

**Comment by ArjunSrR** [comment]
Hi Cito,

I am new to graphql, I have n column want to apply distinct on a single column based on query input and return that alone using graphene. Is that possible?

**Comment by Cito** [comment]
@ArjunSrR see #1462
