### ISSUE TITLE
Can't use JSON string as input 

### ISSUE THREAD

**Issue by simkessy** [graphql-python/graphene#1133]
I'm trying to write a test that takes in json as a value for one of my fields and it's failing: 

I wrote the mutation like this: 

```
        query = '''mutation {
            createScorecard(
                name: "Test Scorecard",
                creatorId: 395549257913,
                questionData: "[{\"title\":\"This is a test question\",\"description\":\"Test question description\",\"answers\":[{\"text\":\"Yes\",\"point\":50,\"autofail\":true},{\"text\":\"No\",\"point\":50,\"autofail\":false}]}]"
            ) {
                scorecard {
                    name
                }
                error
            }
        }'''
```

But i keep getting this error: 

> 
{'errors': [{'message': 'Syntax Error GraphQL (5:40) Expected :, found String ":"\n\n4:                 creatorId: 395549257913,\n5:                 questionData: "[{"title":"This is a test question","description":"Test question description","answers":[{"text":"Yes","point":50,"autofail":true},{"text":"No","point":50,"autofail":false}]}]"\n                                          ^\n6:             ) {\n', 'locations': [{'line': 5, 'column': 40}]}]}

**Comment by pollaro** [comment]
I think it's because you have the double quotes inside each other.
` questionData: "[{\"title\":\"This is a test question\"...` should probably be:
` questionData: "[{\'title\':\'This is a test question\'...`
