### ISSUE TITLE
Changing resolver in Mutation class

### ISSUE THREAD

**Issue by sydoluciani** [graphql-python/graphene#1163]
Changing mutate method to some thing else not working, and for a quick test just added resolver equal to mutate :
class CreatePerson(graphene.Mutation):
    class Meta:
        resolver = mutate

And still received error:
    resolver = mutate
NameError: name 'mutate' is not defined

Have tried changing mutate function name to different name matching the resolver value and still didn't work.

Is this the right way of changing resolver in Mutation class?

**Comment by art1415926535** [comment]
```python
def my_mutate(root, info):
    ...

class CreatePerson(graphene.Mutation):
    class Meta:
        resolver = my_mutate
```

**Comment by jkimbo** [comment]
Thanks @art1415926535 , that should fix your issue @sydoluciani .
