### ISSUE TITLE
AttributeError: 'InputField' has no attribute '_meta' when using graphene.List with graphene.InputField

### ISSUE THREAD

**Issue by estuelke** [graphql-python/graphene#1165]
I would like to be able to pass in a list of `InputObjectType`s when using a specific mutation, but I keep getting an error saying InputField has no attribute '_meta'.  I'm guessing it is similar to #157 in that I should pass `InputField` and not `InputField(...)` to `graphene.List`.  

So how would one go about passing a list of `BatchInput` objects nested inside the `CreateCompoundInput` object in a mutation?

This is how my current InputObjects are set up (the CompoundAttribute and BatchAttribute classes all have normal graphene objects):

```python
class CreateCompoundInput(InputObjectType, CompoundAttribute):
    batches = graphene.List(
        graphene.InputField(
            BatchInput,
            description='Batch information for this compound.'
        )
    )
```

```python
class BatchInput(InputObjectType, BatchAttribute):
    pass
```

If I remove `graphene.List` it works fine, but then I can only pass one at a time.

I also did some digging and in the stack trace it's throwing the error at this point:

> File "..\lib\site-packages\graphene\types\typemap.py", line 337, in get_field_type
>     return map.get(type._meta.name)

And I noticed other types inherit from `BaseType` which has the `_meta` attribute, but `InputType` does not inherit from that.

I'm also really new to graphene/graphql, so maybe I am on the wrong path.  Any help is appreciated.

Thanks!

**Comment by art1415926535** [comment]
`graphene.InputField` is superfluous.

```python

class CreateCompoundInput(InputObjectType, CompoundAttribute):
    batches = graphene.List(
        BatchInput,
        description='Batch information for this compound.'
    )
```

**Comment by jkimbo** [comment]
@art1415926535 is right, that should work @estuelke
