### ISSUE TITLE
Using mutation String argument with multiline text

### ISSUE THREAD

**Issue by realsuayip** [graphql-python/graphene#1169]
What's the proper way to send a multiline text to a mutation argument? Sending a text with newline characters causes  `Syntax Error GraphQL (xxx) Unterminated string`. Using this [reference](https://github.com/graphql/graphql-js/pull/926), I tried block strings, but it didn't really work.

Set up:

```
class WishTopic(Mutation):
    class Arguments:
        title = String()
        hint = String()

    feedback = String()
    ...
```

Query:
```
mutation {
  topic {
    wish(title: "foo", hint: """bar""") {
      feedback
    }
  }
}
```
Result:
`Syntax Error GraphQL (xxx) Expected Name, found String `

Am I missing something?

**Comment by jkimbo** [comment]
@realsuayip you probably want to pass the string as an argument to your mutation like this:

```python
mutation = """
mutation TestMutation($hint: String) {
  wish(title: "foo", hint: $hint) {
    feedback
  }
}
"""

results = schema.execute(
	mutation,
	variable_values={
		"hint": """
bar
""",
	}
)
```
