### ISSUE TITLE
Scalar types not valid in graphql-core

### ISSUE THREAD

**Issue by defrex** [graphql-python/graphene#117]
It can be handy to drop down to graphql-core types for low level things. However currently Graphene's scalar types don't pass graphql-core's type checking. This makes it hard to mix and match. Since Graphene is build on graphql-core, it seems like this should be doable.

Example of failing type check.
https://github.com/graphql-python/graphql-core/blob/master/graphql/core/type/definition.py#L7

**Comment by syrusakbary** [comment]
Hi @defrex, you have to transform the `graphene` types into the `graphql-core` internal types.

For that, just do:

```python
class MyType(graphene.ObjectType):
   ...

graphql_internal_type = schema.T(MyType)
```

**Comment by defrex** [comment]
@syrusakbary Thanks for the quick response! 

Where is that `schema` object coming from?

**Comment by syrusakbary** [comment]
@defrex the schema is your `graphene.Schema` instance.

Like in here: https://github.com/graphql-python/graphene/blob/master/examples/starwars/schema.py#L56

**Comment by defrex** [comment]
Ah, I see. I can't reference that from this point in the code without a circular import, since I'm still defining the schema. That's a good lead though on how to solve it though. I'll dig into the source there and see if I can work around the issue.

**Comment by syrusakbary** [comment]
For avoiding that, you can define the schema before any other type.
https://github.com/graphql-python/swapi-graphene/blob/master/starwars/schema.py#L12

And then set the root Query, Mutation and/or Subscription.
https://github.com/graphql-python/swapi-graphene/blob/master/starwars/schema.py#L173

**Comment by defrex** [comment]
That'll do. Thanks for the help once again.
