### ISSUE TITLE
Separate subscriptions

### ISSUE THREAD

**Issue by nihaals** [graphql-python/graphene#1179]
I would like to deploy to Cloud Run but the only service I can find that has serverless websockets is AWS API Gateway’s [websocket API](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/). I don’t have great knowledge on the AWS, JS nor the JS GraphQL ecosystems but I managed to find https://github.com/apollographql/apollo-server/issues/2129 which seems to cover ways to separate subscriptions to another service, like API GW, and then also running the websocket functions. I’m fairly new to GraphQL but the ability to be serverless and support subscriptions would be really useful (without using something very specific like AWS AppSync) and Python is my language of choice. Is there a way to do something like the packages mentioned in https://github.com/apollographql/apollo-server/issues/2129#issuecomment-538103219?

**Comment by rob-blackbourn** [comment]
Hi @nihaals,

Are you looking for a pure python client and server which supports GraphQL subscriptions?

**Comment by nihaals** [comment]
> Are you looking for a pure python client and server which supports GraphQL subscriptions?
I’m looking for a Python GraphQL server which supports a custom separated `Subscription` server, for example an AWS API Gateway Websocket API. I haven’t seen the exact response from a `Subscription` (request?), but from how it’s talked about in that issue it seems like you can supply a URL for the client to initiate a websocket connection with.

**Comment by rob-blackbourn** [comment]
@nihaals 

I still don't understand. I thinks there's a lot of what's behind this that I would have to learn to get your question. My intuition is that there is a simple solution, if we could get to a common understanding.

What is a "custom separated subscription server"?

With graphene and a web framework you can bring up a server with a specific url with which subscriptions can be made. If this is the answer, the question is more about finding a web server/framework that supports subscriptions at a custom end point?

**Comment by nihaals** [comment]
To avoid XYing, I'll just explain the problem I'm trying to solve.

I'm using serverless compute quite a lot at the moment (specifically Cloud Run), but all of the serverless compute options use short lived connections. Each request is designed to be closed after a short period of time. This is in Cloud Run, Cloud Functions, Lambda and others.

Despite short lived connections, you can still host a GraphQL server fine, even as a (gateway/proxy? I'm not sure what to call it but [Apollo Server](https://www.apollographql.com/docs/apollo-server/) describes it) to combine multiple datasources.

However, the more problem is you can't host subscriptions. You could have your own logic for this and only use GraphQL for queries and mutations, but it's nice to have everything using one system that can be used with plenty of existing clients.

There is **1** good serverless HTTP streaming service: AWS API Gateway WebSocket API. I've always found AWS' docs horrible, but some links:
https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html

This provides a way to have serverless WebSocket connections. This works fine if you don't use GraphQL Subscriptions as you just use it as you would a random WS server, just it has a different domain. However, I would like to integrate it with GraphQL Subscriptions. As I said before, I'm very new to GraphQL so I'm not sure if this is even possible, but my hope is that the way Subscriptions work is you are given a URL you can use to initiate the connection instead of the GraphQL endpoint returning a `101` (as this would mean my idea is impossible without a proxy which defeats many of the advantages of serverless e.g. pay for what you use).

If subscriptions *do* return some kind of response which is then used to initiate a connection, then my idea is possible: simply have the server return the API Gateway URL.

If this is the case, I guess I'm asking how to use graphene to return this custom URL (could also have some unique tokens as the query string for authentication).

**Comment by nihaals** [comment]
Does my explanation make sense?
