### ISSUE TITLE
Defining Queries With Custom Directive

### ISSUE THREAD

**Issue by melvinkcx** [graphql-python/graphene#1194]
I'm trying to integrate [graphql-utilities](https://graphql-utilities.readthedocs.io/en/latest/) with Graphene. I stumbled upon a roadblock trying to define the following schema in Graphene, considering a custom directive `@cost`  is created with `graphql-core>=3.0`.

Any input on how to define the following schema with Graphene would be very much appreciated.

```
interface TimestampedType {
    createdAt: String @cost(complexity: 2)
    updatedAt: String @cost(complexity: 2)
}

type Announcement implements TimestampedType {
    createdAt: String
    updatedAt: String
    announcementId: String! @cost(complexity: 4)
    title: String
    text: String
}
```

**Comment by japrogramer** [comment]
https://github.com/graphql-python/graphql-core/blob/master/graphql/type/directives.py

**Comment by melvinkcx** [comment]
@japrogramer  Thanks for replying, but the link doesn't seem to be working. I am able to define a custom directive after consulting the source code, but I'm stuck trying to define the following object type in Graphene: 
```
type Post {
            postId: ID!
            title: String
            lastSnapshot: String @cost(complexity: 8)
}
```
The closest I could get is:

```
        class Post(graphene.ObjectType):
            post_id = graphene.ID()
            title = graphene.String()
            last_snapshot = graphene.String()
```

 I'm not sure how to specify the field `lastSnapshot` with my `@cost` directive. Any input would be lovely!

**Comment by japrogramer** [comment]
https://github.com/graphql-python/graphql-core/tree/master/src/graphql/type
look at the directives.py 

Can you post how you defined your directive?

**Comment by melvinkcx** [comment]
@japrogramer [Here](https://github.com/melvinkcx/graphql-utilities/blob/master/graphql_utilities/directives.py) is the source code of my directive.

With some input from the community of Slack, it appears that what I'm looking for is not possible at the moment. [Here](https://github.com/melvinkcx/graphql-utilities/blob/master/graphql_utilities/directives.py) is a similar discussion in

**Comment by japrogramer** [comment]
@melvinkcx it's possible in strawberry and it should also be possible in graphene


https://github.com/strawberry-graphql/strawberry/blob/master/CHANGELOG.md

**Comment by melvinkcx** [comment]
@japrogramer I've never came across Strawberry. Yes, you are right, this [snippet](https://github.com/strawberry-graphql/strawberry/blob/6d3af7068f5bf4b20949669b4e55dae92b694a9a/strawberry/directive.py#L31) is how Strawberry implements its `directive` decorator. 

I can't seem to find the documentation though, how would you annotate a field with a directive in Strawberry?

**Comment by japrogramer** [comment]
do you mean this?
```
import strawberry
from strawberry.directive import DirectiveLocation

@strawberry.type
class Query:
    cake: str = "made_in_switzerland"

@strawberry.directive(
    locations=[DirectiveLocation.FIELD], description="Make string uppercase"
)
def uppercase(value: str, example: str):
    return value.upper()

schema = strawberry.Schema(query=Query, directives=[uppercase])
```

**Comment by melvinkcx** [comment]
Yes, I was referring to the second snippet:

```
type Query {
            cake: String @uppercase(value: "Something")
}
```

How would you define it in Strawberry?

**Comment by japrogramer** [comment]
seems to me that the firs snippet answers that.

It creates a Query with a str field
then a directive is defined and it is allowed in fields, the function uppercase defines the parameters to the directive and a return value.

I haven't tried it but i think the first parameter is what the type returned for the field.

**Comment by japrogramer** [comment]
@melvinkcx 
```
@strawberry.type
class Review:
  body: str = strawberry.field(directives=[uppercase(example="username")])
  product: Product

```

**Comment by melvinkcx** [comment]
@japrogramer I don't think that is possible with strawberry, `strawberry.field()` doesn't accept `directives` as keyword argument, as defined here: https://github.com/strawberry-graphql/strawberry/blob/6d3af7068f5bf4b20949669b4e55dae92b694a9a/strawberry/field.py#L272

**Comment by japrogramer** [comment]
@melvinkcx oh i saw it here: https://github.com/strawberry-graphql/strawberry/issues/115#issue-473445600

last comment on that issue is him saying he will add examples soon.
