### ISSUE TITLE
Support generation of graphql query from ObjectType

### ISSUE THREAD

**Issue by jnoortheen** [graphql-python/graphene#1196]
**Is your feature request related to a problem? Please describe.**
It is hard to write grqphql query as strings without any syntax validation during tests.
```
query = '''query { 
  ...
 }'''
```

**Describe the solution you'd like**
If it is possible to automatically generate the graphql queries from `ObjectType ` classes, then this overhead can be minimized. Also is it possible to incorporate something similar to [quiz](https://quiz.readthedocs.io/en/latest/guide.html#constructing-graphql) 's way of constructing queries?

**Comment by jkimbo** [comment]
@jnoortheen constructing graphql queries is out of scope for the Graphene library. Graphene is only concerned with creating graphql servers. You might want to look at [gql](https://github.com/graphql-python/gql) as a way of creating graphql queries.
