### ISSUE TITLE
Date Scalar exception via value_from_ast utility function

### ISSUE THREAD

**Issue by paultop6** [graphql-python/graphene#1199]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**
When passing variables to the graphql query, there is an exception raised when trying to use Date Scalar.  This originates in value_from_ast utility function.  When variables are defined, it calls type_.parse_literal(value_node, variables), but the Date.parse_literal function definition can only handle one parameter (value_node)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar.
https://repl.it/repls/FlickeringAggravatingInterchangeability#main.py

* **What is the expected behavior?**
Should be able to handle variables without issue

* **What is the motivation / use case for changing the behavior?**
Fix bug

* **Please tell us about your environment:**

  - Version:
3.0.0b2
  - Platform:
Ubuntu 18.04, python 3.7.6

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by robjampar** [comment]
yeah I am getting the same issue

**Comment by Cito** [comment]
The `parse_literal` method expects the variables to be passed since GraphQL.js 0.12, but this was only ported to GraphQL-core v3, not to GraphQL-core v2. So the Scalars in Graphene v3 need to be adapted in that regard. We should also add some tests for this.

**Comment by Cito** [comment]
See pull request #1200 with fix and additional tests for this issue.

**Comment by syrusakbary** [comment]
This should now be fixed in `master` thanks to #1200. Closing the issue
