### ISSUE TITLE
[Minor] Improve performance of homepage animation.

### ISSUE THREAD

**Issue by bigblind** [graphql-python/graphene#120]
Because of my visual impairment, I use the mac's built-in zoom functionality. When I visit the Graphene homepage, my mouse movement using zoom gets a bit stuttery. I'm assuming this is because of the animation on the home page. It doesn't happen on any other page of the site.

Note that this is just a minor annoyance for me, so unless it's bothering anyone else, don't give it too muc priority.

**Comment by syrusakbary** [comment]
Hi @bigblind! Sorry for taking long time for fixing this.

Now the home page have no animation on it, so it should be faster and easier to browse!
