### ISSUE TITLE
Question regarding UUID returned by schema.execute

### ISSUE THREAD

**Issue by cglacet** [graphql-python/graphene#1202]
I struggle finding a way to retrieve my identifiers from base (UUID) using a simple query: 

```graphql
findUser(login: "cglacet"){ id }
```

The ID for this user is supposed to be `6ed2b747-e6bd-4853-b7a1-e3f611549940`, but I get the following result: 

```json
{
    "data": {
        "findUser": {
            "id": "VXNlcjo2ZWQyYjc0Ny1lNmJkLTQ4NTMtYjdhMS1lM2Y2MTE1NDk5NDA="
        },
    }
}
```

I investigated a bit and it seems that the problem arise somewhere between the result I get in my resolver (which has the correct ID value) and the schema.execute return value (which doesn't have the correct ID value).

### Model/schema

For context, here are my model and schema:

```python
class User(database.Base):
    __tablename__ = 'users'

    id = Column(UUID(as_uuid=True), primary_key=True, nullable=False, default=uuid.uuid4)
    login = Column(String(100), nullable=False, index=True, unique=True)
    password = Column(String(60), nullable=False)

    @validates('password')
    def validate_password(self, key, raw_password):
        return bcrypt.hash(raw_password)
```

```python
class User(SQLAlchemyObjectType):
    class Meta:
        model = models.User
        interfaces = (relay.Node, )
```

### UUID from within the resolver

From within the resolver I get the expected UUID (the one stored in my postgres database):

```python
class Query(graphene.ObjectType):
    
    find_user = graphene.Field(lambda: User, login=graphene.String())
    
    def resolve_find_user(self, info, login=None):
        query = User.get_query(info)
        user = query.filter(models.User.login == login).first()
        logging.info(f"Resolver user.id = {user.id}")
        return user
```

```bash
INFO:     Resolver user.id = 6ed2b747-e6bd-4853-b7a1-e3f611549940
```

### UUID output from execute

When using executing the query from `schema`:

```python
result = schema.execute("""{
    findUser(login: "cglacet"){
        lastname,
        id
    }
}""")
logging.info(f"Schema user.id = {result.data['findUser']['id']}")
```

Outputs: 

```bash
INFO: Schema user.id = VXNlcjo2ZWQyYjc0Ny1lNmJkLTQ4NTMtYjdhMS1lM2Y2MTE1NDk5NDA=
```

Am I doing something wrong? Or is this the expected behaviour, couldn't find any information on this and I struggle finding what is causing this.

**Comment by jkimbo** [comment]
@cglacet the `relay.Node` interface defines `id` as a base64 encoded ID of the `type:id`:

```python
base64.b64decode("VXNlcjo2ZWQyYjc0Ny1lNmJkLTQ4NTMtYjdhMS1lM2Y2MTE1NDk5NDA=").decode("utf8") == "User:6ed2b747-e6bd-4853-b7a1-e3f611549940"
```

If you don't need to use Relay ID's I would suggest that you remove the relay.Node interface from your `User` type.

**Comment by cglacet** [comment]
Oh ok, thanks a lot! From what I understand having this particular form for ID is a standard?

On the other hand does that mean that ID is converted on the flight every time I make a request to my user's ID? If that's the case, suppose I have a code like this to retrieve a user base on its UUID: 

```python
class DeleteUser(graphene.Mutation):
    ok = graphene.Boolean()

    class Arguments:
        user_id = graphene.UUID()

    @classmethod
    def mutate(cls, root, info, user_id=None):
        user_row = User.get_query(info).filter(models.User.id == user_id)
        nb_deletions = user_row.delete(synchronize_session=False)
        return cls(ok=(nb_deletions == 1))
```

This work without any problem, but on the other hand I can't access the real id from the outside (the UUID is converted on the flight to the base64 ID). So am I supposed to convert my UUID to get the user? (that works as intended for me, but that also looks very odd)

```python
class DeleteUser(relay.ClientIDMutation):
    ok = graphene.Boolean()

    class Input:
        user_id = graphene.String()

    @classmethod
    def mutate_and_get_payload(cls, root, info, **input):
        real_id = base64.b64decode(input['user_id']).decode("utf8").split(':')[1]
        user_row = User.get_query(info).filter(models.User.id == real_id)
        nb_deletions = user_row.delete(synchronize_session=False)
        return cls(ok=(nb_deletions == 1))
```

In particular `real_id = base64.b64decode(input['user_id']).decode("utf8").split(':')[1]` is very strange to write in the code, isn't a way to hide that? Since the UUID converted automatically on the way out I guess there is a way to convert it automatically when it comes as input too? 

Am I missing something here?

**Comment by jkimbo** [comment]
There is a helper function you can import from `graphql_relay` to make the conversion easier:

```python
from graphql_relay import from_global_id

type, id = from_global_id(global_id)
```

It's up to you how you want your client to communicate with your server. As I said before if your client doesn't use relay you don't need to use the `relay.Node` interface at all. Relay requires it so that it can uniquely identify an item in the graph but it is completely optional and Graphene works fine without it.

**Comment by cglacet** [comment]
Yes I understood that it isn't required, but for now I don't know what client I'll use so I prefer to understand both options :). Thanks for helping, that's still not perfectly clear to me how things interact within graphene, but mistake after mistake I'll probably understand it better.

**Comment by jkimbo** [comment]
That looks like a good way of doing it 👍
