### ISSUE TITLE
Should Mutation.mutate be @staticmethod or not

### ISSUE THREAD

**Issue by vshih** [graphql-python/graphene#1205]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**

https://github.com/graphql-python/graphene/blob/master/docs/types/mutations.rst#L22

does not specify the `@staticmethod` decorator, vs.

https://github.com/graphql-python/graphene/blob/master/docs/types/mutations.rst#L107

does.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar.

* **What is the expected behavior?**
One or the other.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Platform:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by jkimbo** [comment]
@vshih the staticmethod decorator is not required for the mutate method. Graphene will convert it to a static method automatically.
