### ISSUE TITLE
Compose Queries like in Apollo

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/graphene#1207]
I have some mutations/queries that i want to compose into a single query/mutation.

for ex.
```
organization = """
mutation ( $organization: OrganizationInput!) {
  Organization: createOrfOrganization (details: $organization) {
    obj {
      id
    }
    status
    errors
  }
}
"""

taxonomy = """
mutation ($taxonomy: TaxonomyInput!) {
  Taxonomy: createOrfTaxonomy (details: $taxonomy) {
    obj {
      id
    }
    status
    errors
  }
}
"""
```

I would like to have a function that can take the code above and do something like this
```
>>> compose(organization, taxonomy)
mutation ( $organization: OrganizationInput!, $taxonomy: TaxonomyInput!) {
  Organization: createOrfOrganization (details: $organization) {
    obj {
      id
    }
    status
    errors
  }
  Taxonomy: createOrfTaxonomy (details: $taxonomy) {
    obj {
      id
    }
    status
    errors
  }
}
```

This is an important feature that the python code should support.

**Comment by jkimbo** [comment]
I don't think this is in scope for the Graphene library. Graphene is a library to build graphql servers not clients. You might want to create this issue on the [gql](https://github.com/graphql-python/gql) library instead.
