### ISSUE TITLE
When raise exception I got graphql error

### ISSUE THREAD

**Issue by Bunlong** [graphql-python/graphene#1217]
I just move from using `responder` library to `starlette`. I got the graphql error when I raise exception.

Server:

```js
app = Starlette(debug=True, routes=[
    Route('/', show_version),
    Route('/healthz', check_health),
    Route('/graphql', GraphQLApp(schema=schema)),
])

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=9090)
```

Schema:

```
...

raise Exception('Something wrong')

...
```

Error:

![Screenshot from 2020-06-24 13-40-48](https://user-images.githubusercontent.com/1308397/85851238-80cda080-b7d8-11ea-8f39-efef4aeff30f.png)

What I expect is it return error message `Something wrong`. instead of error above. 

- Version: 2.1.3
- Platform: Linux (Ubuntu)

**Comment by hnq90** [comment]
@Bunlong This isn't an issue of `graphene`, it belongs to starlette: https://github.com/encode/starlette/blob/master/starlette/graphql.py#L114

**Comment by Bunlong** [comment]
@hnq90 Yes, I got it. I will close the issue now. Thanks :pray:
