### ISSUE TITLE
Schema.introspect fails when using AsyncioExecutionMiddleware

### ISSUE THREAD

**Issue by Wesitos** [graphql-python/graphene#122]
The instrospect method implies that the return value of `Schema.execute` is of type `ExecutionResult` when it depends of the execution midddleware.
```python
def introspect(self):
    # This fails with the AsyncioExecutionMiddleware
    return self.execute(introspection_query).data
```
One workaround could be to temporarily changing the execution middleware to the `SynchronousExecutionMiddleware` before doing the instrospection query.
```python
def introspect(self):
    old_executor = self.executor
    self.executor = None
    response = self.execute(introspection_query)
    self.executor = old_executor
    return response.data
```

**Comment by syrusakbary** [comment]
I believe this is not longer an issue, as the executors are now standarized using `Promise`s.
Please reopen if you see any issue with the latest version.

**Comment by SmileyChris** [comment]
Iiiiiiiiiiiiiiiiiiiii

**Comment by SmileyChris** [comment]
Iiiiiii
