### ISSUE TITLE
No type verification

### ISSUE THREAD

**Issue by tobiasfeil** [graphql-python/graphene#1222]
When I define a class like this
```
class Person(graphene.ObjectType):
    age = graphene.Int()
```
and later instantiate it like this:
```
Person(age='five')
```
no type error is thrown, even though I specified that age should be an Int.

I suppose this is not on purpose?

**Comment by syrusakbary** [comment]
Type errors are thrown at resolution time (when you resolve a query) rather than object instantiation time (when you instantiate an object).
I think both are equivalent, you will never end resolving:
```graphql
{
  person {
    age
  }
}
```
with:
```json
{
  "person": {
    "age": "five" // THIS CAN NEVER HAPPEN
  }
}
```

**Comment by syrusakbary** [comment]
BTW: we are working on adding type-safe schema generation from Python annotations, so at the end you can have also your codebase type-checked via mypy, for example.

**Comment by tobiasfeil** [comment]
Thanks for the swift reply! Sounds good. And very cool about the type annotations, I'm excited about that!
