### ISSUE TITLE
Does graphene support multiple input types

### ISSUE THREAD

**Issue by shmilyhurt** [graphql-python/graphene#1228]
Hi, I maybe need this:

```
query GetData{
   name(a:"www")
}
```
and

```
query GetData{
   name(a:{"host":"www"})
}
```

Is there any way to support multiple input types？
thanks！

**Comment by jkimbo** [comment]
@shmilyhurt unfortunately not. The GraphQL spec does not support unions as input types though there does seem to be a proposal to add it: https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md

If that gets implemented in the future then we'll support it but until then you will have to use multiple inputs for different input types.
