### ISSUE TITLE
[Documentation] Don't use "name" field for hello world example

### ISSUE THREAD

**Issue by alexanderqchen** [graphql-python/graphene#1230]
**Is your feature request related to a problem? Please describe.**
I'm a new user and while reading through the getting started page of the docs, I was confused by the `name` input into the Scalar. `name` here acts as an input for the resolver, but `name` is also used to set a custom name for the field.

Here are the two different uses for `name` within the first 1 pages of docs:
https://docs.graphene-python.org/en/latest/quickstart/#creating-a-basic-schema
https://docs.graphene-python.org/en/latest/types/schema/#auto-camelcase-field-names

**Describe the solution you'd like**
Don't use the input `name` on the getting started page in the documentation. Use `fullName`, `firstName`, etc. instead.

**Describe alternatives you've considered**
Another option is to mention this behavior in the docs when introducing custom field names, but I feel like this would be less concise.

**Additional context**
![image](https://user-images.githubusercontent.com/12878275/87574720-a46f6280-c683-11ea-982f-044174f56aef.png)
![image](https://user-images.githubusercontent.com/12878275/87574740-aa654380-c683-11ea-8571-74e2722efdce.png)
Line 5 and line 3 of these images are what I'm referring to. These screenshots are from the links above.

**Comment by jkimbo** [comment]
This is a very good point @alexanderqchen , thanks for raising.
