### ISSUE TITLE
"Development Status" is still set to Alpha

### ISSUE THREAD

**Issue by remko** [graphql-python/graphene#1248]
I noticed that the PyPI listing and the setup.py metadata lists this project as 'Alpha' quality. I also noticed that version 3.0 is coming up, so I was wondering if this still is valid?

**Comment by skewty** [comment]
Is v3 the code in master branch?  I see a v2 branch and next/master so I am a bit confused.

Does v3 branch get created only on release?
Is next/master not v3?

**Comment by jkimbo** [comment]
@skewty the code in the master branch is the v3 version. The next/master branch is out of date now. 

It does look like the setup.py for v2 still lists the project as Alpha quality which is just an oversight. Thanks for raising it @remko

**Comment by erikwrede** [comment]
fixed
