### ISSUE TITLE
incompatible JSONField  for django 3.1

### ISSUE THREAD

**Issue by hyusetiawan** [graphql-python/graphene#1249]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**
Django 3.1 has a common JSONField that applies to all db not just postgres. I changed the field from django.contrib.pg version to 3.1 common JSONField (as suggested by the warning when you `./manage.py runserver`), the converter throws the following error:
`Exception: Don't know how to convert the Django field api.ObjectInstance.content (<class 'django.db.models.fields.json.JSONField'>)`

**Comment by ekampf** [comment]
@hyusetiawan this is actually a `graphene-django` issue and is already fixed there: https://github.com/graphql-python/graphene-django/commit/67a0492c124587a98435621565c00b3f9e9053f1

**Comment by ekampf** [comment]
Closing issue here but you can discuss it on the [graphene-django](https://github.com/graphql-python/graphene-django/pulls) repo.
The fix is merged to `master` so you will need to upgrade to v3 to get it.
