### ISSUE TITLE
Postgres specific fields for Django 

### ISSUE THREAD

**Issue by mamaar** [graphql-python/graphene#125]
Django supports [PostgreSQL specific model fields](https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/) and it would be nice to use them with Graphene. I'd like to try implementing the ones I use, but need some directions on where/how to begin.

I'm looking to query the lower and upper bounds of range fields.
```
rangeField {
    lower
    upper
}
```

**Comment by lightning18** [comment]
If you want to try, you can start here: https://github.com/graphql-python/graphene/blob/master/graphene/contrib/django/converter.py

**Comment by syrusakbary** [comment]
@mamaar I'm currently implementing that.
I'm thinking about to return the `rangeField` in the query as a `List` rather than an `ObjectType`.

So you could query like:
```
{
    event {
        ages
    }
}
```
returning
```json
{
    "event": {
        "ages": [0, 10]
    }
}
```

Thoughts?

**Comment by syrusakbary** [comment]
Hi @mamaar,

I finally added support for postgres `RangeField`s (and `ArrayField`, `JSONField` and `HStoreField`).
It will output the field data as a js list with two elements `[lower, upper]`.

You can try it in the last version of `graphene==0.8.0` :wink:

**Comment by mamaar** [comment]
That's great, @syrusakbary !
Graphene is definitely a fantastic library.
