### ISSUE TITLE
How to document for GraphiQl

### ISSUE THREAD

**Issue by coler-j** [graphql-python/graphene#1258]
It would be nice to have some clear documentation about how to document your GraphQl API so that it will render documentation in the GraphiQl explorer.

I am coming back to Python after a bit of a hiatus and simple documentaiton on how to document you API would be useful. 

I would be happy to add a PR to the docs page if I knew how to document the API.

i.e.
- How to add a description to the types
- What formats are allowed (MD, etc.)
- How to document type fields etc.
- How to document mutation arguments
- How to document when using serializers or model forms etc.

For example:
- https://stackoverflow.com/questions/59876078/how-to-autodocument-graphql-query-in-graphene-django?r=SearchResults&s=2|95.0070

**Comment by erikwrede** [comment]
Documentation needs to be reworked. This will be tracked in a separate issue soon. If you are still interested in helping out, please keep an eye out on that! 🙂
