### ISSUE TITLE
Does relay.NodeField support many args more than "id" ?

### ISSUE THREAD

**Issue by gwind** [graphql-python/graphene#126]
Hi, guys

In `graphene/relay/fields.py` : 

```python
class NodeField(Field):
    # ...
    def id_fetcher(self, global_id, info):
        # ...
        return object_type.get_node(_id, info)

    def resolver(self, instance, args, info):
        global_id = args.get('id')
        return self.id_fetcher(global_id, info)
```

This define a `get_node` strictly, just global id could be used as arg. 

There is an example about other scene: 

[http://graphql-swapi.parseapp.com](http://graphql-swapi.parseapp.com/?query={%0A%20%20film%28filmID%3A%20%223%22%29%20{%0A%20%20%20%20id%0A%20%20%20%20title%0A%20%20}%0A%20%20allFilms%20{%0A%20%20%20%20edges%20{%0A%20%20%20%20%20%20node%20{%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20}%0A%20%20%20%20}%0A%20%20}%0A}%0A)

They define a more useful interface: 

```
film(id: ID, filmID: ID): Film
person(id: ID, personID: ID): Person
planet(id: ID, planetID: ID): Planet
species(id: ID, speciesID: ID): Species
starship(id: ID, starshipID: ID): Starship
vehicle(id: ID, vehicleID: ID): Vehicle
node(id: ID!): Node
```

It has a 'XXXID' arg in every node field. This is just what I wanted. It would be useful where a `NodeField` can queried by other args not just id.

Any help would be appreciated.
Thanks!

Refs:

- [Relay Global Object Identification Specification](https://facebook.github.io/relay/graphql/objectidentification.htm)

**Comment by mixxorz** [comment]
Did you find a workaround for this?

**Comment by mixxorz** [comment]
I've worked around the issue by using a regular `graphene.Field`, `id` plus other arguments, and doing some trickery in the resolve method.

```python
class GraphQuery(graphene.ObjectType):
    topic = graphene.Field(Topic, id=graphene.String(), slug=graphene.String())

    def resolve_topic(self, args, info):
        field = relay.NodeField(Topic)
        if args.get('id'):
            return field.id_fetcher(args.['id'], info)
        return get_topic(info, **args)
```

**Comment by mjtamlyn** [comment]
The [relay spec](https://facebook.github.io/relay/graphql/objectidentification.htm#sec-Node-root-field) explicitly states that a root node field must accept only a single argument of `id`.

You can have other [root fields](https://facebook.github.io/relay/graphql/objectidentification.htm#sec-Fields) which load data differently, but they have to fit with certain rules.

Of course if you are not building a GraphQL API for Relay, or your node is not at the root, then you can in theory do as you please.

**Comment by syrusakbary** [comment]
As @mjtamlyn commented, this will be probably not implemented in `graphene.relay` as is not in the relay spec.

Closing this issue.

**Comment by ulgens** [comment]
I made something for same need:

```
import graphene
from graphene.relay import Node
from graphene.types.field import Field


class SlugNodeField(Field):
    def __init__(self, node, type=False, deprecation_reason=None, name=None, **kwargs):
        assert issubclass(node, Node), "NodeField can only operate in Nodes"
        self.node_type = node
        self.field_type = type

        super(SlugNodeField, self).__init__(
            type or node,
            description="The ID of the object",
            id=graphene.ID(required=False),
            slug=graphene.String(required=False),
        )


class SlugNode(Node):
    @classmethod
    def Field(cls, *args, **kwargs):  # noqa: N802
        return SlugNodeField(cls, *args, **kwargs)

    @classmethod
    def node_resolver(cls, only_type, root, info, id=None, slug=None):
        if id and slug:
            raise ValueError("id and slug cannot be used together.")
        elif id:
            return cls.get_node_from_global_id(info, id, only_type=only_type)
        elif slug:
            model = only_type._meta.model
            return model.objects.get(slug=slug)
        else:
            raise ValueError("id or slug is required.")
```
In related query, it should be used as

```
class FilmQuery:
    film = SlugNode.Field(FilmNode)
```
