### ISSUE TITLE
Please add a utility to collapse whitespace in a query or mutation

### ISSUE THREAD

**Issue by spacether** [graphql-python/graphene#1268]
**Is your feature request related to a problem? Please describe.**
When apollo server receives queries from graphene, it collapses the whitespace in the query or operation, and then sends that updated query to the downstream graphql service.
If one needs to cryptographically sign the payload that is being sent and will be received, our sent and received payloads must be the same. This assumes that the query will be fulfilled by only one service.

**Describe the solution you'd like**
Please add a utility to collapse the whitespace in a query or mutation the same way that apollo-server does.
This will:
- reduce query and mutation sizes
- ensure that payloads are not mutated by Apollo Server

**Describe alternatives you've considered**
n/a

**Additional context**
When we generate a signature from a payload dict {query: blah, variables: blah}
we attach the signature as a header which is sent along with the payload to apollo server

**Comment by erikwrede** [comment]
`dedent` from `graphql-core` should do the job.
