### ISSUE TITLE
Graphene 3 dataloader

### ISSUE THREAD

**Issue by wakemaster39** [graphql-python/graphene#1273]
Current documentation for graphene on both the released site and the master branch have the promise based dataloader as the recommended method of using dataloaders.

Since promise is no longer included in the graphene and there is no thenable resolution in the chain anymore, how can dataloaders be executed in a synchronous application like flask? I found https://github.com/syrusakbary/aiodataloader which provided an async/await dataloader interface but flask doesn't support it out of the box.

I have hacked in a `loop.run_until_complete()` when executing a graphql request to try and enable dataloaders again but this seems suspect and that I am missing something.

**Comment by KingDarBoja** [comment]
Related to https://github.com/graphql-python/graphql-server/pull/66 as well 🚀

**Comment by jkimbo** [comment]
@wakemaster39 docs have been updated here: https://github.com/graphql-python/graphene/pull/1190
