### ISSUE TITLE
Middleware for Input and Output data from Graphql queries.

### ISSUE THREAD

**Issue by PetrShchukin** [graphql-python/graphene#1285]
I have react frontend and django backend, and transforming data to a camel case from a snake case and vise versa is pretty challenging. I'd like to have a middle where which going to apply camel case to output data and snake case for input data. How can I do that? I was able to add middleware like this:
```
GRAPHENE = {
    'SCHEMA': 'schema.schema',
    'MIDDLEWARE': [
        'utils.graphql_middleware.MyMiddleware',
    ]
}
```
But I can't get field values in middleware:
```
class MyMiddleware(object):
    def resolve(self, next, root, info, **args):
        print(info.field_name)

        return next(root, info, **args)
```
P.S. the challenge not in fields names, but in field data

**Comment by Speedy1991** [comment]
Can you give an example of your returned data and your expectations?

**Comment by PetrShchukin** [comment]
Sure. Let's say there is a JSON field in my model `my_answers = JSONField('answers')` which has format like this:
```
[
   {
      "text":"My answer1",
      "is_correct":true
   },
   {
      "text":"My answer2",
      "is_correct":false
   }
]
```
Graphene converts my_answer to myAnswers in GraphQL query and vice versa, which is perfectly fine. But as you can see in my json field there is s snake case (is_correct), when I query this data on front-end Graphene return original JSON, where snake case takes place. I'd like to have some kind of middleware to change data that comes to and out from Graphene. There is djangorestframework-camel-case package that does the same, I'm not sure if it's gonna work with Graphene but the idea is the same

**Comment by Speedy1991** [comment]
Sorry for the delay

If you use a JSON field you are fully responsible for its key/values - most times it is better if you write an own custom type (this will convert the keys defined in `MyType `to camel case by default)

```
import graphene

class MyType(graphene.ObjectType):
    text = graphene.String(required=True)
    is_correct = graphene.Boolean(required=True)
    example = graphene.String(required=True)

class Query:
    my_type = graphene.Field(MyType, required=True)

    def resolve_my_type(self, info):
        json_field = {"text": 'My answer 1', "is_correct": True, "random": "abc"}
        return MyType(text=json_field["text"], is_correct=json_field["is_correct"], example=json_field["random"])
```


However, you can convert the JSON data yourself recursively (`keep_value` keeps string values, just remove it if also string values should be converted):

```
import graphene
from graphene.types.generic import GenericScalar
from graphene.utils import str_converters

def to_camel_case(data, keep_value=False):
    if isinstance(data, str) and not keep_value:
        return str_converters.to_camel_case(data)
    if isinstance(data, dict):
        converted_data = dict()
        for k, v in data.items():
            converted_data[str_converters.to_camel_case(k)] = to_camel_case(v, isinstance(v, str))
        return converted_data
    if isinstance(data, list):
        return [to_camel_case(d) for d in data]
    return data

class Query:
    data = GenericScalar(required=True)

    def resolve_data(self, info):
        json_field = {"text": 'My answer 1', "is_correct": True, "random": "abc"}
        return to_camel_case(json_field)    
```

I would _not_ use a middleware, because this is a really bad sideeffect and as a developer I wouldn't expect to get the data resolved by a resolver to be manipulated by a middleware (IMO)

**Comment by PetrShchukin** [comment]
Thanks! That's a good example.
