### ISSUE TITLE
Custom serialization for UUIDs

### ISSUE THREAD

**Issue by bburtin** [graphql-python/graphene#1289]
Is there a way to override the default serialization for UUIDs (or any object type)?  In order to not serialize UUIDs with dashes, I'm having to do this for every UUID field:

```
    @staticmethod
    def resolve_id(parent: MyObject, info: graphene.ResolveInfo) -> str:
        return parent.id.hex
```

**Comment by Speedy1991** [comment]
Hi!
Sorry for the late reply.
You can just define your own custom Scalar (e.g. UUIDHex)
You can find information about this in the [docs](https://docs.graphene-python.org/en/latest/types/scalars/#custom-scalars)

**Comment by daniel-skale** [comment]
Just wondering if this is for a custom node implementation to replace the default relay.Node style b64 hashed IDs? If so I was also wondering how to implement a dictionary/table to map the UUID to the primary key of the models?

**Comment by Speedy1991** [comment]
Not sure if I get the point (I don't use relay), but you can define a serializer and a deserializer in the scalar. That means you can use UUIDHex values in your schema but query by a real UUID from your database, so there is no need to create a mapping dictionary/table
