### ISSUE TITLE
Field "myTests" argument "id" of type "ID!" is required but not provided.

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#13]
First of all great work on these sets of python libraries they really seem great so far :)

Anyway, just trying out graphene 0.1.6.0 (on python 2.7.x) with react/relay for the first time so might be some beginners mistake, But having

```py
class Test(relay.Node):

    custom_id = graphene.IDField(description='The id of the test.')
    test_name = graphene.StringField(description='The name of the test.')
    description = graphene.StringField(description='The description of the test.')
    test_type = graphene.StringField(description='What type the test has.')
    test_price = graphene.StringField(description='The price of each test.')
    test_clients = graphene.StringField(description='Number of test clients.')

    @classmethod
    def get_node(cls, custom_id):
        print('in get_node', custom_id)
        return Test(getTest(custom_id))

class Query(graphene.ObjectType):
    my_tests = relay.NodeField(Test,
                               customArg=graphene.Argument(graphene.String))
   all_my_tests = relay.ConnectionField(Test,
                                      connection_type=MyConnection,
                                      customArg=graphene.Argument(graphene.String))
  node = relay.NodeField()

    @resolve_only_args
    def resolve_my_tests(self, **kwargs):
        print('we are resolving all tests!')
        for key in kwargs:
            print('kwargs received', key, kwargs[key])
        return [Test(t) for t in getTests()]
```

I am managing to return some data with hand-written queries, but trying a query that react passes, e.g. 

```
result = schema.execute('''
        query TestsQuery {
            myTests (customArg:"1") {
                ...__RelayQueryFragment0pgs7aw
            }
        }
        fragment __RelayQueryFragment0pgs7aw on Test{custom_id,description,id}
        ''')
```

just throws the error `Field "myTests" argument "id" of type "ID!" is required but not provided.`. If I do provide an `id` field I get an error that it clashes:
```   
class Test(relay.Node):
  File "/usr/local/lib/python2.7/dist-packages/graphene/core/types.py", line 85, in __new__
    field_names[field.name].__class__)
Exception: Local field 'id' in class 'Test' (<class 'graphene.relay.fields.GlobalIDField'>) clashes with field with similar name from Interface Node (<class 'graphene.core.fields.StringField'>)
```

Any idea how to get around/fix this?

**Edit**: I made some progress using the `ConnectionField` but I suppose I am just a bit unsure what the best way forward is with graphene if I want to define a schema where I can show all tests I have but also query them for certain parameters such as name, type etc.

The need for a connection class (with its own fields) with `ConnectionField` seems a bit like an extra step I am not sure is necessary for what I am trying to do.

So I suppose what I am imagining is something like
```
query testsQuery {
  allTests(customArg: "1") {
    ...__RelayQueryFragment0pgs7aw
  }
}
fragment __RelayQueryFragment0pgs7aw on Test{custom_id,description, test_name, id}
```

Where-as right now I am creating on the fronend
```
query testsQuery{allTests(customArg:"1"){...__RelayQueryFragment0pgs7aw}} 
fragment __RelayQueryFragment0pgs7aw on TestMyConnection{
  edges{node{custom_id,description, test_name, id},cursor},
  pageInfo{hasNextPage,hasPreviousPage
}}
```

**Comment by Globegitter** [comment]
Sorry to keep on piling here, but seems I am running into this issue: https://github.com/facebook/relay/issues/112

**Comment by syrusakbary** [comment]
The easiest solution is add a viewer field to your query.
This is how SWAPI Graphene is dealing with it:
https://github.com/graphql-python/swapi-graphene/blob/master/starwars/schema.py#L143
https://github.com/graphql-python/swapi-graphene/blob/master/starwars/schema.py#L169-L170

Closing this issue, please reopen it if you think have something to do with this implementation.

**Comment by Globegitter** [comment]
@syrusakbary the example is great thanks, but how can I query the viewer now? I can't find any tests or examples about it.

E.g.
```
query{viewer{...__RelayQueryFragment0u3d70s}}fragment __RelayQueryFragment0u3d70s on allFilms{...}
```
just thorws me an error `[GraphQLError('Unknown type "allFilms".',)]`
I tried a few other queries as well but all not working so far. Will carry on playing around with it but an example would be much appreciated. Thanks!
