### ISSUE TITLE
relay.Connection.__init__ does not call super

### ISSUE THREAD

**Issue by miracle2k** [graphql-python/graphene#131]
https://github.com/graphql-python/graphene/blob/master/graphene/relay/types.py#L58

Is there a reason why not?

It seems to be the cause of a ``__init__() got an unexpected keyword argument '_root'"`` error I am getting using a ``ConnectionField`` and a custom ``relay.Connection`` subclass. There are some other things going in my code so it's not easy to post an example, but essentially, ``ConnectionField`` inherits ``Field``, and the wrapped resolver in ``Field.internal_type`` always wants to pass ``_root``.

**Comment by syrusakbary** [comment]
Sorry for taking some time in taking a look. I've been in vacations... but I'm back!

`relay.Connection` as you mentioned should call super. Fixing this now.
