### ISSUE TITLE
How to add GraphiQL or graphql graphene to 

### ISSUE THREAD

**Issue by SebastianKurpSyn** [graphql-python/graphene#1316]
Hi 👋 , 
New to graphql in python and I was wondering if there are ways to include to the graphql playground with out having to use the django or flask version of graphene. 
If it's not possible then I'm okay without it, but would like to try see if there's a way I could make the front ends devs life a bit eaiser.
I have been unable to find a tutorial or docs online so I figured I would ask at the source.

**Comment by jkimbo** [comment]
@SebastianKurpSyn you can follow the instructions for graphiql on their repo: https://github.com/graphql/graphiql/blob/main/packages/graphiql/README.md

Just change the url in the fetcher to be the url of your graphql endpoint.
