### ISSUE TITLE
Graphene Enum input returns EnumMeta instead of enum option value

### ISSUE THREAD

**Issue by fredgido** [graphql-python/graphene#1317]
Using Enum on input of mutation the value given to the mutation is not the value of the enum.

I expect only the value of the enum choise to be returned.

Using this for example on DjangoModelFormMutation breaks simplicift and workflow.

  - Version: v3.0.0b7
  - Platform: django, linux

See image below as in kwargs it is returned EnumMeta instead of value correspondent on enum.
![2021-03-20_23-59](https://user-images.githubusercontent.com/17598829/111888901-b8205500-89d8-11eb-88dd-2699b8cbd252.png)

**Comment by sbor23** [comment]
See https://github.com/graphql-python/graphene/issues/1277 and consider closing this.

**Comment by fredgido** [comment]
I see, I don't  understand the need for it to return the enum but if it is designed that way I will live with it. I used a mixin to get the value if any input is enum.
