### ISSUE TITLE
Compatibility with python 3.10 in v2

### ISSUE THREAD

**Issue by mhuin** [graphql-python/graphene#1339]
* **What is the current behavior?**

While v3 is compatible with python 3.10, v2 isn't. 

* **What is the expected behavior?**

The graphene library should release a version that is compatible with python 3.10.

* **What is the motivation / use case for changing the behavior?**

Some distros, for example Fedora, will switch to python 3.10 as the default python version on their next release. This library will therefore not work as is unless v3 is released before the switch happens.

* **Please tell us about your environment:**

  - Version: Rawhide
  - Platform: Fedora

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

Fix: https://github.com/mhuin/graphene/tree/fix_py310

**Comment by jrd** [comment]
Agreed. And this is a really simple fix : [Direct link to the commit from @mhuin](https://github.com/mhuin/graphene/commit/4e89e3c329f7f3f5b09c6852d4b514ad22576b96)

**Comment by jrd** [comment]
This is really simple to apply to the `v2` branch.
Could this be done and a version release to PyPI?
If it helps, I can create a merge request.

**Comment by jrd** [comment]
Here is pull request #1345

**Comment by jkimbo** [comment]
Released in v2.1.9
