### ISSUE TITLE
Support nullable types in graphene

### ISSUE THREAD

**Issue by wyajunjun** [graphql-python/graphene#1356]
**Is your feature request related to a problem? Please describe.**
Do we have null type in graphene? The example, the default value of `mode` is null is not pass null value, 

`mutation{
  insertModel(input:{
    modelName: "model1"
  })`
but some cases we need to pass null, the return error is "Syntax Error GraphQL (4:63) Unexpected Name \"null\"
`mutation{
  insertModel(input:{
    modelName: "model1"
    mode: null
  })`

**Describe the solution you'd like**
GraphQL supports null values, can graphene also support that? https://github.com/graphql/graphql-spec/pull/83

**Describe alternatives you've considered**

**Additional context**

**Comment by wyajunjun** [comment]
@jkimbo @Speedy1991 Can you help answer the questions?

**Comment by jkimbo** [comment]
@wyajunjun what version of graphene are you using?

**Comment by Speedy1991** [comment]
As far I know - I don't use graphene anymore - you can just say `required=False` and in your resolver you do something like this: `input.get('mode', None)`

**Comment by wodCZ** [comment]
You have to pass the `null` as a variable, not inlined in the GraphQL query.

![CleanShot 2021-08-11 at 15 47 15](https://user-images.githubusercontent.com/1174421/129040729-e2b9d3e7-0911-4ff1-bf50-a8fd02379994.png)

vs

![CleanShot 2021-08-11 at 15 48 23](https://user-images.githubusercontent.com/1174421/129040804-743dd5d3-5527-49c8-9217-284e50cb6445.png)

**Comment by jkimbo** [comment]
@wodCZ you're correct that in Graphene v2 that is the way to get it to work. However in Graphene v3, because it's using graphql-core v3, you can use `null` in the query directly: https://replit.com/@jkimbo/Graphene-v3#main.py

**Comment by ajgrover** [comment]
it is possible that the issue is the missing comma in the input? `{modelName: "model1" mode: null}`
