### ISSUE TITLE
Observed Concurrency in Mutation

### ISSUE THREAD

**Issue by KokeCacao** [graphql-python/graphene#1358]
* **What is the current behavior?**
When I create mutations, I observe that mutations run concurrently. (which ruins my database)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar.
I have created mutation like this
```
schema = graphene.Schema(query=Query, mutation=Mutation, auto_camelcase=True)
```

```
class Mutation(graphene.ObjectType):
    test = TestMutation.Field()
```

```
class TestMutation(graphene.Mutation):
    class Arguments:
        uuid = graphene.String(required=True)
        ... and more ...

    vocab_id = graphene.String()
    ... and more ...

    @staticmethod
    @mutation_jwt_required
    def mutate(parent, info, **kwargs):
        print("Enter mutation")

        ... code containing database modification and access ...
        ... race condition is detected here (enter mutation twice without exiting) ...

        print("Exit mutation")
        return TestMutation(...)
```

* **What is the expected behavior?**
According to GraphQL documentation, the mutation is run in sequential execution.

* **What is the motivation / use case for changing the behavior?**
I wonder if this behavior is intended.

* **Please tell us about your environment:**

  - Version: 
```
  - flask=1.1.2
  - flask-sqlalchemy=2.4.4
  - numpy=1.20.0
  - pandas=1.2.1
  - pip=20.3.3
  - python=3.7.3
  - sqlalchemy=1.3.22
  - sqlite=3.34.0
  - pip:
    - flask-graphql==2.0.1
    - flask-graphql-auth==1.3.2
    - graphene==2.1.8
    - graphql-core==2.3.2
    - graphql-relay==2.0.1
    - graphql-server-core==1.2.0
```

  - Platform: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by jkimbo** [comment]
@KokeCacao that shouldn't happen. What does your query look like?

**Comment by KokeCacao** [comment]
> @KokeCacao that shouldn't happen. What does your query look like?

Thank you for your quick response. Here is the `Query` class that I have passed in `graphene.Schema`
```
class Query(graphene.ObjectType, HelloWorldQuery, UserQuery):
    pass
```

**Comment by jkimbo** [comment]
No sorry I meant the graphql query that your client is sending.

**Comment by KokeCacao** [comment]
> No sorry I meant the graphql query that your client is sending.

```

    mutation {
        test(key: "secret key", action: "something") {
            success
        }
    }
```

With the full example above. You should be able to replicate this.

**Comment by jkimbo** [comment]
Oh I see. I think what's happening is that your server is just processing the 2 requests at the same time (which is should since they are sent at the same time). Graphene will only execute mutations sequentially in the same query but it doesn't attempt to do any kind of global locking to make sure that mutations can't be run concurrently by multiple clients. 

If you need that functionality then you should look into db table locking or using something like https://pypi.org/project/python-redis-lock/ to implement a locking mechanism inside your mutation.

**Comment by KokeCacao** [comment]
> Oh I see. I think what's happening is that your server is just processing the 2 requests at the same time (which is should since they are sent at the same time). Graphene will only execute mutations sequentially in the same query but it doesn't attempt to do any kind of global locking to make sure that mutations can't be run concurrently by multiple clients.
> 
> If you need that functionality then you should look into db table locking or using something like https://pypi.org/project/python-redis-lock/ to implement a locking mechanism inside your mutation.

I see. What does sequential mean in the context of a mutation? One request can only have one thread (instead of multiple threads) running? How is it differ from a query?

**Comment by jkimbo** [comment]
Sequential means that if a mutation operation has multiple mutations in it then each will be executed after each other (which is different to a regular query where each field might be executed in parallel). 

For example with this operation:

```
mutation {
  test() { success }
  anotherMutation() { success }
}
```

The `test` mutation will execute before `anotherMutation`. 

Does that make sense?

**Comment by KokeCacao** [comment]
> Sequential means that if a mutation operation has multiple mutations in it then each will be executed after each other (which is different to a regular query where each field might be executed in parallel).
> 
> For example with this operation:
> 
> ```
> mutation {
>   test() { success }
>   anotherMutation() { success }
> }
> ```
> 
> The `test` mutation will execute before `anotherMutation`.
> 
> Does that make sense?

Yes. It makes perfect sense. Thank you so much!
