### ISSUE TITLE
Date formating

### ISSUE THREAD

**Issue by sdcooke** [graphql-python/graphene#136]
JSON doesn't have a date format so dates in graphene are just string fields. This means any dates that are output without being formatted first (e.g. if you use a DjangoNode with only_fields where one of the fields is a date field) are just output as `unicode(date_object)` (which looks like `2016-03-29 17:42:01.683650+00:00`). If you take that date in JavaScript and do `new Date(myDateStr)` browsers will probably work it out but it's not an officially supported date format (as we found out when we tried to parse it in React Native - i.e. Javascript Core on iOS - which doesn't handle it).

I'm happy to create a pull request but I'm not sure what the best solution would be. Here are some options:
 * Make all dates output as `2016-10-01T14:12:00+01:00` which is a format JavaScript understands (which makes sense since we're outputting JSON)
     * if we go down this route I'm not sure where the best place to hook it in would be - maybe another special case in coerce_string in graphql-core like there is for booleans?
     * another option would be to just do it for Django fields - make a DateTimeString type with a separate serialize function and modify convert_django_field for the DateField
 * Do one of the above but make it configurable somehow
 * If those are't options (e.g. for backwards compatibility) then it would be nice to be able to hook in and do it ourselves without having to think about a fix every time we encounter a date field

Happy to do the work. If you'd like that, let me know which option you'd prefer and I'll open a PR.

**Comment by syrusakbary** [comment]
Hi @sdcooke,
`graphql` explicitly doesn't set any DateType and `graphene` chose this path too.
However I can see the usefulness in this.

Check the [custom scalars section in graphene documentation](http://graphene-python.org/docs/basic-types/).
I'm thinking about an option for adding this to graphene in a configurable way.

**Comment by syrusakbary** [comment]
I finally added complete support for conversion from `DateField` to a `DateTime` scalar in graphene that will output the python date in a ISO-8601 format (Javascript Date format).

You can update `graphene` to the last version `0.8.0` and it will be working as expected.

**Comment by creimers** [comment]
I'm having difficulties to use `DateTime` with the graphiql query variables.

This is the error I'm getting:
![query](https://user-images.githubusercontent.com/6090492/27434112-cec4d8c4-5757-11e7-8f97-6ed5cee6dcd8.png)

And this is how I declare the variable:
![image](https://user-images.githubusercontent.com/6090492/27434124-d73e7bb8-5757-11e7-9265-a468c7f1a533.png)

Can you think of a reason why this doesn't work? There's nothing wrong with the datetime string as far as I can see, as it works perfectly fine when I use it in the query instead of the variable.

For the sake of completeness, this is how I declare the field:
<img width="478" alt="bildschirmfoto 2017-06-22 um 14 36 25" src="https://user-images.githubusercontent.com/6090492/27434216-41be13d6-5758-11e7-8202-9456e234383c.png">

**Comment by jameswyse** [comment]
@creimers Shouldn't it be `query DingDong($fromDate: DateTime!) { ... }`? the `!` at the end of the type is because of `required=True`

**Comment by creimers** [comment]
@jameswyse That's it. Thanks for spotting it.

**Comment by rdhara** [comment]
I don't see the `graphene.types.datetime.DateTime` class; I am running `graphene==2.0.1`. Has this feature been removed?

**Comment by Audace** [comment]
I also have run into an issue on a model with a DateTimeField. During testing, graphene seems to be unable to serialize the value. 

Stacktrace:
```
Traceback (most recent call last):
  File "/Users/williamfry/Development/SolutionLoft/code-clippy-portal/venv/lib/python3.6/site-packages/promise/promise.py", line 65, in try_catch
    return (handler(*args, **kwargs), None)
  File "/Users/williamfry/Development/SolutionLoft/code-clippy-portal/venv/lib/python3.6/site-packages/graphql/execution/executor.py", line 375, in <lambda>
    resolved
  File "/Users/williamfry/Development/SolutionLoft/code-clippy-portal/venv/lib/python3.6/site-packages/graphql/execution/executor.py", line 399, in complete_value
    return complete_leaf_value(return_type, result)
  File "/Users/williamfry/Development/SolutionLoft/code-clippy-portal/venv/lib/python3.6/site-packages/graphql/execution/executor.py", line 440, in complete_leaf_value
    return return_type.serialize(result)
  File "/Users/williamfry/Development/SolutionLoft/code-clippy-portal/venv/lib/python3.6/site-packages/graphene/types/datetime.py", line 54, in serialize
    'Received not compatible datetime "{}"'.format(repr(dt))
AssertionError: Received not compatible datetime "'2018-01-20 09:35:53+00:00'"
```

**Comment by helpse** [comment]
Problem starts with code:
```
reunion.fecha = fecha
reunion.hora = hora
reunion.save()
return UpdateReunionMutation(reunion=reunion)
```
Here, `fecha` is a string. It will save the model, but graphene will trigger the error.
Change last line to:
```
return UpdateReunionMutation(reunion=Reunion.objects.get(pk=reunion.pk))
```
And problem solved

**Comment by mathieusteele** [comment]
I found this issue and followed the advice of helpse and fetched the saved object before returning it at the end of the mutation function. This fixed the issue I was having when sending date data ("2018-03-30") in a mutation but I'm not really sure _why_.

**Comment by rok-povsic** [comment]
I've solved the `AssertionError: Received not compatible datetime "'2018-01-20 09:35:53+00:00'"` issue by creating and using a custom type that overrides `serialize` and parses the string datetime:

```python
from dateutil.parser import parse
class CustomGrapheneDateTime(graphene.DateTime):
    @staticmethod
    def serialize(date):
        if isinstance(date, str):
            date = parse(date)
        return graphene.DateTime.serialize(date)
```

**Comment by themotu** [comment]
How do you apply something like this easily to a model field? Seems like if I use my own scalar I can't just reference a model in meta

**Comment by jkimbo** [comment]
@themotu if you are using something like graphene-django then you can use your own scalar by overriding the model field as explained here: http://docs.graphene-python.org/projects/django/en/latest/queries/#customised-fields

**Comment by nshaphan** [comment]
> @mathieusteele @helpse the issue is that Django does not convert the field that has just been set into a datetime object until you re-instantiate the model.
> 
> You can see this happening in the shell:
> 
> ```python
> reunion.fecha = '2018-04-04T20:10:00+00:00'
> reunion.save()
> print(reunion.fecha)  # '2018-04-04T20:10:00+00:00'
> reunion.refresh_from_db()
> print(reunion.fecha)  # datetime.datetime(2018, 4, 4, 20, 10, tzinfo=<UTC>)
> ```
> 
> Since Graphene doesn't know anything about Django, it just takes whatever object it is given and reads the fields off it.

Thanks, This solved my problem
