### ISSUE TITLE
graphiql interface is blank when deployed on AWS lambda + gateway API and queried with /graphql

### ISSUE THREAD

**Issue by opqpop** [graphql-python/graphene#1363]
* **What is the current behavior?**
- Get blank screen when I hit my `/graphql` AWS gateway API hooked to AWS lambda running Django + graphene. I deployed using zappa

![image](https://user-images.githubusercontent.com/5566843/132263471-66815116-ab5b-4bd9-b0ef-a039c4229559.png)

the tail however shows it's giving 200:

```
$ zappa tail
1630966892874] 98.148.64.63 - - [06/Sep/2021:22:21:32 +0000] "GET /graphql HTTP/1.1" 200 2081 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:78.0) Gecko/20100101 Firefox/78.0" 0/2.863
```

Also the actual graphql requests are confirmed working

If I run it locally, graphiql shows up fine

![image](https://user-images.githubusercontent.com/5566843/132263513-a7d92766-1da0-48a1-bc29-de4ca9a6408e.png)

My `urls.py` file
```
urlpatterns = [
    ...,
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True))),
]
```

Not sure if this is a bug. Anyone know if there's anything special I have to do to make graphiql work on AWS?

**Comment by jkimbo** [comment]
@opqpop What errors do you see in the browser console? Have you setup static file hosting? (https://docs.djangoproject.com/en/3.2/howto/static-files/deployment/) 
WhiteNoise is a good option for that: http://whitenoise.evans.io/en/stable/
