### ISSUE TITLE
graphene/docs/execution/queryvalidation.rst missing usage example

### ISSUE THREAD

**Issue by reubenosborne1** [graphql-python/graphene#1371]
From graphene/docs/execution/queryvalidation.rst 
> **Usage** 
> Here is how you would implement depth-limiting on your schema.

Is missing a link or example code

**Comment by codebyaryan** [comment]
@reubenosborne1 I had actually added a couple of examples, but I think that it isnt rendering because of incorrect formatting. We have to make space between codefences in that file, I'll try to do it when I get time this week.

**Comment by reubenosborne1** [comment]
Great thank you @codebyaryan. I can see that graphene.validation only exists in master, when do you think it will make it into a tagged release?

**Comment by codebyaryan** [comment]
> Great thank you @codebyaryan. I can see that graphene.validation only exists in master, when do you think it will make it into a tagged release?

I am not a maintainer here, hence I dont have release access. I think that we should ask @syrusakbary or @jkimbo regarding this! :)

**Comment by reubenosborne1** [comment]
Ok thank you! 

I have tried to run your example of depth limiting validation but I am getting the following error:
```
    raise TypeError(f"Expected {inspect(schema)} to be a GraphQL schema.")
TypeError: Expected <Schema instance> to be a GraphQL schema.
```
Any ideas what is wrong?

**Comment by codebyaryan** [comment]
I've now fixed it, please take a look at the changed files in the PR!
