### ISSUE TITLE
Resolve query directly on query object.

### ISSUE THREAD

**Issue by akayunov** [graphql-python/graphene#1372]
Hi guys, We would like to use graphql internally in our project without share graphql interface with any client, to gather data from different apis for our internal tasks. So it looks stupid to write text graphql query for ourself. We have all definitions which allowed us resolve query without writing it,  just doing something like call `resolve` method on query object and get all magic that graphene suggest, without any text query. Doesn't it possible to add such magic to graphene?

**Comment by codebyaryan** [comment]
If I understood your question correctly, you want to do something like this.


```py
class Query(ObjectType):
    hello = String()
   
    def resolve_hello(self):
        pass

schema = Schema(Query)
result = schema.query.resolve()
```

AFAIK, Graphene doesnt and doesnt need to support this feature. The query root type is used to build a graphql schema instance, provided by graphql-core. The only way to query your schema would be with GraphQL - the query language. This is a part of intended design.
