### ISSUE TITLE
Filter child fields

### ISSUE THREAD

**Issue by joanteixi** [graphql-python/graphene#1386]
**Is your feature request related to a problem? Please describe.**
We'd like to allow add filter values inside child fields, as the fields_objects in Django  Filters. 

**Describe the solution you'd like**
Actually, it's not possible to create filters for a child object of type "Field".

**Comment by erikwrede** [comment]
This is a `graphene-django` issue, please reopen it there :)
I can't move the issue to that repository since I'm not a maintainer of the django extensions.
