### ISSUE TITLE
DataLoaders with Graphene 3

### ISSUE THREAD

**Issue by MaehMaeh** [graphql-python/graphene#1390]
This is a duplication of:
https://github.com/graphql-python/graphene-django/issues/1272

I have implemented the DataLoaders in Graphene 2 using these instructions:
https://jerrynsh.com/solving-n-1-in-graphql-python-with-dataloader/

After upgrading to Graphene 3, the DataLoaders no longer works. Now I get the following error messages:
* Case 1: Fetch a list of Articles for each Reporter (reporters -> articles)
`Received incompatible instance \"<Promise at 0x5ddcef8 fulfilled with Reporter(id=1)>\".`
* Case 2: Fetch a single Reporter for each Article (articles ? reporter)
`Cannot return null for non-nullable field ArticleConnection.edges.`

Has anyone had any experience with DataLoaders under Graphene 3?

**My environment:**
django 3.2.7
graphene 3.0
graphql-core 3.1.6
graphql-relay 3.1.0
graphene-django 3.0.0b
Python 3.8
Windows 10

**Comment by AlexCLeduc** [comment]
Technically not a bug, graphene 3 no longer supports promise-based dataloaders, only asyncio. Use [aiodataloader](https://github.com/syrusakbary/aiodataloader) instead.

**Comment by MaehMaeh** [comment]
Thanks for the quick reply. I seem to have overlooked that.
Is aiodataloader production ready? Version number 0.2.0 does not sound particularly confidence-inspiring.
