### ISSUE TITLE
Is there a way to export schema from Postgres database?

### ISSUE THREAD

**Issue by krish7919** [graphql-python/graphene#1395]
I currently use the `postgraphile` CLI as such:

```
postgraphile \
  --connection "postgres://user:pass@pg_host:5432/db_name?sslmode=verify-ca&sslrootcert=pg_ca.pem" \
  --schema public \
  --port 5000 \
  --host localhost \
  --export-schema-graphql ./schema.gql
```

This fetches the SDL from Postgres using `postgraphile` CLI written in JS and stores it in `schema.gql` file.

I wanten to automate this step and looking for a way to do this in Python. Is this not possible as of today using graphene (or any of the other Python graphql libraries)?

I have checked `graphql-core`, `graphene`, `graphene-sqlalchemy`, and `ariadne` with no luck.

**Comment by jkimbo** [comment]
@krish7919 as far as I'm aware there isn't a python tool to do this. postgraphile is probably you're best option at the moment (unless you want to write a python version).

**Comment by krish7919** [comment]
Thanks, @jkimbo for the answer (even though this might not be the right forum). Can you please give me any pointers on how one would go about implementing this (considering that I have never touched JS in my life)?

I would like to get an idea on how complex would it be to get this done in `graphql-core` or `graphene` libs before giving up on this approach; and if I have the necessary skillset to get this done for the community (and use it myself too).

**Comment by jkimbo** [comment]
@krish7919 I'm not familiar with postgraphile but I imagine what you want to do is export the postgres schema and then convert the columns into GraphQL types. I.E. if the column is of type Text then convert it to a string type. You can probably just use graphql-core for this (libraries like Graphene and Strawberry are just wrappers around graphql-core).

**Comment by hutber** [comment]
Off topic, but I would also like to use the feature, I'm currently trying to crack it, if I do I'll let you know. Also using postgraphile

**Comment by hutber** [comment]
I got it working with:

  app.use(
    postgraphile(process.env.DATABASE_URL || dbUrl, 'public', {
      appendPlugins: [ConnectionFilterPlugin],
      connectionFilterRelations: true,
      watchPg: true,
      graphiql: true,
      enhanceGraphiql: true,
      exportJsonSchemaPath: './graphql/schema/schema.json', //here is the key part
      exportGqlSchemaPath: './graphql/schema/schema.graphql',
      enableQueryBatching: true,
      graphileBuildOptions: {
        connectionFilterAllowEmptyObjectInput: true,
        connectionFilterAllowNullInput: true, // default: false
      },
    })
  )

Or via cli

`"graphile": "npx postgraphile -c 'postgres://hutber:pass@localhost/unsal' --cors -p 4006 --watch --enhance-graphiql --dynamic-json --export-schema-graphql schema.graphql --append-plugins postgraphile-plugin-connection-filter",`
