### ISSUE TITLE
v3 upgrade documentation?

### ISSUE THREAD

**Issue by mattbasta** [graphql-python/graphene#1396]
Similar to https://github.com/graphql-python/graphene/blob/master/UPGRADE-v2.0.md, is there a guide to upgrading to v3 from v2? I cannot seem to find any information beyond the list of changes from the GH release: https://github.com/graphql-python/graphene/releases/tag/v3.0.0

**Comment by jkimbo** [comment]
@mattbasta I wrote some release notes a while ago: https://github.com/graphql-python/graphene/wiki/v3-release-notes

I think they are still up to date (I've also added them to the GitHub release)

**Comment by syrusakbary** [comment]
Great work on the release notes @jkimbo, just read them and are great!

**Comment by erikwrede** [comment]
Referenced the doc in the GH release.
