### ISSUE TITLE
2.* is incompatible with Python >= 3.9

### ISSUE THREAD

**Issue by cammil** [graphql-python/graphene#1397]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**

2.* will fail if used with Python 3.9

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar.

Install 2.* on a python 3.9 environment
Import graphene

* **What is the expected behavior?**

Don't fail

* **What is the motivation / use case for changing the behavior?**

I want to upgrade to python >= 3.9

* **Please tell us about your environment:**

  - Version:
  - Platform:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by jkimbo** [comment]
@cammil https://github.com/graphql-python/graphene/releases/tag/v2.1.9 should work on Python versions >=3.9
