### ISSUE TITLE
Bug in relay.NodeField

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#14]
When the name of MyNode in the relay tests: https://github.com/graphql-python/graphene/blob/master/tests/relay/test_relayfields.py#L22 is changed to anything else (and updated here https://github.com/graphql-python/graphene/blob/master/tests/relay/test_relayfields.py#L31) then graphene seems to throw the following error: `[GraphQLError('Type MyNode not found in <Schema: Schema (8778058338473)>',)]`

**Comment by syrusakbary** [comment]
Somehow the schema is not able to reach the node you mentioned.
A easy hack is doing:
```python
@schema.register
class MyNode(relay.Node):
    name = graphene.StringField()

    @classmethod
    def get_node(cls, id):
        return MyNode(MyType())
```

However if you can create a Gist would be great, I would like to know why the schema is not reaching your node.

**Comment by syrusakbary** [comment]
@Globegitter is this problem solved? Let me know for closing the issue.

**Comment by Globegitter** [comment]
Sorry, after a quick sprint yesterday I had to put our relay advancements on hold for the time. For now I am just using a connectionfield as a workaround. Will put up an example as soon as I get time the next few days.

**Comment by syrusakbary** [comment]
@Globegitter ok! Let me know!! I would love to fix any problem as soon as possible!

**Comment by Globegitter** [comment]
Just looking into this again now @syrusakbary so should have an update soon.

**Comment by Globegitter** [comment]
Just tried more, and so far I am not getting around the error `[GraphQLError('Incorrect padding',)]`

Example:

```
schema = graphene.Schema()

class Tester(relay.Node):
    name = graphene.StringField()

    @classmethod
    def get_node(cls, id):
        print('stuff')
        return Tester(name='mo')

class Query(graphene.ObjectType):
    tester = relay.NodeField(Tester)

schema.query = Query

query = '''
  query RebelsShipsQuery {
    tester(id:"mo") {
      name
    }
  }
'''
results = schema.execute(query)
print(results.errors)
print(results.data)
```

**Comment by syrusakbary** [comment]
The reason for the error is the id is not a correct base64 id (for knowing the id for certain node instance, just call `your_node_instance.to_global_id()` where `your_node_instance` is a instance of a class that inherits from `graphene.Node` and have a defined id.

So this should work:
```python
t = Tester(id="mo")
the_id = t.to_global_id()
print the_id
```

And then use `the_id` in the query (id:"$the_id_value").

However Graphene should return a None value instead of throwing a error. So will keep this issue open until is solved.

**Comment by syrusakbary** [comment]
@Globegitter This will be fixed (returning None for non-valid ids) in graphene 0.4.0
