### ISSUE TITLE
Found different types with the same name in the schema

### ISSUE THREAD

**Issue by LeOndaz** [graphql-python/graphene#1404]
Bear with me please

Let's assume I have a type called `Product` in schema1 and a type with the same name in schema2 and I want to expose __both__ schemas via the same API, I get an error saying that I can't have two types with the same name, even though I'm using TOTALLY different types from different files

```
# file 
class Product(...):
   pass

# another file
class Product(...):
   pass
```

The workaround is to rename the type to something like ProductX or smth, but I want to know why does this specific behavior happen, is there any kind of _global_ registry that I'm not aware of? I've ran through the code but I found nothing

**Comment by theodesp** [comment]
@LeOndaz  I didn't find any issues with a different name:. For example I created another example in the examples folder named simple_example:

```python
import graphene

from simple_example import Patron as Patron2

class Patron(graphene.ObjectType):
    id = graphene.ID()
    name = graphene.String()
    age = graphene.Int()

class Query(graphene.ObjectType):

    patron = graphene.Field(Patron)
    patron2 = graphene.Field(Patron2)

    def resolve_patron(root, info):
        return Patron(id=1, name="Syrus", age=27)

    def resolve_patron2(root, info):
        return Patron2(id=2, name="Miles", age=30)

schema = graphene.Schema(query=Query)
query = """
    query something{
      patron {
        id
        name
        age
      }
      patron2 {
        id
        name
        age
      }
    }
"""

if __name__ == "__main__":
    result = schema.execute(query)
    print(result.data)

```

This imports the Patron model from simple_example and create an alias for it.

```
❯ python3 examples/simple_example2.py
{'patron': {'id': '1', 'name': 'Syrus', 'age': 27}, 'patron2': {'id': '2', 'name': 'Miles', 'age': 30}}
```

Is that something you considered?
