### ISSUE TITLE
Latest Graphene (v3.0.0) is incompatible with latest gql (v3.0.0)

### ISSUE THREAD

**Issue by serramatutu** [graphql-python/graphene#1406]
# Current behavior
Current Graphene (v3.0.0) and GQL (v3.0.0) packages are incompatible due to no overlap between specified `graphql-core` versions. 

If you try to install both using a package manager with a dependency resolver such as [Poetry](https://python-poetry.org/), it'll break.

# Demo project or reproducible steps
There's no need for a demo project. Here are the minimal steps to reproduce the problem: 
1. Create an empty folder 
2. Run `poetry init`
3. Run `poetry add graphene`
4. Run `poetry add gql`. 
5. It'll break and complain `graphql-core` package versions are incompatible.

# What is the expected behavior?
Graphene and GQL should be installable together

# Use case/motivation
It'd be nice if both packages worked well together.

# My environment
  - Version: 3.0.0
  - Platform: Ubuntu 20.04 LTS

# Other info
Graphene specifies `graphql-core~=3.1.2` while GQL specifies `graphql-core>=3.2,<3.3`. There are obviously no overlapping versions.
I suggest bumping the `graphql-core` version.

## Screenshots
![image](https://user-images.githubusercontent.com/18057473/153266816-52460abc-7971-454f-84d3-22b7dffb89be.png)
![image](https://user-images.githubusercontent.com/18057473/153266847-af2c9889-205b-45a8-ac4b-04bbf5d22e7d.png)

**Comment by ddelange** [comment]
FYI our current workaround is to pin to a `gql` release candidate:

```
graphene==3.0 (3.0)
├── aniso8601<10,>=8 (9.0.1)
├── graphql-core~=3.1.2 (3.1.7)
└── graphql-relay<4,>=3.0 (3.1.5)
    └── graphql-core<3.2,>=3.1 (3.1.7)
gql==3.0.0rc0 (3.0.0rc0)
├── graphql-core<3.2,>=3.1.5 (3.1.7)
└── yarl<2.0,>=1.6 (1.7.2)
    ├── idna>=2.0 (3.3)
    └── multidict>=4.0 (6.0.2)
```

**Comment by serramatutu** [comment]
@ddelange As a workaround, I vendored dependencies in the Dockerfile and added the import paths to be `from vendor.gql.gql import ...`. So I effectively installed 2 different versions of GQL.

**Comment by rexledesma** [comment]
Looks like this should beresolved with https://github.com/graphql-python/graphene/pull/1421!! Do you know when we should expect a new release of graphene with this change?

**Comment by ddelange** [comment]
> Looks like this should beresolved with #1421!! Do you know when we should expect a new release of graphene with this change?

pinging @Cito for this question

**Comment by Cito** [comment]
@ddelange Yes, I think this is resolved. But I'm not a Graphene maintainer and currently don't use it actively. I have passed the question on to the Graphene slack channel.

**Comment by richin13** [comment]
Pinging @mvanlonden since he was able to help with releases in the past! 🙏🏼
