### ISSUE TITLE
cannot import force_text in Django 4.0

### ISSUE THREAD

**Issue by vivekthedev** [graphql-python/graphene#1409]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

The force_text in django 4.0 has changed to force_str

* **What is the current behavior?**
Here is the traceback
![image](https://user-images.githubusercontent.com/71426368/158454188-68a53b90-be8d-42e8-8c1c-f1a09aeca04b.png)

Hardcoding force_str in my site-packages solved the problem

* **Please tell us about your environment:**

  - Version: 
  - Python 3.9
  - Django 4.0
  - Platform:
  - Window

**Comment by r4gesingh47** [comment]
Can i work on it?

**Comment by mariorojas** [comment]
hello, any plan for solved this bug? I applied a work around editing `VENV/lib/python3.8/site-packages/graphene_django/utils/utils.py`

```
...
from django.utils.encoding import force_str

...
def _camelize_django_str(s):
    if isinstance(s, Promise):
        s = force_str(s)
    return to_camel_case(s) if isinstance(s, six.string_types) else s
...
```

**Comment by artemijan** [comment]
In open source world you can always fork a repo and patch the issue, but I believe it would be more convenient to have this fix in main repo, moreover the fix is not so hard. Any plans to release a new version with a fix for that?

**Comment by theodesp** [comment]
@mariorojas this is related to `graphene-django` and not `graphene`: See https://github.com/graphql-python/graphene-django/issues/1284.

**Comment by mariorojas** [comment]
@theodesp agreed
