### ISSUE TITLE
Argument with wrong value type do not raise an error

### ISSUE THREAD

**Issue by tcleonard** [graphql-python/graphene#1413]
Currently, setting the value of an input with the wrong type is not raising an error.
For example if the input as the type `UUID` and that you provide the value `2` it doesn't fail.

There are various cases like that (see tests in the pull request for an extensive list).

This is due to the fact that now no value is represented by `Undefined` and not `None` in graphql-core.

**Comment by DarknessRdg** [comment]
Hi, @tcleonard !

I'm just commenting the link to your PR:  https://github.com/graphql-python/graphene/pull/1414

**Comment by erikwrede** [comment]
Merged!

**Comment by anusha-bylla** [comment]
“Hi, I am new to Qt Creator. I successfully ran QGroundControl on Windows, but now I am trying to run QGroundControl for Android in Qt Creator, and I am encountering the following error:”
can you please help me to solve this error…

![Screenshot (7)](https://github.com/user-attachments/assets/23826e33-27eb-44b4-826a-2fefdd3e0443)
![Screenshot (8)](https://github.com/user-attachments/assets/b9a77d1e-db6f-43a6-bc25-d831a118ed11)
