### ISSUE TITLE
Update docs for v3

### ISSUE THREAD

**Issue by multimeric** [graphql-python/graphene#1422]
The current documentation website hasn't been updated for Graphene v3:

![image](https://user-images.githubusercontent.com/5019367/167337144-bb56b4ef-ff85-4af8-934a-0dbc4f7b5393.png)
![image](https://user-images.githubusercontent.com/5019367/167337169-806797cb-ba08-46c7-aac6-ec2243eeb2ab.png)

The release notes are helpful, but if you are starting using Graphene for the first time with v3, it is confusing to be faced with outdated docs.

**Comment by erikwrede** [comment]
Documentation needs an overhaul. This will be tracked in a separate issue soon!
