### ISSUE TITLE
Dataloaders for existing REST APIs as data source

### ISSUE THREAD

**Issue by rshreemr12** [graphql-python/graphene#1433]
Is there a feature already existing for dataLoaders to load graphene RESTFUL APIs as datasource

current Behaviour 
https://docs.graphene-python.org/en/latest/execution/dataloader/#using-with-graphene
Existing docs provide info to load the data from database and load dataloaders by filtering id.

Please suggest if there a way to use dataloaders for existing REST APIs as data source. 
Couldn't find it anywhere in docs

https://stackoverflow.com/questions/48541204/graphene-relation-using-restfull-api-as-data-source
https://stackoverflow.com/questions/72544729/graphql-wrapper-for-rest-apis-with-django?noredirect=1&lq=1

**Comment by erikwrede** [comment]
This works very similar to the JS tutorial. As mentioned above, you will need to use aiodataloader. Now you need to create your grapheme object types with the correctly typed fields. Then create data loaders for all the object types. These should return an instance of the object type based on the object id. Inside of the dataloaders you can use httpx, requests or other HTTP clients to make your rest calls. 
Let me know if that works for you.
