### ISSUE TITLE
Filtering docs point to wrong URLs

### ISSUE THREAD

**Issue by BenQuigley** [graphql-python/graphene#1438]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**

At this graphene docs page: https://docs.graphene-python.org/projects/django/en/latest/filtering/ -  
\- the hyperlink on "django-filter" in the first sentence 404s because it points to https://django-filter.readthedocs.io/en/master/
\- it should point to https://django-filter.readthedocs.io/en/stable/
\- and the next one, on "usage documentation", 404s because it points to https://django-filter.readthedocs.io/en/master/guide/usage.html#the-filter
\- it should point to https://django-filter.readthedocs.io/en/stable/guide/usage.html#the-filter

Sorry for opening an issue instead of raising a PR. I cloned the repo but wasn't able to find the strings or URLs in this page by grepping it. It looks like the docs were removed from this repo a long time ago, but I wasn't able to find by googling where they went, so I'm just posting about it here in the hopes that someone here knows.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Platform:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by erikwrede** [comment]
If you can find the respective .rst file in the docs folder of the repo, I'd appreciate a PR fixing the behavior. Other than that, I can not do much about the docs currently. Once we have better access to the website I will take this on.

**Comment by BenQuigley** [comment]
Thanks!
