### ISSUE TITLE
Incorrect query AST when there are duplicated nested fields with different selection sets

### ISSUE THREAD

**Issue by fireteam99** [graphql-python/graphene#1440]
When resolving a query with duplicated nested fields with different selection sets, only the first selection set is available to the resolver info AST. 

Given the following query:
```gql
query {
    person {
        firstName
    }
    person {
        lastName
    }
}
```
When inspecting the AST available in `info.field_nodes`, only `firstName` will be available. 

Expected behavior: the person resolver is called once, and `firstName` and `lastName` are available in the AST. Or, the person resolver gets called twice: first with `firstName` in the AST and the second with `lastName` in the AST. 

Current behavior: the person resolver is called once, and only with `firstName`. 

This is a problem, because I want to be able to know all the full selection set of a queried field for optimization purposes. This bug is especially puzzling because the data returned is in the correct shape with the merged selection sets, yet it seems like the resolver is only returning incomplete data. Any insight on this issue would be greatly appreciated!

Here is a minimal reproducible example: https://gist.github.com/fireteam99/20be417e397a1672380e33b18164ec12.

  - Version: 3.1
  - Platform: MacOS/Linux

**Comment by erikwrede** [comment]
Thanks for the report and the easy-to-execute example!

I'm not too familiar with the part of GQL-Spec related to fragment merging. However, I suspect this might be an issue related to graphql-core. Can you reproduce this just using just graphql-core ObjectTypes, nothing graphene related?

**Comment by fireteam99** [comment]
@erikwrede sounds good! I'll give it a try and report back.

**Comment by erikwrede** [comment]
I had some spare time to recreate this in GraphQL. Behavior is the same. For further testing, I added a query using fragments and printed all contents of `info.field_nodes`. It seems like this has two entries instead of one. 
The first entry contains the person with the `first_name` field and the second entry includes the person with the `last_name` field. 
From the spec, I would have expected the merging of a type's fields (https://spec.graphql.org/June2018/#sec-Field-Selection-Merging) to have happened before main resolvers fields are executed, but it seems like at this stage, they are split into two separate `FieldNode`s. Iterating through all field nodes and merging them yourself should give you a way to access all fields, but I can't explain why the logic was designed this way. 

Maybe @Cito knows the reason for this, but I suspect this behavior is based on the `graphql-js` reference implementation. I suggest asking him over at `graphql-core` or doing some extra research if you need more information.

For reference: GQL repro code based on your gist.
```python
from collections import deque
from dataclasses import dataclass

from graphql import GraphQLSchema, GraphQLObjectType, GraphQLField, GraphQLString, graphql_sync

person = GraphQLObjectType(name='Person', fields={
    'firstName': GraphQLField(
        GraphQLString,
        resolve=lambda obj, info: obj.first_name
    ),
    'lastName': GraphQLField(
        GraphQLString,
        resolve=lambda obj, info: obj.last_name
    ),
    'fullName': GraphQLField(
        GraphQLString,
        resolve=lambda obj, info: f"{obj.first_name} {obj.last_name}"
    ),
})

@dataclass
class PersonData(object):
    first_name: str
    last_name: str

def inspect_fields(node):
    """Walks the AST breadth first and prints out all field nodes."""
    queue = deque([node])

    while queue:
        node = queue.popleft()

        if node.kind == "field":
            print(f"Field: {node.name.value}")

        if node.selection_set:
            for child in node.selection_set.selections:
                queue.append(child)

def resolve_person(obj, info):
    print("Resolve called")
    inspect_fields(info.field_nodes[0])
    inspect_fields(info.field_nodes[1])
    return PersonData(**{
        "first_name": "John",
        "last_name": "Doe",
    })


schema = GraphQLSchema(
    query=GraphQLObjectType(
        name='Query',
        fields={
            'person': GraphQLField(
                person,
                resolve= resolve_person
            ),
        }
    )
)

query_string = """
    query {
        person {
            firstName
        }
        person {
            lastName
        }
    }
"""

query_string_fragments = """
    query {
        person {
            lastName
        }
        ...FNFragment
    }
    fragment FNFragment on Query {
        person {
            firstName
        }
    }
"""
result = graphql_sync(schema, query_string_fragments)
print(result)

```

**Comment by Cito** [comment]
@erikwrede The [section](https://spec.graphql.org/June2018/#sec-Field-Selection-Merging) in the spec that you linked to covers only validation, and in fact GraphQl-core has a validation rule that implements this section. However, that does not mean that the fields are merged before the query is run. The algorithm used for execution is described in [another section](https://spec.graphql.org/June2018/#sec-Field-Collection) of the spec.

But I do not see a problem here, the field nodes passed in the ResolveInfo are exactly as @fireteam99 expected. In the resolver for person, you get the the first person node as first item and the second person node as second item. In the resolver for firstName, you get only the firstName node and in the resolver for lastName, you get only the lastName node.

**Comment by erikwrede** [comment]
Thanks for the insight&quick response @Cito! The technical details of field collection are something I haven't had to deal with before.

I think what @fireteam99 was looking for was a way to access the field nodes in a merged way _before_ the field collection happens. The solution I mentioned (and you confirmed) certainly does the trick. 
For the sake of completeness, I'm curious: is there a better approach (using features from core) to that than just to manually merge the field nodes provided in the GQLResolveInfo?

**Comment by Cito** [comment]
@erikwrede I currently do not see a better approach, but I also do not understand the need for doing this.

To sum it up, the problem in the code used by @fireteam99 was that it only inspected the first item in `field_nodes`, but not the other ones. It can be fixed like this:

```python
def inspect_fields(nodes):
    queue = deque(nodes)
    seen = set()
    while queue:
        node = queue.popleft()
        if node.kind == "field":
            name = node.name.value
            if name not in seen:
                seen.add(name)
                print(f"Field: {node.name.value}")
        if node.selection_set:
            for child in node.selection_set.selections:
                queue.append(child)

def resolve_person(root, info):
    inspect_fields(info.field_nodes)
    return PersonData(first_name="John", last_name="Doe")
```

**Comment by fireteam99** [comment]
@erikwrede @Cito, thank you for spending the time to look into this issue! I did not realize that they would be in the other items in `field_nodes`. @Cito the solution you presented is exactly what I was looking for!
