### ISSUE TITLE
Implement deprecation directive for field args, directive args and input fields

### ISSUE THREAD

**Issue by flbraun** [graphql-python/graphene#1446]
The GraphQL spec finally allows using the `@deprecated` directive on field args, directive args and input fields (see graphql/graphql-spec#805)

It would be nice to support this in Graphene using the established `deprecated_reason='....'` kwarg to the respective constructors.

**Comment by erikwrede** [comment]
Sounds like a great addition!

TODOS for this:
- [ ] Is this already supported in graphql-core?
- [ ] Add deprecation reason field to Meta Options Classes and [Input]Field logic 
- [ ] Check that required NonNull input fields are not deprecatable (see spec)

If someone is willing to work on a PR I'd be happy to assist and review!

**Comment by vhutov** [comment]
@erikwrede Hi Erik. Is this issue still relevant? I'd like to give it a try

**Comment by erikwrede** [comment]
@vhutov Yes this is still relevant. Sounds great! Feel free to tag me when you need a review 🙂

**Comment by erikwrede** [comment]
Will be  released in `2.1.2`, thanks to @vhutov! 🎉
