### ISSUE TITLE
Exception is swallowed in mutation

### ISSUE THREAD

**Issue by glusa8** [graphql-python/graphene#1464]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**
When I throw an exception in a mutation, the exception does not show up (double checked on GraphiQL). If there is a way to have the exception show up, I couldn't find it in the documentation. Is swallowing the exception an expected behavior?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar.

See the screenshots below. The example I created is easy to reproduce.

* **What is the expected behavior?**

The exception should show up as an error.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Version: Graphene 3.1.1
  - Framework: Django (graphene_django 3.0.0)
  - Platform: Mac OS
  - Python: 3.10.5

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

<img width="1191" alt="Screen Shot 2022-10-08 at 10 24 35 PM" src="https://user-images.githubusercontent.com/4329589/194739648-38fc9526-1aeb-496f-97e6-9b9d1a38b736.png">

<img width="908" alt="Screen Shot 2022-10-08 at 10 24 11 PM" src="https://user-images.githubusercontent.com/4329589/194739644-6e5aad6d-3c62-4e4b-a7a4-dee543a74ef9.png">

**Comment by erikwrede** [comment]
This is an issue with `graphene-django` which is not directly related to graphene. 
You can find some solutions in this thread: https://github.com/graphql-python/graphene-django/issues/124
If that doesn't solve the issue, feel free to open another one over there 🙂
