### ISSUE TITLE
Allow variables passed to schema.execute

### ISSUE THREAD

**Issue by defrex** [graphql-python/graphene#147]
Is there a way to pass "variables" to  `schema.execute`? In the same way Relay mutations input is passed, ideally.

It's not clear from the docs/code how I would do this.

**Comment by defrex** [comment]
I figured it out. It's the `args` keyword argument to `schema.execute`. It should be a dict (or other map type) and the keys should be camelCase. For example:

```Python
schema.execute(
    '''
    mutation UpdateItem($input_key: UpdateItemMutationInput!) {
        updateItem(input: $input_key)
    }
    ''',
    args={
        'input_key': {
            'clientMutationId': 'whatever',
            'someOtherInputValue': 42,
        }
    },
)
```

**Comment by jimmay5469** [comment]
FYI - It appears as though `args` has been renamed `variable_values`.

**Comment by pablofiumara** [comment]
Variables (instead of variable_values) worked for me
