### ISSUE TITLE
How to desirelize from graphene object to json?

### ISSUE THREAD

**Issue by SomeAkk** [graphql-python/graphene#1480]
Try to desirelize from graphene object to json, and do not know how to.

```
class From(graphene.ObjectType):
    node_id = graphene.String()
  pod = graphene.String()

mail = From(**json.loads(message))
... # some staf with mail object
json_mail = mail.dump() <- no such feature, how to it?
```
Want in json_mail see json or dict (which can be dumped to json with json.dump())

**Comment by erikwrede** [comment]
Graphene Types are currently not json-serializable without further. Why do you need this feature?

**Comment by SomeAkk** [comment]
You know, it was so genius idea, that I'm ashamed to tell))
Main idea was to use graphene for data validation: just to not to use another library in project, but after research a found that there is no any variant to do that, so by that there is no any need to dump graphene objects to dict/json.

I thing problem solved.
