### ISSUE TITLE
Allow configuring schema.introspect 

### ISSUE THREAD

**Issue by erikwrede** [graphql-python/graphene#1484]
`Schema.introspect` should implement some mechanism to modify the introspection query settings (see `graphql.utilities.get_introspection_query`). 
A use case for this is the recently implemented deprecated argument and input fields support (#1472). These are by default excluded from the introspection query.

**Comment by MakonnenMak** [comment]
Hey @erikwrede this PR was completed and closed, but I'm not seeing how one configures the inputs to `get_introspection_query` when calling [introspect](https://github.com/graphql-python/graphene/blob/c335c5f529dec8fa6c56b3d629690791e5179640/graphene/types/schema.py#L518) ?  https://github.com/graphql-python/graphene/blob/c335c5f529dec8fa6c56b3d629690791e5179640/graphene/types/schema.py#L55

**Comment by erikwrede** [comment]
@MakonnenMak I meant to close as won't fix, sorry for the confusion. The preferred way currently is to go through print_filtered_schema in graphql core instead of schema.introspect for this case.

**Comment by MakonnenMak** [comment]
Ah no problem @erikwrede. I just made my own custom `instrospect` method for now that imports and passes arguments to to `get_introspection_query` which should be good enough. 

Thanks for the response and clarification!
