### ISSUE TITLE
Thanks for Thanks for GraphQL Python Roadmap

### ISSUE THREAD

**Issue by denisart** [graphql-python/graphene#1485]
Hello, thanks for Thanks for GraphQL Python Roadmap

I see that this project is the most alive in https://github.com/graphql-python

I use python as GraphQL client and server in my projects and
I created the package for pydantic data-model generation from some GraphQL schema and
for queries and mutations generation: https://github.com/denisart/graphql2python
Docs: https://denisart.github.io/graphql2python/

Queries generation examples: https://github.com/denisart/graphql-query
Data-model generation examples: https://denisart.github.io/graphql2python/model.html
Using with gql: https://denisart.github.io/graphql2python/gql.html

This package so far has few settings. This will be fixed in future releases. For example:

- custom templates for render of data-model (your pydantic style or other packages (https://github.com/lidatong/dataclasses-json, ...));
- custom input for output file;
- load GraphQL as like in https://the-guild.dev/graphql/codegen/docs/config-reference/schema-field;
- custom base class;
- and more;

I hope that graphql2python can be useful to you and the python GraphQL community.

**Comment by conao3** [comment]
is this related to graphene?
