### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by rapilabs** [graphql-python/graphene#149]
Would be awesome if a CHANGELOG was added to the repo so I can review updates before upgrading :)

**Comment by syrusakbary** [comment]
Good idea! Right now it could be achieved easily by looking at the releases:
https://github.com/graphql-python/graphene/releases

**Comment by jkimbo** [comment]
Hi @rapilabs . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
