### ISSUE TITLE
http://www.graphene-python.org Has EXPIRED

### ISSUE THREAD

**Issue by riodw** [graphql-python/graphene#1528]
![image](https://github.com/graphql-python/graphene/assets/10352814/dd3fd46b-f43f-4433-b1dd-365526a26a52)

Looks like you could buy [graphene-python.com](https://www.godaddy.com/domainsearch/find?domainToCheck=graphene-python.org&isc=GPPTCOM&itc=parkedpage_landers&key=parkweb&tmskey=dpp_dbs) for treefitty tho 😉

**Comment by erikwrede** [comment]
@riodw thanks for the report, we're on it. The current maintainer team is not the one managing the website, although we can push to the docs via the GitHub repository. Hopefully we can get this resolved quickly.

**Comment by riodw** [comment]
Fixed!
