### ISSUE TITLE
Add error/warning for returning wrong types/fields

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#154]
It has happened to me twice now that I had a situation similar to this:

``` py
class DirectDebitInstructionStatus(graphene.Enum):
    some = 1
    fields = 2
    ...

class DirectDebitInstruction(graphene.ObjectType):
    has = ...
    other = ...
    accepted_fields = ...

class someOtherNode(relay.Node):

    direct_debit_instruction = graphene.Field(DirectDebitInstruction)

def resolve_direct_debit_instruction(...):
    return DirectDebitInstructionStatus(has='something', other='something_else')
```

And on the frontend this just returns fields set to null. It would be great if there was either an exception thrown or at the very least some warning. I suppose that could be on two levels, one on the `graphql-core` and the other on `graphene`. `graphql-core` could simply warn/error if any fields are returned in the resolve that are not specified on the ObjectType/Node (Might take a look to see if `graphql-js` does anything there or has an issue related to that). `graphene` could even go a step further and could just throw/log if and `ObjectType` gets initialized with fields not defined in the class as well as when the wrong class gets returned.

So in this case that would be, 

for graphql-core: `Returning fields 'has', 'other' are not defined for type`DirectDebitInstruction`

for graphene: `DirectDebitInstructionStatus does not have fields 'has', 'other'` and `Returning type`DirectDebitInstructionStatus`when type`DirectDebitInstruction`was expected`

or along those lines.

What do you think @syrusakbary?

**Comment by jkimbo** [comment]
Hi @Globegitter . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
