### ISSUE TITLE
release 3.4.0

### ISSUE THREAD

**Issue by dulmandakh** [graphql-python/graphene#1560]
Today is a version 3.3.0 anniversary. It looks like graphene got around 15 commits since then, gaining support for Python 3.12 and dropped a few dependencies.

IMHO, we need to merge https://github.com/graphql-python/graphene/pull/1559 to have consistent README both on GitHub and PyPI.

Maybe it's time for 3.4.0 😎 @erikwrede @syrusakbary

**Comment by erikwrede** [comment]
@dulmandakh I have a few things left on my to-do list, including checking all your PRs. After that I'll publish a new release 🚀

**Comment by dulmandakh** [comment]
> @dulmandakh I have a few things left on my to-do list, including checking all your PRs. After that I'll publish a new release 🚀

I have another very small improvement, and waiting for Ruff PR to be merged due to possible code conflicts.

**Comment by gmetzker-4c** [comment]
Any movement on this?  Would be nice to see official 3.12 support.

**Comment by erikwrede** [comment]
the release is out, thanks again for contributing! @dulmandakh  😊
