### ISSUE TITLE
grphene.List not work correctly

### ISSUE THREAD

**Issue by elyas-hedayat** [graphql-python/graphene#1569]
* **What is the current behavior?**
When using from graphene.List() and in inner type use from String or any other data  type  and make it required it is excepted that not accept empty List .

for example `graphene.List(graphen.ID,required=True)` it accept [ ]
 

* **What is the expected behavior?**
expected to not accept empty list and check for related data for that to validate

**Comment by erikwrede** [comment]
Hey there, this is actually intended behavior. `required` just signifies that the field cannot be `Null` in the input or response. An empty list is perfectly valid, as it is different from a field where `null` is passed on. If you only want to accept lists with at least one element, please add custom validation inside of your resolvers.
