### ISSUE TITLE
String References not working with `InputFields`

### ISSUE THREAD

**Issue by cwaeland** [graphql-python/graphene#157]
In order to overcome some circular dependencies I switched over my Schema to use String References as mentioned in this issue: https://github.com/graphql-python/graphene/issues/110

However, I've run into some issues with my `InputObjectType` classes.  So looking at something of the form:

```
# category_type.py
@schema.register
class CategoryInput(graphene.InputObjectType):
    Post = graphene.List('PostInput')

# post_type.py
@schema.register
class PostInput(graphene.InputObjectType):
    category = graphene.InputField('CategoryInput')
```

The `InputField` referencing 'CategoryInput' triggers an [AssertionError](https://github.com/graphql-python/graphql-core/blob/master/graphql/type/definition.py#L618) (`AssertionError: PostInput.category field type must be Input Type but got: CategoryInput.`) saying that it's expecting an InputType as opposed to 'CategoryInput'.  However, the `List` seems to work correctly.  Taking a cursory glance at the code I'm thinking it's not correctly converting the String reference to the `InputObjectType`.

Any ideas?

**Comment by cwaeland** [comment]
I've found that using something like `category = graphene.InputField(schema.types['CategoryInput'])` works.  Although that seems like it shouldn't be necessary.

**Comment by syrusakbary** [comment]
I just fixed this in the latest commit.
