### ISSUE TITLE
When passing the empty string to Date Type, it occurs `IndexError: string index out of range`

### ISSUE THREAD

**Issue by KaniKim** [graphql-python/graphene#1571]
* **What is the current behavior?**

![image](https://github.com/user-attachments/assets/6cea08c3-b58d-472a-8889-3da150898db6)
![image](https://github.com/user-attachments/assets/ed8c7d16-d8bb-4282-a174-fe8e18eb03b5)

* **What is the expected behavior?**

When I passed a empty string to Date Field, It occurs GraphQL 400 error, with message, `IndexError: string index out of range`

And then I found that `aniso8601` module occurs this error. Are there any solutions to prevent this one?

I can just pass a `null` to Date, but I think there are more proper way to handle this problem.

* **What is the motivation / use case for changing the behavior?**

If the behavior of sending empty string is wrong, I think this would be good time to change module or package

* **Please tell us about your environment:**

  - Version: graphene-django = "2.16.0", graphene = "2.1.9"
  - Platform: mac os sonoma 14.5, python 3.11.9

**Comment by erikwrede** [comment]
Hey,
this should be fixed in Graphene 3, as we don't rely on aniso anymore.

**Comment by KaniKim** [comment]
@erikwrede I apologize for not noticing. I will be more careful next time. Thank you for letting me know.
