### ISSUE TITLE
Django:  how to set_cookie with graphQL mutation?

### ISSUE THREAD

**Issue by HelloYie** [graphql-python/graphene#160]
Hi! How to set cookie in my domain by `response.set_cookie()` with graphql ? For exmaple:
```python
import graphene

class CreatePerson(graphene.Mutation):
    class Input:
        name = graphene.String()
    person = graphene.Field('Person')

    @classmethod
    def mutate(cls, instance, args, info):
        person = Person(name=args.get('name'))

        # ======== Here I want to set_cookie and return httpResponse ... =======

        return CreatePerson(person=person)
```

**Comment by syrusakbary** [comment]
Hi @HelloYie, you cannot "quit" the GraphQL context inside a GraphQL query.

In fact, there is a good reason for that:
If you quit the GraphQL context, GraphQL could not assure that all the mutations that the client sent are executed.
