### ISSUE TITLE
Middleware support

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#163]
I just started looking into the new graphql version - first of all thanks for all the work, the Promise stuff is really going to make things simpler for us. 

Before the update graphql supported multiple excutors/middlewares such as:

```
    import third_party.python.graphene as graphene
    from third_party.python.graphql.core.execution import Executor

    return graphene.Schema(
        query=Query,
        mutation=Mutation,
        name='Some Relay Schema',
        executor=Executor([ZipkinGraphqlMiddleware(), ThreadPoolExecutionMiddleware()]))
```

Now after looking into this, first of all the `Executor` is gone, but also from what I can see only one excutor/middleware is allowed per schema? Is that right, or am I just reading into the code wrong and I could just pass a list of middlewares?

As a side note: This is an extremely useful feature for us and do hope support is still here :)

**Comment by syrusakbary** [comment]
Hi @Globegitter, for simplifying the executors in `graphql-core` we got rid of the middleware, so there is no longer any way for having multiple "middlewares" at the same time.

What could be the use case for having middleware?

**Comment by Globegitter** [comment]
@syrusakbary We used it for zipkin tracing, i.e. to get an accurate time profile of each resolve function. This has been quite useful to track down performance bottlenecks.

**Comment by syrusakbary** [comment]
I think is reasonable adding middleware.

I'm checking various implementations like:
* [express](http://expressjs.com/en/guide/writing-middleware.html) (node.js)
* [Koa](https://github.com/koajs/koa/blob/master/docs/guide.md#writing-middleware) (node.js)
* [Django middleware](https://docs.djangoproject.com/en/1.9/topics/http/middleware/)
* [Aiohttp](http://aiohttp.readthedocs.io/en/stable/web.html#middlewares)
* [GraphQL-Ruby](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/defining_your_schema.md#middleware)

**Comment by syrusakbary** [comment]
I added support for middlewares, now you should be able to add tracking :)

**Comment by syrusakbary** [comment]
Check instructions here: http://graphene-python.org/docs/middleware/

**Comment by Globegitter** [comment]
@syrusakbary man that was fast! Thanks :D

**Comment by syrusakbary** [comment]
@Globegitter any feedback on the middleware? :)

**Comment by Globegitter** [comment]
@syrusakbary Haven't gotten around to it just yet. Been working on improving error-handling and Promise support first :) It is on my list for this week though, so will let you know once I got to it.
