### ISSUE TITLE
Discussion - Pass context to resolve methods

### ISSUE THREAD

**Issue by mjtamlyn** [graphql-python/graphene#164]
The context story seems very confused in the newest version. My understanding from [the graphql-js 0.5.0 release notes](https://github.com/graphql/graphql-js/releases/tag/v0.5.0) is that all resolving functions should now have the signature `([self,] args, context, info)`, as opposed to `([self,] args, info)`.

At the moment, if I update a `resolve_NAME` method to take context, then it throws argument errors.

Also, mutations don't take context and therefore they cannot access context data. It think a patch similar to [this one](https://github.com/graphql/graphql-relay-js/pull/77) on graphql-relay-js is necessary for the relay mutations at least, but probably for all of them.

**Comment by danielfarrell** [comment]
That PR seems to address this issue for me, and I've got it working locally.  If there should be anything else on there, let me know.

**Comment by syrusakbary** [comment]
@mjtamlyn @danielfarrell thanks for opening the issue and the PR.

How the resolvers will work in future versions of graphene will be similar to the one exposed in the [Roadmap](https://github.com/graphql-python/graphene/wiki/Roadmap), so `context` and `info` will be not mandatory arguments in the resolver and resolvers could access the context and info only if they requested explicitly by using the `with_context` and `with_info` decorators.

The current implementation only uses `with_context`, as step in the middle before the next stable release.

*PS: In JS this is a little bit easier as you could call a function with less arguments than required without triggering an error as it will complete the argument values with undefined.*

Thoughts?

**Comment by mjtamlyn** [comment]
Right, I think that makes sense. Python actually wanting a proper set of arguments to a function does complicate the issue slightly.

By the way, there's no tagged release or changelog I can find for 0.9 which did make this slightly more complicated to work out! I'll give it a go using `with_context`.

**Comment by mjtamlyn** [comment]
Ok, I've got it working fine apart from relay mutations which need a bit of extra work I've done in the PR. It would also be very helpful to add some docs about `with_context` and how to use it.

**Comment by danielfarrell** [comment]
Dangit, how was I all over the codebase yesterday and didn't see `with_context`.  Ha, I'll close the PR.

**Comment by Globegitter** [comment]
@syrusakbary is it possible to maybe have this as an option? We use the `context` all over the place and it would be quite a pain to have to add the `with_context` decorator to 90% of our resolve function. Also it does not seem too much of an issue to me to just write `resolve_bla(self, _, __) if you don't need the arguments.

**Comment by mjtamlyn** [comment]
I would agree that `resolve_blah(self, args, **options)` where `options` is now `info=, context=` but can be extended later would be more pythonic.

**Comment by syrusakbary** [comment]
I would like to discuss about that.
Somehow I like having the args exposed directly as keyword arguments in the resolver.

Like:
```python
class Query(graphene.ObjectType):
    say = graphene.String(what=graphene.String())
    def resolve_say(self, what):
        return "Hey {}".format(say)
```

I think it's too verbose having `info` and `context` as required arguments... as are not going to be used always.

Maybe using a decorator (like `with_context`) seem a very "magic" solution that could not be maintainable.

I would like to get into a solution that could solve both point of view at the same time.

**Comment by Globegitter** [comment]
@syrusakbary yeah that is a quite difficult one. I mean the only other solution I could think of then is `dict(args=args, context=context, info=info)` to not have potential name conflict. I personally would prefer that all to the decorator.

**Comment by mjtamlyn** [comment]
Ok, so this is a tricky design decision in some ways because we want to mimic the "argument magic" that javascript can manage in python. We've also got a possible name clash issue.

Here are a few possible approaches:
- Use decorators to explicitly mark which resolvers need which arguments. This is the current proposal. It doesn't feel very pythonic. We could have a convention that `context` and `info` could be passed as `_context` and `_info` if there's a name clash, or always.
- Use the inspect module to find the signature. `inspect.getargspec(resolver_func).args` will return a list of names of arguments. If that includes `context` or `info` then we pass them. This is "fully" magical, but I don't find it any more distasteful than the `_root`/`getattr` pattern we have at the moment. I'm not sure if we can get access to which arguments might be relevant to deal with name clashes, but it would be easy to see if a user is expecting `context` AND `_context` and pass the arg as the former and the context as the latter.
- Define a more pythonic standard API for a resolver. Something like `def resolve_foo(self, arg1, arg2, **options)`. Again we can deal with name clashes with `_context` if necessary, or just have a convention that you don't do that. I feel this is the route we would be taking if there wasn't the JS reference implementation.

**Comment by syrusakbary** [comment]
Hi @mjtamlyn, @Globegitter.

I've been researching and Jinja use the decorators for passing some extra args to the function.
http://jinja.pocoo.org/docs/dev/api/#jinja2.contextfunction
Implementation: https://github.com/pallets/jinja/blob/75685ec5e5079bcdbd443696c3d79d0cb86f7cf8/jinja2/utils.py#L41

Also, if this is the final path... could be completely possible to skip this behavior.

I'm not very sure yet about what's the good choice here though.

Another option, is grouping context and info in other instance and pass something like:

```python
def resolve_blablabla(self, context_with_info, **args):
    pass
```

**Comment by ekampf** [comment]
Maybe its coming from the Ruby world... but I kinda like the "magical" approach of automatically injecting values by argument name using `inspect.getargspec(resolver_func).args` (and `inspect.signature()` in 3.6+).
This way you can automatically not just `context` and `info` but args like in @syrusakbary's example too.

This automatic objection could be implemented as a decorator too... (which can help resolving possible name by providing some sort of mapping between default name and var name...)

**Comment by syrusakbary** [comment]
@ekampf @mjtamlyn I've been thinking in a good way to solve this for a long time.

If we use a magical approach using `inspect`, we could make the api's more obscure and handling things like middleware could become a problem (as the middleware functions have to be aware of the resolver context based on the inspection of the original function).

Also, the resolver in `graphene` should have exactly the same structure as is in `graphql-core`.

I'm thinking of merging back `context` into `info`, so you can have functions like:
```python
def resolve_blablabla(self, info, args):
    context = info.context
    # ...
```

Thoughts?

**Comment by mjtamlyn** [comment]
I think `info, args` is the simplest option, I don't think we need extra arguments.

**Comment by Globegitter** [comment]
@syrusakbary Having thought about it a bit more I am leaning mostly towards the `inspect.getargspec(resolver_func).args` approach suggested by @ekampf. That would make it really straightforward and simple to use.

Also if the arguments passed in would ever change again it that approach would imo make it a bit simpler.

That all said though, I do think your suggested approach also works.

**Comment by syrusakbary** [comment]
I think I found a way to make the resolvers much more fun to write using type annotations in Python 3.

Would love to get some feedback! @Globegitter @mjtamlyn @ekampf
Code and examples of usage in the PR: #500

**Comment by FrankSalad** [comment]
According to the docs: http://docs.graphene-python.org/en/latest/types/objecttypes/

`By default resolvers take the arguments args, context and info.`

then the example only contains `info` and `word`. There was no usage or discussion of the `info` or `context` params at all. I'm *still* digging around to try to understand what I should expect in these params. This is confusing and unpythonic. I had to find this issue to understand what you guys were even trying to do here.

**Comment by vinigfer** [comment]
In case anyone is also having troubles on how to access the context, after an endless effort/search I found on this link:

http://docs.graphene-python.org/projects/django/en/latest/authorization/

that I can access context like this:

```if not info.context.user.is_authenticated():```

Hope this helps anyone

**Comment by jkimbo** [comment]
Hi @mjtamlyn . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
