### ISSUE TITLE
Plugins bypassed

### ISSUE THREAD

**Issue by sdcooke** [graphql-python/graphene#165]
Since this method has been removed (in 0.9) https://github.com/graphql-python/graphene/blob/v0.8.0/graphene/contrib/django/views.py#L15 and the execution code paths have changed plugins are no longer executed unless you call schema.execute directly.

**Comment by syrusakbary** [comment]
Good catch. Will fix this soon

**Comment by syrusakbary** [comment]
Plugins are now deprecated. If you were using `DjangoDebugPlugin` please see the latest docs for integrate `DjangoDebugMiddleware`.

http://graphene-python.org/docs/django/debug/

**Comment by syrusakbary** [comment]
(using the middleware should solve the problem)
