### ISSUE TITLE
access to context (request) in DjangoConnectionField.get_queryset()

### ISSUE THREAD

**Issue by stefanfoulis** [graphql-python/graphene#179]
We're subclassing ``graphene.contrib.django.fields.DjangoConnectionField.get_queryset()`` and ``graphene.contrib.django.fields.filter.DjangoFilterConnectionField.get_queryset()`` to enforce user based queryset filtering. To do the permission based filtering we need ``request.user`` in ``get_queryset()``. Previously we got it from ``info.request_context.user``, but this is no longer available. And ``@with_context`` does not seem to work here.

I have the same problem on ``graphene.contrib.django.types.DjangoNode.get_node``, where I also need ``request.user`` to filter results.

Maybe I missed something. Is there a better way to do this?

https://github.com/graphql-python/graphene/blob/da0927aa841635c5b44fb496497d80d26f916fbc/graphene/contrib/django/fields.py#L28

**Comment by mjtamlyn** [comment]
This could be fixed in the same way as `mutate_and_get_payload` was fixed - https://github.com/graphql-python/graphene/commit/61e7beee7b9c83c55b7b47c3814f120e421400b6. The discussion is quite related to what we decide to do in the long term with resolver functions though - See #164

**Comment by stefanfoulis** [comment]
Thanks for the pointers you grave me on slack @mjtamlyn .

This is my ``DjangoNode`` subclass that allows filtering the queryset by overriding ``get_queryset()``:

```python
class QuerysetDjangoNode(graphene.contrib.django.types.DjangoNode):
    class Meta:
        abstract = True

    @classmethod
    def get_queryset(cls, id, context, info=None):
        """
        Added get_queryset to allow overriding the queryset in subclasses.
        """
        model = cls._meta.model
        return model.objects

    @classmethod
    @graphene.with_context
    def get_node(cls, id, context, info=None):
        """
        Same as super(), but gets the queryset from get_queryset()
        """
        qs = cls.get_queryset(id, context, info=info)
        try:
            instance = qs.get(id=id)
            return cls(instance)
        except cls._meta.model.DoesNotExist:
            return None
```

and this is an application specific subclass that always adds ``.for_user(user)`` to the queryset (we have that method as a chainable queryset on all Model managers:

```python
class PermissionAwareDjangoNode(QuerysetDjangoNode):
    class Meta:
        abstract = True

    @classmethod
    @graphene.with_context
    def get_queryset(cls, id, context, info=None):
        qs = (
            super(PermissionAwareDjangoNode, cls)
            .get_queryset(id, context=context, info=info)
        )
        user = context.user
        return qs.for_user(user)
```

and similarly a permission aware ``DjangoFilterConnectionField``:

```python
class PermissionAwareDjangoFilterConnectionField(
    graphene.contrib.django.filter.DjangoFilterConnectionField):

    def get_queryset(self, qs, args, context, info):
        # permission check:
        qs = qs.for_user(context.user)
        return (
            super(PermissionAwareDjangoFilterConnectionField, self)
            .get_queryset(qs, args, info)
        )

    def from_list(self, connection_type, resolved, args, context, info):
        resolved_qs = maybe_queryset(resolved)
        qs = self.get_queryset(resolved_qs, args, context, info)
        return (
            # we are calling super of DjangoConnectionField on purpose, because
            # we've re-implemented from_list here and don't want to run it
            # again.
            super(graphene.contrib.django.fields.DjangoConnectionField, self)
            .from_list(connection_type, qs, args, context, info)
        )
```

**Comment by stefanfoulis** [comment]
I'm closing this issue for now. If there is interest in having ``get_queryset()`` on ``DjangoNode`` in core, I can make a pull request.

**Comment by mjtamlyn** [comment]
Thanks, that's really useful!

I think it makes sense for `get_queryset` to have a consistent API between `DjangoNode`, and possibly also `DjangoConnection` rather than `DjangoConnectionField`. I was bouncing some ideas around in https://github.com/graphql-python/graphene/issues/180#issuecomment-221283513 which might remove the need for a separate connection field anyway.

The [Roadmap](https://github.com/graphql-python/graphene/wiki/Roadmap) plans to move `graphene.contrib.django` out into its own package (`graphene-django`) for 1.0. I think in that package we need to try and provide approaches which feel more "Django" than "graphql-js", having this `get_queryset` method definitely does that.
