### ISSUE TITLE
Improvements next stable package

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphene#18]
Inspired by other GraphQL implementations, next version should be able to:

* [x] Simplify Fields definition (rename `graphene.{type}Field` to `graphene.{type}`).
* [x] Add Types dynamic instantiation into ObjectTypes, Interfaces (as field), or in Field kwargs (as Arguments)
* [x] Add `.List` , `.NonNull` to Types
* [x] Add Union Type
* [x] Add Scalar Type (for having, for example a DateTime Scalar type)

**Comment by jhgg** [comment]
Mmmmmmmm. Good ideas.
