### ISSUE TITLE
Django debug toolbar conflicts

### ISSUE THREAD

**Issue by mjtamlyn** [graphql-python/graphene#181]
[This commit](https://github.com/graphql-python/graphene/commit/c5b15cec2f0a7082006b94314ca45ee1322af60d) attempted to fix the conflict between DDT and the SQL tracking in the debug middleware (formerly plugin).

Unfortunately this doesn't seem to work at the moment. We delete `connection.cursor` in the `unwrap_cursor` functions in both [Graphene](https://github.com/graphql-python/graphene/blob/master/graphene/contrib/django/debug/sql/tracking.py#L51) and [DDT](https://github.com/django-debug-toolbar/django-debug-toolbar/blob/0ed1538374d3dc41d51fc562b4e8be6ce8208552/debug_toolbar/panels/sql/tracking.py#L51).

I'm not 100% sure what the correct approach here should be, especially within graphene as the DDT code will execute later. Would having both sets of tracking set up result in a problem anyway?

For the moment, you can disable the SQL panel in DDT when you want to use the middleware. Perhaps if we can't have both cursor wrappers enabled, we could detect the `hasattr(connection, '_djdt_cursor')` case and print a more helpful message.

**Comment by dvf** [comment]
Unearthing here, but is there any update here?
