### ISSUE TITLE
Explicit registration of object types

### ISSUE THREAD

**Issue by mjtamlyn** [graphql-python/graphene#182]
I'm not sure if the answer to this is "I'm doing it wrong" but here we go.

## Problem

So one thing I want to do is to be able to get information about the current user from the API. I have an `AnonNode` and a `UserNode` which both implement `UserInterface`. I think add a field `current_user = graphene.Field(UserInterface)` with an appropriate resolver. `UserNode` is also explicitly registered in other places, but `AnonNode` is not, I'm not using it for anything other that this specific field. If I query the field as an anonymous user, I get the following error:

```
Runtime Object type "AnonNode" is not a possible type for "UserInterface".
```

If I explicitly register the `AnonNode` by adding a meaningless field anywhere in my schema which uses that type directly, everything works.

I was hoping to be able to use `schema.register(AnonNode)`, but this seems to only update `graphene.Schema` and not the underlying `graphql.Schema`. The new type becomes present in `my_schema.type_map` but not `my_schema.schema.type_map`. The latter appears to be largely immutable.

## Possible solutions
- Deal with having to have every type associated directly with a field, but document that in the interfaces docs
- Update `schema.register` to allow explicit registration of arbitrary object types.
- Add some other API for explicit registration.
- Update `graphene.Field` to give it an extra `implementations` arg or similar when registering an `Interface` (this could  - anything matching that interface should be valid).

**Comment by syrusakbary** [comment]
I think is possible to fix `schema.register` adding the type also in the `types` argument in `GraphQLSchema` (GraphQL `v0.5.0`)

If you please can post (here or creating a test scenario in a branch) the code for showcasing this bug would be great. So I can be make sure that the fix is working :)

**Comment by mjtamlyn** [comment]
I think that's a minimal test case.

**Comment by jameswyse** [comment]
👍  I was also having difficulty understanding/implementing this.

**Comment by syrusakbary** [comment]
Just pushed a fix into master.
