### ISSUE TITLE
Flask SQLAlchemy example app /graphiql 404

### ISSUE THREAD

**Issue by iawia002** [graphql-python/graphene#188]
I clone Flask SQLAlchemy example and after I install the requirements, I run the app, when i access `/graphiql` i got a 404, but `/graphql` is ok

**Comment by syrusakbary** [comment]
Hi @iawia002, the latest version of flask-graphql have the graphiql endpoint in the `/graphql` url.

You have to enable it having the option `graphiql=True`:
```python
app.add_url_rule('/graphql', view_func=GraphQLView.as_view('graphql', schema=schema, graphiql=True))
```

**Comment by iawia002** [comment]
thanks
