### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphene#19]
Add documentation based on the GraphQL one: http://graphql.org/docs/getting-started/

Also, improve based in other implementation docs. (sangria)

Sections:
- Scalars
- Interfaces
- ObjectTypes
- Unions
- InputTypes
- Mutations
- Relay
- Schema
- Django Models

**Comment by ratson** [comment]
I am wondering how it could be integrated with `django.contrib.auth`, an example / tutorial will help a lot.

**Comment by adamcharnock** [comment]
I'm just getting started and this looks really promising, but some docs would *really* help out. I'd be happy to lend a hand in anyway I can (e.g. proofing, newbie's perspective)

**Comment by syrusakbary** [comment]
Thanks @adamcharnock, will let you know once the docs are ready!

**Comment by syrusakbary** [comment]
@adamcharnock Some of this new documentation is now living in the `docs` branch (until is finished and merged into master), take a look and let me know your thoughts! https://github.com/graphql-python/graphene/tree/docs/docs/pages

Feel free to open any Pull request into `docs` branch with all the changes/improvements you think could be useful!!

* [x] docs / Quick start
* [x] docs / Django Quick start
* [x] guide / ObjectType
* [x] guide / Interface
* [x] guide / Mutation
* [ ] guide / Fields
* [ ] guide / Relay

**Comment by adamcharnock** [comment]
Fantastic! I've just submitted #54 which expands the django quickstart a little
