### ISSUE TITLE
Add a `--indent` option to `./manage.py graphql_schema`

### ISSUE THREAD

**Issue by mjtamlyn** [graphql-python/graphene#192]
Like in [`dumpdata`](https://docs.djangoproject.com/en/1.9/ref/django-admin/#dumpdata).

This will make VCS diffs in the schema easier to understand.

**Comment by syrusakbary** [comment]
I think this is reasonable :)

**Comment by jkimbo** [comment]
PR: https://github.com/graphql-python/graphene/pull/241

**Comment by mjtamlyn** [comment]
Thanks @jkimbo
