### ISSUE TITLE
How to optimize django nested/related/joined queries?

### ISSUE THREAD

**Issue by antitoxic** [graphql-python/graphene#197]
What is the recommended way to execute and optimized query in django that includes related objects with graphene?

```
article {
  categories: {
     creator: ...
  }
```

Graphene schema is declaritve way to get/resolve a node but how do you build an efficient query?

**Comment by mjtamlyn** [comment]
This appears to be an open problem at the moment. There's some discussion in #57, #28 and in the JS graphQL implementation in https://github.com/graphql/graphql-js/pull/304.

**Comment by syrusakbary** [comment]
There is no much progress in the *planning phase* related to the GraphQL execution.
Other than that, now is possible to use `DataLoader`s with Graphene, solving the N+1 loading problem.
http://docs.graphene-python.org/en/latest/execution/dataloader/

Closing the issue.
