### ISSUE TITLE
How to make a List that allows null values?

### ISSUE THREAD

**Issue by MrSurly** [graphql-python/graphene#202]
If I specify a list in this manner:

```
class UserNotificationsInput(graphene.InputObjectType):
    # other fields removed for clarity
    regions                 = graphene.List(graphene.String())
```

And then try to mutate:
```
mutation { 
   updateUser( userId: "c8af345f-e785-490d-8d55-0af6048a5d3e", 
    notifications: {
       regions: [ Null ]
} ) { success reason} }
```

I get this: 

> Argument "notifications" has invalid value < ... very long actual input removed ... > In field "regions": In element #0: Expected type "String", found Null.

My (probably wrong) understanding is:

graphene.List(graphene.String())                               # <-- **Nullable** list that **can** contain nulls
graphene.List(graphene.NonNull(graphene.String())) # <-- **Nullable** list that **cannot** contain nulls
graphene.NonNull(graphene.List(graphene.String()) # <-- **Non-null** list that **can** contain nulls
graphene.NonNull(graphene.List(graphene.NonNull(graphene.String())) # <-- **Non-null** list that **cannot** contain nulls

**Comment by syrusakbary** [comment]
Hi @MrSurly, I think the issue is in typing `Null` instead of `null` in the input.

Hopefully this will solve the issue, please reopen if not.
PS: Your understanding in the nullables is perfect :)
