### ISSUE TITLE
/graphiql 404 not found in Flask-sqlalchemy example

### ISSUE THREAD

**Issue by ap1459777123** [graphql-python/graphene#203]
Hi, sry for asking this simple and stupid question..

I just followed the README (https://github.com/graphql-python/graphene/tree/master/examples/flask_sqlalchemy) and started a flask app, but when visiting http://0.0.0.0:4999/graphiql, I got 404 not found for resp.
(and resp `{"errors":[{"message":"Must provide query string."}]}` for http://0.0.0.0:4999/graphql)

I've changed `app.run()` to `app.run(host='0.0.0.0', port=4999)` above, yet using default config (`app.run()`) still got 404 when visiting http://127.0.0.1:5000/graphiql.

I run app use cmd `$ python app.py` and here is my virtualenv after pip install:
$ pip freeze
Flask==0.10.1
Flask-GraphQL==1.3.0
graphene==0.10.2
graphql-core==0.5.2
graphql-relay==0.4.2
iso8601==0.1.11
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
promise==0.4.1
singledispatch==3.4.0.3
six==1.10.0
SQLAlchemy==1.0.11
Werkzeug==0.11.10

I am wondering if there is something I misunderstood and will keep trying, thanks for reading this!

**Comment by ap1459777123** [comment]
Hi!

After tracing some code in flask-graphql and refering to https://pypi.python.org/pypi/Flask-GraphQL, I found that `GraphQL` should take argument `graphiql=True`.

So app.py:30
`GraphQL(app, schema=schema, default_query=default_query)`
should be
`GraphQL(app, schema=schema, default_query=default_query, graphiql=True)`
And the gui would be found at /graphql.

Also tested POST method /graphql with payload `{"query":"query{allEmployees{edges{node{id}}}}"}`,
 was able to get the content set in database.py

Thanks!

**Comment by syrusakbary** [comment]
Thanks for submitting the issue!

I've updated the docs reflecting the latest version usage of `Flask-GraphQL`.

https://github.com/graphql-python/graphene-python.org/commit/60ba59b2bcc9c3e2f5c9fa4ffa167a660f0490b8
