### ISSUE TITLE
order_by_fields not working

### ISSUE THREAD

**Issue by stefanfoulis** [graphql-python/graphene#207]
If I add ``order_by_fields=True`` or ``order_by_fields=['my_field']`` to on a ``DjangoNode`` on the ``Meta`` class (as is described in the docs), I get the following error:

``TypeError: 'class Meta' got invalid attribute(s): order_by_fields``

Searching through the entire sourcecode of graphene only shows ``order_by_fields`` to appear in the docs.

**Comment by syrusakbary** [comment]
Hi @stefanfoulis, the docs were wrong... the actual attribute is `filter_order_by`. Fixing it now.
