### ISSUE TITLE
Incorrect resolver param makes the entire query return None

### ISSUE THREAD

**Issue by mattbillenstein** [graphql-python/graphene#212]
Taking the tea store example:

https://gist.github.com/mattbillenstein/ecc3e8b3b1130e615b2f6f6e5beca5ea

You'll note I spelled the "orderBy" param "orderby" in the second execute -- it doesn't raise any type of exception, but just returns None.  This makes debugging queries basically impossible.

IMO, exception handling in this framework is poor and makes it generally unusable for anything real -- the default should be to raise with perhaps options to catch and null out some fields -- let the consumer deal with exceptions.  Catching everything and passing it through logging is bad practice in Python IMHO.

**Comment by syrusakbary** [comment]
Hi @mattbillenstein, you can get the exceptions with result.errors.
But I agree with you that the exceptions handling in GraphQL/Graphene should be better when playing with it. I'm researching in few different ways to improve it, any help will be always welcome too.

**Comment by jkimbo** [comment]
@syrusakbary is this still an issue since 2.0? I have not had any issues with error handling in 2.0

**Comment by syrusakbary** [comment]
Exception handling has been improved significantly in Graphene 2.0, we can close the issue but @mattbillenstein feel free to reopen if you think is still an issue.
