### ISSUE TITLE
Resolving List of ObjectTypes with AsyncExecutor

### ISSUE THREAD

**Issue by AlecAivazis** [graphql-python/graphene#214]
Hey @syrusakbary, 

I'm having trouble resolving a list of object types from a coroutine. If I run the following example:

``` python
import asyncio
from graphql.execution.executors.asyncio import AsyncioExecutor
import graphene

class Recipe(graphene.ObjectType):
    name = graphene.String()

class Query(graphene.ObjectType):

    recipes = graphene.List(Recipe)

    @asyncio.coroutine
    @graphene.resolve_only_args
    def resolve_recipes(self):
        return [
            Recipe(name='hello')
        ]


schema = graphene.Schema(
    query=Query,
    executor=AsyncioExecutor()
)

executed = schema.execute("""
    query {
        recipes {
            name
        }
    }
""")

print(executed.data)
```

Then I get  `OrderedDict([('recipes', [])])` printed in the console. However, If I remove the `asyncio.coroutine` decorator then I get what I expected: `OrderedDict([('recipes', [OrderedDict([('name', 'hello')])])])`. Am I missing something?

**Comment by insolite** [comment]
Looks like resolver should not be a `coroutine`. However it can return `asyncio.Future` which will be executed asynchronously. And of course `Schema.execute` should be called with `return_promise=True` to get promise and execute it in your asyncio event loop. I've modified your code a bit so now it now returns `OrderedDict([('recipes', [OrderedDict([('name', 'hello')])])])` as expected.
```python
import asyncio
from graphql.execution.executors.asyncio import AsyncioExecutor
import graphene

class Recipe(graphene.ObjectType):
    name = graphene.String()

class Query(graphene.ObjectType):

    recipes = graphene.List(Recipe)

    @asyncio.coroutine
    def async_resolve_recipes(self):
        return [
            Recipe(name='hello')
        ]

    @graphene.resolve_only_args
    def resolve_recipes(self):
        return asyncio.async(self.async_resolve_recipes())


schema = graphene.Schema(
    query=Query,
    executor=AsyncioExecutor()
)

executed_promise = schema.execute("""
    query {
        recipes {
            name
        }
    }
""", return_promise=True)
executed = asyncio.get_event_loop().run_until_complete(executed_promise)

print(executed.data)
```

**Comment by syrusakbary** [comment]
I think this is solved in the latest version of Graphene, GraphQL core and Promise.

Please reopen the issue if not!
