### ISSUE TITLE
Can't use filter named "type" in graphene.Field

### ISSUE THREAD

**Issue by tom-zeit** [graphql-python/graphene#216]
Hello,

I'm trying to create filters for my django model, and one of the model fields is called "type". 
The following code throws an exception:
`    bla = graphene.Field(DocumentNode, type=graphene.String())
`
This is the exception:
`    TypeError: __init__() got multiple values for argument 'type'
`

That's because the init function of graphene.Field has already argument called type.

I think that the best solution to avoid this kind of issues is to pass the filter arguments explicitly in a specific dictionary arguments.

**Comment by syrusakbary** [comment]
@tom-zeit the first parameter of the Field is the GraphQL type, and is named as `type` keyword argument.
You can bypass this this by doing:
```python
bla = graphene.Field(DocumentNode, _type=graphene.String(name='type'))
```

Please reopen the ticket if this doesn't work or you run in more issues.
