### ISSUE TITLE
orderBy multiple fields

### ISSUE THREAD

**Issue by sehmaschine** [graphql-python/graphene#218]
I'm just trying to construct a query with multiple ordering fields (I'm using the django example btw).

Here's what I have right now ...

```
{
  allCategories(orderBy: "name")
  edges {
    node {
      id
      name
      slug
    }
  }
}
```

This works fine, but I like to order by multiple fields ...

```
allCategories(orderBy: "name, slug")
allCategories(orderBy: ["name", "slug"])
```

Am I using the wrong syntax or is this not even possible?

**Comment by syrusakbary** [comment]
Graphene doesn't support that yet, it might be a good case to add!

**Comment by ivlevdenis** [comment]
https://gist.github.com/ivlevdenis/3fb0ede89650889cc9f62a77770e7156

**Comment by callsamleung** [comment]
@ivlevdenis helpful. "inherit" is very "beautiful" solutions, thank you so much.

**Comment by heyrict** [comment]
I'm using this resolve function to handle a list of orderBy.
(Though filtering with annotation does not work recently.)
```python
    def resolve_all_users(self, info, **kwargs):
        orderBy = kwargs.get("orderBy", None)

        if orderBy:
            return User.objects.order_by(*orderBy)
        else:
            return User.objects.all()
```

**Comment by jkimbo** [comment]
Looks like some workable solutions have been suggested for this issue. Closing

**Comment by piaro** [comment]
great solutions, thanks
