### ISSUE TITLE
How to set default for custom object types arguments?

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#219]
I want have something like:

``` py
field = graphene.Field(SomeField,    
    order_by=graphene.Argument(graphene.List(OrderingParameter,
                                             default=[OrderingParameter(
                                                  key=OrderingKeys.CREATION_TS,
                                                  direction=OrderingDirection.DESC)]
                                             )),)
```

that is being able to have a list-argument but also set a default for it. The OrderingParameter is an `InputObjectType` so I get `Exception: An InputObjectType cannot be initialized`. Is there any way around this, apart from not having a default and then just having some logic in the resolver?

**Comment by yfilali** [comment]
I think what you're looking is on Argument (not list like you show above) and is called default_value, not default:
```

        field = graphene.Field(SomeField, order_by=graphene.Argument(graphene.List(OrderingParameter), default_value=[
            OrderingParameter(key=OrderingKeys.CREATION_TS, direction=OrderingDirection.DESC)])

```
https://github.com/graphql-python/graphene/blob/master/graphene/types/argument.py#L11

P.S.: Jul 5th unanswered issue! I hope this is still relevant to you...

**Comment by Globegitter** [comment]
@yfilali That has changed with the `1.0` release and thanks for the answer, will give that a try.

**Comment by jkimbo** [comment]
Hi @Globegitter. We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
