### ISSUE TITLE
Arguments on individual Node fields

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#22]
It would be great to have a test/example that shows how args on e.g. a `StringField` work. Right now I am getting an error `AssertionError: Client.name(test:) argument type must be Input Type but got: ....`

I have tried to use `InputObjectType` but there are very few tests on that and very little documentation (in the source code)

Also, now that I am starting to understand graphql, relay and graphene better I would be more than up to add some more tests or documentation if that would help at all.

**Comment by Globegitter** [comment]
Ahh, managed to get it to work using e.g. `full_name = graphene.StringField(args={'to': graphene.Argument(graphene.String)})`

**Comment by syrusakbary** [comment]
Great! A new simpler syntax will come with version `0.4.0` that simplifies how arguments and fields are handled
