### ISSUE TITLE
How to return nested structure?

### ISSUE THREAD

**Issue by czchen** [graphql-python/graphene#221]
Hello,

I want to return the following JSON in graphene:

```json
{
    "key1": {
        "key2": "value2"
    }
}
```

However, I don't know how to write the return Object for this kind of return. I tried the following code, but graphiql does not show `key1` at all.

```python

class Inner(ObjectType):
    key2 = String()

class Outer(ObjectType):
    key1 = Inner()
```

**Comment by Globegitter** [comment]
I think you have to instantiate it as `graphene.Field(Inner())`. And your types are also registered in the schema?

**Comment by czchen** [comment]
@Globegitter Thanks for the hint.

**Comment by alehl** [comment]
@czchen something like this? 

```    class Inner(CmsObjectType):
        image_asset = GrapheneHelper.string_field('image_asset')

    class Outer(CmsObjectType):
        height = GrapheneHelper.int_field(Inner('height'))
        width = GrapheneHelper.int_field(Inner('width'))```
