### ISSUE TITLE
DjangoFilterConnectionField does not support lazy types.

### ISSUE THREAD

**Issue by nickhudkins** [graphql-python/graphene#224]
``` python
class UserNode(DjangoNode):

    full_name = graphene.String()
    avatar = graphene.Field(Image)
    username = graphene.String()

    classmates = DjangoFilterConnectionField(graphene.LazyType('User'))
```

results in this traceback: 

```
  File "***/src/graphene/graphene/contrib/django/filter/fields.py", line 11, in __init__
    self.order_by = order_by or type._meta.filter_order_by
AttributeError: 'LazyType' object has no attribute '_meta'
```

which makes sense, but, it means that DjangoFilterConnectionField is not fully in parity with ConnectionField. 

Is there another way to refer to the `UserNode` there from within the `UserNode` that I'm missing? I believe the proper solution here is to lazily resolve the type but it means I am giving up the DjangoFiltering on the connection because I must use the follwing to make it work:

``` python
class UserNode(DjangoNode):

    full_name = graphene.String()
    avatar = graphene.Field(Image)
    username = graphene.String()

classmates = ConnectionField(graphene.LazyType('User'))
```

**Comment by jkimbo** [comment]
So I've had a quick look into trying to fix this but I'm not sure how to do it. The [line that causes the issue](https://github.com/graphql-python/graphene/blob/b8a9e454fa72220716ed3b2a2b6e1272aa3b540b/graphene/contrib/django/filter/fields.py#L12) and the subsequent lines are used to actually construct the kwargs for the underlying connection type and as far as I can see, need to be defined at instantiation. However `LazyType` needs to have the context of the schema to resolve `Type` into the actual definition and this is not available in the `__init__` method of `DjangoFilterConnectionField` and I can't see an easy way of deferring all the instantiation to resolve time.

@syrusakbary any ideas?

**Comment by nickhudkins** [comment]
Has there been work done to resolve this? If not, I'd love to dive in and see if we can figure this out.

**Comment by pcraciunoiu** [comment]
Currently, there is no way for a`DjangoObjectType` to have a `DjangoFilterConnectionField` that references itself unless this issue is fixed.

Or is there another way and I am missing it?

E.g. This does not work: ```
class User(DjangoObjectType):
    followers = DjangoFilterConnectionField(lambda: User)
```

`Could not import 'example.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: 'function' object has no attribute '_meta'.`

**Comment by nickhudkins** [comment]
Have a look here: https://github.com/graphql-python/graphene-django/pull/58 This may be of use to you

**Comment by jkimbo** [comment]
It looks like this issue might have been fixed in https://github.com/graphql-python/graphene-django/pull/58

In an effort to clean up the issue tracker I'm going to close this issue. If it is still important @nickhudkins  please comment and I'll reopen this.

Thanks!
