### ISSUE TITLE
Creating database sessions per query?

### ISSUE THREAD

**Issue by impguard** [graphql-python/graphene#225]
Using SQLAlchemy and my current process of creating database sessions revolve around a context manager and a session factory.

AKA in a RESTful API I would do something like this:

    def someroute():
        with session_factory() as session:
            ...do some controller stuff with the session...
            return result

Since Graphene/GraphQL seems to wrap a lot of the magic around querying, how do I inject the session I create dynamically on a query/mutation request?

It seems like the model expected here is to have a persistent global database session (instead of a factory)? Am I correct in assuming this?

P.S. I originally opted for this model since I wanted to contain all database side-effecty stuff in one python module instead of having to hook into my backend request teardown loop to handle cleaning up sessions.

**Comment by syrusakbary** [comment]
Hi @impguard thanks for submitting the issue.

In the next version of graphene, the session will be tied to the context, and would be very easy to change the context session depending on the route :)

**Comment by syrusakbary** [comment]
Closing the issue.
You can now use a custom session tied to the GraphQL `context_value` :).

The SQLAlchemy integration is now living here: https://github.com/graphql-python/graphene-sqlalchemy

**Comment by impguard** [comment]
Fantastic! And I see lots of changes have been made since I first played around here. I'll take a look at all the cool work you've done! Thanks!
