### ISSUE TITLE
Django MPTT support?

### ISSUE THREAD

**Issue by zargold** [graphql-python/graphene#226]
Does this or could this support [django mptt ](https://github.com/django-mptt/django-mptt)fields which are used for infinitely nested tree architectures?
* category
 * section
   * keyword
      * magic
      * force
         * light
         * dark

**Comment by syrusakbary** [comment]
Not yet, is completely possible to support it though!
I would be super happy to merge a integration for that, if you are interested in creating a PR! :)

**Comment by syrusakbary** [comment]
The `graphene-django` repo is now separated in its own repo.
https://github.com/graphql-python/graphene-django/

Feel free to open a PR with a integration for `django-mptt`!

**Comment by Eraldo** [comment]
@zargold Did you manage to get mptt to work with graphene-django?
