### ISSUE TITLE
Graphene example is down to minor Syntax error on front end

### ISSUE THREAD

**Issue by zargold** [graphql-python/graphene#228]
1. Went to link in Readme....

> What is supported in this Python version? Everything: Interfaces, ObjectTypes, Scalars, Unions and Relay (Nodes, Connections), in addition to queries, mutations and subscriptions.
>
>NEW!: >[Try graphene online](http://graphene-python.org/playground/)

So I went to the link and got a blank page...
2. got this error in console...

```javascript
webpackMissingModuleError: Cannot find module "!!./../node_modules/gatsby/node_modules/css-loader/index.js!./../node_modules/stylus-loader/index.js!./main.styl"
```

**Comment by syrusakbary** [comment]
This should be fixed now!
Please let me know if the issue persist!
