### ISSUE TITLE
django GraphQLView isn't implemented properly

### ISSUE THREAD

**Issue by jhgg** [graphql-python/graphene#23]
https://github.com/graphql-python/graphene/blob/master/graphene/contrib/django/views.py

Isn't implemented properly. Doesn't do proper error handling & doesn't handle GraphQL variables at all.

I was thinking instead we could remove this from graphene, and make this into it's own standalone package that could be given a GraphQL Schema and create a Django View for it. 

That way it could be used with bare `graphql-core`, `graphql-epoxy` and `graphene`.

Thoughts?

**Comment by jhgg** [comment]
I've created a repo here:

https://github.com/graphql-python/graphql-django-view

I'm going to start porting over the view code, fixing it up, writing tests, etc....

**Comment by syrusakbary** [comment]
Hi @jhgg, I've seen that... I would had love to do it by myself but you been so fast.
Please add me to the pypi package as maintainer so I could update it.

However I think the best thing is mixing the django-graphql and the other view from graphene. And provide only one package. Probably the naming could be improved.
I would love to discuss when a new repo comes out without actually throwing the code into the community, if that makes sense :)

**Comment by jhgg** [comment]
Right. The code was just there to get things setup. I'm probably going to end up re-writing it tomorrow. It doesn't seem to work right with graphiql/relay, and isn't properly handling errors (i.e. syntax errors). 

But I just wanted to have something there for now.

**Comment by jhgg** [comment]
I've rewritten the `GraphQLView` in https://github.com/graphql-python/graphql-django-view/blob/master/graphql_django_view/__init__.py

Need to finish writing tests.

**Comment by syrusakbary** [comment]
Maybe is easier if you start here https://github.com/graphql-python/graphene/blob/master/tests/contrib_django/test_views.py :wink: (vars are not supported in graphene view implementation yet, so are not tested as well)

**Comment by jhgg** [comment]
v1.0.0 has been released w/ stable API & 100% test coverage:

https://pypi.python.org/pypi/graphql-django-view/

**Comment by jhgg** [comment]
Also @syrusakbary I've added you as contributor & maintainer of pypi package.

**Comment by jhgg** [comment]
PR #25 is open to replace the implementation of `GraphQLView` with `graphql-django-view` in an API backwards compatible way. ^^

**Comment by jhgg** [comment]
Closed PR #25 in favor of #26 which will merge into 0.4.0 branch.

**Comment by jhgg** [comment]
Fixed in 0.4.0
