### ISSUE TITLE
django reverse order

### ISSUE THREAD

**Issue by sehmaschine** [graphql-python/graphene#230]
I just tried using a query with reverse ordering:
```
{
    "query": "query {allSections(orderBy:\"-name\"){edges{node{id,name,slug}}}}"
}
```

That doesn't work unless I add ``-name`` to ``filter_order_by``:
```
class SectionNode(DjangoNode):
    class Meta:
        model = Section
        filter_order_by = ['id', '-id', 'name', '-name', 'slug', '-slug', 'position', '-position']
```

Is that intended behaviour?

**Comment by syrusakbary** [comment]
This behavior is defined by `django-filters`, so it's seems is required.

Graphene-Django doesn't enforce it. Closing the issue.

Feel free to open a PR in the docs in the `graphene-django` repo if something could be more clear!
