### ISSUE TITLE
Instantiate graphql types with _ attributes

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#234]
Given a type e.g.

```
class Some(graphene.ObjectType):
  _state = None // some state I do not want to have in the schema
 _other_state = None
```

I have to instantiate this as follows which is quite cumbersome and feels very unpythonic:
```
s = Some()
s._state = 'secret'
s._other_state = 'other_secret'
```
where-as it would be nice to be able to just do `s = Some(_state='secret', _other_state='other_secret')`. I know you can do `s = Some(_root={'_state': 'secret', '_other_state': 'other_secret'})` but that makes it far less explicit about what state I am sharing and especially in a big schema this can turn into a problem quickly as it is very easy to loose track of what is shared with what type.

So it would be nice if we could get the best of both worlds and just allow `s = Some(_state='secret', _other_state='other_secret')

**Comment by syrusakbary** [comment]
This is fixed in `1.0`. Closing the issue :)
