### ISSUE TITLE
Docs down?

### ISSUE THREAD

**Issue by jkimbo** [graphql-python/graphene#236]
I'm getting a blank page when I visit http://graphene-python.org/docs/quickstart/

Looks like https://github.com/graphql-python/graphene/commit/062b26e5e4bb78cbedebaceaca798b425687259f wiped out the generated html files?

**Comment by jnak** [comment]
I would happily to send you a pull request with it fixed but it seems to be handled by travis, I don't have access to the logs to see what's going on

**Comment by syrusakbary** [comment]
I'm working on fixing this and isolating the docs in a new repo. In few hours will be solved.
Thanks all for the support!

**Comment by syrusakbary** [comment]
This is now fixed.
The docs are now living in https://github.com/graphql-python/graphene-python.org

**Comment by jkimbo** [comment]
Thanks!
