### ISSUE TITLE
Django graphql query reverse set is listing all available models of that type in my database

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene#245]
Hey guys, love what you're working on! I've run into an issue that I'm seems like a bug.

I have two models address and building 
```
class Address(models.Model):
   street_number = models.TextField(default='')
   route = models.TextField(default='')

class Building(models.Model):
   address = models.ForeignKey(Address)

```

And when I query to see what buildings are pointing to my addresses, I get every building in my database returned when I'm only expecting one. (theres a reason i'm not using a 1-to-1 field)

This doesn't happen when I use the example project. And I'm following it closely so I have no idea what could be the issue.

this is what my nodes and query object look like

```
class AddressNode(DjangoNode):
    class Meta:
        model = Address
        # Allow for some more advanced filtering here
        fields = {
            'route': ['exact', 'icontains'],
            'street_number': ['exact', 'icontains'],
            'buildings': ['exact']
        }


class BuildingNode(DjangoNode):
    class Meta:
        model = Buildings
        # Allow for some more advanced filtering here
        filter_fields = {
            'address__route': ['exact', 'icontains'],
            'address__street_number': ['exact', 'icontains'],
            'address': ['exact'],
        }

class Query(ObjectType):
    building = relay.NodeField(BuildingNode)
    all_buildings = DjangoFilterConnectionField(BuildingNode)

    addresses = relay.NodeField(AddressNode)
    all_addresses = DjangoFilterConnectionField(AddressNode)


    class Meta:
        abstract = True
```

And this is what my query looks like on http://localhost:8000/graphiql

```
query{
  allAddresses(route: "Sansome St", first:1 ) {
    edges {
      node { 

        streetNumber
        route,

        buildings {
          edges {
            node {
              id
            }
          }
        },
      }
    }
  }
}
```

I should be getting back exactly one building, but I'm getting all 200 in my database. Am I missing something, or is there something wrong?

**Comment by BossGrand** [comment]
I'm using a custom uuid primary key for my models, any chance that would be the cause?

**Comment by BossGrand** [comment]
Ok so I found what was causing this to happen,
I had to add `related_name='buildings'` to my address foreign key field on Building model.

Is this a bug? It wasn't clear in the docs that this was required

**Comment by syrusakbary** [comment]
Yeah, that's a bug! Thanks for all the detailed information, I will take a look!

**Comment by syrusakbary** [comment]
This should be fixed in the `master` branch in [graphene-django](https://github.com/graphql-python/graphene-django/)! :)

(feel free to open the issue there if this problem still occur).

**Comment by nlhkh** [comment]
I think I still see this problem with the latest version. I have to explicitly specify the `related_name`.
