### ISSUE TITLE
only_fields does not exclude fields not listed in it

### ISSUE THREAD

**Issue by alecklandgraf** [graphql-python/graphene#250]
I have a django 1.10 project with the following packages installed and cannot seem to get only fields preventing the query of a user's password, which **is not in only_fields**.

Is this something goofy with the Django User model or did I miss something?

```
django-filter==0.14.0
django-graphiql==0.4.4
graphene==0.10.2
graphql-core==0.5.3
graphql-django-view==1.3
graphql-relay==0.4.4
```

The schema:

```py
"""Graphene schemas.

The schema.query is exposed under the endpoint /graphql
"""
import graphene
from graphene import ObjectType, with_context
from graphene.contrib.django.filter import DjangoFilterConnectionField
from graphene.contrib.django.types import DjangoNode

from django.contrib.auth.models import User


class UserNode(DjangoNode):
    class Meta:
        model = User
        only_fields = ('first_name', 'last_name', 'email')
        filter_fields = ['first_name', 'last_name', 'email']
        filter_order_by = ['first_name']


class Query(ObjectType):
    me = DjangoFilterConnectionField(UserNode)

    @with_context
    def resolve_me(self, args, context, info):
        """Return the user's info."""
        # context will reference to the Django request
        if not context.user.is_authenticated():
            return []
        else:
            return User.objects.filter(id=context.user.id)

schema = graphene.Schema(name='User Schema')
schema.query = Query
```
![localhost_8000_graphiql_query__7b_0a__me__7b_0a____edges__7b_0a______node__7b_0a________id_0a________email_0a________firstname_0a________lastname_0a________password_0a_______7d_0a_____7d_0a___7d_0a_7d_0a](https://cloud.githubusercontent.com/assets/2336595/17790488/87cd1354-654b-11e6-9b38-011202297a48.png)

Thanks,
Aleck

**Comment by alecklandgraf** [comment]
Closing this as it was an errant `.pyc` left around after I moved the `schema` file and didn't update my urls to reference the new location, which found the `pyc` file locally.

Sorry,
Aleck

**Comment by fortheworld2017** [comment]
Hi
I got this error in serverless code
TypeError: Error when calling the metaclass bases
    __init_subclass_with_meta__() got an unexpected keyword argument 'model'
import graphene
from models.people import People
from graphene import relay

class Character(graphene.Interface):
    name = graphene.String()
class PeopleNode(graphene.ObjectType):
      class Meta:          
          interfaces = (Character,)
          model = People


class Query(graphene.ObjectType):
    peoples = graphene.List(PeopleNode)

    def resolve_users(self, args, context, info):
        return People.scan()


schema = graphene.Schema(query=Query)
Please help me
