### ISSUE TITLE
Is there a way to make limits required

### ISSUE THREAD

**Issue by slorg1** [graphql-python/graphene#252]
Hi,

Is there a way to make limits required?

When working with the graphene graphql implementation I wanted to make `first` or `last` required (I would prefer an `OR` by I could settle for pinning 1 to required).

When investigating this I found `graphene.core.types.definitions.NonNull` which does exactly what I want and when applied to any argument works like a charm!

However. (sorry, if I am here, there is a "however") `first` and `last` are hardcoded in `graphene.relay.fields.ConnectionField` in the `kwargs` and I could not do:
`first=NonNull(Int()),`

For example. It would make sense here to use some sort of defaulted arguments merged with the `kwargs` or allow a connection centric configuration.

Thank you.

**Comment by syrusakbary** [comment]
That makes sense! I will work on it :)

**Comment by slorg1** [comment]
thx!

**Comment by gowtham-sai** [comment]
any docs regarding this ?
