### ISSUE TITLE
Not numeric IDs

### ISSUE THREAD

**Issue by felix-zg** [graphql-python/graphene#259]
Hey Guys,

Really like the library, thanks!

We are using not numeric ids(Guids) in our DB. When we use your library, we get an exception from "IntegerField().clean(_id)" inside "GlobalIDFormField.clean" method.

Can you please check it?

Thanks,
Felix.

**Comment by syrusakbary** [comment]
Fixed in `1.0.dev` :)

**Comment by felix-zg** [comment]
Thanks!
