### ISSUE TITLE
Creating Custom Arguments for Flask/SqlAlchemy

### ISSUE THREAD

**Issue by kfuchs** [graphql-python/graphene#260]
I've been trying to figure out how to create a custom argument and how to apply logic to that argument.

So far this is what I have:
`all_stores = SQLAlchemyConnectionField(Store, business_unit=graphene.String())`

I successfully get the businessUnit argument in the Docs, but I don't understand how I should apply logic to it.

I'm really just trying to accomplish what the docs explain for `django-filters`.

**Comment by AT-SyT** [comment]
I also tried to enable custom filters/mutations with existing SQLAlchemy Schemas but I haven't found a way to do so. 

Are these features not implemented in graphene or am I missing something?

**Comment by syrusakbary** [comment]
Hi @kfuchs, @AT-SyT I've created a gist with an example of how to do it in the newest version of `graphene-sqlalchemy` (`1.0.dev`):

https://gist.github.com/syrusakbary/6cdb2597daee9922f330a05a7a08413c

Hope this helps!

**Comment by AT-SyT** [comment]
Thank you for providing this example. 
Exactly what I was looking for.
