### ISSUE TITLE
Cannot query from relay 

### ISSUE THREAD

**Issue by imzautomation** [graphql-python/graphene#263]
Hello i have followed the django tutorial and made a graphql endpoint and I must say the automatic mapping of django models is magical , and I alook interacted with the endpoint from GraphiQL, however I am confused on how to implement this in relay as suggested by tutorial I dumped my schema.json and copied the same in data folder of relay starter kit and made a simple component l/container to query my endpoint but I am getting validation errors please help as I am using to for soon to be launched app

**Comment by syrusakbary** [comment]
I recommend you using `graphiql` and trying to do there the test queries!

There is also some documentation about querying relay connections and nodes that might help!
http://graphene-python.org/docs/relay/

If you post here the errors you are seeing while doing the frontend I might be able to help! :)

**Comment by syrusakbary** [comment]
Closing the issue as more input is needed but there is no response.

Feel free to comment and I will happily re-open if there is more data to dig in.
