### ISSUE TITLE
error in django example

### ISSUE THREAD

**Issue by hyusetiawan** [graphql-python/graphene#267]
following the:[ User-based Queryset Filtering](http://graphene-python.org/docs/django/authorization/) example for django 

the `return []` will cause this error: AttributeError: 'list' object has no attribute 'all'
i believe the framework expects a ResultSet, with that said, `return None` has the same effect as `Model.objects.all()` as in, no filtering.

I am also having problem with accessing a foreign key, it keeps complaining `"Cannot query field ` I have specified related name as well, is there anything extra i should do? 
this is how the foreign key is defined:
`request = models.ForeignKey(Request, on_delete=models.CASCADE)`
this is my Query:

```
   class RequestQuery(ObjectType):
    myRequests = DjangoFilterConnectionField(RequestNode)

    @with_context
    def resolve_myRequests(self, args, context, info):
        # context will reference to the Django request
        if not context.user.is_authenticated():
            return None # TODO: this returns all
        else:
            return Request.objects.filter(author=context.user)

```

**Comment by hyusetiawan** [comment]
i just figured out that i need to expose the foreign key related class in the Query before I can traverse from ParentClass --foreignkey--> ChildClass.
Is there a way to traverse the foreign key relationship without exposing it through Query?

**Comment by jkimbo** [comment]
Hi @hyusetiawan 

Regarding the error in the docs, the example should return `Post.objects.none()` since you're right the resolver does expect a queryset to be returned. I've raised a PR for the docs here: https://github.com/graphql-python/graphene-python.org/pull/4

As for your other question on how to exclude fields, you can use the `exclude_fields` meta attribute. e.g.

```
class UserNode(DjangoNode):
    class Meta:
        model = User
        exclude_fields = ('password',)
```

Hope that helps!

**Comment by hyusetiawan** [comment]
thanks, that answers it!
