### ISSUE TITLE
App name crash (django)

### ISSUE THREAD

**Issue by femesq** [graphql-python/graphene#271]
Hi,

I'm having problems when loading `graphene.contrib.django` on `INSTALLED_APPS`:
```
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: django
```

Since Django 1.7, there a differente way of declaring the app, to avoid [this](https://docs.djangoproject.com/en/1.7/ref/applications/#for-application-authors).

I've tried removing the possible conflicts, and discovered that in my case the problem was with `lettuce.django`. 

Is this really a bug?
Should I contact the other library's author?

Thanks,

**Comment by syrusakbary** [comment]
What you commented might be the cause.
In the `1.0.dev` version this is not longer an issue as the Django integration is moved into a external package `graphene-django`.

You can install it by doing `pip install graphene-django>=1.0.dev`.
If you do, would be helpful to read the [Upgrade Guide](https://github.com/graphql-python/graphene/blob/master/UPGRADE-v1.0.md).

Please reopen this issue if the problem persists.
