### ISSUE TITLE
Make graphene-django 1.0.dev available for pip install

### ISSUE THREAD

**Issue by daironmichel** [graphql-python/graphene#272]
Hey guys. I'm currently working with `graphene 1.0.dev` and `graphene-core 1.0.dev` for the performance features mentioned on #268 but I also needed `graphene-django` which I had to install manually from the folder on the `next` branch because I could not use pip to install it. It would be great to use `pip install graphene-django==1.0.dev` just like for `graphene 1.0.dev`. Please consider doing this when you get the chance. In the mean time I'll be testing the `next` branch with our system and posting any issues we might encounter. Thanks!

**Comment by syrusakbary** [comment]
Now you should be able to install it using `pip install graphene-django==1.0.dev`.

**Comment by daironmichel** [comment]
Thanks! @syrusakbary
