### ISSUE TITLE
Python 3 incompatible print statement in graphene 1.0.dev

### ISSUE THREAD

**Issue by daironmichel** [graphql-python/graphene#275]
Hey guys,

There's a `print` statement without parenthesis in `graphene/types/typemap.py`
It seems like it was put there for debugging reasons and the forgot to remove. This is the error I'm getting:

```
File ".../site-packages/graphene/types/typemap.py", line 166
    print map[type._meta.name].fields
            ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by syrusakbary** [comment]
Updated the PyPI package. Should be good to go now :)

**Comment by daironmichel** [comment]
Thanks! @syrusakbary
