### ISSUE TITLE
Django choices don't work if first character of choice is a number

### ISSUE THREAD

**Issue by benjaminjkraft** [graphql-python/graphene#277]
If you have a model like this:

```
class Foo(Model):
    bar = models.IntegerField(choices=((0, "0 - zero"), (1, "1 - one")))
```

this will attempt to create an enum with name `0_ZERO`, which is invalid -- the first character has to be `[_a-zA-Z]`, and it fails with an assertion error in `graphql.utils.assert_valid_name`.

**Comment by yen223** [comment]
This also fails for choices with non-ASCII characters, e.g. django-countries's `CountryField` will fail on `ÅLAND_ISLANDS` . I'm not sure what the solution to this will look like.

**Comment by benjaminjkraft** [comment]
I'm not sure what the best thing to do here is.  One option is to prefix with an underscore, but that has other meanings.  Another option is to truncate the initial prefix until finding something valid, but that might cause dupes, or result in a similar underscore-prefix.  Perhaps the best option is to just allow the user a way to easily override the enum data?  Not sure if that's already possible.

**Comment by yen223** [comment]
> Perhaps the best option is to just allow the user a way to easily override the enum data?

Totally agreed. Also, we should take this discussion over to https://github.com/graphql-python/graphene-django

**Comment by syrusakbary** [comment]
This is fixed in `graphene-django` :)
Closing issue!

**Comment by pity7736** [comment]
I have the same problem. I'm using graphene-django 1.1.3.
