### ISSUE TITLE
resolvers can't be classmethods

### ISSUE THREAD

**Issue by benjaminjkraft** [graphql-python/graphene#278]
Many resolver functions never use `self`, but attempting to define them as `@classmethod`s results in the wrong number of arguments getting passed, due to the way they're called.  (In particular, the error is `resolve_whatevers() takes exactly 4 arguments (5 given)`.)

**Comment by syrusakbary** [comment]
Hey @benjaminjkraft,

Even if a resolver is defined as a `classmethod`, it needs to receive a `root` (parent) element.
So the classmethod resolvers would look something like:

```python
class MyObjectType(graphene.ObjectType):
    name = graphene.String()
    @classname
    def resolve_name(cls, root, args, context, info):
        return 'My Name'
```

I know it sounds a little bit counter intuitive but all resolvers needs to receive the parent element they are working with.

Hope this helps!

**Comment by benjaminjkraft** [comment]
Ok.  It seems like in that case, the correct non-`classmethod` definition would be
```
def resolve_name(self, root, args, context, info):
    ...
```
since it seems like the `root` isn't really properly a `self` argument at all -- so maybe the docs should be updated to do that (or the classmethod)?

This is a pretty minor thing, in any case, just something that confused me for a few minutes.

**Comment by Globegitter** [comment]
@benjaminjkraft why not just define them as free form function and use them like `name = graphene.String(resolver=resolve_name)`

**Comment by benjaminjkraft** [comment]
Yeah, that would work too; it's certainly easy enough to work around this in several ways.  That is, this isn't broken per se, it's just a somewhat confusing API in  my opinion.

**Comment by syrusakbary** [comment]
I improved the documentation regarding resolvers, so it's easier to know what's going on.
http://docs.graphene-python.org/en/latest/types/objecttypes/#resolvers

Closing issue!
