### ISSUE TITLE
Retrieve fields on mapped Django models efficiently

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphene#28]
Retrieve fields in Django models efficiently depending on requested fields in the GraphQL query (so DB will be hit in an optimal way).
Thanks @bigblind for the pointing this out!

**Comment by bigblind** [comment]
I think you can get this info from the query AST, but there should be a more convenient way to get this.

**Comment by syrusakbary** [comment]
Related issue: #57

**Comment by mjtamlyn** [comment]
I've written something along these lines for my own project. It just works on a connection at the moment. It uses the info to work out which fields (if any) are being requested on the underlying node, and then checks the corresponding node type for a `optimize_foo` classmethod. If that exists, it passes the queryset through that method, before passing the queryset to the `connection_from_foo` function. They have a similar signature to a resolver. You have to be careful in resolver methods that both optimized and non-optimized cases are covered in some cases.

```python
class PostNode(DjangoNode):
    [...]

    @classmethod
    def optimize_owner(cls, queryset):
        return queryset.select_related('owner')

    @classmethod
    @with_context
    def optimize_loved(cls, queryset, context):
        # Sets user_loves attribute on post
        return queryset.prefetch_user_loves(context.user)

    @with_context
    def resolve_loved(self, args, context, info):
        try:
            return self.user_loves
        except AttributeError:
            return self.love_set.filter(user=context.user).exists()

    @classmethod
    def optimize_field_with_arguments(cls, queryset, args):
        return queryset.process_args(args)
```

**Comment by jkimbo** [comment]
@syrusakbary I think this issue can be closed? If it's still an issue then it should be raised on the [graphene-django](https://github.com/graphql-python/graphene-django) repo

**Comment by syrusakbary** [comment]
Yup, we can close the issue here and reopen in graphene-django if necessary
