### ISSUE TITLE
How to compose multiple queries together in v1.0

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene#287]
I'm getting this error message when I try to query my schema on http://localhost:8000/graphiql

    "message": "Query fields must be a mapping (dict / OrderedDict) with field names as keys 
     or a function which returns such a mapping."

I've upgraded to 1.0 using https://github.com/graphql-python/graphene/blob/master/UPGRADE-v1.0.md

this is what my schema looks like

    from graphene import relay, ObjectType
    from graphene_django.filter import DjangoFilterConnectionField

    from master_database.schemas.buildings import BuildingsNode

    class MasterDatabaseQuery(ObjectType):
       building = relay.Node.Field(BuildingsNode)
       all_buildings = DjangoFilterConnectionField(BuildingsNode)

and this is what my BuildingsNode looks like after the upgrade

    import graphene
    from graphene.relay import Node
    from graphene_django import DjangoObjectType

    from master_database.models import Buildings

   
    class BuildingsNode(DjangoObjectType):
      uuid = graphene.String(description='uuid')

      def resolve_uuid(self, args, info):
          return self.instance.id

      class Meta:
          interfaces = (Node, )
          model = Buildings

Did I do something incorrectly?

**Comment by BossGrand** [comment]
So it looks like the issue is how I was pulling this query into my main query


when I changed 
    class Query(md_schemas.MasterDatabaseQuery):
        # This class will inherit from multiple Queries
        # as we begin to add more apps to our project
        pass


     schema = graphene.Schema(query=Query)

to


     

     schema = graphene.Schema(query=md_schemas.MasterDatabaseQuery)

it worked as expected. This change wasn't documented in the upgrade guide. What is the proper way to compose queries from multiple apps together now?

**Comment by syrusakbary** [comment]
Hey @BossGrand,

Thanks for pointing this. As of right now `ObjectType`s don't work when are inherited.
If you want to extend a Type, you should be able to use `AbstractType`s for it.

Like:

```python

class MasterDatabaseQuery(graphene.AbstractType):
    my_query_field_1 = graphene.String()

class Query(MasterDatabaseQuery, graphene.ObjectType):
    pass
```

Hope this helps!
Closing the issue, but feel free to open a PR in the Upgrading guide with a extra comment for this case! (I will try to fix it anyway, but any help is always welcome!).

**Comment by BossGrand** [comment]
Sweet thanks for the help, I'll add a pr request over the weekend with an updated readme!
