### ISSUE TITLE
Would you consider a pull-request adding support for Peewee ORM?

### ISSUE THREAD

**Issue by coleifer** [graphql-python/graphene#289]
Hi, my name is Charles Leifer. I'm the author of [Peewee](http://docs.peewee-orm.com/), a lightweight Python ORM. It's been steadily growing in popularity in the last couple years and has over 3000 stars and 500+ forks. `graphene` is an impressive library and I am grateful to you for taking the time to write it and open-source it. I think it'd be great for the users of Peewee to be able to use your library, and if you did not want to write the bindings I would be happy to contribute some in a pull-request.

What do you think?

**Comment by syrusakbary** [comment]
Hi Charles,

I'm absolutely open for having an integration between Peewee and Graphene, I think it will be super valuable for the developers!

Starting with the next version `1.0`, Graphene integrations will be separated from the main codebase into external repos within the [graphql-python](https://github.com/graphql-python) community. (This is already happening for the [Graphene Google App Engine integration](https://github.com/graphql-python/graphene-gae))

Each of the repos would be maintained by different people that are specialized in the framework that are integrating with (I can't think of someone better than you for the graphene-peewee integration! 😉 )

We can follow the same process we did for `graphene-gae`: You can start a `graphene-peewee` repo in your profile and once is mature (tested and with a working example) we can move it into the `graphql-python` community :)

Or we can start directly creating a `graphene-peewee` repo in `graphql-python` and you will be the admin of this repo.

Just let me know which you prefer! :)

**Comment by coleifer** [comment]
I'll take it on as a personal repo, and we can take it from there. Thanks for your encouragement and your interest!

**Comment by syrusakbary** [comment]
Great! :)
PS: I just added you to the maintainer role for the `graphene-peewee` package in PyPI

**Comment by ParthGandhi** [comment]
@coleifer Awesome, look forward to it. I'd love to help if you need any.

**Comment by joshdavey** [comment]
Hey guys, thanks so much for these two amazing libraries. Can't wait for them to work together officially. Is there anywhere I can follow the progress of graphene-peewee?

Thanks

**Comment by danigosa** [comment]
@coleifer we need to decide in our organization if we go for SQLAlchemy or Peewee (coming from Django ORM in older projects), could you open the work in progress so we can check how is it doing and possibly contribute to make it possible? Most devs in my team we prefer Peewee (congrats and thanx!) but GraphQL is one elevated requirement for the stack we are building.

**Comment by coleifer** [comment]
Hey @danigosa -- between work and moving our house I don't believe I'll be able to work on this for at least a couple weeks. I hope you understand.

**Comment by danigosa** [comment]
Don't even worry, we are facing other architecture layers? Anyway we are using peewee-async finally so no matter what in the times to come if you start this we'll contribute, for now we are not going to far in the frontend side to use graphql at its best so... Good luck with the move :)

**Comment by axsauze** [comment]
Thank you very much for this contribution @coleifer! @Danigosa I would definitely recommend Peewee, especially if you come from the Django ORM world

**Comment by jontonsoup** [comment]
Is there a place where I can follow this? @coleifer

**Comment by Hendler** [comment]
Excited! Can we help out? Is there a place we can follow @coleifer ?

**Comment by jamrizzi** [comment]
What's the status of this? Are there any existing ways to use peewee with graphql?

**Comment by alexpantyukhin** [comment]
It's interesting for me. I can try to implement if it's not done yet and nobody already works with it..

**Comment by insolite** [comment]
If someone is interested I've done some implementation for [peewee-async](https://github.com/05bit/peewee-async) package [here](https://github.com/insolite/graphene-peewee-async). It should not be much different from [graphene-django](https://github.com/graphql-python/graphene-django) integration which I mostly relied on at the design stage. Initially I was doing that for my own needs, but now I am trying to provide generic maintaining. So if someone will make use of it or want to contribute, I would be glad to help.

**Comment by Tarun-S** [comment]
I ported @insolite’s [graphene-peewee-async](https://github.com/insolite/graphene-peewee-async) to the regular Peewee. See it here:

[graphene-peewee](https://github.com/emperorplatform/graphene-peewee)

This is my first major OSS contribution, so please leave feedback if anything can be improved. Also, this is an early release with limited testing. It has not been used in production by me. There may well be bugs.
