### ISSUE TITLE
Allow mutation input type name to be specified

### ISSUE THREAD

**Issue by rapilabs** [graphql-python/graphene#29]
Currently mutation input type names are [hardcoded to `<Mutation>InnerInput`](https://github.com/graphql-python/graphene/blob/d46e9578631ce2b324086e2238566e2920b66f40/graphene/relay/types.py#L109)

I prefer `<Mutation>Input` like the types generated in graphql-relay :)

**Comment by syrusakbary** [comment]
This is changed in upcoming version `0.4.0` to `<Mutation>Input` -> https://github.com/graphql-python/graphene/blob/0.4.0/graphene/relay/types.py#L117

Let me know if you have more suggestions!

**Comment by rapilabs** [comment]
Awesome, I should check these new branches before I suggest something ;)

**Comment by syrusakbary** [comment]
Version `0.4.0` is now on master. Closing issue.
