### ISSUE TITLE
Fragments: <Type> can never be of type <Type>

### ISSUE THREAD

**Issue by mjtamlyn** [graphql-python/graphene#293]
I'm getting some strange behaviour with fragments on the most recent 1.0 dev release. Graphene seems to be duplicating the definition of a particular type, and therefore disallowing certain fragments.

[Here's a query which fails](https://graphene-tutorial.herokuapp.com/plain/graphiql/?query=fragment%20F0%20on%20Person%20%7B%0A%20%20name%0A%20%20residence%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A%0A%7B%0A%20%20people%20%7B%0A%20%20%20%20name%0A%20%20%20%20family%0A%20%20%20%20children%3A%20relationships(relationship%3A%20child)%20%7B%0A%20%20%20%20%20%20...F0%0A%20%20%20%20%7D%0A%20%20%20%20parents%3A%20relationships(relationship%3A%20parent)%20%7B%0A%20%20%20%20%20%20...F0%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

[Code all available](https://github.com/mjtamlyn/graphene-tutorial/blob/master/plain/api.py)

**Comment by syrusakbary** [comment]
Looking at it now! :)

**Comment by syrusakbary** [comment]
Just merged the code propose change in: https://github.com/graphql-python/graphene/pull/266

This should solve the issue! (I tried the `graphene-tutorial` and the fragment error no longer exists :) )

Pushing the graphene dev version to PyPI

**Comment by mjtamlyn** [comment]
Amazing thanks! That'll make my workshop tomorrow go rather better ;)
