### ISSUE TITLE
How do you introspect the schema?

### ISSUE THREAD

**Issue by ashinohara** [graphql-python/graphene#3]
I see that the graphiql interface is able to introspect the schema, but I am not sure how you would export the schema form python.  I see the introspect function on the Schema object, but that simply returns the objects from the type_map.

**Comment by syrusakbary** [comment]
@ashinohara I've fixed the introspection method in the schema.
Just update your graphene package to `0.1.3` version and run in your `graphene.Schema`:

```python
import json

schema = graphene.Schema(....)

introspection_dict = schema.introspect()
# Print the schema in the console
print json.dump(introspection_dict)

# Save the schema into some file
open(‘schema.json’, ‘w’) as fp:
    json.dump(introspection_dict, fp)
```

**Comment by syrusakbary** [comment]
Thanks @jhgg for showing me the way :wink:

**Comment by jhgg** [comment]
No problem!

**Comment by llevar** [comment]
This should be automatically exposed by Graphene as a query that returns the file.

**Comment by isakal** [comment]
If you want to get schema in GraphQL SDL format:
```python
>>> from your_project.schema_definition import schema
>>>  print(schema)
schema {
  query: Query
  mutation: Mutation
}

type CreateUser {
  user: User
  message: String
  success: Boolean
}
# and so on ...
```

**Comment by Curiouspaul1** [comment]
> If you want to get schema in GraphQL SDL format:
> 
> ```python
> >>> from your_project.schema_definition import schema
> >>>  print(schema)
> schema {
>   query: Query
>   mutation: Mutation
> }
> 
> type CreateUser {
>   user: User
>   message: String
>   success: Boolean
> }
> # and so on ...
> ```
How does one save this to a file like schema.graphql or .gql

**Comment by 5chulzi** [comment]
> > If you want to get schema in GraphQL SDL format:
> > ```python
> > >>> from your_project.schema_definition import schema
> > >>>  print(schema)
> > schema {
> >   query: Query
> >   mutation: Mutation
> > }
> > 
> > type CreateUser {
> >   user: User
> >   message: String
> >   success: Boolean
> > }
> > # and so on ...
> > ```
> 
> How does one save this to a file like schema.graphql or .gql

Here you go:

```python
with open('schema.graphql', 'w') as f:
    f.write(str(schema))
```

This works, because the schema class uses the `def __str__(self)` method to return the string representation of the underlying graphql schema.

**Comment by krish7919** [comment]
(Sorry to comment on a closed issue but this seems to be the right place)

Is there a way for graphene to query Postgres directly and generate an SDL file ?

**Comment by gitexel** [comment]
@syrusakbary Hi, each time I generate GQL schema, some fields' order changes. 
<img width="839" alt="Screen Shot 2022-10-22 at 8 11 49 PM" src="https://user-images.githubusercontent.com/14273726/197356258-c54d223c-310c-47e8-8c7d-a4e9ffd828a1.png">
Any I idea how I generate it, to be in the same order?
My goal is to trace schema changes in git.

**Comment by conao3** [comment]
just a note, `schema.introspect()` is now missing and `str(schema)` is just default str serializer.

If you want to get result of introspect query,
```python
import graphql

graphql.introspection_from_schema(schema)  # -> TypedDict
```

And you want to get SDL of schema,
```python
import graphql

graphql.print_schema(schema)  # -> str
```

**Comment by conao3** [comment]
Sorry, this is graphene repo, not graphql-core. ignore me.
