### ISSUE TITLE
Cannot query field clientMutationId on Payload

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene#300]
I have a clientIdMutation

    class EditBuildingMutation(graphene.ClientIDMutation):
        class Input:
            id = graphene.String(required=True)
            neighborhood = graphene.String()

        building = graphene.Field(BuildingNode)
        clientMutationId = graphene.String()

        @classmethod
        def mutate_and_get_payload(cls, args, context, info):
            #edit building logic

            clientMutationId = args.get('clientMutationId')
            return EditBuildingMutation(building=building, clientMutationId=clientMutationId)
 

I'm forced to manually add clientMutationId to my payload. Shouldn't graphene.ClientIDMutation be handling this automatically?

If I don't put it there I get this error whenever I call the mutation.
`message: "Cannot query field "clientMutationId" on type "EditBuildingMutationPayload".`

**Comment by syrusakbary** [comment]
Thanks for the report, I just fixed it on master :)
