### ISSUE TITLE
django-filter-0.15.0 breaks Graphene-0.10.2

### ISSUE THREAD

**Issue by Luftzig** [graphql-python/graphene#302]
A [commit](https://github.com/carltongibson/django-filter/commit/6413331d16876b4629470862c79fc6482bc1d40d) from June 16 in django-filter moved `filterset.filter_overrides` to `filterset._meta.filter_overrides`. This breaks the following code (filter/filterset.py:48):

    class GrapheneFilterSetMetaclass(FilterSetMetaclass):

      def __new__(cls, name, bases, attrs):
          new_class = super(GrapheneFilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
          # Customise the filter_overrides for Graphene
          for k, v in GRAPHENE_FILTER_SET_OVERRIDES.items():
              new_class.filter_overrides.setdefault(k, v)
          return new_class`

**Comment by Luftzig** [comment]
This issue belongs in graphene-django

**Comment by syrusakbary** [comment]
Yeah! This is actually fixed in the latest development version of `graphene-django` 😉
