### ISSUE TITLE
Where does resolver context and info come from? Can I give context when creating the Schema?

### ISSUE THREAD

**Issue by jpeg729** [graphql-python/graphene#306]
The docs are silent on these points.
## Motivation

I want to implement access controls, and [others](http://rmosolgo.github.io/blog/2015/08/04/authorization-in-graphql/) suggest doing this by passing a user object into the context and using resolvers that return None when the user in the context isn't allowed to access that particular resource.

Hence my questions.

**Comment by mjtamlyn** [comment]
You can pass context to `schema.execute` as `context_value=<obj>`. Info describes the structure of the query from this point downwards, you can inspect it but you can't control it.

(ref: https://github.com/graphql-python/graphql-core/blob/49fa28f2a75a8bca6a90ad7852772a58ae8599fc/graphql/graphql.py#L30-L32)
