### ISSUE TITLE
v1.0: Lazily load model class in Field and relay.ConnectionField as in v0.x

### ISSUE THREAD

**Issue by JimVanEeden** [graphql-python/graphene#316]
Currently rewriting our GraphQL API to work with graphene 1.0 but I'm coming across a big problem:

In order to create the models, I've written a construction class that will convert the actual database models to models used by graphene. There arises a problem however when creating relations on the models using the Field and relay.ConnectionField classes. In graphene 0.x I would be able to provide the name string as argument to Field and relay.ConnectionField, but apparently this is not possible anymore in 1.0 (I'm wondering why you took this out as well). 

It's impossible to import the model classes in the construction class due to circular dependencies. I'm hoping there is another solution to this problem, other than completely rewriting everything to something that is not logically structured at all anymore. Is this something that is going to change in the future or is there a fix available?

**Comment by jameswyse** [comment]
I've ran into a similar problem, I need to include the parent when using RANGE_ADD mutations but `graphene.Field('Viewer')` no longer works

**Comment by syrusakbary** [comment]
Hi @JimVanEeden @jameswyse, in `v1.0` you can use lambdas in a Field.

A simple example:

```python
class Viewer(graphene.ObjectType):
    viewer = graphene.Field(lambda: Viewer)
```

**Comment by JimVanEeden** [comment]
Yes I got that from the documentation, the problem is that I can't import the classes. The only solution is to put all the models and the construction class in one file, which is highly undesirable.

**Comment by jameswyse** [comment]
Same problem here. I'm gonna try using `__import__` or `importlib.import_module` inside the lambda. Not ideal either but it should do the trick.

**Comment by jameswyse** [comment]
@JimVanEeden It works :)

Here's some example code:

```python
import graphene
from importlib import import_module
from graphql_relay.connection.arrayconnection import offset_to_cursor
from something_app.models import Something
from something_app.schema import SomethingNode


class CreateSomething(graphene.relay.ClientIDMutation):
    class Input:
        name = graphene.String()
        
    viewer = graphene.Field(lambda: import_module('your_app.schema').Viewer)
    something_edge = graphene.Field(SomethingNode.Connection.Edge)
    success = graphene.Boolean()

    @classmethod
    def mutate_and_get_payload(cls, input, context, info):
        name = input.get('name')

        something = Something(name=name)
        something.save()

        # hacky but works for now
        cursor = offset_to_cursor(Something.objects.count() - 1)
        edge = SomethingNode.Connection.Edge(node=something, cursor=cursor)

        return cls(viewer=import_module('your_app.schema').Viewer, edge=edge, success=bool(something.id))
```

and the client-side mutation config:
```javascript
import Relay from 'react-relay';

export default class CreateSomethingMutation extends Relay.Mutation {

  getMutation () {
    return Relay.QL`
      mutation { createSomething }
    `;
  }

  getVariables () {
    return { name: this.props.name };
  }

  getFatQuery () {
    return Relay.QL`
      fragment on CreateSomethingPayload @relay(pattern: true) {
        clientMutationId
        success
        edge {
          node {
            id
          }
        }
        viewer {
          id
          allSomethings
        }
      }
    `
  }

  getConfigs () {
    return [{
      type: 'RANGE_ADD',
      parentName: 'viewer',
      parentID: this.props.viewer.id,
      connectionName: 'allSomethings',
      edgeName: 'edge',
      rangeBehaviors: {
        '': 'append'
      }
    }];
  }
}
```

**Comment by JimVanEeden** [comment]
I got it to work as well :)

Short example of how I implemented it for anyone with the same problem:

    @staticmethod
    def _convert_relationships(db_model_class):
        converted_relationships = {}

        for prop_name, relationship in iteritems(db_model_class.__dict__):
            if not isinstance(relationship, Relationship):
                continue

            direction = relationship.direction
            model_name = relationship.target

            def get_graphql_model_class():
                module = import_module('example.models.' + model_module_name)
                return getattr(module, model_name, None)

            if direction == Direction.MANYTOONE or direction == Direction.ONETOONE:
                converted_relationships[prop_name] = Field(get_graphql_model_class)
            elif direction == Direction.ONETOMANY or direction == Direction.MANYTOMANY:
                converted_relationships[prop_name] = relay.ConnectionField(get_graphql_model_class)

        return converted_relationships

This uses a custom class Relationship that is added to the models, but should be clear enough to understand what is going on.

**Comment by JimVanEeden** [comment]
I solved it only partially. Below is the solution I could come up with. My case differs from the above in that the model class name is a variable, where in the above example it's a constant (Viewer).

````python
from importlib import import_module
from functools import partial


def convert_relationships(db_model_class):
    converted_relationships = {}

    for prop_name, relationship in iteritems(db_model_class.__dict__):
        if not isinstance(relationship, Relationship):
            continue

        direction = relationship.direction
        model_name = relationship.target

        if direction == Direction.MANYTOONE or direction == Direction.ONETOONE:
            converted_relationships[prop_name] = Field(partial(
                get_graphql_model_class, model_name=model_name))
        elif direction == Direction.ONETOMANY or direction == Direction.MANYTOMANY:
            converted_relationships[prop_name] = relay.ConnectionField(
                partial(get_graphql_model_class, model_name=model_name))

    return converted_relationships


def get_graphql_model_class(model_name):
    module = import_module('examplemodule.models.' + model_name)
    return getattr(module, model_name, None)
````

_note: My database model classes have custom Relationship properties that are used to create the field properties, but the code should be understandable without knowing the Relationship class_

**However**

functools.partial is used to pass model_name to the function so the function knows which model to return (I don't know of any other way to do this). **But**, this doesn't work out of the box with the Field class from graphene:
````python
@property
def type(self):
    if inspect.isfunction(self._type):
        return self._type()
    return self._type
````
inspect.isfunction does not recognize a partial function as a function, so I had to adapt that code a bit to have it recognize a partial as well. 

Now it works perfectly fine, but my request is to preferable change the functionality from 0.x back where you can just pass the name string, and otherwise have it recognize functools.partial. But the latter still feels a bit hacky to me.

**Comment by jameswyse** [comment]
@JimVanEeden `callable(self._type)` might be a good alternative to `inspect.isfunction` :)

**Comment by syrusakbary** [comment]
@jameswyse graphene is not using callable there because `self._type` could be a class reference. (in this case, callable will be True and field.type would return a type instance instead of the class type).

**Comment by jameswyse** [comment]
ah good point.

**Comment by JimVanEeden** [comment]
As a quick fix i changed it to `inspect.isfunction(self._type) or type(self._type) is partial`, but this is not ideal.
