### ISSUE TITLE
Documentation for implementing custom database backends

### ISSUE THREAD

**Issue by zbyte64** [graphql-python/graphene#321]
I am looking at implementing a custom backend for graphene but there is no documentation on the matter.

Some topics that would be useful when developing a custom backend:
- general strategy and project layout
- querying interface
- mutation interface
- get_node interface

**Comment by zbyte64** [comment]
Found the unit tests from graphql-core to be very enlightening: https://github.com/graphql-python/graphql-core/blob/master/tests/starwars/starwars_schema.py

**Comment by yfilali** [comment]
I have spent the last couple of days implementing the PynamoDB integration. What I ended up doing is grabbing the SQLAlchemy repo and creation the PynamoObjectType, PynamoConnectionField, and PynamoObjectTypeMeta.

Getting the tests and examples to run with PynamoDB was a good way of getting the basic support up and running.

**Comment by jkimbo** [comment]
Hi @zbyte64 . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
