### ISSUE TITLE
In progress integration with PynamoDB ORM for DynamoDB

### ISSUE THREAD

**Issue by yfilali** [graphql-python/graphene#322]
I just started this using the SQLAlchemy integration as a template. The tests are passing and there is a basic example. I have some work to do to get Travis working as DynamoDB is not supported out of the box so I'll have to run against AWS.

One big decision point I am struggling with is what to do about relationships. This is something left to the user in DynamoDB as it's a NoSQL database. I might add an example for this instead of adding it to the integration...not sure yet.

Repo here: https://github.com/yfilali/graphql-pynamodb

Any feedback would be much appreciated!

**Comment by syrusakbary** [comment]
Great work there! I will take a closer look the next days and try to give you some feedback! :)

**Comment by yfilali** [comment]
This is now pretty stable, I've been using it for a little while and I am pretty content with it's current status. Let me know if you see anything amiss or what you'd like to do with it next.
