### ISSUE TITLE
Filtering ID-based node access, get_node classmethod override not working

### ISSUE THREAD

**Issue by maistrotoad** [graphql-python/graphene#328]
If you have a Node like this:

```
class FooNode(DjangoObjectType):
    class Meta:
        model = Foo
        only_fields = ('bar',)
        interfaces = (relay.Node,)

    @classmethod
    def get_node(cls, id, context, info):
        try:
            foo = cls._meta.model.objects.get(id=id)
        except cls._meta.model.DoesNotExist:
            return None

        if foo.is_authenticated():
            return foo
        return None
```
FooNode is used in a DjangoFilterConnectionField like:
```
  class Query(ObjectType):
    foo = DjangoFilterConnectionField(FooNode)
```
The get_node override does not seem to be working, i.e., the code is never reached. To be clear FooNode works fine otherwise, I can access the field 'bar', but I cannot limit access to it.

**Comment by syrusakbary** [comment]
I think this was because `foo` is an instance of `SimpleLazyObject` and not a model.
This issue was reported in https://github.com/graphql-python/graphene-django/issues/22 and is now fixed!

PS: Graphene-django issues are better reported in https://github.com/graphql-python/graphene-django/ :)
