### ISSUE TITLE
Additional attributes on custom edge_type

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#33]
For a `ConnectionField` we can pass in a a custom edge as so: `addresses=relay.ConnectionField(Address, connection_type=AddressType, edge_type=AddressTypeEdge)`. But when the custom edge has some additional fields it seems there is no way for these to be set, as this line: https://github.com/graphql-python/graphql-relay-py/blob/master/graphql_relay/connection/arrayconnection.py#L46 only ever tries to set `node` and `cursor`. It would be great to have support to resolve some custom fields on a custom edge.

I might look into a fix myself tomorrow since I need that for one of our implementations.

**Comment by syrusakbary** [comment]
Good catch!

**Comment by Globegitter** [comment]
A more complete example btw (just picked out the relevant pieces):

```py
class Address(relay.Node):
    address_id = graphene.ID()
    postal_line = graphene.String()

    @classmethod
    def get_node(cls, address_id):
        return Address(address_id=address_id, postal_line='3 March Avenue')

class AddressTypeEdge(relay.Edge):
        address_type = graphene.String()

class AddressType(relay.Connection):
    edges = graphene.List(graphene.LazyType(AddressTypeEdge))

class User(relay.Node):
    user_id = graphene.ID()
    addresses = relay.ConnectionField(Address, connection_type=AddressType,
    edge_type=AddressTypeEdge)

    @classmethod
    def get_node(cls, user_id):
        user = {'user_id': '1'}
        return User(**user)
    
    def resolve_addresses(self, args, info):
            return [AddressTypeEdge(address_type='1', node=Address(address_id='1', postal_line='UK'))]


node_type = 'User'
user_id = '1'
relay_global_id = base64(':'.join([node_type, str(user_id)]))
query = '''
            query testQuery {
                user(id: "%s") {
                    userId,
                    addresses {
                        edges {
                            addressType
                            node {
                                postalLine
                            }
                        }
                    }
                }
            }
        ''' % relay_global_id

result = schema.execute(query)
```

On `0.4.0.1` that results into `[GraphQLError("'node' is an invalid keyword argument for this function",)]`

**Comment by syrusakbary** [comment]
@Globegitter Will take a look on your example shortly!

**Comment by syrusakbary** [comment]
In your example, you don't really need to create AddressType, just only with `relay.ConnectionField(Address, edge_type=AddressTypeEdge)` will work.

Your example is failing because you are using LazyField in a resolved component (LazyField only wants either a string or a function for resolve once the schema is known).
So you can solve it doing:
```python
    edges = graphene.List(AddressTypeEdge)
```
Or
```python
    edges = AddressTypeEdge.List
```

**Comment by syrusakbary** [comment]
I will keep this issue until LazyType notifies if a wrong input is received (not str or function)

**Comment by Globegitter** [comment]
Also when I have 
```
class AddressType(relay.Connection):
    edges = graphene.List(AddressTypeEdge)
```

I get the same error/behaviour. The thing that I want, is to have extra fields on the `AddressTypeEdge`, it might be `address_type` but could be a bunch of other as well.


So the expected output that I would like to get is something like:

`{"customer": {"customerId": "1", "fullName": "Paul Kalk", "addresses": {"edges": [{"addressType": 'has some value', "node": {"street": "UK"}}]}}}`


Where-as right now I only manage to get:

`{"customer": {"customerId": "1", "fullName": "Paul Kalk", "addresses": {"edges": [{"addressType": null, "node": {"street": "UK"}}]}}}` , or some error as mentioned above.

**Comment by syrusakbary** [comment]
Hi @Globegitter!
Thanks to this commit you can return a Connection instance in the ConnectionField resolver.
https://github.com/graphql-python/graphene/commit/fe860774e8525cb50095f857c6013cffbc41f117

Reopen this issue if you find any errors.

**Comment by Globegitter** [comment]
Will give it a try, thank you!

**Comment by Globegitter** [comment]
@syrusakbary Just tested it and now getting `[GraphQLError("'node' is an invalid keyword argument for this function",)]`. Could this be related to the change a few days ago: https://github.com/graphql-python/graphene/commit/266dd5efe089e92d235802166471b1fbbf7f58d6#diff-5483f154953c0d23d7680373eec49d90L30

**Comment by Globegitter** [comment]
Also from what I can tell you would have to manually implement `pageInfo` and `cursor` the current way, right?

**Comment by syrusakbary** [comment]
@Globegitter could you post your schema definition? I could either see if is a problem in `graphene` or guide you for fixing it :)

**Comment by syrusakbary** [comment]
(the code is the same you posted before?)

**Comment by Globegitter** [comment]
Yes, the code is pretty much the same as above:

```py
class Address(relay.Node): address_id = graphene.ID() postal_line = graphene.String() @classmethod def get_node(cls, address_id): return Address(address_id=address_id, postal_line='3 March Avenue') class AddressTypeEdge(relay.Edge): address_type = graphene.String() class AddressType(relay.Connection): edges = graphene.List(graphene.LazyType(AddressTypeEdge)) class User(relay.Node): user_id = graphene.ID() addresses = relay.ConnectionField(Address, connection_type=AddressType, edge_type=AddressTypeEdge) @classmethod def get_node(cls, user_id): user = {'user_id': '1'} return User(**user) def resolve_addresses(self, args, info): return AddressType(edges=[AddressTypeEdge(address_type='1', node=Address(postal_line='blaa'))]) node_type = 'User' user_id = '1' relay_global_id = base64(':'.join([node_type, str(user_id)])) query = '''             query testQuery {                 user(id: "%s") {                     userId,                     addresses {                         edges {                             addressType                             node {                                 postalLine                             }                         }                     }                 }             }         ''' % relay_global_id result = schema.execute(query)
```

**Comment by Globegitter** [comment]
@syrusakbary Have you had the chance to look into this some more again?

**Comment by Globegitter** [comment]
@syrusakbary here is the example on the new playground: http://graphene-python.org/playground/?schema=import%2520collections%250A%250Aimport%2520graphene%250Afrom%2520graphene%2520import%2520relay%250A%250Aclass%2520Address(relay.Node)%253A%250A%2520%2520%2520%2520address_id%2520%253D%2520graphene.ID()%250A%2520%2520%2520%2520postal_line%2520%253D%2520graphene.String()%250A%250A%2520%2520%2520%2520%2540classmethod%250A%2520%2520%2520%2520def%2520get_node(cls%252C%2520address_id)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520Address(address_id%253Daddress_id%252C%2520postal_line%253D%273%2520March%2520Avenue%27)%250A%250Aclass%2520AddressTypeEdge(relay.Edge)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520address_type%2520%253D%2520graphene.String()%250A%250Aclass%2520AddressType(relay.Connection)%253A%250A%2520%2520%2520%2520edges%2520%253D%2520graphene.List(graphene.LazyType(AddressTypeEdge))%250A%250Aclass%2520User(relay.Node)%253A%250A%2520%2520%2520%2520user_id%2520%253D%2520graphene.ID()%250A%2520%2520%2520%2520addresses%2520%253D%2520relay.ConnectionField(Address%252C%2520connection_type%253DAddressType%252C%250A%2520%2520%2520%2520edge_type%253DAddressTypeEdge)%250A%250A%2520%2520%2520%2520%2540classmethod%250A%2520%2520%2520%2520def%2520get_node(cls%252C%2520user_id)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520user%2520%253D%2520%257B%27user_id%27%253A%2520%271%27%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520User(**user)%250A%250A%2520%2520%2520%2520def%2520resolve_addresses(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520AddressType(edges%253D%255BAddressTypeEdge(address_type%253D%27some%2520text%27%252C%2520node%253DAddress(postal_line%253D%27blaa%27))%255D)%250A%250Aclass%2520Query(graphene.ObjectType)%253A%250A%2520%2520%2520%2520user%2520%253D%2520graphene.Field(User)%250A%2520%2520%2520%2520%250A%2520%2520%2520%2520def%2520resolve_user(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520user%2520%253D%2520%257B%27user_id%27%253A%2520%271%27%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520User(**user)%250A%250Aschema%2520%253D%2520graphene.Schema(query%253DQuery)%250A&query=query%2520testQuery%2520%257B%250A%2520%2520user%2520%257B%250A%2520%2520%2520%2520userId%252C%250A%2520%2520%2520%2520addresses%2520%257B%250A%2520%2520%2520%2520%2520%2520edges%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520addressType%250A%2520%2520%2520%2520%2520%2520%2520%2520node%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520postalLine%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%2520%2520%257D%250A%257D

**Comment by ekampf** [comment]
+1 here.
Trying to define a list on an edge type: `slices = graphene.List(ESSearchResultEdge)` and getting a `GraphQLError('Cannot query field "node" on type "ESSearchResultEdge".',)`.

```
class ESSearchResultEdge(relay.Edge):
    search_result_info = graphene.Field(SearchResultInfoType, required=True)

...
slices = graphene.List(ESSearchResultEdge)

```

The schema generated:
```
type ESSearchResultEdge {
  cursor: String!
  searchResultInfo: SearchResultInfoType!
}

```
