### ISSUE TITLE
Query with variables

### ISSUE THREAD

**Issue by richburdon** [graphql-python/graphene#331]
I can query the schema with simple queries, but I can't figure out how to pass variables using the API.

E.g., if I have the following payload from my Relay client:

REQ = {
  "query": "query User($userId_0:ID!) {\n  user(userId:$userId_0) {\n    id,\n    ...F0\n  }\n}\nfragment F0 on User {\n  id,\n  title\n}", 
  "variables": {
    "userId_0": "VXNlcjpVLTE="
  }
}

My query works fine with GraphiQL. And schema.execute(query) works if I manually input the query params (i.e., userId) into the query string. I was expecting execute to have a "variables" param?

**Comment by syrusakbary** [comment]
The argument name is `variable_values`.

So you can do:

```python
schema.execute(query, variable_values={"userId_0": "123"})
```

PS: The name is `variable_values` instead of `variables` for being more similar to the GraphQL JS API.

**Comment by thisiswei** [comment]
@syrusakbary 

how can I pass parameters like following: 


```js
{
 emailAddresses(id: 10) {
   id
 }
}
```





```python
class EmailAddress(SQLAlchemyObjectType):
    class Meta:
        model = EmailAddressModel


class Query(graphene.ObjectType):
    email_addresses = graphene.List(EmailAddress)

    def resolve_email_addresses(self, args, context, info):
        query = EmailAddress.get_query(context)
        return query.all()


schema = graphene.Schema(query=Query)
```
how do I pass id=10 to EmailAddress and only fetch EmailAddress with id 10?

**Comment by thomasloh** [comment]
@thisiswei check args, args['id'] == 10
