### ISSUE TITLE
Website docs not displaying

### ISSUE THREAD

**Issue by osman-masood** [graphql-python/graphene#334]
Flashes briefly then disappears.

<img width="1432" alt="screen shot 2016-10-21 at 12 47 35 pm" src="https://cloud.githubusercontent.com/assets/453352/19609539/a3698714-978c-11e6-9adb-c79c64ba16dd.png">

Thanks!

**Comment by ecamaj** [comment]
Same for me, but not for all pages. I found this link in some other issue - http://graphene-python.org/docs/middleware, and nothing is shown when I click on it. 
Tried in Chrome and Safari.

Also, where are middleware pages in docs? There is no mention of Middlewares in http://docs.graphene-python.org/en/latest/.

Am I missing something here?

**Comment by reverie** [comment]
Lots of pages like this are indexed by Google. I think they are deprecated/old URLs somehow. You have to click Documentation at the top and then navigate to the one you want.

**Comment by ecamaj** [comment]
Sure. That would make sense if you can show me link to middleware explanation.

**Comment by bcb** [comment]
Any chance of redirecting the old URLs?

**Comment by syrusakbary** [comment]
Just fixed this by adding a redirection meta in the old doc pages.
Here is the commit: https://github.com/graphql-python/graphene-python.org/commit/df0c0e572996768aefae612dfb7deccbb9d0748d
(Google should also update this page urls soon in their engine once they crawl the new contents)

Now when someone access: http://graphene-python.org/docs/relay/ it will be redirected to: http://docs.graphene-python.org/en/latest/relay/

@ecamaj Just checked that middleware is not ported to the new docs, I will work on it! :)

**Comment by bcb** [comment]
That worked for most docs @syrusakbary although I noticed the [django tutorial](http://graphene-python.org/docs/django/tutorial/) now leads to 404.
