### ISSUE TITLE
Support for Github GraphQL

### ISSUE THREAD

**Issue by WGierke** [graphql-python/graphene#339]
Hey everyone,
that's a really nice project!
Is it possible to query the Github GraphQL API as well?
Github already wrote an example for that in [Rails](https://github.com/github/github-graphql-rails-example).
Their schema is defined as JSON and they're requiring a personal access token.
Thanks!

**Comment by yfilali** [comment]
@WGierke graphene is a server side implementation of graphql, not a client. You probably should post this under https://github.com/graphql-python/gql/issues

Although, afaik, the example there should be more than enough to get you there anyway:
https://github.com/graphql-python/gql/blob/master/tests/test_transport.py

Move this issue there if you can't get it working.
