### ISSUE TITLE
Need to have resolution "helpers" (including in get_node)

### ISSUE THREAD

**Issue by inklesspen** [graphql-python/graphene#34]
In my preferred SQLAlchemy setup, simply having the model class is not sufficient to load a model. In addition, you must have a separate `session` object, which has a query method.

For example, the Django approach of :
```python
ship = Ship.objects.get(id=1)
```

would instead work like this:
```python
ship = session.query(Ship).filter_by(id=1).one()
```

I also require the ability to pass a notion of the current user into the query so that my resolvers can verify the user is authorized to access this data.

This means the 'session' and 'auth' objects must be provided to the `schema.execute` method and get passed into any resolvers. I had planned to do this using the ExecutionContext. However, the `get_node` classmethods don't get provided the ExecutionContext.

What do you suggest?

**Comment by jhgg** [comment]
Regarding `graphene`, I think that the execution context should be added to `get_node`. As a good practice, the execution context should be available in all resolvers for this very reason.

Regarding `graphql-core`, in addition to `root_value`, I provide a `request_context` inside of `ExecutionContext` which can be set to any value you want to use. In `graphql-django-view`, I use it to store the current `request` object from Django. But given your use-case, perhaps it would make more sense to pass it a `dict` containing your `session` and `auth` objects.

You should be able to do this using `graphene.core.Schema.execute()` by passing `request_context` as a kwarg to that function.

**Comment by jhgg** [comment]
This is going to be a breaking change... but I think should be made. 0.5.0 here we come lol.

**Comment by syrusakbary** [comment]
@inklesspen Yep, is a breaking change but will be accepted.
However a node could only be retrieved by the id arg (there are no other args in the base javascript implementation/ relay specification)
So, the syntax could be something like this:

```python
    @classmethod
    def get_node(cls, id, info):
        pass
```

**Comment by inklesspen** [comment]
ok, so it wouldn't support `resolve_only_args` then.

I will try to prepare a PR in the next day or so.

**Comment by inklesspen** [comment]
Just a reminder the PR is ready.

**Comment by syrusakbary** [comment]
Merged!
