### ISSUE TITLE
ConnectionBase.edges should be NonNull

### ISSUE THREAD

**Issue by barakcoh** [graphql-python/graphene#341]
We're using `gql2flow` to generate Flow types from the GraphQL schema and found that all of our `Connection` fields are defined with `edges` being nullable. 

According to [`graph-relay-js`](https://github.com/graphql/graphql-relay-js/blob/5927f0becf43740a1f1026c6e960811c4359d342/src/connection/connectiontypes.js) seems that `ConnectionBase.edges` should be defined as `NonNull(List(edge))`

Is there a scenario in which `edges` may be `None`?

**Comment by syrusakbary** [comment]
This should be fixed with #342 (thanks to @ekampf work).
