### ISSUE TITLE
Network Batching support

### ISSUE THREAD

**Issue by chaffeqa** [graphql-python/graphene#351]
Just curious how tough it would be to try to implement [Apollo Network Batching](http://dev.apollodata.com/core/network.html#GraphQLResult).

just from a high level do you think, knowing the internals, do you think it would be something u could point to a certain spot in the codebase (specifically django) where we could start such an implementation?

**Comment by syrusakbary** [comment]
For sure!!

The Django integration already have batching support on `master` thanks to this PR: https://github.com/graphql-python/graphene-django/pull/38

(a new version will be uploaded to PyPI soon)
