### ISSUE TITLE
Can I have resolver in AbstractType?

### ISSUE THREAD

**Issue by lebeier** [graphql-python/graphene#354]
```
class CountryQuery(AbstractType):
     country = Node.Field(CountryNode)
     all_countries = DjangoFilterConnectionField(CountryNode)
```

Suppose this is what I have, can I use resolver in here? Or resolver can only be defined in ObjectType at the root level?

**Comment by ekampf** [comment]
yes you can.
To use an abstract type you derive from it: `class SpecificQuery(ObjectType, CountryQuery):`
So any method defined on `CountryQuery` will also be available on `SpecificQuery`

**Comment by syrusakbary** [comment]
The solution provided by @ekampf should work. Closing issue
