### ISSUE TITLE
Document how to use input types with Mutations

### ISSUE THREAD

**Issue by qubitron** [graphql-python/graphene#364]
The following example shows how to use input types with Queries:
https://github.com/graphql-python/graphene/blob/master/examples/complex_example.py

But I can't figure out how to get it to work for mutations, I tried to create an example here:
https://github.com/qubitron/graphene/blob/patch-1/examples/complex_example.py

Relevant code is:
```
class SetAddress(graphene.Mutation):
    class Input:
        geo = graphene.InputField(GeoInput)

    latlng = graphene.Field(Address) 
    def mutate(self, args, context, info):
        geo = args.get('geo')
        return SetAddress(latlng="({},{})".format(geo.get('lat'), geo.get('lng')))

class Mutation(graphene.ObjectType):
    setAddress = SetAddress.Field()
```
I get the following error when trying to run it:
```
Traceback (most recent call last):
  File "complex_example.py", line 31, in <module>
    class Mutation(graphene.ObjectType):
  File "complex_example.py", line 32, in Mutation
    setAddress = SetAddress.Field()
  File "/usr/local/lib/python3.5/site-packages/graphene/types/field.py", line 53, in __init__
    self.args = to_arguments(args or OrderedDict(), extra_args)
  File "/usr/local/lib/python3.5/site-packages/graphene/types/argument.py", line 40, in to_arguments
    raise ValueError('Unknown argument "{}".'.format(default_name))
ValueError: Unknown argument "geo".
```

Would be great if someone could show us how to do it!

**Comment by ekampf** [comment]
This should work:
```
class SetAddress(graphene.Mutation):
    class Input:
        geo = GeoInput()
```

**Comment by syrusakbary** [comment]
@ekampf example should work, I also improved the messaging in `graphene` so it's easier to fix from a developer view.

**Comment by qubitron** [comment]
@ekampf @syrusakbary 
I have updated the sample to use:
```
class SetAddress(graphene.Mutation):
    class Input:
        geo = GeoInput()

    address = graphene.Field(lambda: Address) 
    def mutate(self, args, context, info):
        geo = args.get('geo')
        address = Address(latlng="({},{})".format(geo.get('lat'), geo.get('lng')))
        return SetAddress(address=address)
```

The mutate( ) method never gets called and the code returns an error:

```
$ python complex_example.py
(32.2,12.0)
Traceback (most recent call last):
  File "complex_example.py", line 73, in <module>
    print(result.data['address']['latlng'])
TypeError: 'NoneType' object is not subscriptable
```

I noticed that the [mutation docs](http://docs.graphene-python.org/en/latest/types/mutations/) look like they were recently updated and advise using ```graphene.InputField( ... )```, and  
if I switch it back to ```graphene.InputField(GeoInput)```, now I get a different error:
```
$ python complex_example.py
Traceback (most recent call last):
  File "complex_example.py", line 31, in <module>
    class Mutation(graphene.ObjectType):
  File "complex_example.py", line 32, in Mutation
    setAddress = SetAddress.Field()
  File "/usr/local/lib/python3.5/site-packages/graphene/types/field.py", line 53, in __init__
    self.args = to_arguments(args or OrderedDict(), extra_args)
  File "/usr/local/lib/python3.5/site-packages/graphene/types/argument.py", line 56, in to_arguments
    arg.type
ValueError: Expected geo to be Argument, but received InputField. Try using Argument(GeoInput).
```

When trying to use graphene.Argument(GeoInput), the mutate method never gets called and I get the same runtime error as above. I've updated my fork here with the example code:
https://github.com/qubitron/graphene/blob/patch-1/examples/complex_example.py

**Comment by streamliner18** [comment]
I second re-opening this.. We really have no way of nesting abstract types, and it seems like AbstractType is no longer a thing in the documentation. We're literally duplicating fields for everything now.

**Comment by AlecMcQuarrie** [comment]
Streamliner18, I actually found out how to do it:

```
class AddressInput(graphene.InputObjectType):
    zip = graphene.Int()
    lat = graphene.Float()
    street = graphene.String()
    long = graphene.Float()
    state = graphene.String()
    city = graphene.String()

class CreateSeminar(graphene.Mutation):
    class Arguments:
        address = graphene.Argument(AdressInput)

    ok = graphene.Boolean()
    seminars = graphene.Field(lambda: Seminars)

    @staticmethod
    def mutate(self, root, address):
        seminars = SeminarsModel(address=address)
        seminars.save()
        ok = True
        return CreateSeminar(seminars=seminars, ok=ok)
```

You can see that we need to use "graphene.InputObjectType" for the input field and also use "graphene.Argument(AdressInput)" when using it in the mutation function. If you have any other questions, let me know.
