### ISSUE TITLE
Deprecation reason not appearing in mutation input field unless explicitly wrapped in Field

### ISSUE THREAD

**Issue by acruis** [graphql-python/graphene#368]
We have this:

```
class SomeMutation(graphene.ClientIDMutation):
   class Input(object):
      some_id = ID()
```

I want to deprecate `some_id`, so I do this:
`some_id = ID(deprecation_reason="I have no need for this any more")`

...but the deprecation reason doesn't appear. But if I do this:
`some_id = Field(ID, deprecation_reason="I have no need for this any more")`

Then it works.

**Comment by wodCZ** [comment]
Similar here, except that your workaround doesn't work for me.

```
class InteractWithAnnouncement(graphene.ClientIDMutation):
    class Input:
        interaction_id = graphene.Field(graphene.String, deprecation_reason='Deprecated')
```

works exactly same as 

```
class InteractWithAnnouncement(graphene.ClientIDMutation):
    class Input:
        interaction_id = graphene.String(deprecation_reason='Deprecated')
```

which works exactly same as 

```
class InteractWithAnnouncement(graphene.ClientIDMutation):
    class Input:
        interaction_id = graphene.String()
```

I don't get deprecation notice in graphiql nor in console.

**Comment by ksonj** [comment]
I also can confirm that this is not working and I am using `ClientIDMutation` as well.

**Comment by jkimbo** [comment]
This was fixed by https://github.com/graphql-python/graphene/commit/a7a4ba62af4cb8b00ffa6a9f8cf79bd87dfb5e95

**Comment by mzins** [comment]
I am wanting to deprecate input parameters for a backend query rather than a mutation. Example 

`class NameArgs(InputObjectType):
    firstname = List(String, description="query by a list of first names")
    lastname = List( String, description="query by a list of last names" )

class PersonQuery(ObjectType):
    person = List(PersonType, input_args=NameArgs())
    
    def resolve_person( self, info, input_args ):
        return back_end_query(**input_args)
    `

say I wanted to deprecate first name and only allow users to query by last name, the following edit does not actually depreciate the last name argument 

`class NameArgs(InputObjectType):
    firstname = List(String, description="query by a list of first names")
    lastname = List( String, description="query by a list of last names",
                     deprecation_reason="last name is no longer supported by "
                                        "database")`
