### ISSUE TITLE
How to run graphene quietly

### ISSUE THREAD

**Issue by jwfehr** [graphql-python/graphene#374]
I am trying to create unit tests of my schema to make sure that everything is working as I expect it to, however when I run the unit tests graphene prints out a bunch of extra information that I don't want clogging up my unit test prints. Is there a way to disable turn this printing off?

**Comment by syrusakbary** [comment]
Hey @jwfehr,

There was an issue in `graphql-core` that was causing a lot of unwanted prints: https://github.com/graphql-python/graphql-core/issues/94 .

I believe this should be fixed with the latest version of graphene and graphql-core

```shell
pip install graphene>=1.1.2
pip install graphql-core>=1.0.1
```

Let me know if that works for you!

**Comment by jwfehr** [comment]
That did the trick! Thanks @syrusakbary
