### ISSUE TITLE
Incorrect Error Message

### ISSUE THREAD

**Issue by jwfehr** [graphql-python/graphene#375]
For a mutation class, if you return something other than an instance of the mutation class the error message is:
`[GraphQLError('Cannot return null for non-nullable field X.',)]`

it should tell you that you are not returning the right thing. (In my case I was mistakenly returning a string - which was non-null)

**Comment by syrusakbary** [comment]
Could be possible to have a working example describing this issue?

**Comment by jkimbo** [comment]
Hi @jwfehr . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
