### ISSUE TITLE
String own References not working 

### ISSUE THREAD

**Issue by fbyossi** [graphql-python/graphene#376]
Trying to refrence own class using string refrences fails.

```python
class UserType(graphene.ObjectType):

    id = graphene.Int()
    name = graphene.String()
    friends = graphene.List('UserType')

    def resolve_name(self, args, context, info):
        return self.name

    def resolve_friends(self, args, context, info):
        return self.friends
```

Get's me the following error:

> graphql/type/typemap.py", line 59, in reducer
    if type.name in map:
AttributeError: 'str' object has no attribute 'name'

graphene==1.1.2
graphene-sqlalchemy==1.1.0
graphql-core==1.0.1
graphql-relay==0.4.5

**Comment by fbyossi** [comment]
Alright, I got it working with 
'''python
friends = graphene.Dynamic(lambda: graphene.List(UserType))
'''
Is this the correct solution?

**Comment by syrusakbary** [comment]
@fbyossi using `graphene.Dynamic` is a valid solution however I recommend using this simpler version.

```python
friends = graphene.List(lambda: UserType)
```

PS: Dynamic is the recommended approach when the field is resolved "lazily" depending on the schema. For example, having or not certain field in a model (rather than deciding the type lazily).
