### ISSUE TITLE
Using Unions in a Connection

### ISSUE THREAD

**Issue by wkiser** [graphql-python/graphene#377]
I'm having some issues implementing a connection field that returns a Union type. The issue seems to be that I need a class that has both the Union and Node metaclasses.

Any suggestions on how to proceed here? I would like to avoid hacking up some temporary metaclass. From the code it looks like this should be supported:

`assert issubclass(options.node, (Scalar, Enum, ObjectType, Interface, Union, NonNull)), (
            'Received incompatible node "{}" for Connection {}.'
        ).format(options.node, name)`

Here's a simple schema I used to reproduce the error:

```
class Cat(graphene.ObjectType):
    class Meta:
        interfaces = (relay.Node,)
    name = graphene.String()

class Dog(graphene.ObjectType):
    class Meta:
        interfaces = (relay.Node,)
    name = graphene.String()

class Animal(Union):
    class Meta:
        types = (Cat, Dog)

class Query(graphene.ObjectType):
    animals = graphene.ConnectionField(Animal)
```

**Comment by sofiama** [comment]
it should be `animals = relay.ConnectionField(Animal)`

**Comment by syrusakbary** [comment]
For using unions as connections, you need to create a ConnectionType for the union.
The following should work:

```python
class Cat(graphene.ObjectType):
    class Meta:
        interfaces = (relay.Node,)
    name = graphene.String()

class Dog(graphene.ObjectType):
    class Meta:
        interfaces = (relay.Node,)
    name = graphene.String()

class Animal(Union):
    class Meta:
        types = (Cat, Dog)

class AnimalConnection(graphene.Connection):
    class Meta:
        node = Animal

class Query(graphene.ObjectType):
    animals = graphene.ConnectionField(AnimalConnection)
```

(related issue #356)

**Comment by wkiser** [comment]
@syrusakbary , worked for me. Thanks!

**Comment by kimutaiRop** [comment]
how about if you are trying to introduce filter?

**Comment by kasikn77** [comment]
@syrusakbary can you please show us query example? How we can filter results using union?

**Comment by pfcodes** [comment]
> how about if you are trying to introduce filter?

This. Using a `filterset_class` with DjangoFilterConnectionField doesn't work.
