### ISSUE TITLE
Required mutation input arguments

### ISSUE THREAD

**Issue by janhancic** [graphql-python/graphene#380]
Why can't input arguments be marked as required in mutations (and I suppose in the normal schema too)? It seems it's possible if you create a `InputField` to have it be required, but I can't mark primitives as required.

This:
```python
class DoSomething(graphene.Mutation):
    class Input(object):
        param_1 = graphene.String(required=True)

    @classmethod
    @with_context
    def mutate(cls, _, args, context, __):
        pass
```

blows up with `__init__() got an unexpected keyword argument 'required'`.

Is this intended or an oversight?

**Comment by syrusakbary** [comment]
Hey @janhancic,

Your code should work with the latest version of Graphene (it seems you're using 0.10.X).
Please reopen the issue if not :)

**Comment by janhancic** [comment]
Yes that was it. Finished the upgrade now and can use the `required` now. Thanks!
