### ISSUE TITLE
SearchFilter implementation

### ISSUE THREAD

**Issue by odero** [graphql-python/graphene#383]
What would be the best way to implement SearchFilter similar to the one in django admin and/or DRF?
Basically searching for a term across multiple search fields - django-filter doesn't seem to support this.

**Comment by amelius15** [comment]
I've accomplished a similar functionality by adding a "search" method filter and using django-watson to actually perform the search. Something like this

`class ObjectFilter(django_filters.FilterSet):
    search = django_filters.MethodFilter(action='filter_search')
    class Meta:
        model = Object
    def filter_search(self, queryset, value):
        return watson.filter(queryset, value)`

I don't know if this is considered the best way, but it certainly works.

**Comment by odero** [comment]
This actually solved it thank you. Hadn't used django-watson before.
