### ISSUE TITLE
Implement JSON type

### ISSUE THREAD

**Issue by hung-phan** [graphql-python/graphene#384]
For right now, we can only handle JSONString type, is there any chance that we would have the proper JSON type like https://github.com/taion/graphql-type-json?

**Comment by hung-phan** [comment]
Sth like this for example:

```
import graphene
from graphql.language.ast import BooleanValue, StringValue, FloatValue, IntValue, ListValue, ObjectValue


def identity(value):
    return value


class JSON(graphene.Scalar):
    """
    The `JSON` scalar type represents JSON values as specified by
    [ECMA-404](http://www.ecma-international.org/
    publications/files/ECMA-ST/ECMA-404.pdf).
    """
    serialize = identity
    parse_value = identity

    @staticmethod
    def parse_literal(ast):
        if isinstance(ast, (StringValue, BooleanValue)):
            return ast.value
        elif isinstance(ast, (FloatValue, IntValue)):
            return float(ast.value)
        elif isinstance(ast, ObjectValue):
            value = {}

            for field in ast.fields:
                value[field.name.value] = JSON.parse_literal(field.value)

            return value
        elif isinstance(ast, ListValue):
            return map(JSON.parse_literal, ast.values)
        else:
            return None
```

**Comment by syrusakbary** [comment]
As the implementation is completely abstract from the `json` serialization/unserialization I renamed the `JSON` type to `GenericScalar`.

You can use it by:
```python
from random import random
from ..generic import GenericScalar
from ..objecttype import ObjectType


class Query(ObjectType):
    generic = GenericScalar(input=GenericScalar())

    def resolve_generic(self, args, context, info):
        if random() > 0.5:
            return 5.0
        return False
```

Hope this helps!

**Comment by cristianfraser** [comment]
Hey @syrusakbary, not meaning to post in this old thread... but should GenericScalar still work? Was it replaced?

In the changelog I can only see when it was added, but nothing else. And when importing with `from graphene.types.generic import GenericScalar` I get that it doesn't exist.

**Comment by japrogramer** [comment]
is GenericScalar stilll around .. I need to return a json object .. and i can't find it.

@syrusakbary

**Comment by amildoto** [comment]
@japrogramer can you post an example how you did it? I want to return SQLAlchemy JSONB field as json

**Comment by japrogramer** [comment]
from graphene.types import generic

...
    errors = generic.GenericScalar()

**Comment by yashas123** [comment]
Is it not possible that if the resolver returns dict it's automatically taken as JSON?
