### ISSUE TITLE
How to define a schema that has cross references?

### ISSUE THREAD

**Issue by eclipselu** [graphql-python/graphene#388]
@syrusakbary 
Hi, I recently encountered the following issue when using graphene:

My desired schema:

```python

class Artist(graphene.ObjectType):
    id = graphene.ID()
    famous_song = graphene.Field(Song)

class Song(graphene.ObjectType):
    id = graphene.ID()
    artist = graphene.Field(Artist)

```

As you can see, `Artist` and `Song` are referencing each other, which will inevitably leads to error in python. It would complain something like `Song is not defined`.

I think this is actually a pretty common scenario, just wonder how to do this in graphene. 
Thanks!

**Comment by angieellis** [comment]
You can utilize the dynamic field type by using lambda: 

famous_song = graphene.Field(lambda: Song)

**Comment by eclipselu** [comment]
@angieellis Great! Thank you very much! This works.  :hooray:
