### ISSUE TITLE
Ability to merge queries

### ISSUE THREAD

**Issue by kevinbarabash** [graphql-python/graphene#389]
I have some JSON blobs on my server that contain data for different modular components that I'm rendering.  Which components I render depends on which blobs of data get sent down.  I'd like to be able to merge that data together to dedupe it and only send the names of the components and the deduped data.  I was thinking that GraphQL might make sense, but there doesn't seem to be any way to merge queries using Graphene.  I'd appreciate any suggestions you might have about how to go about merging queries.

**Comment by angieellis** [comment]
@kevinbarabash This seems to be a prevalent concern in the GraphQL community right now. Many GraphQL libraries don't support batch querying or merging queries. There is a library in Javascript that provides this functionality (https://github.com/stems/join-monster), but none that I know of in Python. This is definitely something I would like to see as well.

**Comment by bforchhammer** [comment]
I had a similar problem (see https://github.com/graphql-python/graphene/issues/358#issuecomment-269220991), maybe that also works for you...

**Comment by jkimbo** [comment]
Hi @kevinbarabash . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
