### ISSUE TITLE
graphql subscriptions

### ISSUE THREAD

**Issue by predmond** [graphql-python/graphene#393]
How can I support subscriptions using graphene?

**Comment by globophobe** [comment]
That would depend on what kind of subscription, for example long-polling or WebSocket. It also depend on your backend, for example Django, with django channels, could handle subscriptions by broadcasting to connected sockets from a post_save signal.

**Comment by jameswyse** [comment]
Would love to see an example using Django Channels. The new databinding features look ideal for graphql subscriptions :)

https://channels.readthedocs.io/en/stable/binding.html

**Comment by Jufik** [comment]
I'd guess it's pretty straight forward to code a model related subscription.
I'm working with Django, and plan to use Django Channel: my suggestions and answers are opinionated that way.

Getting inspired by  mutation from sources, one could push down the data to customer quite easily.
In case of Mutation, _mutate_ is called is the resolver. I guess a general _subscribe_  function could be written to "hookup" the customer channel on an "subscription specific channel", it self hooked up on the "model channel". 
Using a post_save, writting down a custom save method or binding could do the Job to propagate the data down to clients.

I don't know how to solve two stuff though:
- how to get the information of which channel is expecting which "_query_" (eg which fields should be sent to which client).
- parameters handling. Like how to handle a subscription to a model, based on a category filter.

For the first point, I guess I could use  caching engine and a 3 layer structure to  push data to my channel. Like: Customer Channel hooked up to a Query Channel, that his hooked up to the model channel. The query used  in the Query Channel being store in cache. It seems non trivial bu feasible.

For the second point, only a cache based solution seems viable, storing filters in a dict, stored in cache. But that's lot of work. 

Any suggestion on those two questions is welcome!

I'll give a basic architecture a try, and create share repo' to give some feedback.

**Comment by jeffreybrowning** [comment]
@Jufik Any updates?

**Comment by hballard** [comment]
I implemented a port of the apollo graphql subscriptions modules ([graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions) and [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws)) for graphene / python.  They work w/ [apollo-client](https://github.com/apollographql/apollo-client).  

It is [here](https://github.com/hballard/graphql-python-subscriptions).

Same basic api.  It is still very rough...but works so far, based on my limited testing.  Uses [redis-py](https://github.com/andymccurdy/redis-py), [gevent-websockets](https://bitbucket.org/noppo/gevent-websocket), and [syrusakbary/promises](https://github.com/syrusakbary/promise).  It is still missing a few of the server options and keep-alive messages, but those are pretty easy to implement and I'll do that in the next few days.  Only works on python2 for now and it needs tests, setup.py, etc.  I figured I'd go ahead and share in case anybody is interested...

I'm very new to open source, so any critiques or pull requests are welcome.

**Comment by dfee** [comment]
@hballard checking it out. But wow, this was one of the major things holding me back.

**Comment by hballard** [comment]
Cool.  Let me know your thoughts.  I just pushed an update that added the keep_alive messages and the on_connect, on_disconnect, on_subscribe, and on_unsubscribe optional server setup functions.  This should make it mostly the same as the Apollo subscriptions API at this point.

**Comment by japrogramer** [comment]
@globophobe django channels cannot do broadcasting with ws
https://channels.readthedocs.io/en/stable/concepts.html#groups

**Comment by globophobe** [comment]
@japrogramer You're right. There's an extra step. The client would need to be added to a group. I don't have time (nor ever will) to explore this. Personally waiting for, https://github.com/encode/uvicorn and https://github.com/encode/apistar to bring good things to Django, or obviate my need for it.

**Comment by japrogramer** [comment]
For anyone interested this is how i implemented subscriptions with channels.
https://github.com/graphql-python/graphene/pull/500#issuecomment-325560994

**Comment by miketout** [comment]
I just collaborated with @IlyaRadinsky on a graphene/Tornado/subscriptions integration with websockets that requires one line of code to get your graphene schema + subscriptions up and available as an API. Here's a link to his original repo, which has incorporated my changes as well:
https://github.com/IlyaRadinsky/tornadoql

**Comment by japrogramer** [comment]
@miketout awesome, lots of interesting techniques and code there, will definitely be taking a look.

**Comment by dfee** [comment]
I'm about to start digging into subscription support probably tomorrow, but I'm looking at the code [here](https://github.com/graphql-python/graphql-core/blob/0b0551e7dfb724dedc66759145b9221595ec8598/graphql/execution/tests/test_subscribe.py) (graphql-python test code)

**Comment by dfee** [comment]
Here's a [very simple gist](https://gist.github.com/dfee/ca0aaff06d250b10c8f39fb4f862517a) of how to use subscriptions with graphene.

In a nutshell, it's probably easiest to return an `rx.Observable` using the pattern in the implementation above, though returning an `AsyncIterator` is also allowed. `rx` is a dependency of `graphene` anyway, meaning that it's not additional requirement you'll need to install, and it works on py2 and py3.

As you're probably using this for a web view, you'll actually want to save that [subscriber](https://gist.github.com/dfee/ca0aaff06d250b10c8f39fb4f862517a#file-graphene_subscription-py-L126) and store it in a dict so a user can unsubscribe from it in the future. And, you'll probably also want to use websockets, or socket.io, etc. so you can actually push the subscription data out instead of appending it to a list as I've done on that same line.

**Comment by japrogramer** [comment]
@dfee any ideas on how to use django signals with observables ..?

I was thinking of doing the same thing you are doing here 
```
subject = rx.subjects.Subject()
# and in the signal consumer have
@receiver(post_save, sender=Model)
def send_update_product(sender, instance, created, *args, **kwargs):
    # I think I might be misunderstanding where I should put this line
    subject.on_next((instance.pk, created))
```

```
 19 def send(result, message):
 18     data = result.data
 17     message.reply_channel.send(
 16         {
 15             'text': str({'data': json.loads(json.dumps(data))})
 14         })
 13
 12
 11 @channel_session
 10 def ws_GQLData(message):
  9     clean = json.loads(message.content['text'])
  8     query = clean.get('query')
  7     foovar = clean.get('variables')
  6     message.dataloaders = DataLoaders(get_language())
  5     kwargs = {'context_value': message}
  4     #  TODO: Implement weight, can this query run for this user or is it too expensive <10-11-17> #
  3     #  TODO: Implement timeout mechanism <10-11-17> #
  2     result = schema.execute(query, variable_values=foovar, allow_subscriptions=True, **kwargs)
  1     if isinstance(result, rx.Observable):
37          class MyObserver(rx.Observer):
  1
  2             def on_next(self, x):
  3                 send(x, message)
  4
  5             def on_error(self, e):
  6                 ...
  7
  8             def on_completed(self):
  9                 ...
 10
 11         result.subscribe(MyObserver())
 12     else:
 13         send(result, message)
```

**Comment by dfee** [comment]
@japrogramer I honestly haven't used Django since 1.4 (about 6 years ago), so I don't have too much to offer about specifics.

However, my hunch is that Django's `signals` concept and the `rx` concept are pretty similar in theory, but quite different in implementation. You'll probably need some glue to connect the `rx.Observable` object and the Django signal.

I did notice in your code that you're defining `class MyObserver`. If I'm imagining  correctly, that you lifted that from the tests [here](https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/tests/test_subscribe.py#L78) I'd point out two things:
1) you probably don't need to define a class **
2) the test code isn't even using that class. It should be dropped from the file.

** see this note from the [rxpy docs](https://github.com/ReactiveX/RxPY):
> Most of the time you will not want to go through the verbosity of implementing your own Observer. You can instead pass 1 to 3 lambda arguments to subscribe() specifying the on_next, on_complete, and on_error actions.

```python
from rx import Observable

source = Observable.from_(["Alpha", "Beta", "Gamma", "Delta", "Epsilon"])

source.subscribe(on_next=lambda value: print("Received {0}".format(value)),
                 on_completed=lambda: print("Done!"),
                 on_error=lambda error: print("Error Occurred: {0}".format(error))
                 )
```

**Comment by japrogramer** [comment]
@ProjectCheshire your solution looks a lot more elegant than what i ended up implementing

https://github.com/graphql-python/graphene/issues/430#issuecomment-396015394

my solution is so convoluted and the graphql-core package doesn't like that i have loop already running https://github.com/graphql-python/graphene-django/issues/452  it raises an error but doesn't stop thee execution of the subscription.

That leads to some issues that I have found a work around, unfortunately that leaves me with some undesired behavior
 that lead me to not  actually using the subscription directly instead I use it to trigger a refetch on the actual query im inteerested in 

 ```
   this.subscription = this.props.data.subscribeToMore({
      document: gql`
        subscription ChangeInProduct($id: ID!) {
          subProduct(product: $id) {
            title
          }
        }
      `,
      variables: { id: this.props.match.params ? this.props.match.params.id : null },
      updateQuery: (prev, { subscriptionData }) => {
        if (!subscriptionData.data) {
          return prev;
        }
        console.log('interesting', prev, subscriptionData);
        this.props.data.refetch()
        return prev;
      },
    });

```

**Comment by prokher** [comment]
JFYI: We have eventually published our domestic subscriptions implementation DjangoChannelsGraphqlWs. Probably someone will find it useful. Actually we implemented a simple WebSocket-based GraphQL server implemented on Django Channels. Subscriptions are implemented in the Graphene-like style.

**Comment by taybin** [comment]
Disappointing that this was autoclosed as stale when websockets are a big part of the GraphQL spec.

**Comment by japrogramer** [comment]
The issue should be open in djago-graphene or flask-graphene not pure graphene .. because of the way python web frameworks work
