### ISSUE TITLE
Using Graphene + Relay + SQL Alchemy

### ISSUE THREAD

**Issue by pedrorjbr** [graphql-python/graphene#396]
I am trying to use graphene and respect relay specification. By database is backed uisng SQL Alchmey ORM.

```
class Product(SQLAlchemyObjectType):
    class Meta:
        model = ProductModel
        interfaces = (relay.Node, )

    @classmethod
    def get_node(cls, id, context, info):
        session =  context['session']
        p = session.query(ProductModel).filter(ProductModel.id == id).first()
        return p
        
        
class Query(graphene.ObjectType):
    product = graphene.Field(Product, id=graphene.String())
    node = relay.Node.Field()

    #resolve product
    def resolve_product(self, args, context, info):
        session =  context['session']
        id_ = from_global_id(args['id'])[1]
        p = session.query(ProductModel).filter(ProductModel.id == id_).first()
        return p
```

On resolve_product I always need to decode the global unique ID to a primary key database. Is it the correct approach? or Is it better to have another key on database called UUID for example?

**Comment by jkimbo** [comment]
Hi @pedrorjbr. We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by manuFL** [comment]
Still relevant, relay ids and db ids seems to conflict and breaks the queries...
