### ISSUE TITLE
How to use graphene.Connection with SQL Alchemy?

### ISSUE THREAD

**Issue by pedrorjbr** [graphql-python/graphene#397]
I am trying to use Graphene + SQLAlchmey. I am struggling to find way to implement pagination using Connection Field. The resolver: `resolve_all_products`

```
class Query(graphene.ObjectType):
    product = graphene.Field(Product, id=graphene.ID())
    all_products = relay.ConnectionField(ProductConnection)
    products = graphene.List(Product)
    node = relay.Node.Field()
    
    def resolve_product(self, args, context, info):
        session =  context['session']
        id_ = from_global_id(args['id'])[1]
        p = session.query(ProductModel).filter(ProductModel.id == id_).first()
        return p

    def resolve_products(self, args, context, info):
        session =  context['session']
        return session.query(ProductModel).all()
        
    def resolve_all_products(self, args, context, info):
        session =  context['session']
        first = args.get('first')
        # how to get cursor and paginate?
        return session.query(ProductModel).limit(first).all()
```

**Comment by cliedeman** [comment]
Hello

Have you looked at the [sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy) integration project?

Pagination is already implemented there for relay.

Ciaran

**Comment by jkimbo** [comment]
Hi @pedrorjbr . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
