### ISSUE TITLE
Example for InputFields and InputObjectTypes

### ISSUE THREAD

**Issue by marcovc** [graphql-python/graphene#398]
The example in the docs [here](http://docs.graphene-python.org/en/latest/types/mutations/#inputfields-and-inputobjecttypes) doesn't work.

I got 
`ValueError: Expected person_data to be Argument, but received InputField. Try using Argument(PersonInput).`
and have no idea what it means.

**Comment by angieellis** [comment]
Can you please paste your code for this?

**Comment by marcovc** [comment]
Hi, 
The code is the one from the documentation linked above. 
Thanks
Marco

**Comment by m-charlton** [comment]
The following code, from the given link, works fine (on my setup at least):

```python
import graphene

class PersonInput(graphene.InputObjectType):
    name = graphene.String()
    age = graphene.Int()

class CreatePerson(graphene.Mutation):
    class Input:
        person_data = graphene.InputField(PersonInput)

    person = graphene.Field(lambda: Person)

    def mutate(self, args, context, info):
        p_data = args.get('person_data')

        name = p_data.get('name')
        age = p_data.get('age')

        person = Person(name=name, age=age)
        return CreatePerson(person=person)
```

However the next example, on the same page, fails:

```python
1    import graphene
2
3    class LatLngInput(graphene.InputObjectType):
4        lat = graphene.Float()
5        lng = graphene.Float()
6
7    #A location has a latlng associated to it
8    class LocationInput(graphene.InputObjectType):
9        name = graphene.String()
10       latlng = graphene.InputField(LatLngInputType)
```
with this traceback:

```python
Traceback (most recent call last):
  File "ex1.py", line 8, in <module>
    class LocationInput(graphene.InputObjectType):
  File "ex1.py", line 10, in LocationInput
    latlng = graphene.InputField(LatLngInputType)
NameError: name 'LatLngInputType' is not defined
```

It looks as if there is a typo on line 10: `LatLngInputType` should be `LatLngInput`,
or the class `LatLngInput`should be `LatLngInputType`.

The error is in `docs/types/mutations.rst`.

I'm willing to make and test the change.

Python 2.7 environment as follows:

```
graphene==1.1.3
graphql-core==1.0.1
graphql-relay==0.4.5
promise==1.0.1
six==1.10.0
typing==3.5.3.0
```

**Comment by lucascosta** [comment]
I can confirm the error reported by @marcovc using `1.1.3`. There's even specific code for raising it in the `to_arguments` function on `types.argument::52`:
``` python
        if isinstance(arg, (InputField, Field)):
            raise ValueError('Expected {} to be Argument, but received {}. Try using Argument({}).'.format(
                default_name,
                type(arg).__name__,
                arg.type
            ))
```
