### ISSUE TITLE
Query does not support snake case query names

### ISSUE THREAD

**Issue by ashinohara** [graphql-python/graphene#4]
When I create a query that has a snake case name and attempt to execute it, I get the following error:

    [graphql.core.error.GraphQLError('Cannot query field "work_order" on "Query".')]

Here is what my query looks like:

     class Query(ObjectType):
        work_order = Field(WorkOrder, id=graphene.Argument(graphene.String))

        @resolve_only_args
        def resolve_work_order(self, id):
            return WorkOrder(id='1', state='test')

Here is what my GraphQL query looks like:

    query = """
    query test {
        work_order(id: "1") {
            state
        }
    }
    """

if I change the name of the query to workorder instead of work_order, or workOrder it works just fine.  Is this intended behavior?

**Comment by jhgg** [comment]
Yes, that is the intended behavior. If you want the snake_cased name (which I don't recommend you do -- keep with convention and use camelCasing) you can simply pass `name='work_order'` to the Field constructor. 

```python
 class Query(ObjectType):
    work_order = Field(WorkOrder, id=graphene.Argument(graphene.String), name='work_order')

    @resolve_only_args
    def resolve_work_order(self, id):
        return WorkOrder(id='1', state='test')

```

**Comment by ashinohara** [comment]
Great, thanks.  I am more concerned with the fields when defining the schema actually, where name seems to work as well:

    class WorkOrder(Node):
        id = IDField()
        state = StringField()
        nodes = ListField(WorkOrderNode)
        req_uid = StringField(name='req_uid')

Since we are defining the schema in python it is nice to make it more pythonic.  Why don't you recommend using snake case?

**Comment by jhgg** [comment]
The schema is generally going to be consumed by a JavaScript application. Casing there is camel. Graphene will keep things in Python snake cased, but outwards facing graphQl schema will be camel cased which is generally the convention for JavaScript and grqphQL.

**Comment by ashinohara** [comment]
Thanks for the clarification!
