### ISSUE TITLE
Multiple `ConnectionField` fields do not function as expected

### ISSUE THREAD

**Issue by adamcharnock** [graphql-python/graphene#40]
I am finding that once I have multiple `relay.ConnectionField` fields attached to a Query, all requests will be validated against the second field

I have the following Query class:

```python
class Query(ObjectType):
    # Accounts have a 'name' field
    all_accounts = relay.ConnectionField(nodes.Account, description='All the accounts')
    # Transactions do not have a 'name' field
    all_transactions = relay.ConnectionField(nodes.Transaction, description='All the transactions')

    @resolve_only_args
    def resolve_all_accounts(self, **kwargs):
        return [nodes.Account(obj) for obj in models.Account.objects.all()]

    @resolve_only_args
    def resolve_all_transactions(self, **kwargs):
        return [nodes.Transaction(obj) for obj in models.Transaction.objects.all()]
```

Upon running this query:

```graphql
query {
  allAccounts {
    edges {
      node {
        name
      }
    }
  }
}
```

I receive:

```graphql
{
  "errors": [
    {
      "locations": [
        {
          "column": 9,
          "line": 5
        }
      ],
      "message": "Cannot query field \"name\" on \"Transaction\"."
    }
  ]
}
```

Note that the above error seems to think I am querying `Transaction` which, after tripple checking my code, I'm pretty sure I'm not. Also, if I switch the order of the fields on the Query class then the query will be successfully processed and data returned.

Caveat: I'm still pretty new to this, and the whole `edges { nodes {` part of that query looks a little suspect to me. However, there are little to no examples I can find on anywhere online regarding how one should query for more than a single object. I'm almost entirely running off GraphiQL's autocomplete!

**Comment by adamcharnock** [comment]
I just updated from 0.4.0 to 4a591354f1d809e0c5d34ba425bcd4a0960fe2ee and this seems to be fixed now.

I'd be very grateful if someone could give me a nod wrt the query I'm doing though. Does that look sane?

**Comment by syrusakbary** [comment]
Hi @adamcharnock , just uploaded to PyPI the latest code under version `0.4.1`.

The models are already wrapped in Django mapping, so you could do:

```python
    @resolve_only_args
    def resolve_all_accounts(self, **kwargs):
        return models.Account.objects.all()

    @resolve_only_args
    def resolve_all_transactions(self, **kwargs):
        return models.Transaction.objects.all()
```

A full working example is [swapi-graphene](http://swapi.graphql-python.org). Check the [schema](https://github.com/graphql-python/swapi-graphene/blob/master/starwars/schema.py) which is where everything happens.
Ping me if any question!

**Comment by syrusakbary** [comment]
I removed temporary the version `0.4.1` from PyPI until I add the support for previous `get_node` syntax. (Will be done in few mins)

**Comment by syrusakbary** [comment]
Reuploaded again, everything should work fine :)

**Comment by adamcharnock** [comment]
@syrusakbary Ah yes, thank you very much. The SW example has been very handy actually. I think #40 was throwing me a bit, but now that is sorted that should make life easier.
