### ISSUE TITLE
Potentially obsolete/incorrect information in README

### ISSUE THREAD

**Issue by raun** [graphql-python/graphene#405]
Hey!

I am new contributor and checked out the package. I followed all the instructions to install all dependencies and run tests before making any changes.

However, the test run failed with the following message : 

`_________________________________________________________________________________________ ERROR collecting examples/starwars/tests/test_query.py __________________________________________________________________________________________
ImportError while importing test module '/Users/anshul/Devel/Source/open_source/graphene/examples/starwars/tests/test_query.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
examples/starwars/tests/test_query.py:3: in <module>
    from ..schema import schema
examples/starwars/schema.py:2: in <module>
    from graphene import resolve_only_args
E   ImportError: cannot import name resolve_only_args
___________________________________________________________________________________ ERROR collecting examples/starwars_relay/tests/test_connections.py ____________________________________________________________________________________
ImportError while importing test module '/Users/anshul/Devel/Source/open_source/graphene/examples/starwars_relay/tests/test_connections.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
examples/starwars_relay/tests/test_connections.py:2: in <module>
    from ..schema import schema
examples/starwars_relay/schema.py:2: in <module>
    from graphene import relay, resolve_only_args
E   ImportError: cannot import name resolve_only_args
_____________________________________________________________________________________ ERROR collecting examples/starwars_relay/tests/test_mutation.py _____________________________________________________________________________________
ImportError while importing test module '/Users/anshul/Devel/Source/open_source/graphene/examples/starwars_relay/tests/test_mutation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
examples/starwars_relay/tests/test_mutation.py:2: in <module>
    from ..schema import schema
examples/starwars_relay/schema.py:2: in <module>
    from graphene import relay, resolve_only_args
E   ImportError: cannot import name resolve_only_args
_______________________________________________________________________________ ERROR collecting examples/starwars_relay/tests/test_objectidentification.py _______________________________________________________________________________
ImportError while importing test module '/Users/anshul/Devel/Source/open_source/graphene/examples/starwars_relay/tests/test_objectidentification.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
examples/starwars_relay/tests/test_objectidentification.py:2: in <module>
    from ..schema import schema
examples/starwars_relay/schema.py:2: in <module>
    from graphene import relay, resolve_only_args
E   ImportError: cannot import name resolve_only_args
___________________________________________________________________________________________ ERROR collecting graphene/tests/issues/test_313.py ____________________________________________________________________________________________
ImportError while importing test module '/Users/anshul/Devel/Source/open_source/graphene/graphene/tests/issues/test_313.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
graphene/tests/issues/test_313.py:4: in <module>
    from graphene import resolve_only_args
E   ImportError: cannot import name resolve_only_args
___________________________________________________________________________________________ ERROR collecting graphene/tests/issues/test_356.py ____________________________________________________________________________________________
graphene/tests/issues/test_356.py:7: in <module>
    class SomeTypeOne(graphene.ObjectType):
E   AttributeError: 'module' object has no attribute 'ObjectType'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`

Either I am doing something terribly wrong or the README has not been updated.

Thanks!

**Comment by BossGrand** [comment]
Can you put your code from the class thats causing the issue

**Comment by jkimbo** [comment]
Hi @raun. We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
