### ISSUE TITLE
AttributeError: type object '<class>' has no attribute 'name'

### ISSUE THREAD

**Issue by Exertive** [graphql-python/graphene#411]
Syrus. I have been using Django with Graphene for a couple of weeks now with some success. 

However, I keep coming across this error message. Like rattrayalex in an earlier issue, I have been inheriting from both AbstractType and ObjectType in the Query and Mutation classes. This is fine at the overall application level but if I try to instantiate a Schema within a sub-application schema file -- for unit testing -- I get the dreaded "AttributeError: type object 'Address' has no attribute 'name'" error when doing the following:

```python
schema = graphene.Schema(query=Query, mutation=Mutation)
```

where 'Address' is a class in the schema file which is used in Query and Mutation:

```python
class Address(DjangoObjectType):

    class Meta:
        model = AddressModel
        interfaces = (graphene.Node,)
        filter_fields = {
            'line_1': ['exact', 'icontains', 'istartswith'],
            'line_2': ['exact', 'icontains', 'istartswith'],
            'town': ['exact', 'icontains', 'istartswith'],
            'county': ['exact', 'icontains', 'istartswith'],
            'postcode': ['exact', 'icontains', 'istartswith'],
        }
```
I am struggling to understand what I am doing wrong here. Can you provide any pointers?

David

Using Django 1.10.5 with Python 2.7 and latest build of Graphene.

**Comment by gbezyuk** [comment]
@Exertive any progress on this one? Which `name` do you think does the system lack?

**Comment by dfee** [comment]
For what it's worth, when i've run into this problem it had nothing to do with multiple schemas with the same name. Rather, I was bungling a model name and a schema name. I'm using SQLAlchemy, but this might provide some insight (notice how I'm importing the model with an underscore):

```
import graphene
from graphene import relay
from graphene_sqlalchemy import SQLAlchemyConnectionField

from .message import Message
from ..models import Message as _Message


class Query(graphene.ObjectType):
    messages = graphene.List(Message)
    node = relay.Node.Field()

    def resolve_messages(self, args, context, info):
        query = _Message.get_query(context)
        return query.all()
```

**Comment by jkimbo** [comment]
Hi @Exertive . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by sandwichsudo** [comment]
In case this helps someone, I had a similar bug in my code:

```
class SerializerErrorType:
    field = graphene.String(required=True)
    messages = graphene.List(graphene.NonNull(graphene.String), required=False)

```

Which was missing the parent class: 

```
class SerializerErrorType(graphene_types.ObjectType):
    field = graphene.String(required=True)
    messages = graphene.List(graphene.NonNull(graphene.String), required=False)

```

**Comment by erikwrede** [comment]
@squarewave24 can you tell me the location of the error? Maybe we can add some checks.
