### ISSUE TITLE
Can't run sample mutation

### ISSUE THREAD

**Issue by dmitry-saritasa** [graphql-python/graphene#417]
https://github.com/graphql-python/swapi-graphene/blob/master/starwars/schema.py

```
class CreateHero(graphene.ClientIDMutation):

    class Input:
        name = graphene.String(required=True)
        homeworld_id = graphene.String(required=True)

    hero = graphene.Field(Hero)
    ok = graphene.Boolean()

    @classmethod
    def mutate_and_get_payload(cls, input, info):
        name = input.get('name')
        homeworld_id = input.get('homeworld_id')
        try:
            homeworld_id = int(homeworld_id)
        except ValueError:
            try:
                _type, homeworld_id = Node.from_global_id(homeworld_id)
                assert _type == 'planet', 'The homeworld should be a Planet, but found {}'.format(resolved.type)
            except:
                raise Exception("Received wrong Planet id: {}".format(homeworld_id))

        homeworld = Planet._meta.model.objects.get(id=homeworld_id)
        hero = Hero._meta.model(name=name, homeworld=homeworld)
        hero.save()

        return CreateHero(hero=hero, ok=bool(hero.id))


class Mutation(graphene.ObjectType):
    create_hero = graphene.Field(CreateHero)


schema = graphene.Schema(
    query=Query,
    mutation=Mutation,
)
```

[playground ](http://swapi.graphene-python.org/graphql?query=mutation%20%7B%0A%20%20createHero(name%3A%22Test%22%2C%20planet%3A%22Test%22)%7B%0A%20%20%20%20hero%20%7B%0A%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20name%2C%0A%20%20%20%20%20%20homeworld%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=undefined&variables=)

```
mutation {
  createHero(name:"Test", planet:"Test"){
    hero {
      id,
      name,
      homeworld {
        id
      }
    }
  }
}
```

I always get this message

```
{
  "errors": [
    {
      "message": "Unknown argument \"name\" on field \"createHero\" of type \"Mutation\".",
      "locations": [
        {
          "line": 2,
          "column": 14
        }
      ]
    },
    {
      "message": "Unknown argument \"planet\" on field \"createHero\" of type \"Mutation\".",
      "locations": [
        {
          "line": 2,
          "column": 27
        }
      ]
    }
  ]
}
```

what am I doing wrong?

**Comment by abdulhaq-e** [comment]
The playground doesn't seem to be relevant to the code in `scheme.py` which you linked.

**Comment by BossGrand** [comment]
all inputs to a mutation have to be wrapped in a input object

this 
`createHero(name:"Test", planet:"Test"){`

should be 
`createHero(input:{ name:"Test", planet:"Test" }){`

**Comment by dmitry-saritasa** [comment]
@BossGrand I tried with 'input' and it didn't work either

```
mutation {
  createHero(input:{name:"Test", planet:"Test" }){
    hero {
      id,
      name,
      homeworld {
        id
      }
    }
  }
}
```

and this is the error
```
mutation {
  createHero(input:{name:"Test", planet:"Test" }){
    hero {
      id,
      name,
      homeworld {
        id
      }
    }
  }
}
```

**Comment by BossGrand** [comment]
I see another error

    class Mutation(graphene.ObjectType):
        create_hero = graphene.Field(CreateHero)

should be 
    
    class Mutation(graphene.ObjectType):
        create_hero = CreateHero.Field()

**Comment by syrusakbary** [comment]
The example that @BossGrand provided should solve the issue.
Also, I improved the mutation docs so I will close this issue.

Feel free to reopen if something is not clear!

**Comment by keepexploring** [comment]
Hi, I'm struggling to be able to get the mutations working. I set up the project and the query's work fine, but when I post in GraphiQl:

mutation {
  createHero(input:{name:"Test", planet:"Test" }){
    hero {
      id,
      name,
      homeworld {
        id
      }
    }
  }
}

I get the following response:

{
  "errors": [
    {
      "message": "Unknown argument \"input\" on field \"createHero\" of type \"Mutation\".",
      "locations": [
        {
          "line": 2,
          "column": 14
        }
      ]
    },
    {
      "message": "Field \"createHero\" argument \"name\" of type \"String!\" is required but not provided.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "message": "Field \"createHero\" argument \"homeworldId\" of type \"String!\" is required but not provided.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}

I modified the mutation code as suggested above.

even if I use the online demo, it does not seem to work:
http://swapi.graphene-python.org/graphql?query=mutation%20%7B%0A%20%20createHero(input%3A%7Bname%3A%22Test%22%2C%20planet%3A%22Test%22%20%7D)%7B%0A%20%20%20%20hero%20%7B%0A%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20name%2C%0A%20%20%20%20%20%20homeworld%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=undefined

What am I doing wrong? I'm sure there must be a simple solution to this!

Thanks so much!
