### ISSUE TITLE
Deploying graphene on AWS Lambda + API Gateway

### ISSUE THREAD

**Issue by pedroabi** [graphql-python/graphene#420]
I am trying to use graphene with AWS Lambda + API Gateway. Does anyone has a code snippet showing how to handle the graphQL payload and response?

**Comment by yfilali** [comment]
I've used Zappa pretty successfully with flask + graphene + lambda. Zappa sets out api gateway routes for you and is a snap to get up and running from a flask application: https://github.com/Miserlou/Zappa

Shameless plug: there is also a [pynamodb](https://github.com/yfilali/graphql-pynamodb) implementation for graphene in case you need to use dynamodb.

**Comment by pedrorjbr** [comment]
Hey. Why do you need flask to run it on Aws Lambda + API gateway?

I thought you just need to use graphene + API gateway + Aws lambda

**Comment by jkimbo** [comment]
Hi @pedroabi . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by uprego** [comment]
I got here looking for a simplest tutorial on deploying Graphene for Python to AWS Lambda to be used via AWS API Gateway **without** (if possible) adding Zappa.

The product is relatively small and the use case is kind of niche and (probably) unable to grow too large, so if there is no boilerplate or convenient demo, I'm going to be tempted into not using Graphene... and I don't like that.

**Comment by yfilali** [comment]
@uprego: packaging your application to run on AWS Lambdas has nothing to do with graphene. Graphene provides the graphql part of your backend, not the web application which would be provided by Flask/Django, etc.

Zappa is just one utility that helps you package your whole backend application for AWS API Gateway/Lambda, nothing prevents you from doing the same manually, but that is not graphene related. Using zappa for your project will take you about 5 minutes and 2-3 commands on the command line, so I highly recommend reading the getting started there: https://github.com/Miserlou/Zappa#basic-usage

**Comment by uprego** [comment]
Things have pivoted aggressively so I'm not trying it before several months from now, but I am now more confident [the basic example](https://github.com/graphql-python/graphene/tree/8bf937d1ff5a8dd24d0ed87464863092c8d23b49#examples) is probably going to be enough for me.

> Zappa is just one utility that helps you package your whole backend application for AWS API Gateway/Lambda, nothing prevents you from doing the same manually, but that is not graphene related. Using zappa for your project will take you about 5 minutes and 2-3 commands on the command line, so I highly recommend reading the getting started there: https://github.com/Miserlou/Zappa#basic-usage

I appreciate your zeal, but I really think Zappa is sadly still very young for me to be considered as a good generic pipeline for AWS Lambda deployment (sources [this](https://github.com/miserlou/zappa#initial-deployments), [this](https://github.com/Miserlou/lambda-packages/tree/master/lambda_packages), [this](https://github.com/Miserlou/lambda-packages/issues/71) and [this](https://github.com/Miserlou/lambda-packages/issues/72), among others relating to proprietary software), by the way without needing Zappa I can already upload new code to AWS Lambda in one step, whenever no new dependency is required (sadly I've had to become knowledgeable in the arts of generating dependencies ready for the AWS Lambda runtimes Python 2 and 3).

Sorry for the noise and keep up the good stuff.
