### ISSUE TITLE
Tracing errors is hard

### ISSUE THREAD

**Issue by mleonard87** [graphql-python/graphene#422]
Tracing errors can be incredibly difficult as graphene collects the error messages and returns them. This is great for production but not during development. For example, I get the following back from a query and have no idea what is causing the error:

```
{
  "errors": [
    {
      "message": "'unicode' object has no attribute 'get'"
    }
  ],
  "data": {
    "users": null
  }
}
```

Would it be possible to include some sort of debug flag that can raise exceptions with stacktraces on error?

**Comment by mleonard87** [comment]
I believe I've raised this in the wrong place it should be in Flask-graphql. Apollogies.

**Comment by TimOrme** [comment]
@mleonard87  Did you ever find a way to do this in flask-graphql? Having the same issue

**Comment by ekampf** [comment]
@mleonard87 `graphene` generate the response json not `Flask`.  It collect said errors as part of its execution...  should probably improve it and add trace etc

**Comment by reverie** [comment]
The discussion at https://github.com/graphql-python/graphql-core/issues/237 might be helpful
