### ISSUE TITLE
GraphQL and Sanic  integration

### ISSUE THREAD

**Issue by grazor** [graphql-python/graphene#424]
Hi @syrusakbary!

You might've heard about [Sanic](https://github.com/channelcat/sanic) web framework that utilizes new eventloop functionality on top of high perfomant uvloop and mimics Flask's API. It seems to be really interesting and promising project so far, even though it's in the pre-alfa status.

Thus, I've implemented [Sanic-GraphQL](https://github.com/grazor/sanic-graphql) bindings basing on the [Flask-GraphQL](https://github.com/graphql-python/flask-graphql) project. I'm certain that it's already stable enough to use and I'm going to keep it up to date in future. However, I believe that it would be better to transfer this project to the graphql-python organization in order to make it easier to discover.

I've tried to make my fork as legally correct as possible, although I don't really care much about my copyrights here and I can transfer this project to you and allow you publish it under your own name if you want.

**Comment by syrusakbary** [comment]
Great work @grazor!

I've created a repo in the organization: [sanic-graphql](https://github.com/graphql-python/sanic-graphql), you should have received an email from Github to join the organization and also have write perms on the repo.

:)

**Comment by grazor** [comment]
Thanks, @syrusakbary!

I've finished transfering sanic-graphql to the organization. Could you please enable Travis Ci and Coveralls for this repo?

**Comment by syrusakbary** [comment]
Done! Also, if you can add me perms to the PyPI package (https://pypi.python.org/pypi/Sanic-GraphQL) would be great, so I can automate the package submission to PyPI once a new tag is pushed to the git repo :)

My PyPI username: syrusakbary

**Comment by grazor** [comment]
@syrusakbary, done as well!

**Comment by syrusakbary** [comment]
Closing issue as we already have a repo for GraphQL in Sanic! :)
