### ISSUE TITLE
Adding default_resolver broke graphene-django

### ISSUE THREAD

**Issue by abdulhaq-e** [graphql-python/graphene#425]
Commit 98825fa4bc0f2fd6f88d11796b1093e0d63a51ee added a default_resolver for objecttypes, this broke `graphene-django`. Found it after hours of debugging ^_^

Now in `graphene-django` errors appear such as `Options has no attribute 'registry'` because the new `options` doesn't take into account the `_meta` key passed in the attributes.

**Comment by syrusakbary** [comment]
Great catch! Will push a fix soon :)
