### ISSUE TITLE
Is there a convenient way to override or extend PageInfo?

### ISSUE THREAD

**Issue by yen223** [graphql-python/graphene#426]
`Connection` objects implicitly implement a `PageInfo` object. Is there any way to extend this object?

**Comment by rhoog** [comment]
I would like this functionality as well. I need a more traditional pagination approach using pages instead of cursors (which is not difficult to implement) and I also want to store the current pagenumber in pageInfo (which I have not managed)

**Comment by vivekdurai** [comment]
See @ekampf code in #307

**Comment by jkimbo** [comment]
Implementing a custom `PageInfo` object is possible using something like the code in https://github.com/graphql-python/graphene/issues/307#issuecomment-250881176
