### ISSUE TITLE
Fixing ObjectType special types caused new errors in graphene-django

### ISSUE THREAD

**Issue by abdulhaq-e** [graphql-python/graphene#432]
See @Tchol comment at: https://github.com/graphql-python/graphene/commit/ad251e9a8dd46d212e39da67945df4fc3e02b361#commitcomment-21088472

I have fixed it in a rather obscure way because I have not studied the library code well enough:

```python
        _meta = attrs.pop('_meta', None)
        if _meta:
            options = _meta
            added_options = {
                'name': name,
                'description': trim_docstring(attrs.get('__doc__')),
                'interfaces': (),
                'default_resolver': None,
                'local_fields': OrderedDict()
            }
            if attrs.get('Meta'):
                added_options.update(attrs.pop('Meta'))
            for key, val in added_options.items():
                if not hasattr(options, key):
                    setattr(options, key, val)
        else:
            options = Options(
                attrs.pop('Meta', None),
                name=name,
                description=trim_docstring(attrs.get('__doc__')),
                interfaces=(),
                default_resolver=None,
                local_fields=OrderedDict(),
            )
```

If this is good enough for now I can submit a PR.

**Comment by Tchol** [comment]
You can fix this one in many ways.
I think the simplest fix would be to add the following :
```python
cls = ObjectTypeMeta.__new__(cls, name, bases, dict(attrs, _meta=options))
options = cls.options # <- this
```
in [graphene-django.types l#86](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/types.py#L86)

or by calling `extend_with_meta` on either `_meta` from graphene.objecttypes or `options` from graphene-django.types.

Haven't tried it yet though.

I am not really sure what was intended with this implementation in the first place but it feels that both fixes are somewhat wacky patterns.
