### ISSUE TITLE
Protobuf Enum scalar

### ISSUE THREAD

**Issue by janhancic** [graphql-python/graphene#433]
I was trying to make a custom scalar that would act as a value that maps to some protobuf defined enum, but I can't seem to do that since all the functions defined on the `Scalar` are static, which means I can't do this:

```
class Bob(graphene.ObjectType):
    my_field = ProtoEnum(my_pb2.MyEnum)
```

Where `ProtoEnum` would be my scalar that would take the proto enum as an argument so I could then validate the values inside the `parse_literal` for example.

Right now I'm just defining fields that map to protobuf enums as `graphene.Int()`s, but I'd like to have some checks in place.

Is there any way to do what I want?

**Comment by syrusakbary** [comment]
Hi @janhancic,

It might be a good idea to create a  converter from the ProtobufEnum to the graphene Enum.

Something like this will probably work:

```python
def pb2enum_to_graphene_enum(pb2_enum):
    desc = pb2_enum.DESCRIPTOR
    return graphene.Enum(desc.name, desc.values_by_name)

MyEnum = convert_pb2enum_to_graphene_enum(my_pb2.MyEnum)
```

And then use it like:
```python
class Bob(graphene.ObjectType):
    my_field = MyEnum()
```

Hope this helps!

**Comment by janhancic** [comment]
Hi @syrusakbary thanks, but this is exactly what I wanted to avoid.

I'm using protos on the FE too, so want to keep the link as direct as possible. This also seems like code duplication basically.

Is there any reason we couldn't have the serialize&co functions be instance functions? That would allow me to do what I want, and as far as I can see everything else would continue to function just fine?

**Comment by janhancic** [comment]
Hey @syrusakbary sorry to bother but have toy got any new info on this?

**Comment by syrusakbary** [comment]
The way I would recommend is actually creating a `GraphQL` enum type, as is more powerful, semantic and takes the advantage of GraphQL enums that clients might find useful.

However, re-reading the issue, it seems is not actually the desired behavior.

You can achieve something similar by creating a new field type, and mapping from the protobuf to a `Int`.

```python
from functools import partial

class ProtoEnum(graphene.Field):
    def __init__(self, protobuf_enum, *args, **kwargs):
        self.protobuf_enum = protobuf_enum
        super(ProtoEnum, self).__init__(graphene.Int, *args, **kwargs)

    def resolver(self, parent_resolver, root, args, context, info):
        resolved_value = parent_resolver(root, args, context, info)
        # We check is a valid value in the protobuf enum
        # This might be not actually the way to check, but serves the concept!
        assert resolved_value in self.protobuf_enum
        return resolved_value

    def get_resolver(self, parent_resolver):
        return partial(self.resolver, parent_resolver)
```

Again, I think the cleaner and best way to achieve this would be using a `graphene.Enum` (as it maps to a GraphQL enum), and could be used not only in output fields, but also in input arguments.

**Comment by janhancic** [comment]
Sweet, I haven't thought about using a Field to do this. Thanks, I'll give it a spin after the holidays. Cheers!

**Comment by janhancic** [comment]
Finally got some time to try this out. I had to modify your code a bit (`resolver` method was being overridden by `Field` in it's init, and you can't use `partial` on class methods), but in general it works exactly as I wanted.

For anyone reading this in the future, this is what I ended up doing:

```python
from functools import partial

import third_party.python3.graphene as graphene


class ProtoEnum(graphene.Field):
    """Provides a link between protobuf enums and GraphQL fields"""

    def __init__(self, protobuf_enum, *args, **kwargs):
        super(ProtoEnum, self).__init__(graphene.Int, *args, **kwargs)
        self.protobuf_enum = protobuf_enum

    def get_resolver(self, parent_resolver):
        return partial(_enum_resolver, self.protobuf_enum, parent_resolver)


def _enum_resolver(protobuf_enum, parent_resolver, root, args, context, info):
    resolved_value = parent_resolver(root, args, context, info)

    if resolved_value not in protobuf_enum.values():
        raise ValueError('Enum value "%s" is invalid' % resolved_value)

    return resolved_value
```

So thank you very much for the help!

**Comment by syrusakbary** [comment]
Thanks for including a working example!
Closing the issue :)
