### ISSUE TITLE
Graphene 1.2.0 breaks relay.Node.Field(CustomRelayNode)

### ISSUE THREAD

**Issue by blakegong** [graphql-python/graphene#437]
Hi,

The following line works in `1.1.3` but not in `1.2.0`:

```python
custom_relay_field = relay.Node.Field(CustomRelayNode)
```

It is wrapped inside my `Viewer` field as:

```python
class Viewer(ObjectType):
    class Meta:
        name = 'Viewer'
        interfaces = (relay.Node,)

    custom_relay_field = relay.Node.Field(CustomRelayNode)
```

It gives the correct introspection query result in `1.1.3` and `1.2.0`, which is:

`customRelayField(id: ID!): CustomRelayNode`

But executing a query in `1.2.0` like:
```
{
  viewer {
    customRelayField(id: "valid_id_here") {
      xxx
    }
  }
}
```

Would result in:
```
{
  "errors": [
    {
      "message": "Must receive an CustomRelayNode id.",
      "locations": [
        {
          "column": 5,
          "line": 3
        }
      ]
    }
  ],
  "data": {
    "viewer": {
      "customRelayField": null
    }
  }
}
```

In `1.1.3`, the above query would give the correct result.

May I know is it intentional or is it broken? Should I go for custom `resolver` for `Relay` nodes in the future or stick with my current code?

Thanks!

**Comment by blakegong** [comment]
For now I have modified `customRelayField = relay.Node.Field(CustomRelayNode)` to:

```python
custom_relay_field = graphene.Field(CustomRelayNode, id=graphene.NonNull(graphene.ID))

def resolve_custom_relay_field(self, args, context, info):
    return relay.Node.get_node_from_global_id(args.get('id'), context, info)
```

This is for now the workaround I am using, and is working fine. But the problem remains.

**Comment by syrusakbary** [comment]
Hi @blakegong,

It seems this is a bug. Could you create a PR with a test case that helps to reproduce it, so I might be able to fix it quicker?

**Comment by blakegong** [comment]
Hi @syrusakbary ,

Sure. Will prepare one and let you know again :)

**Comment by blakegong** [comment]
This issue happened on my company repo. Was not able to connect during weekends.

Will try to extract a minimal reproduction code and come back here in a day or two ;)

**Comment by syrusakbary** [comment]
Ok!

**Comment by blakegong** [comment]
Well... I tried all the ways I could think of to reproduce this issue by using only package `graphene` itself, but could not get the same error output. Then I tried to reproduce this issue in the big company repo (I was questioning myself whether this is a real issue after failing so many times to reproduce it), and indeed it was there.

I guess I will set up a minimal Django project to demo it (the same as the company repo), hopefully you could kindly help to debug on that! Thanks!

**Comment by blakegong** [comment]
Hi @syrusakbary,

Please take a look at [this repo](https://github.com/blakegong/graphene-issues-437) if possible. The actual code written by myself in this project is less than 100 lines, just to get everything set up and going. 

I have written a brief `README` over there and should help to get the project up and running. Please let me know if anything else is needed.

Apologies for the long delay and this unusual way to report the bug... Hope you would understand :)

Thanks!

**Comment by syrusakbary** [comment]
Will take a look soon! Thanks for reporting the issue and creating the repo :)

**Comment by blakegong** [comment]
Thank you @syrusakbary! 👍
