### ISSUE TITLE
How to lazy_import relay Node Connection / Edge?

### ISSUE THREAD

**Issue by blakegong** [graphql-python/graphene#438]
I am trying to port the following line (in ClientIDMutation) into using `lazy_import`:

```python
edge = graphene.Field(lambda: import_module('some_package.schema.nodes').Event.Connection.Edge)
```

I have tried:
```python
edge = graphene.Field(lazy_import('some_package.schema.nodes.Event.Connection.Edge'))
# and
edge = graphene.Field(lazy_import('some_package.schema.nodes.Event'.Connection.Edge))
```

The first does not work. `lazy_import` uses `dotted_path.rsplit('.', 1)` which cannot recognise this kind of deeply nested class. It throws `ImportError: No module named Event.Connection`

The second does not work either, throwing `AttributeError: 'functools.partial' object has no attribute 'Connection'`

Is there a recommended way to write this using `lazy_import`? Or maybe I should be writing my `ClientIDMutation` in another way?

Thanks!

**Comment by blakegong** [comment]
The suggestion I could give is... when doing `module_path, class_name = dotted_path.rsplit('.', 1)`, if `class_name == Edge` or `class_name == Connection`, recursively going deeper into the upper path to resolve the class.

Or maybe just always try all the combination of `module_path` and `class_name`, if certain layer can be imported correctly, just return. e.g.:

```python
# function call:
lazy_import('some_package.schema.nodes.Event.Connection.Edge')

# imports to be tried (module_path, class_name_with_attributes):
some_package.schema.nodes.Event.Connection        Edge
some_package.schema.nodes.Event        Connection.Edge
some_package.schema.nodes        Event.Connection.Edge
some_package.schema        nodes.Event.Connection.Edge
some_package        schema.nodes.Event.Connection.Edge
```

If you think this is good, I can write a PR for this.

**Comment by syrusakbary** [comment]
Hey @blakegong,

I think improving lazy_import to accept a extra argument as inner attr might be a more robust solution.
Something like:

```python
lazy_import('some_package.schema.nodes.Event', 'Connection.Edge')
```

Thoughts?

**Comment by blakegong** [comment]
Hi @syrusakbary ,

Looks good! Yours is more definitive and can be easily implemented. Should lead to less bugs in production compared to the API I was proposing.

**Comment by syrusakbary** [comment]
Great! If you wanna create a PR I will happily review it and merge 🔥
