### ISSUE TITLE
Filtering at several levels in the query

### ISSUE THREAD

**Issue by camd** [graphql-python/graphene#445]
I want to write a query where I filter at several levels to get the exact data I'm looking for.  I have a Django structure of ``Pushes`` - oneToMany-> ``Jobs`` - oneToMany -> ``JobDetails``.

The problem is that, at each level, I'm getting ALL the entries in the DB that match the query.  They're not filtered down to only the ones owned by the parent object.  For instance:  For each ``Job`` I get all the ``JobDetails`` in the DB (not just the details for that job) and then the next job repeats all the ``JobDetails`` again.  It IS honoring the filtering I set (only details with url ending in "errorsummary.log") however.

Am I doing something wrong?  Or is this not yet supported?  

My query looks like this:

    query {
      allPushes(revision: "1ef73669e8fccac35b650ff81df1b575a39a0fd5") {
        edges {
          node {
            revision
            author
            jobs (result: "testfailed") {
              edges {
                node {
                  result
                  jobDetails (url_Iendswith: "errorsummary.log") {
                    edges {
                      node {
                        url
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

I have my nodes setup as:

    class JobDetailNode(DjangoObjectType):
        class Meta:
            model = JobDetail
            filter_fields = {
                'url': ('exact', 'icontains', 'iendswith')
            }
            interfaces = (relay.Node, )
    
    
    class JobNode(DjangoObjectType):
        class Meta:
            model = Job
            filter_fields = ('result', 'tier')
            interfaces = (relay.Node, )
    
        job_details = DjangoFilterConnectionField(JobDetailNode)
    
    
    class PushNode(DjangoObjectType):
        class Meta:
            model = Push
            filter_fields = ('revision', )
            interfaces = (relay.Node, )
    
        jobs = DjangoFilterConnectionField(JobNode)

and my Query setup as:

    class Query(ObjectType):
        push = relay.Node.Field(PushNode)
        all_pushes = DjangoFilterConnectionField(PushNode)
    
        job = relay.Node.Field(JobNode)
        all_jobs = DjangoFilterConnectionField(JobNode)
    
        job_detail = relay.Node.Field(JobDetailNode)
        all_job_details = DjangoFilterConnectionField(JobDetailNode)
    
        def resolve_all_pushes(self, args, context, info):
            return Push.objects.filter(**args)
    
        def resolve_all_jobs(self, args, context, info):
            return Job.objects.filter(**args)
    
        def resolve_all_job_details(self, args, context, info):
            return JobDetail.objects.filter(**args)

**Comment by blakegong** [comment]
Well that is a bit wrong indeed...

Take your `Job` resolver for example, `Job.objects.filter(**args)` approximately equates to `Job.objects.all().filter(**args)`. And that is why you are not getting only *children* `Job`s.

Instead you should be putting each *children* resolver inside its *parent* node, and doing something like:

```python
class PushNode(DjangoObjectType):
    class Meta:
        model = Push
        filter_fields = ('revision', )
        interfaces = (relay.Node, )

    jobs = DjangoFilterConnectionField(JobNode)

    def resolve_jobs(self, args, context, info):
        Job.objects.filter(push=self).filter(**args)
```

And of course, remove all the unnecessary `all_*` queries from your root `Query` class.

The above code might not work, but should be enough for demonstration purposes ;)

**Comment by camd** [comment]
Thank you!!  This got me going here.  I hadn't realized I should add resolvers into the Nodes.  I somehow missed that, but makes perfect sense now that I think about it.

Your code was near perfect, but just needed a return in the resolver:

    def resolve_jobs(self, args, context, info):
        return Job.objects.filter(push=self, **args)

**Comment by alfredrumss** [comment]
@blakegong @camd 

how to handle when you have filters in a class level [filterset_class](https://docs.graphene-python.org/projects/django/en/latest/filtering/#custom-filtersets) in the Queries.

I need to get what the filters are returning previously. I haven't figured it out how to fetch in resolve methods what the filters have filtered before.

Any idea?

**Comment by Jacu93** [comment]
@alfredrumss 
Probably you solved it out by yourself but in case someone is looking for an answer in the future I will leave my comment. I'm not sure if this is the correct approach but let's say you have `JobDetailFilter` as `filterset_class` for `JobDetail`.

In that case your `JobNode` would look like this:
```
class JobNode(DjangoObjectType):
    class Meta:
        model = Job
        interfaces = (relay.Node, )

    job_details = DjangoFilterConnectionField(JobDetailNode, filterset_class=JobDetailFilter)
    
    def resolve_job_details(self, args, context, info):
        JobDetailFilter(**args, queryset=JobDetail.objects.filter(Job=self)).qs
```

As you can see there is a possibility to pass predefined queryset as `__init__` argument.
