### ISSUE TITLE
MiddleWare does not have enough information for authorization decisions

### ISSUE THREAD

**Issue by jwfehr** [graphql-python/graphene#447]
Hi,

I am using the middleware feature to implement user permissions. I authenticate the user and then pass their permissions into graphql via the context. I then added a middleware called userPermissions(). In my userPermissions() class I check the desired operation against their permissions and return an error if they do not have permissions. However it should be possible to call next if they have the permissions and return none otherwise. This is not the case because of what I will describe below:

`schema:
query
{
    a: user(id: '100')
    {
        name
        email
    }
    b: user(id: '200')
    {
         name
         email
     }
}`

In this case my middleware gets called 6 times. once with field user arg 100, once with field user arg 200, twice with name and twice with email. Now lets suppose the my user has permissions to query id 100 but NOT 200. I can reject user id: 200 (and this also blocks the name and email requests that correspond) but what I can't do is tell whether or not the field name applies to the query for user 100 or user 200. because of this I have to have the default scenario be that my user permissions rejects only the things its looking for (otherwise the valid request would fail ex. when it asks for name), this is not secure for obvious reasons.
It should be possible to determine which query a given field belongs to make better decisions.

**Comment by TomRaz** [comment]
+1

**Comment by jkimbo** [comment]
Hi @jwfehr . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
