### ISSUE TITLE
No way to use the graphql schema language

### ISSUE THREAD

**Issue by JohnEmhoff** [graphql-python/graphene#448]
Am I missing something, or is there no way to take advantage of the handy graphql schema definition language? It would be great to be able to use the schema language in the same way the javascript implementation does (with `buildschema`, I think).

**Comment by samirbr** [comment]
There is a way, but not in Graphene.

```
import graphql
source = open('/path/to/graphql/schema/file')
ast = graphql.parse(source.read())
source.close()
schema = graphql.build_ast_schema(ast)

def resolve_users(args, context, info):
      // do something
      

resolvers = {
      'users': resolve_users
}
```
Then, in theory you can use `graphql(schema, root_value=resolvers)` to execute. 

I tested parse the schema file to graphql schema, but not execute with my own resolvers yet.

**Comment by jasonphillips** [comment]
I made a minimal example here:

https://gist.github.com/jasonphillips/d80642fc33d98cb34bad131adfcf6ed8

which could be further expanded, but covers the basics (simple resolvers).

**Comment by mplis** [comment]
@jasonphillips that is awesome! I would love for something like this to be included in graphene or installable from another package.

**Comment by tarekrached** [comment]
Would this approach also enable the output of the graphql schema language definition from an instance of `graphene.Schema`, or should I open a new issue to discuss that?

**Comment by tarekrached** [comment]
nm, can do this already with
```python
from graphql.utils import schema_printer
schema_printer.print_schema(schema)
```

**Comment by tarekrached** [comment]
...and even that's unnecessary, as the `__str__` method of `graphene.Schema` [already does this](https://github.com/graphql-python/graphene/blob/0971a05b33bf65cbc89038eebd85de5fec4e1dcf/graphene/types/schema.py#L105-L106).

**Comment by dutradda** [comment]
There's a issue about that on https://github.com/graphql-python/graphql-core?

Because I want to implement a PR on [graphql-core](https://github.com/graphql-python/graphql-core) based on the @jasonphillips code

**Comment by x0y-gt** [comment]
I think that using this new library solves the problem: 
https://graphql-core-next.readthedocs.io/en/latest/usage/sdl.html
