### ISSUE TITLE
Example for InputObject type

### ISSUE THREAD

**Issue by millerjs** [graphql-python/graphene#45]
It seems that there is support for the InputObject type defined in the spec, however, none of the examples cover its usage as an argument.  Is this supported? If so, is it possible to add an example?

**Comment by syrusakbary** [comment]
Hi @millerjs!

I've just added an example of how to use InputObjectType. Let me know if any questions.

**Comment by millerjs** [comment]
Thanks! Your example is as expected, however when I plug it in to a more complex schema, I get a `TypeError: Cannot read property 'types' of undefined` from graphiql.  The example is helpful though, thanks!

**Comment by syrusakbary** [comment]
@millerjs open an issue with a example that replicates the error (query and maybe the some similar ObjectTypes used in the query) so I can take a look into it! (the more info I have the better for fixing it!)

**Comment by millerjs** [comment]
Will do, I figure it's just a misuse on my part.  If it turns out not to be, I'll open that issue.

**Comment by millerjs** [comment]
The reason it did not work for me is because the class was defined in a function local scope (I'm generating ObjectTypes classes at runtime).

**Comment by syrusakbary** [comment]
You have a detailed log where this error was triggering? (file, line)
Could be very useful for adding more feedback to the developer in future cases by raising a custom detailed exception :)
