### ISSUE TITLE
Input args and documentation

### ISSUE THREAD

**Issue by khankuan** [graphql-python/graphene#450]
Hi,

I'm trying to understand how take in arguments for fields but could not find it in documentation.

Also, the playground here seems to be broken as well: http://graphene-python.org/playground/

**Comment by JohnEmhoff** [comment]
I just ran into this myself. After some source-diving and doc perusing I've more or less discovered how it works: the query must be in "long form" where it starts with `query` followed by an operation name and typed argument list. As far as I can tell this operation name is completely arbitrary (someone please correct me if I'm wrong).

``` 
query someMadeUpString(thingId: String!) 
{ 
  getById(id: $thingId) { someField someOtherField }
} 
```

You can then provide a binding to `thingId` by passing it in under `variable_values` to `.execute`:
```
schema.execute(query_string, variable_values=dict(thingId="123"))
```

**Comment by khankuan** [comment]
@JohnEmhoff finally found what i was looking for. It is:
```
class Query(ObjectType):
    thing_by_id = graphene.Field(ThingType, id=graphene.String())
    def resolve_thing_by_id(self, args, context, info):
        print(args['id'])
```

```
query {
  thing_by_id (id: "1") {
  }
}
```

**Comment by syrusakbary** [comment]
@khankuan I think would be a great addition into the docs, if you want to open a PR with a new section documenting the input args I will happily merge it! :)
