### ISSUE TITLE
why i can't debug?

### ISSUE THREAD

**Issue by fangaofeng** [graphql-python/graphene#451]
this is my code 
```python
class Query(graphene.ObjectType):
    all_expresscompany = graphene.List(ExpressCompanyType)
    expresscompany = graphene.List(ExpressCompanyType)

    def resolve_expresscompany(self, args, context, info):
        i =1+1                                                         # test   break point 
        return ExpressCompanyModel.query.all()  # SQLAlchemy query   break point 
        

    def resolve_all_expresscompany(self, args, context, info):
        
        return ExpressCompanyModel.getcompanyall()  # SQLAlchemy query
```
It can work ，but when i debug，set break point in resolve_expresscompany function. Never stop.

**Comment by syrusakbary** [comment]
Hi @fangaofeng,

The code seems right, what is the query you are making?

**Comment by fangaofeng** [comment]
@syrusakbary i query express all filed. It can work and query result is right, except nod debug.
other code:
`class ExpressCompanyModel(db.Model):
    __tablename__ = "express_company"
    id = db.Column(
        db.Integer, primary_key=True, nullable=False, autoincrement=True)
    name = db.Column(db.String(20), nullable=False)
    num_courier = db.Column(db.Integer, default=0, nullable=False)

    def __init__(self, name):
        self.name = name
class ExpressCompanyType(SQLAlchemyObjectType):
    class Meta:
        model = ExpressCompanyModel

schema = graphene.Schema(query=Query)`

**Comment by syrusakbary** [comment]
If the code is executed properly, I'm not sure why you can't set a break point.

Two things that might help to debug:
* Are you using a custom GraphQL executor?
* What debugging tool are you using?

**Comment by fangaofeng** [comment]
I use flask_GraphQL . 
```
app.add_url_rule(
    '/graphql',
    view_func=GraphQLView.as_view('graphql', schema=schema.schema, graphiql=True))
```
debugging tool is vscode  1.9 and python plugin. 
I try eclipse pydev,thank you replay.

**Comment by fangaofeng** [comment]
i test by eclipse pydev ,it can debug. 
thank you very much.
