### ISSUE TITLE
Self-referential unions

### ISSUE THREAD

**Issue by adamdonahue** [graphql-python/graphene#453]
Is there a way to define self-referential unions?

I have a polymorphic type that can contain instances of itself (think of a filesystem, with a folder file being able to contain other files of various types).

So we have something like:

```python
class FolderType(ObjectType):
    files = graphene.List(FileUnionType)
        
    def resolve_files(...):
     
class FileUnionType(graphene.Union):
    @classmethod
    def resolve_type(cls, ...):
        ...

    class Meta:
        types = [..., FolderType, ...]
```

These require each other at class creation time, so I'm wondering if there's a deferral hook in there somewhere, or a way to "reopen" the FolderType class and define its `files` attribute once `FileUnionType` is created.

Thanks.

**Comment by adamdonahue** [comment]
Just found out that a `lambda` works.  Closing.

**Comment by taffit** [comment]
For all the poor souls (like myself) coming here in search for a solution to the problem: What @adamdonahue ment and what seems to work fine is something like this:
```python
class FolderType(ObjectType):
    files = graphene.List(lambda: FileUnionType)
        
    def resolve_files(...):
     
class FileUnionType(graphene.Union):
    @classmethod
    def resolve_type(cls, ...):
        ...

    class Meta:
        types = [..., FolderType, ...]
```
I was lost and had to experiment in order to figure this out. So I just want to save someone some minutes of fiddling.
