### ISSUE TITLE
Implement "Relay Modern" features

### ISSUE THREAD

**Issue by superquest** [graphql-python/graphene#454]
(I've never used Relay so I'll need some help here)

Facebook just announced [Relay Modern](https://code.facebook.com/posts/1362748677097871/relay-modern-simpler-faster-more-extensible/)

"Static Queries" are a big new feature that Graphene will want to support. From the release:

> The Relay compiler extracts colocated GraphQL snippets from across an app, constructs the necessary queries, saves them on the server ahead of time, and outputs artifacts that the Relay runtime uses to fetch those queries and process their results at runtime.

**Comment by jameswyse** [comment]
Static Queries is also something the Apollo team are working on (see https://github.com/apollographql/persistgraphql) - it'd be great if we could find a common solution!

**Comment by Tritlo** [comment]
What's the status of these in Graphene?

**Comment by ekampf** [comment]
Its not really clear what you want `graphene` to do here.
Relay Modern still makes regular GraphQL calls to the server...   the only thing you can do is know in advance what kind of queries to expect and optimize your resolves accordingly...

**Comment by jkimbo** [comment]
I don't think implementing static (aka persisted) queries is within the scope of the Graphene project since it is tightly coupled to the rest of your application. You would need to define where the persisted queries are stored, how the front end part of your app adds new queries, how your server interprets static queries etc.

Here is a quick pseudo code example of how I imagine it could be setup inside an application:

```python
// Graphql endpoint view
import graphene

from my_graphql_server import schema // your apps schema

def graphql_endpoint(request):
	query_identifier, variables = parse_body(request)

	try:
		// Retrieve a grapqhl.language.ast.Document instance from an identifier
		// so that query doesn't need to be parsed again
		document = get_document_from_identifier(query_identifier)
		return schema.execute(document, variable_values=variables)
	except QueryNotFound:
		return HttpResponse(status=404) 
```

**Comment by syrusakbary** [comment]
As @jkimbo commented, the logic is better when coupled with your API server.

I started the project `graphql-env` to provide an abstraction similar to the pseudocode commented.
https://github.com/graphql-python/graphql-env
