### ISSUE TITLE
Question: large PostgreSQL table as data backend of Graphene 

### ISSUE THREAD

**Issue by frbsfri** [graphql-python/graphene#457]
I want to use graphene in my project,

I have a postgreSQL table with lots of columns (~1000 columns) and here is the schema:

Table log(
  id bigint,
  date date,
  shid integer,
  color character(1),
  hid smallint,
  dz0 smallint,
   ...,
 dz1000 smallint)

How can I write the data model of log table using graphene. Do I have to add each feild manually? or is there anyway to import the schema of the postgreSQL table ? in all the examples i see that the fields are written manually but in my case the table has lots of columns.

I would be thankful if you give me insights on this.

**Comment by syrusakbary** [comment]
Hi,

I recommend you using the [SQLAlchemy automap feature](http://docs.sqlalchemy.org/en/latest/orm/extensions/automap.html).

And then transform the table model to Graphene automatically with [Graphene-SQLAlchemy](https://github.com/graphql-python/graphene-sqlalchemy).

This way you will not need it to do it by hand :)

**Comment by frbsfri** [comment]
Thanks for your reply,

I used SQLalchemy automap in the example of _Graphene-SQLAlchemy_. So I created 3 tables (`Department`, `Roles`, and `Employee`) in postgreSQL. 

 I used SQLAlchemy automap to create the Models:

```
Base = automap_base()
engine = create_engine("postgresql://qfsa:123@localhost:5433/mydb", echo=True)
session = Session(engine)


Base.prepare(engine, reflect=True)
metadata = MetaData()
metadata.reflect(engine, only=['roles','employee','department'])

Base = automap_base(metadata=metadata)
Base.prepare()
DepartmentModel=Base.classes.department
RoleModel=Base.classes.roles
EmployeeModel= Base.classes.employee

```
Then, with Graphene-SQLAlchemy, I have the following code:
```
class Department(SQLAlchemyObjectType):

    class Meta:
        model = DepartmentModel
        interfaces = (relay.Node, )


class Employee(SQLAlchemyObjectType):

    class Meta:
        model = EmployeeModel
        interfaces = (relay.Node, )

class Role(SQLAlchemyObjectType):
    class Meta:
        model = RoleModel
        interfaces = (relay.Node, )
class Query(graphene.ObjectType):
    node = relay.Node.Field()
    all_employees = SQLAlchemyConnectionField(Employee)
    all_roles = SQLAlchemyConnectionField(Role)
    role = graphene.Field(Role)

schema = graphene.Schema(query=Query, types=[Department, Employee, Role])
query = '''
{
  allEmployees {
    edges {
      node {
        id,
        name,
        department{
        id,
        name
        }
        role{
        id,
        name
        }
      }
    }
  }
}'''
result=schema.execute(query,context_value={'session': session})
print(result.data)
```
This gives me `None` as the result.
Can you please tell me what I am doing wrong here?

Thanks :)
