### ISSUE TITLE
Snake case to camel case

### ISSUE THREAD

**Issue by millerjs** [graphql-python/graphene#46]
I didn't find a forced conversion to camelCase in the spec. Did I miss it? Or is graphene just opinionated on style standards.  Will there be any way to opt out of this in the future?

**Comment by jhgg** [comment]
It's convention. Generally you would want to use camel case in javascript world. But graphene keeps things snake cased in Python. If you want to use snake cased fields though you can explicitly specify a name.

**Comment by syrusakbary** [comment]
Hi @millerjs, thanks for asking!
I think path to go will be having *snake_cased* fields converted to *camelCase* by default, but adding the possibility for changing this via some global variable or graphene settings.
Will keep this issue open until graphene adds the ability of not camelCase if defined in settings.

**Comment by syrusakbary** [comment]
Probably adding custom permissions for querying/updating using `django-guardian` is also a good enhancement (and could be required when using automutation models?). Thoughts about that?

**Comment by millerjs** [comment]
:+1: This would be a great feature despite it's unconventionality.

**Comment by syrusakbary** [comment]
@millerjs this is now fixed.
Thanks to a new plugin structure you can even create [some plugin for transform the name](https://github.com/graphql-python/graphene/blob/master/graphene/plugins/camel_case.py) the way you want.

The current usage for disable the auto camelCase is:
```python
schema = graphene.Schema(query=..., auto_camelcase=False)
```

Hope it helps! ;)

**Comment by millerjs** [comment]
Fantastic! thanks @syrusakbary

**Comment by sulabhjain** [comment]
> @millerjs this is now fixed.
> Thanks to a new plugin structure you can even create [some plugin for transform the name](https://github.com/graphql-python/graphene/blob/master/graphene/plugins/camel_case.py) the way you want.
> 
> The current usage for disable the auto camelCase is:
> 
> ```python
> schema = graphene.Schema(query=..., auto_camelcase=False)
> ```
> 
> Hope it helps! ;)

Hi @syrusakbary, I am using this thread for a question related to auto_camelcase, let me know if there is more appropriate forum to addresses this issue.

We are running into a requirement where not all clients of graphql api wants to use camelCase for interacting with the api (eg. non-javascript based internal services). So the question here is, if there is a way to dynamically pass a parameter to graphql api which determines if camelCase to snake_case conversion should happen or not on the server side. If not, is this a requirement on the future roadmap ? Appreciate your help.

**Comment by oxbits** [comment]
defaulting to camel case is not a fair assumption

**Comment by EgorChernik** [comment]
So, it's a cool feature, indeed. In the same time, I noticed that the keys of nested structures aren't been transformed. 
How do you see, if that behavior will appear in graphene?
