### ISSUE TITLE
graphene.List with and without lambda

### ISSUE THREAD

**Issue by ewdicus** [graphql-python/graphene#461]
I noticed that one of the examples shows two different ways of creating a List (lines 16 & 17 [here](https://github.com/graphql-python/graphene/blob/0148401c0694893ef57d6b52a40adae272e6ebd5/examples/starwars/schema.py#L17)):

```python
class Character(graphene.Interface):
    id = graphene.ID()
    name = graphene.String()
    friends = graphene.List(lambda: Character)
    appears_in = graphene.List(Episode)
```

The [documentation](http://docs.graphene-python.org/en/latest/types/list-and-nonnull/#list) shows only without a lambda: 

```python
class Character(graphene.ObjectType):
    appears_in = graphene.List(graphene.String)
```

Are these equivalent? If not when would you use one form or the other?

Thanks!

**Comment by syrusakbary** [comment]
Usually lambdas are used when there is a dependency that only can be resolved lazily.
(for example, a self-reference to the field parent type).

Otherwise, using the non-lambda form is the recommended approach :)
