### ISSUE TITLE
join of data from different data sources in graphene query

### ISSUE THREAD

**Issue by frbsfri** [graphql-python/graphene#464]
I have two data sources , one is `PostgreSQL table` and the other is `CSV file`. I used `SQLAlchemy-graphene` to create the model for postgreSQL and I used `graphene.objectType `for creating the class Model of csvfile.

Now I want to join data from these models. I dont know how can i define the join query. Please guide me. Thanks.

here is my models and schema:

```
class Sheetheight(graphene.ObjectType):
    ullid= graphene.Float()
    id=graphene.ID()
    sheetid=graphene.String()
    passcolum=graphene.Int()

   
class Dzlog(Base):
    ullid=Column(Float)
    id=Column(Integer,primary_key=True)
    date=Column(Date)
    sheetid=Column(Integer)
    passcolumn=Column(Integer)
    color=Column(String)
    headid=Column(Integer)

```

I am able to query each singles classes separately. 

This is how I resolve the query for postgreSQL table:
```
q1= graphene.List(Dzlog)
def resolve_q1(self, args,context,info):
        query=Dzlog.get_query(args).filter(DzlogModel.ullid==49876996433,DzlogModel.sheetid==6394503)
        return query.all()
```

This is how I resolve the query for csv file:
 ```
q4=graphene.List(SheetheightModel)
    def resolve_q4(self, args,context,info):
         with open(csvpath, 'r') as csvfile:
                df= pd.read_csv(csvfile, sep=';' )
                if(df['ullid']==50096853911 and df['sheetid']==6391743):
                        dframe.append(df[i])                       
                return dframe

```
now I want to join them based on the common column which is ullid.  how should I write the new query resolver and model?

**Comment by frbsfri** [comment]
Is anyone there to look at my problem with understanding the join? I am stopped in my project to solve this issue. Please help me.

**Comment by jkimbo** [comment]
Hi @frbsfri . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by autogestion** [comment]
This is still important
