### ISSUE TITLE
row id vs global id

### ISSUE THREAD

**Issue by bochuxt** [graphql-python/graphene#468]
When query all-objects, it overrides the row id which is primary key by global id (ID!) which is a cursor.

But we still need the raw id which is table primary key.

  allAuthUsers{
    edges
    {
      node{
      id
      username
      }
    }
  }

---
"data": {
    "allAuthUsers": {
      "edges": [
        {
          "node": {
            "id": "QXV0aFVzZXI6MQ==",
            "username": "anonymous"
          }
        },

**Comment by bochuxt** [comment]
class Coworker(SQLAlchemyObjectType):

    class Meta:
        model = CoworkerModel
        interfaces = (relay.Node,)
    rowid=graphene.Int()
    @resolve_only_args
    def resolve_rowid(self, **args):
        # print(self.__dict__)
        id = self.__dict__['id']
        return id

**Comment by syrusakbary** [comment]
A similar solution to what @bochuxt pointed would be:
```python
class Coworker(SQLAlchemyObjectType):
    class Meta:
        model = CoworkerModel
        interfaces = (relay.Node,)

    rowid=graphene.Int()

    @resolve_only_args
    def resolve_rowid(self, **args):
        return self.id
```
