### ISSUE TITLE
NameError: name 'AbstractType' is not defined

### ISSUE THREAD

**Issue by phil303** [graphql-python/graphene#472]
I'm getting a kind of weird exception that I can't readily explain when I try to import graphene in a file or the python repl.
```python
>>> import graphene
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/graphene/__init__.py", line 19, in <module>
    from .types import (
  File "/usr/local/lib/python3.4/dist-packages/graphene/types/__init__.py", line 3, in <module>
    from .objecttype import ObjectType
  File "/usr/local/lib/python3.4/dist-packages/graphene/types/objecttype.py", line 7, in <module>
    from .abstracttype import AbstractTypeMeta
  File "/usr/local/lib/python3.4/dist-packages/graphene/types/abstracttype.py", line 40, in <module>
    class AbstractType(six.with_metaclass(AbstractTypeMeta)):
  File "/usr/local/lib/python3.4/dist-packages/graphene/types/abstracttype.py", line 24, in __new__
    if not issubclass(base, AbstractType) and issubclass(type(base), AbstractTypeMeta):
NameError: name 'AbstractType' is not defined
```

I'm not too familar with this usage of `six.with_metaclass` but if it's calling into `__new__` before `AbstractType` is defined then the exception makes sense but searching through the issue tracker, I'm not seeing anyone having the same problem. Any insight on this would be much appreciated.

This is running python 3.4.3 with graphene 1.4.0.

**Comment by phil303** [comment]
I've figured out the issue here. It was a problem with the particular `six` version, 1.6.1 and it's implementation of `with_metaclass`. Upgrading up to 1.10.0 fixes this.

**Comment by sineo** [comment]
I'm currently experiencing the same issue with Graphene and Six. I'm on OSX Yosemite and using Graphene 1.1, Six 1.10.0 with Python 2.7.
Here's the traceback:

/Library/Python/2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
.format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
File “run.py”, line 1, in 
from application import application
File “/Users/mmcartor/Sites/shiphero-api-v1/application.py”, line 29, in 
import shiphero_app.core.database
File “/Users/mmcartor/Sites/shiphero-api-v1/shiphero_app/core/database/init.py”, line 529, in 
import graphene
File “/Library/Python/2.7/site-packages/graphene/init.py”, line 19, in 
from .types import (
File “/Library/Python/2.7/site-packages/graphene/types/init.py”, line 3, in 
from .objecttype import ObjectType
File “/Library/Python/2.7/site-packages/graphene/types/objecttype.py”, line 6, in 
from .abstracttype import AbstractTypeMeta
File “/Library/Python/2.7/site-packages/graphene/types/abstracttype.py”, line 40, in 
class AbstractType(six.with_metaclass(AbstractTypeMeta)):
File “/Library/Python/2.7/site-packages/graphene/types/abstracttype.py”, line 24, in new
if not issubclass(base, AbstractType) and issubclass(type(base), AbstractTypeMeta):
NameError: global name ‘AbstractType’ is not defined

Any help would be greatly appreciated.

**Comment by sineo** [comment]
@phil303 Do you mind re-opening this issue please, as your solution did not work for me.

**Comment by phil303** [comment]
Sure, reopening per @sineo request.

**Comment by syrusakbary** [comment]
@sineo could be possible to have some code that reproduces this issue?
(either a repo or a code snippet would work)

With that I might be able to assist on a quick fix easily.

**Comment by jkimbo** [comment]
Hi @sineo . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
