### ISSUE TITLE
Mutations - batch creation of objects

### ISSUE THREAD

**Issue by quytang** [graphql-python/graphene#473]
I want to use graphene to create many people in one go.
The document only mention the way to create one person like this:

    class CreatePerson(graphene.Mutation):
    class Input:
        name = graphene.String()
        age = graphene.Int()

    ok = graphene.Boolean()
    person = graphene.Field(lambda: Person)

    @staticmethod
    def mutate(root, args, context, info):
        person = Person(name=args.get('name'), age=args.get('age'), mobile=args.get('mobile'))
        ok = True
        return CreatePerson(person=person, ok=ok)

are there any ways to get it done?

I also created [a question on SO](http://stackoverflow.com/questions/44070485/mutations-batch-creation-of-objects)

**Comment by quytang** [comment]
I've just got it done.
Thanks

**Comment by zafaralam** [comment]
> I've just got it done.
> Thanks

Do you mind sharing your solution?
Thank 😊

**Comment by Instrumedley** [comment]
@quytang Would be nice in cases like this to also post the solution for the next ones that find the thread

**Comment by astockwell** [comment]
@Instrumedley this SO answer appears to have the OP's answer: https://stackoverflow.com/questions/44070485/mutations-batch-creation-of-objects
