### ISSUE TITLE
SQLAlchemy and Nested Schema

### ISSUE THREAD

**Issue by ArfatSalman** [graphql-python/graphene#474]
I have two models, User and Deal. 
```python
class User(SQLAlchemyObjectType):

	class Meta:
		model = UserModel	

class Deal(SQLAlchemyObjectType):
	class Meta:
		model = DealModel
```

Now I can query the DB using Graphql. One such query is:
```graphql
query {
	trendingDeals {
		title 
		user {
			name
			location
			deals {
				title 
			}
		}
	}
}
```

I can keep on nesting fields and SQLAlchemy-Graphene will keep on traversing the relationships associated with them. However, I do not want the **user** field of **Deal** model to contain the whole User schema. Instead, only some particular fields. But, if I use `exclude_fields` in the **User** schema, that field is becomes hidden. I want to traverse the said field when the root query is just `users`. Like this - 

This should be valid.
```graphql
{
	user {
		name
		deals {
			title
		}
	}
}
```   
This should not be valid. 

```graphql
query {
	Deals {
		title 
		user {
			name
			location
			deals { # user should not contain the deals field when nested in some other query
				title 
			}
		}
	}
}
```
In essence, how can I give alternate representation of some fields in a model without remapping the whole model to a new schema.
Is there any way?

Thanks.

**Comment by nimish-gupta** [comment]
@ArfatSalman Same here, i want to restrict the fields in the nested query. But how to do? Any Sol?

**Comment by taybin** [comment]
I worked around this by setting up my own resolvers for those fields that used DataLoader to batch the queries together.  Then nested, redundant fields would use the same data, avoiding the N+1 issue.

**Comment by jkimbo** [comment]
This issue looks like it should be raised on [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy)
