### ISSUE TITLE
Apollo Optics Integration

### ISSUE THREAD

**Issue by chaffeqa** [graphql-python/graphene#476]
Apollo just started rolling out optics free teir, and are [offering for different languages](https://dev-blog.apollodata.com/apollo-optics-is-now-free-for-small-projects-c23d70569913).

I will be looking into how possibly to integrate this into our app, but would love any pointers on where to start.

[Relevant documentation](https://github.com/apollographql/optics-agent)

**Comment by syrusakbary** [comment]
Hi @chaffeqa!

I think creating an Optics client for Graphene would be a great move for @apollographql as few more people already asked for that.

The easiest way would be doing the integration using a custom middleware for it.

Curious to know if this in your plans? @helfer @stubailo

**Comment by stubailo** [comment]
Right now we aren't actively working on Graphene integration but we provide advice and support for people working on new agents, for example there is one currently being worked on for Sangria. Looks like you're ahead of the game @chaffeqa, since you've found the correct repository. I'll ping people on Slack to get in touch and pass along any more resources we have!

**Comment by pobed2** [comment]
Hey guys,

Any progress on this? Is there anything I can do to help?

**Comment by chaffeqa** [comment]
none here :( sorry been deep in integrating apollo w next.js 🎉

**Comment by stubailo** [comment]
I'd suggest joining the Apollo slack and messaging me there, we have a channel to help people build agents.

**Comment by ekampf** [comment]
Maybe I'm missing something but it doesn't seem like whats in https://github.com/apollographql/optics-agent should make sense outside the Apollo team...
It would be great if there was a rough "Quickstart" on the guidelines for a new agent...

**Comment by syrusakbary** [comment]
Given the recent interest (here and offline), I'm thinking to create an open-source GraphQL logging tool with an easy integration with Graphene or any other GraphQL framework.
(similar business model as Sentry).

Will some of you be open to pay half of the price as apollo optics while having a similar interface?

**Comment by chaffeqa** [comment]
regardless of what my company says, we will gladly pay for that!

I've honestly been looking for ways to contribute to both graphene and apollo personally, its making huge wins for our company and my personal sanity 😉

**Comment by ekampf** [comment]
@syrusakbary I'd be happy to help build it.

**Comment by stubailo** [comment]
@chaffeqa, I think @martijnwalraven is the person to talk to to help build out an Optics integration! We're dedicated to making sure the pricing works for people at all scales. The new free tier is just the first step, we want to make sure everyone who wants to get insight into their GraphQL API can do that.

We have some ideas also about how we can work towards a more standard way for GraphQL servers to report performance data so you can send data to optics or any other service in an easy way that all servers can support. So if anyone is interested in that let's set up a hangout sometime soon?

**Comment by chaffeqa** [comment]
Great idea!  Count me in.  You can reach me or hangout me at chaffeqa@gmail.com

(east coast... cuz timezones /shrug)

**Comment by martijnwalraven** [comment]
@chaffeqa: Great! I'll ping a few more people and we can try to set up a meeting for next week.

**Comment by ajhyndman** [comment]
I'm interested in helping make a graphene-optics-agent client a reality!

I'll try joining the Apollo slack team to make myself a little more reachable.

**Comment by martijnwalraven** [comment]
@syrusakbary @chaffeqa @ajhyndman: I'm sorry I'm only getting back to you now, but I just published a first description of [Apollo Tracing](https://github.com/apollographql/apollo-tracing), a proposed tracing format for GraphQL that will allow all GraphQL servers to report data to Optics. Would be great to get your feedback and see how we can add support for this to Graphene!

**Comment by ekampf** [comment]
So I'm 99% done integrating Apollo Tracing into Graphene.
The code is actually in `graphql-core` (See https://github.com/graphql-python/graphql-core/pull/148) and `graphql-server-core` where the code middleware doing the tracing and adding the data is (PR today\tomorrow)

**Comment by dvndrsn** [comment]
@ekampf It looks like graphql-python/graphql-core#148 was merged ~15 days ago. Any update on the remaining changes for `graphql-server-core` and `graphene`?

**Comment by ekampf** [comment]
@dvndrsn I kinda stopped working on it waiting for that PR to merge. 
Will try and find time to complete this feature ASAP...

**Comment by dvndrsn** [comment]
Thanks sir! We're pretty excited for this feature, please let us know if there's anything we can do to help!

**Comment by akaone** [comment]
Any news on this ?

**Comment by lmatheus** [comment]
@chaffeqa @ekampf This seems like a great feature to have. Hope you we can have it soon!

**Comment by vanpelt** [comment]
@ekampf I'm eager to hook up Optics.  What can I do to help push this over the finish line?  My company would gladly make a monetary contribution and I can contribute some code if you point me in the right direction.

**Comment by ekampf** [comment]
Sorry I didnt have the time to work on it latelly...  I will try to finish everything and push some code this weekend. 
Will need help testing it :)

I will update here ASAP

**Comment by ekampf** [comment]
Ok so I haven't had time to complete it in the past few days but I'm sharing the work that has already been done.  I hope I'll be able to get to it this week but anyone who wants to help is welcome :)

*graphql-server-core*
https://github.com/ekampf/graphql-server-core/tree/feature/tracing

`TracingMiddleware` is where we implement the collection of the tracing data that we later need to expose somewhere in the `run_http_query` flow...

**Comment by ekampf** [comment]
So this has been a long awaited update...
I have updated https://github.com/ekampf/graphql-server-core/tree/feature/tracing to match the spec (use nanoseconds) and support Python 3.7.

I'm going to do some testing with Apollo to make sure this works this weeks.
However, I think the right place for the `TracingMiddleware` would be `graphql-core` - this way we could also instrument the parsing & validation phases.

So I will do some more testing and then move the code there.

@syrusakbary any thoughts?

**Comment by ekampf** [comment]
@Prince-Leto you dont use it directly but rather call `set_default_backend(GraphQLCoreBackend(tracing=True))` before initializing `GraphQLView`

**Comment by ekampf** [comment]
The reason is its not a pure middleware - it has a middleware part to trace all the resolvers, but it also has part that has to ruin in backend itself to measure parsing and validating the query (before resolvers start to run)

**Comment by helpse** [comment]
> Given the recent interest (here and offline), I'm thinking to create an open-source GraphQL logging tool with an easy integration with Graphene or any other GraphQL framework.
> (similar business model as Sentry).
> 
> Will some of you be open to pay half of the price as apollo optics while having a similar interface?

I'd be happy to contribute! Is there a Slack channel that I could join?

**Comment by ekampf** [comment]
@helpse you can find me at the #graphene channel at the GraphQL slack

**Comment by ezchen92** [comment]
I'd like to get involved in this. What is the status?

**Comment by odero** [comment]
@ekampf any word on this?

**Comment by danieltahara** [comment]
@ekampf did you decide to abandon this?

**Comment by jackton1** [comment]
@ekampf What's the status of this ?

**Comment by shukryzablah** [comment]
Is there some sort of status summary that can be written on what happened with this PR?

**Comment by conao3** [comment]
hi, this issue does not seems to be active but please could you put this on roadmap? (related comment: https://github.com/graphql-python/graphene/pull/1019#pullrequestreview-255370742)

**Comment by pfcodes** [comment]
Bump
