### ISSUE TITLE
Support to map input args to object model

### ISSUE THREAD

**Issue by quytang** [graphql-python/graphene#477]
I find that this style of code is very verbose to map input `args` fields to the model's fields.

```
class CreatePerson(graphene.Mutation):
    class Input:
        name = graphene.String()

    ok = graphene.Boolean()
    person = graphene.Field(lambda: Person)

    @staticmethod
    def mutate(root, args, context, info):
        person = Person(name=args.get('name'))
        ok = True
        return CreatePerson(person=person, ok=ok)
```
It's even worse when `Person` has more fields. 

For example: 

- If Person is a form of `Person(name, age, address, mobile...)`
=> I have to write: `Person(name=args.get('name'), age=args.get('age'), ...)`

I wonder if there are any ways to solve it?

Thanks

**Comment by picturedots** [comment]
You can do something like Person(**args)

**Comment by quytang** [comment]
Yikes, I know it recently! Thanks!
