### ISSUE TITLE
How to test `resolve_XXX` functions of Queries in isolation?

### ISSUE THREAD

**Issue by mbrochh** [graphql-python/graphene#482]
Let's say I have this code:

```
class ProductType(DjangoObjectType):
    class Meta:
        model = models.Product
        interfaces = (CustomNode, )
        exclude_fields = ('tags', )

    image1_thumbnail = graphene.String()

    def resolve_image1_thumbnail(self, args, context, info):
        return self.get_image1_thumbnail()
```

Now I would like to test the resolver function in isolation, so I tried this:

```
class ProductTypeTestCase(TestCase):
    longMessage = True

    def test_resolve_image1_thumbnail(self):
        product = mixer.blend('marketplace.Product')
        instance = schema.ProductType(product)
        res = instance.resolve_image1_thumbnail(None, None, None)
        self.assertEqual(...)
```

It turns out, when I run a graphQL query for real, `self` inside the resolver function is not an instance of `ProductType`, it is an instance of `Product`, instead.

When I just instantiate the `ProductType` manually in my tests and call the resolver function, then `self` is an instance of `ProductType`, as one would expect.

How can I create an instance of `ProductType` in such a way that it is properly initiated and also replaces it's `self` so that my tests work?

**Comment by mbrochh** [comment]
Any insights on this? Should I re-post this issue on the graphene-django repo?

**Comment by ekampf** [comment]
Hey @mbrochh,
My solution to that problem was to define a simple mock Schema for my test and make a real query.
For example:
```
def test_resolve_image1_thumbnail(self):
  p = mixer.blend('marketplace.Product')

  class Query(ObjectType):
    product = Field(ProductType)
    def resolve_product(self, *_):
       return p

  schema = Schema(query=Query)
  result = schema.execute('''
  {
    product {
      image1Thumbnail 
    }
  }
  ''')
  self.assertIsNone(result.errors)

  result_thumbnail = result.data["product"]["image1Thumbnail"]
  self.assertEqual(...)
```

**Comment by ekampf** [comment]
But if you really insist on testing the resolver method directly you can just test it as a method.
Instance method are simply functions who's first param is self so you can do something like:
```
product = mixer.blend('marketplace.Product')
resolver_fn = ProductType.resolve_image1_thumbnail
result = resolver_fn(product, None, None, None)
```
And now when you're in `resolve_image1_thumbnail` the value of `self` will be `mixer.blend('marketplace.Product')`

See sample run:
```
In [1]: class Product(object):
   ...:     def sayHello(self):
   ...:         print("Hello " + self.name)

In [2]: fn = Product.sayHello
In [3]: class Foo(object):
   ...:     def __init__(self):
   ...:         self.name = "Eran"

In [4]: fn(Foo())
Hello Eran

```

**Comment by mbrochh** [comment]
@ekampf I ended up making a real query as well, but wow... I like that other approach a lot more. 8 years of Python an I never knew that you can pass in self like that.

**Comment by mbrochh** [comment]
@ekampf hmmm... I tried it just now like this:

```
def test_resolve_detail_url(self):
        product = mixer.blend('marketplace.Product', published=True)
        func = schema.ProductType.resolve_detail_url
        res = func(product, None, None, None)
        self.assertEqual(res, product.get_detail_url())
```

And I'm getting this:

`TypeError: unbound method resolve_detail_url() must be called with ProductType instance as first argument (got Product instance instead)`

Are you sure that this method works?

**Comment by mbrochh** [comment]
@ekampf AHA! some google-fu taught me, that there is something called `im_func` in Python (which I was never aware of), so this seems to work:

```
def test_resolve_detail_url(self):
        product = mixer.blend('marketplace.Product', published=True)
        res = schema.ProductType.resolve_detail_url.im_func(product, None, None, None)
        self.assertEqual(res, product.get_detail_url())
```
