### ISSUE TITLE
Resolver for a function that returns an Object

### ISSUE THREAD

**Issue by camd** [graphql-python/graphene#483]
I'm trying to write a resolver that returns an object created by a function.  It gets the data from memcached, so there is no actual ``model`` I can tie it to.

I think my main issue is I can't figure out what ``type`` to use and how to set it up.  I'm using this in conjunction with Django, but I don't think it's a django issue (afaict).  Here's my code so far:

    class TextLogErrorGraph(DjangoObjectType):
    
        def bug_suggestions_resolver(root, args, context, info):
            from treeherder.model import error_summary
            return error_summary.bug_suggestions_line(root)
    
        bug_suggestions = graphene.Field(TypeForAnObjectHere, resolver=bug_suggestions_resolver)

Notice I don't know what ``type`` or ``field`` to use.  Can someone help me?  :)

I would be happy to submit a PR for a doc update if someone can help me figure this out!  :)

**Comment by camd** [comment]
I have sort-of a solution to this:

    class TextLogErrorGraph(DjangoObjectType):
        class Meta:
            model = TextLogError
    
        bug_suggestions = graphene.types.json.JSONString()
    
        def resolve_bug_suggestions(self, args, context, info):
            return error_summary.bug_suggestions_line(self)

In this case, it will return a JSON string for the ``bug_suggestions`` value.  I can, then, load that back into an object in the client.  This isn't optimal, but perhaps that's the only way I can return an ``Object`` for this field.  I'm not yet able to find a ``type`` that would just be an ``Object``.

**Comment by camd** [comment]
This worked to get me a normal object returned, rather than a JSON blob.  I created my own field type as such:

    from graphene.types.scalars import Scalar
    
    class ObjectField(Scalar):
    
        @staticmethod
        def serialize(dt):
            return dt
    
        @staticmethod
        def parse_literal(node):
            return node.value
    
        @staticmethod
        def parse_value(value):
            return value

Then I just use this as my type for the ``bug_suggestions`` field like so:

    bug_suggestions = ObjectField()

I understand why this may be considered by some to be "against GraphQL" because you can't specifically specify which parts of ``bug_suggestions`` get returned.  In my case, I don't care.  I want to return the whole thing and not have to specify it in my query.  Perhaps this will help someone sometime.  :)

**Comment by syrusakbary** [comment]
I'm happy that you found a way to solve the issue.
Closing here, but feel free to reopen if you think something is still not clear :)

**Comment by tahakhan0** [comment]
I was looking for something like this all over the place. Thanks for contributing
