### ISSUE TITLE
Setup a graphql endpoint (non-django framework)

### ISSUE THREAD

**Issue by return007** [graphql-python/graphene#484]
I need to create a Graphql endpoint where the relay containers can query to. I know very well that Graphene will help me create a schema (for my data) and execute queries. But how would the relay containers execute their data requirement queries...? 

I also know the fact the using introspection query, I would be able to get the schema in the client side. 
```

Relay.injectNetworkLayer(
    new Relay.DefaultNetworkLayer('http://some-graphql-endpoint-server.com/')
);
```

I am having a python server running (not django). What the current server does is that it exposes some methods over the http. Should I make schema and execute the queries there itself. But then how would graphql know that when is the query to be executed...?

```
response = schema.execute(query)
```

Where would this query come from, so that it is executed against the schema...?

**Comment by vincentfretin** [comment]
Hi @return007, maybe I'm off topic, but it may interest you. For a webob implementation (for pyramid framework for example) I use https://github.com/ecreall/graphql-wsgi/ on both Python 2.7 and Python 3 projects. I updated it recently to work with latest graphene version. I plan to implement batching queries soon.
