### ISSUE TITLE
How to write nested mutations?

### ISSUE THREAD

**Issue by kaspermarstal** [graphql-python/graphene#485]
Is it possible to pass the output of one mutation to another? I would like the `WriteImage` resolver to accept its input image from the `ReadImage` resolver. 
The schema looks like this:

    import SimpleITK as sitk
    import graphene
    from graphql.execution.executors.asyncio import AsyncioExecutor
    
    class Image(graphene.Scalar):
        '''SimpleITK Image Type'''
    
        @staticmethod
        def serialize(Image):
            return Image
    
        @staticmethod
        def parse_literal(node):
            if isinstance(node, sitk.Image):
                return node
    
        @staticmethod
        def parse_value(value):
            return value

    class ReadImage(graphene.Mutation):
        class Input:
            path = graphene.String()
    
        image = Image()
    
        @staticmethod
        async def mutate(cls, args, context, info):
            image = sitk.ReadImage(args.get('path'))
            return ReadImage(image=image)
    
    
    class WriteImage(graphene.Mutation):
        class Input:
            image = Image()
            path = graphene.String()
    
        image = Image()
    
        @staticmethod
        async def mutate(cls, args, context, info):
            image = args.get('image')
            sitk.WriteImage(image, args.get('path'))
            return WriteImage(image=image)
    
    class Query(graphene.ObjectType):
        dummy = graphene.Field(graphene.String)

        async def resolve_dummy(self, args, context, info):
            return 'dummy'

    class Mutation(graphene.ObjectType):
        readImage = ReadImage.Field()
        writeImage = WriteImage.Field()
    
    
    schema = graphene.Schema(
        query=Query,
        mutation=Mutation,
    )
    
    executed = schema.execute(
        """
            mutation {
                writeImage(
                    image: {
                        readImage(
                            path: "/path/to/image.nii"
                        ) {
                            image
                        }
                    },
                    path: "/Users/kasper/Desktop"
                ) {
                    image
                }
            }
        """, executor=AsyncioExecutor())

    print(executed.data)
    print(executed.errors)

This outputs 

    >>> None
    >>> [GraphQLError('Argument "image" has invalid value ReadImageInput.\nExpected "ReadImageInput", found not an object.',)]

What does this error message mean? Why is it `not an object`? How should the schema be structured so that I may use output from one resolver as input to another?

Additional info: Executing the `ReadImage` produces the following output:

    executed = schema.execute(
        """
            mutation {
                readImage(
                    path: "/path/to/image.nii"
                ) {
                    image
                }
            }
        """, executor=AsyncioExecutor())
    
    print(executed.data)
    print(executed.errors)

    >>> OrderedDict([('readImage', OrderedDict([('image', <SimpleITK.SimpleITK.Image; proxy of <Swig Object of type 'std::vector< itk::simple::Image >::value_type *' at 0x1087b5030> >)]))])
    >>> None

**Comment by ekampf** [comment]
Why is `ReadImage` a mutation and not a query?  
From the looks of it, it only reads data and doesn't mutate anything...

**Comment by ekampf** [comment]
That said, GraphQL arguments cannot be queries...
What I'd do is allow the `WriteMutation` get an optional `path` as input (and make `image` optional too) and if `path` is given run the logic that lots it from file in the `WriteMutation` resolver

**Comment by kaspermarstal** [comment]
You are right that this would solve the problem stated above. However WriteImage should eventually be able to accept an `Image` from many different kinds of mutations, e.g. a smoothing filter or a rescaling operation etc, which themselves should be able accept an image as an input argument. The idea is to script the image processing pipeline in GraphQL. I omitted that from the question to keep it simple but should have included in hindsight. Any input on this particular use case?

**Comment by ekampf** [comment]
I don't think you can do that with GraphQL ...

**Comment by jkimbo** [comment]
Hi @kaspermarstal . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
