### ISSUE TITLE
When resolvers return a type that implements an interface, queries against that field return 'null' unless the type has been used elsewhere on the Query class.

### ISSUE THREAD

**Issue by nikvdp** [graphql-python/graphene#489]
When resolvers return a type that implements an interface, queries against that field return `null` unless the type has been used elsewhere on the `Query` class.

Why do the types that implement an interface need to be used on the `Query` class?

For example, let's say I have an interface `Character`, and two types that implement `Character`; `Human` and `Dog`. I then create a `Query` class that includes a a `graphene.List` of `Character`. If the resolver for that field returns a mixed list of `Human` and `Dog` types, and I query against it, it returns `null` for both the `Human`s and the `Dog`s. However, if I add a field of type `Dog` to the `Query` class, the `Dog` instances start working, and if I add a `Human` field, the `Human` instances start working. 

I've included a short example to reproduce the issue below. Uncommenting the `hum` and `dog` attrs of the `Query` class (as in the snippet directly below) makes the `chr` query work as expected, but why is this needed?

```python
class Query(graphene.ObjectType):
    chr = graphene.List(lambda: Character)
    hum = graphene.List(lambda: Human)
    dog = graphene.List(lambda: Dog)
```

If this is intentional behavior or not feasible to change I would be glad to document it in the [Interface](https://github.com/graphql-python/graphene/blob/master/docs/types/interfaces.rst) docs to avoid someone else facing this same problem in the future!

Runnable example that illustrates the issue below:

```python
import json

import graphene
from graphene import resolve_only_args


class Character(graphene.Interface):
    name = graphene.String()


class Human(graphene.ObjectType):
    class Meta:
        interfaces = (Character, )


class Dog(graphene.ObjectType):
    class Meta:
        interfaces = (Character, )

    color = graphene.String()

human_data = [Human(name="dude in a list"),
              Human(name="not dog in a list")]

dog_data = [Dog(name="dog first in a list"),
            Dog(name="dog in a list")]

# mixed_data = human_data + dog_data
mixed_data = [Human(name="human"), Dog(name="dog"), Human("human2")]


class Query(graphene.ObjectType):
    chr = graphene.List(lambda: Character)
    # hum = graphene.List(lambda: Human)
    # dog = graphene.List(lambda: Dog)

    @resolve_only_args
    def resolve_hum(self):
        return human_data

    @resolve_only_args
    def resolve_dog(self):
        return dog_data

    @resolve_only_args
    def resolve_chr(self):
        return mixed_data


schema = graphene.Schema(query=Query)


query = """
{
    chr {__typename, name}
}
"""
results = schema.execute(query)
print(results.data)
```

**Comment by nikvdp** [comment]
After digging through some related issues, discovered @femesq's comment on  https://github.com/graphql-python/graphene/issues/478#issuecomment-305947413 on https://github.com/graphql-python/graphene/issues/478. 

Adding `types=[Human, Dog]` to the `graphene.Schema(query=Query)` call also fixes the issue for me.  

@syrusakbary I'd like to update the documentation to describe this behavior, would the [interfaces](https://github.com/graphql-python/graphene/blob/master/docs/types/interfaces.rst) doc be the best place to do that?

**Comment by syrusakbary** [comment]
Hey @nikvdp I think documenting this scenario is a great idea.
The interfaces docs is probably the best place to do it!
