### ISSUE TITLE
Help with Mutation

### ISSUE THREAD

**Issue by amitsaha** [graphql-python/graphene#49]
Hello, I am trying to experiment with a simple mutation, here is my schema:

```
import graphene


class Person(graphene.ObjectType):

    name = graphene.String()
    age = graphene.Float()
    id = graphene.Int()

# Database of Person(s)
p1 = Person()
p2 = Person()

p1.id = 1
p1.age = 34
p1.name = 'Jack'

p2.id = 2
p2.age = 31
p2.name = 'Adam'

persons = [p1, p2]

class Query(graphene.ObjectType):

    # Create a field on which we can query and the attributes
    # we allow to query on
    person = graphene.Field(Person, id=graphene.Int())
    def resolve_person(self, args, info):
        for p in persons:
            if p.id == args.get('id'):
                return p

class UpdatePerson(graphene.Mutation):
    # Result field
    # XXX: This doesn't work
    # person = graphene.Field(Person)

    # This does work
    person = graphene.String()

    # The input fields
    class Input:
        name = graphene.String()
        id = graphene.Int()

    @classmethod
    def mutate(cls, instance, args, info):
        name = args.get('name')
        for p in persons:
            if p.id == args.get('id'):
                p.name = name
                return UpdatePerson(person=p.name)

class UpdatePersonMutation(graphene.ObjectType):
    updatePerson = graphene.Field(UpdatePerson)

schema = graphene.Schema(query=Query, mutation=UpdatePersonMutation)

```

In ``UpdatePerson`` above, when I have the person field as ``person = graphene.Field(Person)``, ( and correspondingly ``return UpdatePerson(person=p)``), upon sending a mutation query, I get: ``[GraphQLError('Field "person" of type "Person" must have a sub selection.',)]``. 

Any suggestions as to what I am doing wrong?

**Comment by syrusakbary** [comment]
Hi @amitsaha!
Can you post this in StackOverflow so will be easier for other people for searching if they have the same problem?
I would be more than happy for answering! :)
If you could post here the stackoverflow post url after would be great

**Comment by jhgg** [comment]
Hi @amitsaha  - you are running into the no scalar leafs validation error.

This means your query is wrong.

**Comment by jhgg** [comment]
Chances are you are calling:

```
mutation { 
    updatePerson(id: 5, name: "Hello") {
        person
    }
}
```

You should be calling:

```
mutation { 
    updatePerson(id: 5, name: "Hello") {
        person {
            id
            name
        }
    }
}
```

**Comment by amitsaha** [comment]
Thanks @jhgg - that was it, thank you.

@syrusakbary Do you still want me to post it? For the future, what tags should I be using?

**Comment by syrusakbary** [comment]
@amitsaha You can use #graphql #graphene #python :)
