### ISSUE TITLE
schema.execute with variable_values freezes runserver

### ISSUE THREAD

**Issue by macolsson** [graphql-python/graphene#491]
Hi all,

I've run into a quite odd issue where I see my schema.execute() freezing the current processes completely when passing a query with variables (e.g. `schema.execute(query, variable_values={input: {"testId": "Xyz123="}}, context_value={"someId": "1"})`).

I'm running Graphene, with `graphene-django==1.3` in my django project. I've setup subscriptions and using it with the new relay-modern. To support websockets I'm running `channels==1.1.5`.

What I want to accomplish is through a `post_save()`, using Django signals, dispatch a subscription response by using the above schema execute example. This works perfectly through Django Admin interface, however when I try to accomplish the above using a standard mutation with a `model_instance.save()` it never finishes the `schema.execute()`, instead it just freezes.

Mutation:
```
class PingMutation(graphene.ClientIDMutation):

    class Input:
        support_session_id = graphene.ID()

    ping = graphene.Field(PingNode)

    @classmethod
    def mutate_and_get_payload(cls, args, context, info):
        session_id = from_global_id(args.get('support_session_id'))[1]
        pings = support_models.Ping.objects.get(support_session__id=session_id)

        pings.support_last_ping = datetime.datetime.now()

        # I can see this debug message, before the save.
        logger.debug('SupportPingMutation:pre-save')

        # Will trigger the signal...
        pings.save()

        # The code never reaches this point.
        logger.debug('SupportPingMutation:post-save')

        return cls(ping=pings)
```

Model with trigger:
```
class Ping(models.Model):
    support_session = models.OneToOneField(SupportSession, related_name="ping")
    client_ping = models.DateTimeField(...)
    support_ping = models.DateTimeField(...)

# Sets up a post_save
ModelSignalReceiver.connect_receivers(Ping)
```

Execute segment (executed through an attached post_save):
```
    @classmethod
    def _dispatch_for_subscriptions(cls, instance, subscriptions):
        ...
        if subscription_instance.filter(variables, instance):
            context = {'id': instance.id}

            if query and variables:
                results = schema.execute(
                    query,
                    variable_values=variables,
                    context_value=context)
                data = results.data
                errors = results.errors
      

              message = {
                  'text': json.dumps({
                      'request': {
                          'query': query,
                          'variables': variables,
                      },
                      'payload': {
                          'data': data,
                          'errors': errors,
                      }
                  })
              }
              
              Group(query_hash).send(message)
```

Any ideas or pointers would be most helpful.

Thanks

**Comment by jkimbo** [comment]
Hi @macolsson . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this. It's possible this issue is fixed in [graphene 2.0](https://github.com/graphql-python/graphene/releases/tag/v2.0.0) anyway.

Thanks!
