### ISSUE TITLE
documention on Union

### ISSUE THREAD

**Issue by seansay** [graphql-python/graphene#493]
Hi guys,

Quite new graphene to,  I read on the graphql.org website, http://graphql.org/learn/schema/#union-types. There is this way to define a union type:

```union SearchResult = Human | Droid | Starship```

It seems that there is code about `Union` in the source, but not the documentation, just want to  know Is this already supported in graphene and just lacking of doc?

Thanks!

**Comment by seansay** [comment]
Any one can help? cc @syrusakbary

**Comment by waxisien** [comment]
Hi,

you can implement it that way (simplified) : 

```
class Anything(graphene.types.union.Union):
    class Meta:
        types = (Human, Droid, Starship)

class Query(graphene.ObjectType):
    search = graphene.List(Anything)
```

Then write a resolver for the search that will concatenate results for each type : 
```
def resolve_search(self, args, context, info):
    humans = droids = starships = []
    # search for each type
    return humans + droids + starships
```

**Comment by whalesalad** [comment]
I am also having difficulty here.

```python
import graphene
from graphene.types.union import Union

class Contract(graphene.Interface):
    id = graphene.Int(required=True)
    basis = graphene.Field(DollarAmount)
    contract_date = graphene.Field(Date)
    contract_price = graphene.Field(DollarAmount)
    notes = graphene.String()
    quantity = graphene.Int()
    underlying = graphene.Field(Underlying)


class CashContract(graphene.ObjectType):
    contract_status = graphene.Field(ContractStatus)
    contract_type = graphene.Field(CashContractType)
    delivery_date = graphene.Field(Date)

    class Meta:
        interfaces = (Contract, )


class FuturesContract(graphene.ObjectType):
    expiration_date = graphene.Field(Date)

    class Meta:
        interfaces = (Contract, )


class ContractUnion(Union):
    class Meta:
        types = (CashContract, FuturesContract)
```

I get the following error when I try and request a common attribute, `id`, in my query:

```
"message": "Cannot query field \"id\" on type \"ContractUnion\". Did you mean to use an inline fragment on \"Contract\", \"CashContract\" or \"FuturesContract\"?"
```

=(

**Comment by waxisien** [comment]
@whalesalad Does your query contain an inline Fragment http://graphql.org/learn/queries/#inline-fragments ?
Since the union returns different types you need a query like this : 
```
{
  search {
    __typename
    ... on CashContract{
      id
      contract_status
    }
    ... on FuturesContract{
      expiration_date
    }
  }
}
```

**Comment by whalesalad** [comment]
@waxisien that makes sense, but I also see that in the official guide you can ask for shared attributes between the two different fragments: http://graphql.org/learn/queries/#inline-fragments

```
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name
    ... on Droid {
      primaryFunction
    }
    ... on Human {
      height
    }
  }
}
```

In this case `name` is on both, so you can ask for it without using a fragment.

**Comment by syrusakbary** [comment]
@whalesalad the example you posted for inline fragments is only applicable to `Interface`s.
In the case of `Union`s, there is no "common" fields between types (at least none that the GraphQL engine is aware of, without making some assumptions that might not be correct).
On the other hand, with an `Interface`, you assure that all it's implementations at least have the interface fields in common.

Quoted from the [official GraphQL spec](https://facebook.github.io/graphql/#sec-Unions):
> With interfaces and objects, only those fields defined on the type can be queried directly; to query other fields on an interface, typed fragments must be used. This is the same as for unions, but unions do not define any fields, so no fields may be queried on this type without the use of typed fragments.


Closing the issue

**Comment by whalesalad** [comment]
@syrusakbary thanks for the response. I actually don't even want to use a union type... I want to just pass the interface class into the List for my but that does not work. But I was finding that graphene wasn't happy about putting an interface somewhere where an ObjectType was expected? Is this intentional?

**Comment by seansay** [comment]
@syrusakbary 
Hi Syrus, actaully I opened this issue because of this is any docs about using Union on our `http://graphene-python.org/` website, maybe we could still let this open?
