### ISSUE TITLE
new Structure.of_type "now" breaks lazy types in circular imports

### ISSUE THREAD

**Issue by richmondwang** [graphql-python/graphene#494]
Prior to `v1.3.0`, I was able to do this without any problems at all.

I think this is because of the change of `Structure.of_type` property, which is now using the `utils.get_type`. Now it calls the lazy loader sooner than the lazy loaded class to be in the memory giving me:
 
```
AttributeError: module 'some_module' has no attribute 'GrapheneObject'
```

This goes the same when using the `lazy_import`, raising:

```
ImportError: Module "some_module" does not define a "GrapheneObject" attribute/class.
```

I don't know if this is the intended before after all, so if that is the case you can close this issue right away.

**Comment by sdcooke** [comment]
I've managed to narrow this down (in our test suite, at least) to the `assert` in the `NonNull` class because it checks `self.of_type` in `__init__`. I'm not sure what the best way would be to fix this, but since it's an assert it's obviously not necessary for the code to run.
