### ISSUE TITLE
How to get a nested schema class in the resolver?

### ISSUE THREAD

**Issue by keattang** [graphql-python/graphene#499]
Say I have a schema that is set up like this:

```
class ThingSchema(ObjectType):
    ...


class Query(ObjectType):
    things = List(ThingSchema)
    thing = Field(ThingSchema)

    def resolve_things(self, args, context, info):
        ...

    def resolve_thing(self, args, context, info):
        ...

schema = graphene.Schema(query=Query)
```

What is the best way to get the `ThingSchema` class from inside `resolve_things` and `resolve_thing`? I ask because I am trying to create a generic resolver function that needs to introspect schema class to do some optimisations.

It feels like I should be able to get it from inside the `info` argument but there's a lot going on in there and I haven't quite been able to figure it out.

**Comment by jkimbo** [comment]
Hi @keattang . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by keattang** [comment]
Hi @jkimbo, yes I'm still very interested in having this question answered. 

Cheers!

**Comment by syrusakbary** [comment]
Hi @keattang,

You can do in (graphene 2.0):

```python
    def resolve_thing(self, info, args):
        thing_schema = info.return_type.graphene_type
```
