### ISSUE TITLE
asyncio+graphene:  shema.execute return errors not as promise

### ISSUE THREAD

**Issue by MazokuMaxy** [graphql-python/graphene#503]
In async mode shema.execute return errors not as promise. 
So I need to write something like this:

```
from graphql import execution

co = schema.execute(
    query,
    return_promise=True,
    executor=execution.executors.asyncio.AsyncioExecutor()
)
result = co if isinstance(co, execution.ExecutionResult) else await co
```

**Comment by achimnol** [comment]
That annoys me as well.
This issue could be delegated to https://github.com/graphql-python/graphql-core/issues/112.

**Comment by jkimbo** [comment]
It looks like this issue was fixed in graphql-core. Closing
