### ISSUE TITLE
Link to documentation in Readme

### ISSUE THREAD

**Issue by iAmMrinal0** [graphql-python/graphene#504]
It helps users who want to access the documentation directly instead of visiting the website and going to the documentation.

**Comment by morenoh149** [comment]
@iAmMrinal0 where do you propose the link go exactly? the GitHub repo points to the project page which has docs in the navbar. The readme prominently links to the project page already. I'd vote to close this issue.

**Comment by iAmMrinal0** [comment]
@morenoh149 I was wondering if it could be added in the `Documentation` section. It's a click less when someone is already reading the Readme. The impression one gets when they read the Readme is that they'd need to use Sphinx which is not the case unless one wanted to make changes to the documentation. So I thought it would be a good idea to include the link directly, similar to how other projects like Flask, Requests, Pipenv, Tornado do.

Reference
1. [Flask](https://github.com/pallets/flask#links)
2. [Requests](https://github.com/kennethreitz/requests#documentation)
3. [Pipenv](https://github.com/pypa/pipenv#-documentation)
4. [Tornado](https://github.com/tornadoweb/tornado#documentation)

**Comment by morenoh149** [comment]
I thought so as well, but realized that that is the Contributing > documentation section. Meaning it describes how to build the docs while contributing. In my opinion a link there to the docs is not correct.
