### ISSUE TITLE
"context" value becaome "Flask Request" object in request

### ISSUE THREAD

**Issue by seansay** [graphql-python/graphene#506]
Hi guys,

An weird problem came to me today.

I using something like  in a flask view

```
@bp.route('/graphql', methods=['POST'])
def graphql():
     /// some code
     res = schema.execute(
            query, variable_values=variables, context_value={"user": user})
```

On the resolve I just 
```
    def resolve_current_user(self, args, context, info):
        return context['user']

```

It's normal when you using `schema.execute` on the python shell. 
But if you test on a reqeust, then the context is not a dict I passed in, it's an flask request object:

something like  `<Request 'https://xxxx.com/graphiql' [POST]>` got log for context.

The traceback

```
 File "/app/venv/lib/python2.7/site-packages/graphql/execution/executor.py", line 200, in resolve_or_error
   return executor.execute(resolve_fn, source, args, context, info)
 File "../app/venv/lib/python2.7/site-packages/graphql/execution/executors/sync.py", line 7, in execute
   return fn(*args, **kwargs)
 File "/app/app_code/gql/schema.py", line 142, in resolve_current_user
   return context['user']
 File "/usr/lib64/python2.7/site-packages/werkzeug/local.py", line 373, in <lambda>
   __getitem__ = lambda x, i: x._get_current_object()[i]
'Request' object has no attribute '__getitem_
````

Any idea?

**Comment by seansay** [comment]
oh I found the problem.

I have two graphql endpoint , one is came from the graphiql and one is that I hand written the flask view. And I forget to put `context_value` to the graphiql.

**Comment by syrusakbary** [comment]
Happy you found the bug :)

Closing the issue

**Comment by seansay** [comment]
@syrusakbary 
Thanks

BTW:
Just wonder why the flask-graphiql have the default `context` set to flask request?

**Comment by m3talstorm** [comment]
Now that`info.context` is a Flask request object you can no longer do `info.context` inside a mutation because you get:

"graphql.error.located_error.GraphQLLocatedError: Working outside of request context."

How are you supposed to get context info (such as headers) when in a mutation?
