### ISSUE TITLE
Django many to many relationship problem

### ISSUE THREAD

**Issue by nakeeon** [graphql-python/graphene#507]
Hi guys,
I have interesting issue with many to many relationship between two Django models.

I have a Business model which has a many to many relationship to Service model.

Business model:

```
class Business(models.Model):
    title = models.CharField(max_length=25)
    address = models.CharField(max_length=25)
    location = PointField()
    provider = models.ForeignKey(ServiceProvider, related_name='businesses')
    services = models.ManyToManyField('Service', related_name='businesses')
    logo = models.ImageField(upload_to="businesses/logos")
    description = models.TextField()

    def __str__(self):
        return self.title
```

Service model:
```
class Service(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    car_system = models.ForeignKey(CarSystem, related_name='services')
    icon = models.FileField(upload_to="service_icons")

    def __str__(self):
        return self.name
```

My schema:

```
class ServiceType(DjangoObjectType):
    class Meta:
        model = Service

class BusinessType(DjangoObjectType):
    class Meta:
        model = Business

class Query(graphene.AbstractType):
    services = graphene.List(ServiceType)
    business = graphene.Field(BusinessType, id=graphene.Int())

    def resolve_services(self, args, context, info):
        return Service.objects.all()

    def resolve_business(self, args, context, info):
        business_id = args.get('id')

        if business_id is not None:
            try:
                return Business.objects.get(pk=business_id)
            except Business.DoesNotExist:
                return None

        return None
```

Using graphiql I want to query all services related to specific business

```
{
  business (id:3) {
    title
    services {
    	name
    }
  }
}
```

But I got this error
`Cannot query field \"name\" on type \"BusinessType\"."`

When I look at the graphiql docs I can see that services detected as `BusinessType` instead of `ServiceType`

![416abd91db](https://user-images.githubusercontent.com/17749002/28462076-46908264-6e22-11e7-97ad-3e7ebf44bbff.jpg)

At the same time I able to query all businesses related to services using this query
```
{
  services {
    name
    businesses {
      title
    }
  }
}
```

It works fine.

The interesting part is that when I removed ManyToMantField from a Business model and added it to a Service model everything was work vice versa.
Now I able to query services related to business using this query:
```
{
  business (id:3) {
    services {
      name
    }
  }
}
```

But if I want to query businesses related to services using the old query
```
{
  services {
    name
    businesses {
      title
    }
  }
}
```

I got this error: `Cannot query field \"title\" on type \"ServiceType\"."`

Is it a bug in the graphene or is it my fault? Help me please with that.

**Comment by BossGrand** [comment]
This Issue belongs in https://github.com/graphql-python/graphene-django

**Comment by jkimbo** [comment]
@BossGrand is right, this belongs in the graphene-django repo. If the issue is still important then please open a new issue there.
