### ISSUE TITLE
How to access parent field parameters within child resolver

### ISSUE THREAD

**Issue by JoeNyland** [graphql-python/graphene#510]
I'm trying to build a schema using Graphene that will support the following example query:

```
{
  form(id:1) {
    visits(start:1498863600, end: 1498950000) {
      total
    }
  }
}
```

The expected result from this would be something like this:

```json
{
  "data": {
    "form": {
      "visits": {
        "total": 1123
      }
    }
  }
}
```

So far, I've come up with a schema that's similar to the following. However I'm not sure how to access the `id`
parameter on the `form` field from within the `visits` resolver. I need this `id` parameter in the visits resolver as I
need to retrieve sessions from the DB for a specific form and between a time range (`start` and `end`).

```python
import graphene
from lib import DBI


class ResultSetType(graphene.ObjectType):
    total = graphene.Int()

    def resolve_total(self, args, context, info):
        return 1000  # Hardcoded example


class FormType(graphene.ObjectType):
    id = graphene.ID()
    visits = graphene.Field(ResultSetType)

    def resolve_visits(self, args, context, info):
        """
        I understand that here I can access the 'start' and 'end'
        parameters for this field using args.get('start'), but how
        do I access the 'id' parameter from the parent 'form' field?
        
        My naive attempt of using`args.get('id')` returns `None`
        """
        return DBI.get_form_sessions(form_id=args.get('id'), start_ts=args.get('start'), end_ts=args.get('end'))


class RootType(graphene.ObjectType):
    form = graphene.Field(FormType, id=graphene.ID())

    def resolve_form(self, args, context, info):
        return FormType(id=args.get('id'))

```

How do I access parent field parameters from within a child field resolver?

**Comment by JoeNyland** [comment]
For anyone facing a similar issue, I worked out how to do this. `self.id` holds the ID of the `FormType` object.

For example, the following would be a replacement for the `resolve_visits` method above:

```
    def resolve_visits(self, args, context, info):
        return DBI.get_form_sessions(form_id=self.id, start_ts=args.get('start'), end_ts=args.get('end'))
```

**Comment by pawarchinmay27** [comment]
`class Product(graphene.ObjectType):
	productName=graphene.String()
	productDependecies=graphene.List(ProductDependency)
       '''
                Here I Want access the instanceIP How Can I do that
       '''

class Instance(graphene.ObjectType):
	instanceIP=graphene.String()
	products=graphene.List(Product)
	ebsvolumes=graphene.List(EBSVolume)`
       def resolve_products(self,info):
               #some code that follows

**Comment by athlordJojo** [comment]
Is there any progress ? or any example how to achieve this ?

**Comment by mglraimundo** [comment]
bump, could we get a simple snippet implementing this?

**Comment by JoeNyland** [comment]
@pawarchinmay27 @athlordJojo @mglraimundo Please open a new issue as mine has been solved [here](https://github.com/graphql-python/graphene/issues/510#issuecomment-318686182).
