### ISSUE TITLE
Memory Error on json encoding

### ISSUE THREAD

**Issue by femesq** [graphql-python/graphene#512]
Hi,

I've just got this stacktrace (Django Project):
```
  File "xxx/lib/python2.7/site-packages/graphene_django/views.py", line 180, in json_encode
    return json.dumps(d, separators=(',', ':'))
  File "/usr/lib64/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
MemoryError
```

I will do some investigation and optimizations on my code, but also was wondering if this [link](https://stackoverflow.com/questions/24239613/memoryerror-using-json-dumps) could help and improve the package performance...

Thanks,

**Comment by femesq** [comment]
For reference of others, as my response are pretty big/complex, [using ujson](https://github.com/esnme/ultrajson) brings a perf boost:

```
class CustomGraphQLView(GraphQLView):
    def json_encode(self, request, d, pretty=False):
        if not (self.pretty or pretty) and not request.GET.get('pretty'):
            return super(CustomGraphQLView, self).json_encode(request, d, pretty)
        return json.dumps(d)


urlpatterns = patterns('',
                       url(r'^graphql/$', csrf_exempt(CustomGraphQLView.as_view())),
                       url(r'^graphiql/$', GraphQLView.as_view(graphiql=True)),
                       )
```

**Comment by jkimbo** [comment]
Hi @femesq . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
