### ISSUE TITLE
Django cached page: generate cache key for graphene query (GAE)

### ISSUE THREAD

**Issue by alehl** [graphql-python/graphene#515]
I want to be able to generate cache keys for whatever is being queried via the graphQL gui by the client. It woudn't make sense to do something like `cache.set()` because I simply have too many fields that could be queried and I'm unable to predict which ones will be queried. How could I generate cache keys for all content that queried?

On my view, I have the following: 

    class EVGraphQLView(StaticApiKeyOrInternalMixin, GraphQLView):
        """GraphQL view for clients."""

        def dispatch(self, request, *args, **kwargs):

           self.request = request
           self.kwargs = kwargs
           self.object = self.get_object()

           return GraphQLView.dispatch(self, request, *args, **kwargs)

        def get_object(self):
            if not hasattr(self, '_object'):
                self._object = super(EVGraphQLView, self).get_object()
            return self._object

And on urls file:

    urlpatterns = [

        url(r'^igraphql', cache_page(60 * 15)(GraphQLView.as_view(graphiql=True))),
    ]

It might help to mention that I am using GAE, so these are my settings:

    CACHES = {
        'default': {
            'BACKEND': 'ev_utils.cache.GoogleAppEngineMemcachedCache',
            'TIMEOUT': 3600
        }
    }

None of this has worked, I've been looking through documentation but nothing seems to help.

**Comment by BossGrand** [comment]
This Issue might belong in https://github.com/graphql-python/graphene-django

**Comment by jkimbo** [comment]
Hi @alehl . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
