### ISSUE TITLE
Flask Example

### ISSUE THREAD

**Issue by sibeliusseraphini** [graphql-python/graphene#52]
Add flask example using graphene

**Comment by amitsaha** [comment]
I am working on something: https://github.com/amitsaha/flask-graphql-demo it's really basic, planning to demo file uploading next.

**Comment by amitsaha** [comment]
@syrusakbary is this something you would want to integrate into the source tree as an example? If yes, what would you like to see in it?

**Comment by syrusakbary** [comment]
Hi @amitsaha, I'm willing to create a package for integrating graphql in flask easily (with GraphQL and GraphiQL views). Once is done, yeah... any example will be more than welcome!

Meanwhile I've linked your package in the documentation package (the new version of the website will be released tomorrow):
https://github.com/graphql-python/graphene/blob/docs/docs/pages/community.md

**Comment by amitsaha** [comment]
Thanks @syrusakbary - that would be awesome. Do you already have some work done that I can look at?

**Comment by amitsaha** [comment]
@syrusakbary just wondering if you have any code that you can share? I would like to integrate graphiql into my project. If you don;'t have any, I will try to set it up somehow .. :)

**Comment by msoedov** [comment]
@amitsaha I have really simple flask app example https://github.com/msoedov/flask-graphql-example, you can build docker-compose and check that out

**Comment by syrusakbary** [comment]
I've created the [GraphQL-Flask](https://github.com/graphql-python/graphql-flask) package for using GraphQL in Flask easily.

Also, you can check the Flask SQLAlchemy in the sqlalchemy branch:
https://github.com/graphql-python/graphene/tree/sqlalchemy/examples/flask_sqlalchemy

This example, with the SQLAlchemy support will be merged soon: #87

**Comment by amitsaha** [comment]
Thanks @syrusakbary - will check them out.

**Comment by sibeliusseraphini** [comment]
@syrusakbary you should consider using the [graffiti] (https://github.com/RisingStack/graffiti) approach

To enable **adapters** for databases.
For now, you already have two of them in contribute django and sqlalchemy, I think the next one could be **mongoengine**

Thanks for this repository

**Comment by amitsaha** [comment]
@syrusakbary it works great. @msoedov Will do, does it support file uploads? My approach is very basic here: https://github.com/amitsaha/flask-graphql-demo/blob/master/schema.py 

Would be curious to know if you have a better idea?

**Comment by commandtab** [comment]
Thanks for your repo, @amitsaha! It cleared up a number of things for me as I'm getting going with graphene :)

**Comment by savovs** [comment]
If anyone is looking for a 2017 example: https://www.youtube.com/watch?v=oQc7DC3srNM

**Comment by savovs** [comment]
I'm working on an updated flask example, would like to include file uploads but I'm getting this error:
`UploadFile fields must be a mapping (dict / OrderedDict) with field names as keys or a function which returns such a mapping.
`

Using this simple schema:
```python
from graphene import Schema, Argument, String, Int, ObjectType, Mutation

class Query(ObjectType):
	# Define a field with arguments
	hello = String()

	def resolve_hello(self, info, name, age):
		return 'Hello there.'

class UploadFile(Mutation):
	class Arguments:
		pass

	def mutate(self, info):
		return 'test'

class Mutations(ObjectType):
	uploadFile = UploadFile.Field()


schema = Schema(query = Query, mutation = Mutations)
```
