### ISSUE TITLE
Can't use custom field as input in mutation

### ISSUE THREAD

**Issue by janhancic** [graphql-python/graphene#520]
I have a custom field (written with @syrusakbary help in [this issue](https://github.com/graphql-python/graphene/issues/433)):

```python
from functools import partial

class ProtoEnum(graphene.Field):
    def __init__(self, protobuf_enum, *args, **kwargs):
        super(ProtoEnum, self).__init__(graphene.Int, *args, **kwargs)
        self.protobuf_enum = protobuf_enum

    def get_resolver(self, parent_resolver):
        return partial(_enum_resolver, self.protobuf_enum, parent_resolver)

def _enum_resolver(protobuf_enum, parent_resolver, root, args, context, info):
    resolved_value = parent_resolver(root, args, context, info)
    if resolved_value not in protobuf_enum.values():
        raise ValueError('Enum value "%s" is invalid' % resolved_value)
    return resolved_value
```

I wanted to use it as a input in my mutation like so:

```python
class Input:
    my_field = ProtoEnum(...)
```
Which gave me this error:

```
File "third_party/python3/graphene/types/field.py", line 54, in __init__
  File "third_party/python3/graphene/types/argument.py", line 61, in to_arguments
ValueError: Expected my_field to be Argument, but received ProtoEnum. Try using Argument(Int!).
```

I tried wrapping it in `Argument`, which in turn gave me this error:

```
File "third_party/python3/graphene/types/schema.py", line 44, in __init__
  File "third_party/python3/graphene/types/schema.py", line 105, in build_typemap
  File "third_party/python3/graphene/types/typemap.py", line 65, in __init__
  File "third_party/python3/graphql/type/typemap.py", line 16, in __init__
  File "third_party/python3/graphene/types/typemap.py", line 73, in reducer
  File "third_party/python3/graphene/types/typemap.py", line 103, in graphene_reducer
  File "third_party/python3/graphql/type/typemap.py", line 79, in reducer
  File "third_party/python3/graphql/pyutils/cached_property.py", line 16, in __get__
  File "third_party/python3/graphql/type/definition.py", line 180, in fields
  File "third_party/python3/graphql/type/definition.py", line 189, in define_field_map
  File "third_party/python3/graphene/types/typemap.py", line 246, in construct_fields_for_type
  File "third_party/python3/graphene/types/typemap.py", line 295, in get_field_type
AttributeError: 'ProtoEnum' object has no attribute '_meta'
```

I tried adding a `Meta` class but that didn't do anything. I can use custom field just fine in my schema otherwise.

Am I doing something wrong or is this just not supported?

**Comment by totaki** [comment]
Try this
```python
class Input:
    my_field = graphene.Argument(ProtoEnum)
```

**Comment by joealcorn** [comment]
I'm getting similar errors using a subclass of the built in `Enum` type, seems like using it in inputs is not supported to me. I found [this comment](https://github.com/graphql-python/graphene/issues/134#issuecomment-204665642) from over a year ago but it no longer seems to work.

I've tried all of the following (and wrapper in `Argument` too) and received an error every time

```python
type = ProjectTypeEnum(required=False)
```

```python
type = ProjectTypeEnum(required=False).InputField()
```

```python
type = ProjectTypeEnum(required=False).Field()
```

**Comment by janhancic** [comment]
Can you post the various exceptions you get, maybe that would help @syrusakbary figure out what's going on.

**Comment by totaki** [comment]
In input fields you need use graphene.Argument instead Field. Example: https://github.com/totaki/graphql-learn/blob/develop/articles/ru/episode-2/move_task/README.md

**Comment by joealcorn** [comment]
Wrapping in `Argument` doesn't work either - when trying with
```python
class Input:
        type = graphene.Argument(ProjectTypeEnum(required=False))
```

I get `AttributeError: 'ProjectTypeEnum' object has no attribute 'name'.`

I'm on `graphene==1.4.1`

I can give it a `name` attr and it'll get further, but it still does not work and that is not documented, so I'm feeling like that's the wrong thread to follow.

```
ERROR      2017-08-24 12:12:18,038 [a7a9a0db-2532-4eac-9fbf-3911927bffc0] executor:203 resolve_or_error An error occurred while resolving field __Type.kind
Traceback (most recent call last):
  File "/Users/joe/.venvs/marvel/lib/python2.7/site-packages/graphql/execution/executor.py", line 200, in resolve_or_error
    return executor.execute(resolve_fn, source, args, context, info)
  File "/Users/joe/.venvs/marvel/lib/python2.7/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/Users/joe/.venvs/marvel/lib/python2.7/site-packages/graphene_django/debug/middleware.py", line 55, in resolve
    promise = next(root, args, context, info)
  File "/Users/joe/.venvs/marvel/lib/python2.7/site-packages/graphql/execution/middleware.py", line 57, in make_it_promise
    return Promise.resolve(next(*a, **b))
  File "/Users/joe/.venvs/marvel/lib/python2.7/site-packages/graphql/type/introspection.py", line 213, in kind
    raise Exception('Unknown kind of type: {}'.format(type))
Exception: Unknown kind of type: <marvelapp.graphql.schema.ProjectTypeEnum object at 0x10a8b0390>
```

**Comment by totaki** [comment]
I think you doing some thing wrong, if you want use some custom field you need Scalar http://docs.graphene-python.org/en/latest/types/scalars/

**Comment by joealcorn** [comment]
I'm defining an Enum like the documentation says

http://docs.graphene-python.org/en/latest/types/enums/#definition

**Comment by totaki** [comment]
```
class ProtoEnum(graphene.Field): 
```
it`s not same in documetation
http://docs.graphene-python.org/en/latest/types/enums/#definition

**Comment by joealcorn** [comment]
That's not my code :)

Mine looks like this

```python
class ProjectTypeEnum(graphene.Enum):
    PROTOTYPE = 1
    DESIGN = 2
```

I've been able to get the enum reflected in the schema but I can't manage to actually pass it values using graphql which is why I've been trying to find other ways.

```python
class CreateProjectInput(graphene.InputObjectType):
    type = ProjectTypeEnum(required=False)

class CreateProjectMutation(graphene.Mutation):
    class Input:
        data = graphene.Argument(CreateProjectInput)
```

<img width="352" alt="screen shot 2017-08-24 at 12 35 25" src="https://user-images.githubusercontent.com/1097349/29664722-c17322f0-88c8-11e7-8746-af5c99988107.png">



Request

```graphql
mutation mutName {
  createProject(data: {name: "Test", type: "PROTOTYPE"}) {
    ok
  }
}
```

Response

```json
{
  "errors": [
    {
      "message": "Argument \"data\" has invalid value {name: \"Test\", type: \"PROTOTYPE\"}.\nIn field \"type\": Expected type \"ProjectTypeEnum\", found \"PROTOTYPE\".",
      "locations": [
        {
          "column": 23,
          "line": 2
        }
      ]
    }
  ]
}
```

**Comment by totaki** [comment]
```python
class CreateProjectInput(graphene.InputObjectType):
    type = ProjectTypeEnum(required=False)
```
Where name field?

**Comment by joealcorn** [comment]
I took it out to keep the example short, it's there in reality.

The error message is specifically saying the value for the `type` field is wrong

```
Argument "data" has invalid value {name: "Test", type: "PROTOTYPE"}.
In field "type": Expected type "ProjectTypeEnum", found "PROTOTYPE".
```

**Comment by totaki** [comment]
Change field name :)

**Comment by joealcorn** [comment]
No luck there, but I have found a fix for the issue.
I've been passing the enum value incorrectly.

http://graphql.org/learn/schema/#enumeration-types

Notice that enums aren't defined as strings in the schema, but I've been passing a string in my mutation.

Here's a correct mutation:

```graphql
createProject(data: {type: PROTOTYPE}) {
    ok
}
```

Sorry for hijacking this issue! :)

**Comment by vincentfretin** [comment]
The issue is only on Python 3, this is because in graphene/types/enum.py
there is this:

```
try:                                                                            
    from enum import Enum as PyEnum                                             
except ImportError:                                                             
    from ..pyutils.enum import Enum as PyEnum
```

There seems to actually import again graphene/types/enum.py module, not the enum package from standard lib, as I found out last time I tried to debug this issue.
Try to rename graphene/types/enum.py to something else to see if this resolve the issue.

For a workaround, to not use the wrong imported enum, you can create your enum this way:

```
from graphene.pyutils.enum import Enum as PyEnum
sentiments_enum = PyEnum('SentimentTypes', (                                    
    ('LIKE', 'LIKE'),                                                           
    ('DISAGREE', 'DISAGREE'),                                                   
    ('DONT_UNDERSTAND', 'DONT_UNDERSTAND'),                                     
    ('MORE_INFO', 'MORE_INFO')))                                                
SentimentTypes = graphene.Enum.from_enum(sentiments_enum)
```

**Comment by janhancic** [comment]
Right, so the above are really unrelated to my original comment ...

**Comment by jkimbo** [comment]
Hi @janhancic . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by janhancic** [comment]
Yes, this is still an issue, and I'm waiting for some help from you guys :) (most of the latest comments are not related to my original issue)

**Comment by morenoh149** [comment]
@janhancic could you share a minimal graphene api that reproduces the issue? I actually cannot follow your snippets. Granted I'm new to GraphQL and graphene.
