### ISSUE TITLE
context_value passed to schema.execute should not be dictionary

### ISSUE THREAD

**Issue by picturedots** [graphql-python/graphene#523]
It seems that the all the documentation that uses `context_value` is supplying a dictionary for the value.  For example, from docs/testing/index.rst , the line

        executed = client.execute('''{ hey }''', context_value={'user': 'Peter'})

I believe that this incorrect -- the value `context_value` should actually be an object with an attribute user.  For example, this is working for me instead:

    from django.test import RequestFactory
    request_factory = RequestFactory()
    my_request = request_factory.get('/api/')
    my_request.user = User.objects.first() # randomly picking a real user
    executed = client.execute('''{ hey }''', context_value=my_request)

I am using RequestFactory to create a WSGIRequest object, which I believe is what the `execute` method needs instead of a dictionary for the `context_value` parameter, at least when using Django.

If someone can confirm that I am correct, I'll create the pull request to fix the documentation.

**Comment by abdulhaq-e** [comment]
The value it takes depends on the user. It is a `Request` object if you are using `graphene-django`. This repository is for `graphene`, a general framework for using GraphQL in Python, the GraphQL website has the following regarding `context`:

> **context** A value which is provided to every resolver and holds important contextual information like the currently logged in user, or access to a database.
http://graphql.org/learn/execution/

**Comment by picturedots** [comment]
Thanks -- I guess the documentation as it stands is correct then, but it's misleading for Django users, because there isn't any Django-specific testing docs.
