### ISSUE TITLE
Limiting introspection

### ISSUE THREAD

**Issue by dnltn** [graphql-python/graphene#524]
Hi there!

I was looking into how to implement something similar to the functionality that [Warden](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/schema/limiting_visibility.md) gives to graphql-ruby. Based on the context at execution time, I would like to hide certain schema elements from the user in queries, mutations, and introspection queries. 

Because users and their access can vary a lot in my app, I don't want to generate a separate Schema for each type of access.

What would be the suggested/best way to go about this? Should it be done in a custom Executor class? Maybe overriding GraphQLSchema, the type definitions, and TypeMap in graphql-python to take in masks could also work.

Also, would a feature like this be on the roadmap for this framework?

Some additional discussion:

* https://github.com/rmosolgo/graphql-ruby/issues/269
* https://github.com/graphql/graphql-js/issues/113

Thanks!

**Comment by jychen7** [comment]
It is kind of useful because in our case, we need `user_id` to resolve `user`

it would be better if frontend team only see `user` in introspection

**Comment by Fity** [comment]
Same issue with @pobed2 
Don't know how to solve it yet.

**Comment by harryjubb** [comment]
Gentle bump for this? With Graphene-Django I've made middleware to change access rights depending on whether the user is authenticated (see graphql-python/graphene-django#345), but the whole schema can still be introspected which is not ideal.

**Comment by jstacoder** [comment]
this is easily implemented as a middleware (easy for at least completley turning off introspection, i want to work on it more to possibly allow limited fields to be introspected) but for now i have a working graphene middleware here: https://github.com/jstacoder/graphene-disable-introspection-middleware

**Comment by fkromer** [comment]
Here's the doc to the [webonyx/graphql-php](https://webonyx.github.io/graphql-php/security/#disabling-introspection) implementation.

**Comment by ekampf** [comment]
For blocking introspection in production, the middleware solution @jstacoder described works fine
(and you can block introspection based on context - request parameters, headers, user etc. as the middleware gets the context via `info.context`)

However, I'm not what is the use case for only partially blocking the schema. It seems like a not very "GraphQL-y" solution.
I mean, if you look at Relay\Apollo as the main clients for GraphQL m- they need to know the schema at *build time* so you can't use such trickery...

You can use a middleware to determine permission to query certain values based on context but I'm not sure hiding values entirely from the scheme is something you want to do...

**Comment by jstacoder** [comment]
@ekampf 
we have a graphql api for our ios app to consume, it is not public facing, so this help by allowing us to have introspection in development (so we get highlighting and tab completion) but to restrict it in production, where it would only describe our api to people who dont need to know it.

**Comment by p8ul** [comment]
I found this helpful [disabling graphene introspection](https://medium.com/@pkinuthia10/disabling-djanog-graphene-introspection-query-8042b341c675)
