### ISSUE TITLE
How can I tell graphene to allow any number of arguments as input at a mutation?

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/graphene#525]
Currently my understanding of mutations and graphene have led me to believe that i have to explicitly tell 
what my inputs should be. 
But It has also come to my understanding that graphql can actually be told to capture 'all arguments that follow' into a single variable as 
referenced too in this line of code
https://github.com/EQuimper/twitter-clone-with-graphql-reactnative/blob/ep03/server/src/graphql/resolvers/tweet-resolvers.js#L7

I know that is js, but if there is a procedure to do such a thing in the language which the reference implementation is written in, shouldn't there be such a way in graphene?

**Comment by BossGrand** [comment]
You don't need to make graphene to take more then one input to accomplish this.

i.e
```javascript
editFoo(id: 5, fooString: "test", showOutput: true){
   isSuccessful
}
```
Should  be 

```javascript
editFoo(input: {id: 5, fooString: "test", showOutput: true}){
   isSuccessful
}
```

**Comment by japrogramer** [comment]
I see, so I don't have to do anything special in the input class?
thanks will try.

**Comment by BossGrand** [comment]
nah you don't, from a javascript perspective input is an object and you can put anything you like in your objects :)
