### ISSUE TITLE
Best practices for filtering queries based on grandchildren

### ISSUE THREAD

**Issue by btorellALTA** [graphql-python/graphene#537]
I'm a relative newcomer to GraphQL, and I've run into a bit of a question about the best way to filter a list based on a value on one of its grandchild relations. I am using SQLAlchemy, but not graphene-sqlalchemy as I am not using relay.

Consider this schema:

```
from graphene import ID, String, Int
from mymodels import CustomerModel, OrderModel, LineItemModel

class LineItem(ObjectType):
    id = ID()
    product_count = Int()
    product_name = String()

class Order(ObjectType):
    id = ID()
    line_items = List(LineItem, name=Argument(String))

    def resolve_line_items(self, args, context, info):
        query = LineItemModel.query.filter_by(order_id=self.id)
        if 'name' in args:
            query = query.filter_by(name=args.get('name'))
        return query.all()

class Customer(ObjectType):
    id = ID()
    name = String()
    country = String()
    orders = List(Order)

    def resolve_orders(self, args, context, info):
        return OrdersModel.query.filter_by(customer_id=self.id).all()

class Query(ObjectType):
    customers = List(TranslationJobGroup, country=Argument(String))

    def resolve_customers(self, args, context, info):
        query = CustomerModel.query
        if 'country' in args:
            query = query.filter_by(country=args.get('country')).first()
        return query.all()
```

Suppose, then I wanted to get a list of the names of all customers from the USA that had ever ordered products named "Foo", and how many they ordered. The *wrong* solution would be:

```
query {
    customers(country: "USA") {
        name
        orders {
            lineItems(productName: "Foo") {
                productCount
            }
        }
    }
}
```

This would correctly filter by customers by country, but obviously it would not filter customers by product name. It would instead return all customers from the USA, and *all* their orders, except the orders list of LineItems not matching "Foo" would be empty.

The only way I can see to filter the customers list itself is in the customers resolver, and the only way I can see to do that is to pass a custom argument, and filter using joins, like so:

```
class Query(ObjectType):
    customers = List(TranslationJobGroup, country=Argument(String), with_product_order=Argument(String))

    def resolve_customers(self, args, context, info):
        query = CustomerModel.query
        if 'country' in args:
            query = query.filter_by(country=args.get('country')).first()
        if 'with_product_order' in args:
            query = query.join('orders', 'line_items').filter_by(product_name=args.get('with_product_order')).first()
        return query.all()
```

And then changing the query thusly:

```
query {
    customers(country: "USA", withProductOrder: "Foo") {
        name
        orders {
            lineItems {
                productCount
            }
        }
    }
}
```

However, this filtering method feels...wrong, somehow? I suspect that at least part of this is due to my unfamiliarity with GraphQL, but it feels bad having to add custom arguments everywhere to do this sort of sub-filtering, as well as the need to reach out via joins to execute the actual filter. Part of the appeal of GraphQL, to me, was that query construction was more organic and didn't need a bunch of custom parameters that didn't exist on the corresponding models.

What is the normal GraphQL way of dealing with this problem? What should the API normally look like for such filtering, and how should the resolvers be designed to work to account for it? Do I just bite the bullet and add custom parameters everywhere, or is there a better solution?

**Comment by earlgreyz** [comment]
GraphQL allows you to traverse graph and there is no way to filter on child node properties. In many cases you create backrefs and traverse graph starting in child nodes and then going back to parent, but as you need to filter on both parent and child this won't help you. It feels wrong because GraphQL was not meant for this kind of queries, however your solution is correct for this particular problem.

**Comment by mpmlj** [comment]
@btorellALTA 
I'm in the same situation and just had to implement a list of custom arguments specifically for that, ex. `content_slug` that goes into a related Content type to filter by `slug`.

However, that said, I initially started with this: https://github.com/graphql-python/graphene-django/blob/master/docs/filtering.rst
And looks like it should work with `django-filters`  / `DjangoFilterConnectionField`, allowing you to use arguments like `content__slug` <- check the double underscore in it. Had to stop as getting mixed set of different issues.

**Comment by jkimbo** [comment]
Hi @btorellALTA . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
