### ISSUE TITLE
Website docs describe unreleased 2.0 version?

### ISSUE THREAD

**Issue by denisw** [graphql-python/graphene#538]
It seems that the docs on the Graphene website are for Graphene 2.0 although the current version is still 1.4.1. For instance, the "Mutations" page says that mutation arguments should be defined with a `class Arguments`, while in 1.4.1 only `class Input` seems to work.

**Comment by anisjonischkeit** [comment]
Is graphene 2.0 stable enough for us to start testing with? Is syntax stable?

**Comment by zahlio** [comment]
We would also like to hear about the state of 2.0. Docs tell you to use 2.0 (although its a dev release), should we use 2.0 or stay on 1.X for now?

What is the timeline of 2.0?

**Comment by caffodian** [comment]
I also have similar questions - it would be nice if there was a PR or issue organizing what is left before a 2.0 release (we could even help out, too, if we knew what was needed)

**Comment by mraak** [comment]
It's still not tagged so I guess it's not stable enough.

**Comment by syrusakbary** [comment]
I was waiting for Subscriptions to release the next stable version of Graphene 2.0.

Today, I released Graphene 2.0 (with support to subscriptions) in the GraphQL Summit.

Closing this issue now :)
