### ISSUE TITLE
Running a query without a schema

### ISSUE THREAD

**Issue by pwuertz** [graphql-python/graphene#540]
I'd like to inspect a live data structure on a python server and graphql/graphene seems to be ideal for that task. But from the documentation it seems that any data source must be completely defined by a static schema. Is it possible to use graphene to run queries directly against a python dict/list without being committed to a schema? E.g:

```python
# data dict at the service
data = {
    "too": 42,
    "much": [1, 2],
    "data": "hello world"
}

# query issued by the client
query = """
query data {
    much(1),
    data
}
"""

# run query directly on python dict
result = run_query(query, data)

# result returned to the client
{
    "data": {
        "much": 2,
        "data": "hello world"
    }
}
```

**Comment by earlgreyz** [comment]
You need a schema to query. GraphQL is strongly-typed and you also need resolvers to tell graphene how to get the data from the dict. To make this example work you'll need something like:

```python
from functools import partial
import graphene

SOME_DATA = {
    "too": 42,
    "much": [1, 2],
    "data": "hello world"
}

def resolver(param, self, args, context, info):
    return self[param]


class MyData(graphene.ObjectType):
    too = graphene.Int()
    much = graphene.Field(graphene.Int, index=graphene.Int())
    data = graphene.String()

    resolve_too = partial('too', resolver)
    resolve_data = partial('data', resolver)

    def resolve_much(self, args, context, info):
        index = args.get(index)
        return data['much'][index]


class Query(graphene.ObjectType):
    data = graphene.Field(MyData)
    def resolve_data(self, args, context, info):
        return SOME_DATA

schema = graphene.Schema(query=Query)

result = schema.execute('''
{
    data {
        much(1)
        data
    }
}
''')

print(result.data)
```

The result would be
```json
{
    "data": {
        "much": 2,
        "data": "hello world"
    }
}
```

You might write something more generic to map your dict to graphene type (check out `graphene-sqlalchemy` library source code or `graphene-django`). Let's say you created `graphene-dict` library based on the `graphene-sqlalchemy`/`graphene-django` - then mapping/resolving is generated automatically and you might do:

```python
import graphene
from graphenedict import DictObjectType


class MyData(DictObjectType):
    class Meta:
        model = SOME_DATA

class Query(graphene.ObjectType):
    data = graphene.Field(MyData)
    def resolve_data(self, args, context, info):
        return SOME_DATA

schema = graphene.Schema(query=Query)
```

Don't worry it's actually easier than it sounds ;D.

**Comment by pwuertz** [comment]
Thanks you @earlgreyz for this in-depth explanation! Basically my understanding of graphene's principles was very limited. When I saw its query/response syntax for the first time I was intrigued by the idea of using this protocol in my application as a type of generic object debug/inspection tool (so no statically defined type hierarchy).

With graphene relying on static, strongly typed interfaces this doesn't seem to be the right tool for this specific use case. But if things get more settled here I'd love to take a shot at `DictObjectType` and post my results.

Thanks again!
