### ISSUE TITLE
graphene <= 1.4.1 break as they require graphql-core>=1.1 (breaking in 2.0.dev)

### ISSUE THREAD

**Issue by richmondwang** [graphql-python/graphene#541]
As the title clearly says, graphene requires `graphql-core>=1.1` and a breaking change in `2.0.dev` resolver signature is introduced, which breaks all graphene versions prior to `2.0.dev`

Encountered error: 

```
TypeError: resolve() takes exactly 6 arguments (4 given)
```

**Comment by yarian** [comment]
Experiencing same issue. This broke production for us. `got an unexpected keyword argument`

**Comment by crucialfelix** [comment]
This also broken in pre-2.0 releases. If you pip install:

    graphene==1.4.1
    graphene-django==1.3

You get:

    graphene (1.4.1)
    graphene-django (1.3)
    graphql-core (2.0)
    
And we get the mysterious deep error `TypeError: resolve() takes exactly 6 arguments (4 given)` because graphql-core 2 is not compatible with graphene

The solution is to explicitly add this to requirements:

    graphql-core==1.1.0

**Comment by jkimbo** [comment]
Hi @richmondwang . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by 0xCMP** [comment]
For anyone experiencing this issue please be sure to update your version of `pip` first. I had 1.5.4 installed and it wouldn't respect the `,<2` restraint.
