### ISSUE TITLE
ObjectType as data container with resolver

### ISSUE THREAD

**Issue by mplis** [graphql-python/graphene#548]
The [docs](http://docs.graphene-python.org/en/latest/types/objecttypes/#instances-as-data-containers) mention that `ObjectType`s can be used as data containers like so:

```python
peter = Person(first_name='Peter', last_name='Griffin')

peter.first_name # prints "Peter"
peter.last_name # prints "Griffin"
```

**But what if I want to get an attribute after it's passed through it's resolver?** Here's an example similar to my use case:

```python
class Person(ObjectType):
  first_name = String()
  last_name = String()
  height = Int()

  def resolve_height(self, info):
    return int(self.height)

person_data = {
  'first_name': 'Peter',
  'last_name': 'Griffin',
  'height': '70' # note that this is a string instead of an int
}

peter = Person(**person_data)

type(peter.height) # <type 'str'> - but I want this to be <type 'int'>
```

The reason I'm doing this is because I'm building a GraphQL wrapper around a REST API using graphene and I'm populating a class like this with data from the API, but there are cases where I want to expose a different type than the API does (like changing `height` from a string to an integer).

**Comment by nderkach** [comment]
Simply changing the data type in `Person` to `Int()` should work. Btw, in your example, the resolver is never called.

**Comment by mplis** [comment]
> Btw, in your example, the resolver is never called.

I think that's my problem. I want the resolver to be called when using an `ObjectType` as a data container. I thought it might be called on `__init__` but I don't think that's happening, since in my example, `peter.height` is a string not an integer. Is the only solution to call the resolver manually?

**Comment by jkimbo** [comment]
Hi @mplis . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
