### ISSUE TITLE
Playground uses Graphene 2.0, but example written for 1.0

### ISSUE THREAD

**Issue by martinpeck** [graphql-python/graphene#549]
Visitors to graphene.python.org are given the opportunity to use the Playground. When they do, they are presented with the following Python code...

```python
import graphene

class Query(graphene.ObjectType):
    hello = graphene.String()

    def resolve_hello(self, args, context, info):
        return 'World'

schema = graphene.Schema(query=Query)
```

As you can see, this resolver function takes 4 params.  

When executed, the user is presented with the following result:

```json
{
  "errors": [
    {
      "message": "resolve_hello() takes exactly 4 arguments (2 given)",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ],
  "data": {
    "hello": null
  }
}
```

I believe that this is because the example code is written against the 1.0 API, but the Playground is running against the 2.0 API. 

This is a pretty poor initial experience of Graphene for new users, as it's not clear how to resolve the issue.

**Comment by japrogramer** [comment]
wonder if there is any relation to #538

**Comment by metrafull2** [comment]
use def resolve_hello(self, info, **kwargs): instead, is a problem in this patch, I don't know why

**Comment by syrusakbary** [comment]
Closing as now the website have no playground (once it have it again, will be with the new syntax :) )
