### ISSUE TITLE
define schema using type language 

### ISSUE THREAD

**Issue by seansay** [graphql-python/graphene#550]
I saw there's an type language here from graphql website http://graphql.org/learn/schema/#type-language 

and the `graphql-js` seems to have this thing which you could build schema from the type language, does this thing exist already for graphene? Or any plan to add this?

```
var { graphql, buildSchema } = require('graphql');

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type Query {
    hello: String
  }
`);
```

**Comment by badrobit** [comment]
I would also really like to be able to ingest a schema using the type language, maybe to simplify things just the datatypes instead of the methods but some form of pulling this in would be amazing!

**Comment by jkimbo** [comment]
Looks like @jasonphillips has implemented something similar to this in https://github.com/graphql-python/graphene/issues/448 

Closing this issue in favour of that one
