### ISSUE TITLE
Website documents Graphene 2.0, but 2.0 is unreleased

### ISSUE THREAD

**Issue by g--** [graphql-python/graphene#553]
Hey folks!  I'm having trouble following the website documentation and coding against a 1.x graphene release.  I'm not 100% positive about this, but I get the impression that:

a. 2.0 is coming out soon, and it's going to be awesome, but it's still in "alpha" and shouldn't be used for production things just yet.
b. the documentation on the website is written for Graphene 2.0.
c. points a&b are not obvious from reading the Graphene website

If that's more or less what's happening, I'd say it's awesome the documentation is being updated at the same time as the codebase.  Keep up the awesome work!

**Comment by ravangen** [comment]
Seems to relate to https://github.com/graphql-python/graphene/issues/538

**Comment by g--** [comment]
Yup! Duplicate

**Comment by dperetti** [comment]
At least some warning on the website about this would prevent every newcomer from wasting a couple hours of his lifetime...

**Comment by ekampf** [comment]
2.0 is out. Can close this...
