### ISSUE TITLE
How to find a mutation in a big codebase

### ISSUE THREAD

**Issue by mbrochh** [graphql-python/graphene#557]
A colleague just asked me "Where do I find the SignupMutation" and I told him "it's in accounts.schema.py"

And I realized, there is no easy way for a frontend developer who writes queries in graphiql and apollo, to find a mutation in the python backend code.

For Queries, it's simple, you can turn the query name into snake-case and prepend `resolve_` but for mutations it's not so simple, because there is no resolver function and the class names for the mutation classes can be anything.

Is there some cool way, maybe a Django management command, that lists all queries and mutation endpoints and the files where they are implemented in?

I suggested to use a regex search over the project, i.e. `signup = .*\(` - that would have found exactly the place, but I still wonder if there is a better way to get this information.

**Comment by dfee** [comment]
You can access all known types via `schema.get_type`. For instance:

```python
SignupMutation = schema.get_type('SingupMutation')
print('{}.{}'.format(SignupMutation.__module__, SignupMutation.__qualname__)
```

**Comment by abdulhaq-e** [comment]
You can give the front-end developer a link to the `graphiql` client from which he/she can see everything.

**Comment by jkimbo** [comment]
Hi @mbrochh . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 3 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by jakesyl** [comment]
This looks resolved.
