### ISSUE TITLE
Conditionally used resolve methods

### ISSUE THREAD

**Issue by achimnol** [graphql-python/graphene#563]
I'm writing some codes like below (this is a full working example):

```python
import graphene
import json
from collections import namedtuple


Row = namedtuple('Row', 'status value')

database = [
    Row(status='LIVE', value=1),  # value should be ignored and replaced with 12345
    Row(status='X', value=2),     # value should be preserved
]


class Something(graphene.ObjectType):
    status = graphene.String()
    value = graphene.Int()

    def resolve_value(self, info):
        return 12345  # fetch some value from a remote resource

    @classmethod
    def from_row(cls, row):
        if row.status == 'LIVE':
            # let it use the resolver method to get the latest value
            return cls(status=row.status)
        else:
            # provide some default or cached/stored "value"
            return cls(status=row.status, value=row.value)


class Query(graphene.ObjectType):
    things = graphene.List(Something)

    @staticmethod
    def resolve_things(executor, info):
        return [Something.from_row(row) for row in database]


if __name__ == '__main__':
    schema = graphene.Schema(
        query=Query,
        mutation=None,
        auto_camelcase=False)
    result = schema.execute('{ things { status value } }')
    print(json.dumps(result.data))
```

The problem is that, regardless of `status`, it always uses the `resolve_value()` method.

Expected:
```
{"things": [{"status": "LIVE", "value": 12345}, {"status": "X", "value": 2}]}
```

Actual:
```
{"things": [{"status": "LIVE", "value": 12345}, {"status": "X", "value": 12345}]}
```

What I expected is that it does *not* call the `resolve_value()` method if the `value` field is already "resolved" by being given the initial value when an ObjectType is instantiated.
Please let me know if I'm missing something.

**Comment by achimnol** [comment]
I could workaround this by modifying the `resolve_value()` method:

```python
    def resolve_value(self, info):
        if self.status == 'LIVE':
            return 12345  # fetch some value from a remote resource
        else:
            return self.value
```

But this seems to be unnecessary if graphene/graphql supports conditional use of resolvers.

**Comment by achimnol** [comment]
I began to suspect the root cause of this design "hole" is because there is no discretion between "undefined" and "null" values in Python like Javascript. Maybe we could use a sentinel object to represent undefined values throughout the graphene API.

**Comment by japrogramer** [comment]
Like a custom Scalar ?

**Comment by japrogramer** [comment]
could you change the resolve method to be, 
```
def resolve_value(self, info, **args):
     if hasattr(self, 'value'):
         if self.value:
              return self.value
      return 12345
```

**Comment by jkimbo** [comment]
Hi @achimnol . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 3 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!
