### ISSUE TITLE
parent relationship query in children

### ISSUE THREAD

**Issue by Fercho191** [graphql-python/graphene#564]
Hello! I would like to ask something that is happening to me and if it is the default behavior or if it is an error.

I have a parent model (for example, parent)
```python
class Parent(model.Model):
    name = models.CharField()
```
and a child model
```python
class Child(Parent):
   age = models.IntegerField()
```

I have created a model with a relationship with the parent
```python
class RelatedModel(models.Model):
   parent = models.ForeignKey(Parent, related_name="relations")
```

I have created the DjangoObjectType for each one (using interfaces = (relay.Node,))

When I make a query for the child, the relation does not appear in the Graphiql, therefore, it forces me to do the following:

```
{
    childs {
        edges {
            node {
                id
                parentPtr {
                    relations {
                        id
                    }
                }
            }
        }
    }
}
```

Is the parentPtr necessary? or is there a way to not appear in the query?

**Comment by jkimbo** [comment]
Hi @Fercho191 . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by Fercho191** [comment]
i solved this issue making a `BaseParentNode (AbstractType)` with childs common fields and create 'relay Nodes' inheriting from BaseParentNode
