### ISSUE TITLE
Subclass InputObjectType like test_425

### ISSUE THREAD

**Issue by dfee** [graphql-python/graphene#566]
There is a bug [here](https://github.com/graphql-python/graphene/blob/3ce6031192c7be1b7986448f18a227b1f971b6a3/graphene/types/inputobjecttype.py#L57) which is quite similar to [test_425](https://github.com/graphql-python/graphene/blob/2.0/graphene/tests/issues/test_425.py) which prevents creating a custom `Meta` for `InputObjectType`.

The fix to this is to replicate what is done with [`ObjectType.__init_subclass_with_meta__`](https://github.com/graphql-python/graphene/blob/3ce6031192c7be1b7986448f18a227b1f971b6a3/graphene/types/objecttype.py#L31) -- i.e. don't re-create `_meta` if it's already supplied.

I'll try and find another workaround, but as @syrusakbary seems to be busy with other things (issues & pull requests don't seem to be readily addressed) I'm not convinced putting in the work to make a pull request is worth it.

**Comment by japrogramer** [comment]
I found a work around, 
mine is to have this
class SomeInput:
    class Meta:
             stuff
    def __new__(cls):
    return type('test', (InputObjectType),  ... )

**Comment by dfee** [comment]
Just wanted to leave a note for the future, this is the case for `graphene.Enum` as well.
