### ISSUE TITLE
graphene.types.utils.get_type should take full advantage of import_string

### ISSUE THREAD

**Issue by dfee** [graphql-python/graphene#567]
[`import_string`](https://github.com/graphql-python/graphene/blob/d594a0eca86102ce2ebf9633018437eef8997f42/graphene/utils/module_loading.py#L5) works well. Unfortunately, [`get_type`](https://github.com/graphql-python/graphene/blob/0b92d3dba64f438e97a955d13f2ec542705d1e5e/graphene/types/utils.py#L43) doesn't take advantage of it's ability to accept a second argument, `dotted_attributes`.

The consequence of this is that users are unable to nest ObjectTypes inside a class – say, as an attribute.

In my case, this means that the dynamically generated InputObjectTypes must also be injected into the module namespace, which is poor behavior.

Looking at [`types.Argument`](https://github.com/graphql-python/graphene/blob/ab5a11b3993ae1dac1b8bef7974703c922b3a168/graphene/types/argument.py) it might seem that this functionality was omitted as it's difficult to implement.

However, an acceptable solution might be to modify `get_type` to look something like this:
```
class LazyType:
    def __init__(self, dotted_path, dotted_attributes=None):
        self.dotted_path = dotted_path
        self.dotted_attributes = dotted_attributes

def get_type(_type):
    if isinstance(_type, LazyType):
        return import_string(_type.dotted_path, _type.dotted_attributes)
    if isinstance(_type, string_types):
        return import_string(_type)
    if inspect.isfunction(_type) or isinstance(_type, partial):
        return _type()
    return _type
```

**Comment by jkimbo** [comment]
@dfee is this issue still important?
