### ISSUE TITLE
[Question] How can i put extra fields on edges and populate those fields with data?

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/graphene#568]
Hello I would like to create a connection to my type with an edge where the edge has the same fields as those in the through table.
By looking at this http://docs.graphene-python.org/en/latest/relay/connection/
I don't see that there is any resolve method for the fields in the edges so how do they get resolved and does the respective item from the resolve for the connection get passed to the edge? If so I can see how this would work.

**Comment by japrogramer** [comment]
Is there a method where the node that connects to an edge is passed into where I can then use to to set the appropriate value for the field on the edge

something maybe like this:

```
class Ship(graphene.ObjectType):
    '''A ship in the Star Wars saga'''
    class Meta:
        interfaces = (relay.Node, )

    name = graphene.String(description='The name of the ship.')

    @classmethod
    def get_node(cls, info, id):
        return get_ship(id)
class ShipConnection(Connection):
    extra = String()

    class Meta:
        node = Ship
     

    class Edge:
        other = String()
        def resolve_other(self, info, **args):
              # here I imagine self being the node value for this edge
              return self.value
```

**Comment by japrogramer** [comment]
well, It looks like the above code works but I would like to have access to the Ship from the Edge.
currently I have access to the Node In Edge but not the Ship.

**Comment by japrogramer** [comment]
well, I found a way to work around the problem I was having. so I guess Ill be closing this.

**Comment by tony** [comment]
> well, I found a way to work around the problem I was having. so I guess Ill be closing this.

Hi!  I know this was a long time ago, Do you have any more details to on this? (for those who were searching?)
