### ISSUE TITLE
[Feedback] Too much boilerplate for simple CRUD

### ISSUE THREAD

**Issue by llevar** [graphql-python/graphene#571]
I like what you have done in implementing the GraphQL standard in Python, but in my opinion too much boilerplate code needs to be written in order to implement a simple value object lifecycle. I think your framework would be improved a lot if the vanilla use case of CRUD operations (+list) was achievable with as little extra code as possible (with decorators perhaps).

**Comment by japrogramer** [comment]
How are you doing CRUD?
do you mean the type and Input declaration? are you using graphene with django?

**Comment by llevar** [comment]
I have Graphene + SQLAlchemy + Postgres + Flask on server and React + Relay on front end. There's a well defined business layer on the server and my ideal scenario would be to add some decorators to generate a GraphQL endpoint that can handle CRUD operations on those objects, delegating to SQLAlchemy for ORM. Now I had to define all of these classes by hand, even though they are completely vanilla - "fetch object by id", "fetch all objects", "create new object", "update object by id".

**Comment by ekampf** [comment]
Sounds like a task for `graphene-sqlalchemy` to provide default resolvers...

**Comment by japrogramer** [comment]
you could try making a class, that takes that boiler plate away.
Right know im using graphene-django's construct_fields method in a class generator that generates the input class that take some of the boiler plate away. Im also working on making generic CRUD classes to take away some of the boiler plate. 
But for know I wrote a long snippet that at least makes writting them a little faster.

**Comment by llevar** [comment]
@ekampf Why do you think this needs to be tied to sqlalchemy? If I have a set of Python objects that have a basic CRUD lifecycle I would want to be able to serve them up via GraphQL by writing minimal additional code, whatever they are backed up (if anything). I don't think a dependency on SQL Alchemy is necessary at that point since the interaction between Graphene and these objects should be via their lifecycle (create_blah(), update_blah(), etc.) methods.

**Comment by japrogramer** [comment]
Probably because graphene is design to be agnostic on how the data is retrieved.

**Comment by japrogramer** [comment]
... altho I can think of one instance where graphene and more specifically relay could be more agnostic and make less assumptions about how data is retrieved. And that is in relay.Connection.
hmm, I should open an issue about this.

**Comment by llevar** [comment]
That's kind of my point, presuming you have a business layer that defines lifecycle methods for your objects you ought to be able to annotate these and have graphene auto-generate an endpoint that serves these up without peering into the data access layer.

**Comment by ekampf** [comment]
@llevar implementing CRUD implies writing entities to some store.
You could write a class that implements given an object implements basic create\update\delete mutations but what will those mutations it implements for you do? they have to be tied to some DB right?
Something like:

```
PersonMutations = SQLAlchemyCRUDMutations(Person)

class MutationsRoot(ObjectType, PersonMutations):
   ...
```

Will implement basic `createPerson`, `updatePerson`, `deletePerson` mutations that update the DB with a person entity (You know all the fields from the meta of the `Person` ObjectType so you can create all the types required for said mutations)

**Comment by ekampf** [comment]
`presuming you have a business layer that defines lifecycle methods` 
Similar to what I described above you can probably write a code that takes a function as input (which would be one of your business layer's functions) and infer a Mutation schema from it using Python inspect capabilities.
However, how would you infer types?
Say you have a function: `def updatePerson(person_id, name, age)` how would you infer a Mutation schema who's input is `name` that's a `String` and `age` that is an `Int` ?
If your business layer exposes this information in some way you can write a utility method that automatically converts your business layer functions to mutations...

**Comment by japrogramer** [comment]
Could create a class that generates a class with the correct mutation. The class could have a Meta class that has a Interface as an attribute. It could than infer that it has standard method names for CRUD.
to than create an ObjectType with the correct mutation interface. you could use
`inspect.getargspec(foo)`
to inspect the call signature of function foo combined with pythons new type system it would be trivial to get the appropriate field type from the call signature. 
Than simply add appropriate attributes to the generated class.

**Comment by dfee** [comment]
For what it's worth, I'm in the process of building a package (with the intent of open sourcing) that takes care of a bunch of the boilerplate. There are a handful of constraints in it, inherent due to the structure of `graphene`. Search for issues related to my name, and you'll get a clue as to what those constraints are.

The goal is to get it out in the next few days.

**Comment by SpaceK33z** [comment]
@dfee I was wondering if you ever got around to publishing your package?

**Comment by dfee** [comment]
@SpaceK33z I'm actually *still* working on it. It's pretty much an identical clone of graph.cool's api.

It has query / mutation / subscription support, but is currently hung up on a couple issues, I'm sorting through – largely speaking, that's graphene / graphql naming.

**Comment by dani0805** [comment]
I am trying to find a workable solution too this and I am wandering off in this particular direction, basically trying to scan the model and autogenerate the schema on the fly:

```
registry = {}


def register(target_class):
    registry[target_class.__name__] = target_class


def c2u(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


class AutoSchemaMeta(type):

    def __new__(meta, clsname, superclasses, attributedict):
        new_class = type(clsname, superclasses, attributedict)
        for app_name in new_class.app_models.split(","):
            app_models = apps.get_app_config(app_name.strip()).get_models()
            for model in app_models:
                model_name = model.__class__.__name__
                _node_class = type("{}Node".format(model_name),
                    (DjangoObjectType,),
                    {"Meta":{"model": model, "interfaces": (Node,), "filter_fields": []}})
                register(_node_class)
                setattr(new_class, "all_{}s".format(c2u(model_name)), DjangoFilterConnectionField(_node_class))
                setattr(new_class, "{}".format(c2u(model_name)), Node.Field(_node_class))
        return new_class


class Query(metaclass=AutoSchemaMeta):

    app_models = "app1,app2"
```

but I am running in some kind of recursion... `AssertionError: Found different types with the same name in the schema: ModelBaseNode, ModelBaseNode.` Anyone cares to chip in?

**Comment by dani0805** [comment]
I corrected my code and now I can automagically generate the schema from the model with 2 lines of configuration, namely which apps I want and which models I want.

```
registry = {}


def register(target_class):
    registry[target_class.__name__] = target_class


def c2u(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def s2p(name):
    s1 = re.sub("y$", "ie", name)
    return "{}s".format(s1)


class AutoSchemaMeta(type):

    def __new__(meta, clsname, superclasses, attributedict):
        new_class = type(clsname, superclasses, attributedict)
        include = new_class.include_models.split(",")
        for app_name in new_class.app_models.split(","):
            app_models = apps.get_app_config(app_name.strip()).get_models()
            for model in app_models:
                model_name = model._meta.model_name
                _model_name = c2u(model_name)
                if hasattr(new_class,_model_name) or not model_name in include:
                    continue
                class_name = "{}Node".format(model_name.title())
                _node_class = type(class_name,
                    (DjangoObjectType,),
                    {"Meta":{"model": model, "interfaces": (Node,), "filter_fields": []}})
                register(_node_class)
                setattr(new_class, "all_{}".format(s2p(_model_name)), DjangoFilterConnectionField(_node_class))
                setattr(new_class, _model_name, Node.Field(_node_class))
        print(new_class.__dict__)
        return new_class


class Query(metaclass=AutoSchemaMeta):

    app_models = "app1,app2"
    include_models ="country, address,phone"
```

Is this something that we could build upon to provide a default schema? I welcome any suggestion to improve on this.

**Comment by lovetoburnswhen** [comment]
> @SpaceK33z I'm actually _still_ working on it. It's pretty much an identical clone of graph.cool's api.
> 
> It has query / mutation / subscription support, but is currently hung up on a couple issues I'm sorting through – largely speaking, that's graphene (python) / graphql naming.
> 
> (p.s. it's currently sitting at something like 7500 lines of code with about 750 tests).

Any updates?
