### ISSUE TITLE
How to query translated fields (django-parler)

### ISSUE THREAD

**Issue by taut-and-yare** [graphql-python/graphene#572]
Assuming a model that has translated fields like so:
```
from parler.models import TranslatableModel, TranslatedFields

class Article(TranslatableModel):
    #regular fields
    publishing_date = models.DateTimeField(_('publishing date'),
                                           default=now)
    # translated fields
    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=234),
        slug=models.SlugField(
            verbose_name=_('slug'),
            max_length=255,
            db_index=True,
            blank=True,
        ),
        meta_title=models.CharField(
            max_length=255, verbose_name=_('meta title'),
            blank=True, default=''),
        meta_description=models.TextField(
            verbose_name=_('meta description'), blank=True, default=''),
        meta_keywords=models.TextField(
            verbose_name=_('meta keywords'), blank=True, default=''),
    )
```
How can we query those?

**Comment by japrogramer** [comment]
This doesn't seem to be a graphene problem as detailed here 
http://django-parler.readthedocs.io/en/latest/advanced/mptt.html#combining-managers

**Comment by jkimbo** [comment]
Closing this issue as part of a clean up effort. @taut-and-yare if you are still having issues then please comment and I'll reopen.

**Comment by techdragon** [comment]
@jkimbo I'm currently having this exact issue. The graphene/graphene-django documentation is not yet complete enough for me to see a way to solve this similar to the linked to method of combining managers by inheritance. 

Django-CMS makes _heavy_ use of django-parler so not having a simple solution/documentation to do this will prevent anyone who can't figure out how to extend graphene/graphene-django enough to support this sort of translated model inheritance, from being able to use it with Django-CMS based sites.
