### ISSUE TITLE
[PROPOSAL] Tutorial

### ISSUE THREAD

**Issue by patrick91** [graphql-python/graphene#574]
I think this project will benefit having a tutorial like the [Django Polls Tutorial](https://docs.djangoproject.com/en/1.11/intro/tutorial01/).

I was thinking to divide the tutorial in the following sections:

- [ ] Writing your first schema (same as the getting started)
- [ ] Creating your first query (setting up data)
- [ ] Creating your first mutation
- [ ] Integration with flask
- [ ] Pagination

This is just an idea, not sure if I'll end up with that structure. But what I'd like
to show in this how you can create a simple GraphQL schema in not too much time.
Then we can add additional sections, like:

- [ ] Authentication
- [ ] Permission
- [ ] Caching / Data Loaders

If you have any addition topic that should be covered in the tutorial let me know :)

Also, if you think there's a better example (the polls app is quite simple) let me know as well.

I plan to work on this in the next few weeks :)

**Comment by syrusakbary** [comment]
I think that's a great idea @patrick91!

**Comment by rdemetrescu** [comment]
Amazing @patrick91 .

If possible, could you include info on how to work with Relay and how to address situation where you already have "id" as a column name of your tables/models and using SQLAlchemy ?

(I am thinking about problem described here:  https://github.com/facebook/relay/issues/1061)

Thanks in advance!

**Comment by patrick91** [comment]
@rdemetrescu I never used Relay! I use Apollo, but I might try it :)

Are you using Relay Modern?

**Comment by rdemetrescu** [comment]
@patrick91 , no, I'm doing my first project with Aurelia + Apollo at client side and Graphene + Flask + SQLAlchemy at server side.

Trying to figure out best practices to implement pagination, authentication, authorization at both sides.  :)

I mentioned Relay because, I liked the pagination support it gives. But i guess we can't use Relay + Apollo together, right?

**Comment by patrick91** [comment]
Oh I see what you mean! You can definitively use "relay" with Apollo. For some reason I thought of the Relay client, not the specification :)

See here: https://facebook.github.io/relay/docs/graphql-relay-specification.html

It is "just" a standardised way to add pagination to a graphql field, I'll try to add that in the tutorial as well :)

**Comment by hbutau** [comment]
@patrick91  the idea of a [Django Polls Tutorial](https://docs.djangoproject.com/en/1.11/intro/tutorial01/) like tutorial is great. Just wanted to ask if you will be doing a django-graphql-apollo-ember one also?

**Comment by syrusakbary** [comment]
@patrick91 any progress on the tutorial?

**Comment by patrick91** [comment]
@hbutau I don't use ember, sorry!
@syrusakbary no :( it's on my task list for sunday tho :)

**Comment by SAThomsen** [comment]
It would be awesome with proper coverage of mutations as well the current django-tutorial does not describe that :) 
http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/

**Comment by patrick91** [comment]
@all sorry, I've been busy on so many things during the last few months, I'll try to get back to this soon :)

**Comment by anudeepsamaiya** [comment]
@ALL can I pick this and continue from @syrusakbary left?

**Comment by morenoh149** [comment]
@anudeepsamaiya I'd imagine you're free to pick this up. It's been a few months.
