### ISSUE TITLE
[Question] Timeline of 2.0?

### ISSUE THREAD

**Issue by stasm** [graphql-python/graphene#577]
(I haven't found a better way to ask this.)

What would be the best way of learning more about the timeline of 2.0? It looks very promising! Having some visibility into the release planning would help the current users of 1.4 plan the upgrade. Thanks!

**Comment by pbaranay** [comment]
@stasm This is also being discussed in #538...looks like others have the same question!

**Comment by syrusakbary** [comment]
Sorry for not announcing the plan for it before.

I released the stable version of Graphene 2.0 today 24 Oct at GraphQL Summit.

Closing the issue :)

**Comment by stasm** [comment]
No worries and congrats on the release! :)

**Comment by dmr** [comment]
Congratulations on the new release!

I have one question: Is there an documentation on the new subscriptions features?
I did not find any in the documentation.
