### ISSUE TITLE
Cannot set name nor description of a mutation

### ISSUE THREAD

**Issue by sboisson** [graphql-python/graphene#593]
For example:

```
class Mutations(graphene.ObjectType):  
    add_question_to_faq = AddFAQEntry.Field(name="addQuestionToFAQ", description="Add a question the FAQ")
```

The mutation should be named `addQuestionToFAQ` and the description should be provided in the schema.

**Comment by sboisson** [comment]
#594

**Comment by jkimbo** [comment]
This was fixed by https://github.com/graphql-python/graphene/commit/a7a4ba62af4cb8b00ffa6a9f8cf79bd87dfb5e95 and will be released soon.
