### ISSUE TITLE
InputObjectTypeContainer should set all type attributes

### ISSUE THREAD

**Issue by nparrish** [graphql-python/graphene#597]
One point made in the 2.0 upgrade guide is this:

> If you are using InputObjectType, you now can access its fields via getattr (my_input.myattr) when resolving, instead of the classic way my_input['myattr'].

However, this is only true if all fields on the input type are _required_.  If the fields are optional, and not provided by the caller, then asking for that value will return a raw graphene field (for example, `List`).

Created #596 to address this.

**Comment by jkimbo** [comment]
Looks like this has been resolved now. Closing.
