### ISSUE TITLE
Input object field validation/resolving

### ISSUE THREAD

**Issue by victorandree** [graphql-python/graphene#600]
It would be neat to be able to define validation rules at the `InputObjectType` level. For examples, if I have an argument which is a list of integers that must sum to 100 in order to be valid. One might even expect that `resolve_<field>` on an `InputObjectType` would be called to get the value of that field -- where the alarm could be raised.

```
class Position(graphene.InputObjectType):
    date = graphene.types.datetime.Date(required=True)
    shares = graphene.List(graphene.NonNull(graphene.Int), required=True)

    def resolve_shares(self, info):
        # Maybe shares could be resolved and validated here?
        return self.shares
```

Edit: I looked at the UPGRADE guide and saw this example:

```
class UserInput(InputObjectType):
    id = ID(required=True)

    @property
    def is_valid(self):
        return self.id.startswith('userid_')

class Query(ObjectType):
    user = graphene.Field(User, input=UserInput())

    def resolve_user(self, info, input):
        if input.is_valid:
            return get_user(input.id)
```

This makes sense -- you're not really resolving fields in your application code, the user is resolving fields in their GraphQL query. However, this makes input validation more verbose for simple cases.

**Comment by jkimbo** [comment]
Hi @victorandree . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 3 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by lucascosta** [comment]
I find this important 😄
