### ISSUE TITLE
Schema field names starting with numbers

### ISSUE THREAD

**Issue by sebastiandev** [graphql-python/graphene#603]
We have a sql schema that has a field that starts with a number. We are getting 

> File "/opt/python/run/venv/local/lib/python2.7/site-packages/graphql/utils/assert_valid_name.py", line 9, in assert_valid_name
>     assert COMPILED_NAME_PATTERN.match(name), 'Names must match /{}/ but "{}" does not.'.format(NAME_PATTERN, name)
> AssertionError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "3pl_client_only" does not.
> 

Is there a reason for this? can it be fixed/bypassed in any way?

**Comment by nzjs** [comment]
How did you resolve this @sebastiandev ?
