### ISSUE TITLE
Document default_value

### ISSUE THREAD

**Issue by Cito** [graphql-python/graphene#605]
Please mention the existence and usage of the `default_value` parameter in the docs, and add one example usage in the examples.

It's only mentioned once in the "getting started" section, but nowhere in the reference documentation, and it is not used in any of the examples.

**Comment by jkimbo** [comment]
@Cito this has been added to the docs now: http://docs.graphene-python.org/en/latest/types/scalars/

**Comment by Cito** [comment]
Thank you @jkimbo.
