### ISSUE TITLE
Bug: Name of a connection is always the name of the class

### ISSUE THREAD

**Issue by miracle2k** [graphql-python/graphene#610]
```
class BranchesOnClient(relay.Connection):
    pass
```

Based on the implementation of `relay.Connection` I expect the default name to be `BranchesOnClientConnection`.

```
class BranchesOnClient(relay.Connection, name="Foo"):
    pass
```

Now I expect the type name to be `Foo`.

In fact, in both cases the name will be `BranchesOnClient`. This is because `BaseType` sets `_meta.name` to the class name if no `name` argument is passed, and no `name` argument is passed because `relay.Connection` already caught it, assigned it to `_meta`, and removed it from the `**kwargs` dict that is passed on through the ``__init_subclass_with_meta__`` chain.

**Comment by syrusakbary** [comment]
Thanks for the report. This is now fixed on master.
