### ISSUE TITLE
graphene/graphene/types/__init__.py is missing types for "Date", "DateTime", and "Time"

### ISSUE THREAD

**Issue by picturedots** [graphql-python/graphene#613]
It seems like graphene/graphene/types/__init__.py should have:
`from .datetime import Date, DateTime, Time`

and these objects added to `__all__` in the same file.

**Comment by tomanizer** [comment]
I think that's right.
Graphene 2.01 currently errors with
AttributeError: module 'graphene.types' has no attribute 'datetime'
when declaring a class with:

class Observation(graphene.ObjectType):
    id = graphene.ID()
    date = graphene.types.datetime.Date()

**Comment by jkimbo** [comment]
@tomanizer to use the datetime types you can import them like this:
`from graphene.types.datetime import DateTime, Date, Time`

**Comment by picturedots** [comment]
@jkimbo That's correct -- the point though is that `DateTime` etc. aren't consistent with other types now.  For example, here's how you important both `Int` and `Date`:

```from graphene.types.datetime import Date
from graphene.types import Int```

**Comment by jkimbo** [comment]
Ok that is fair enough. Looks like https://github.com/graphql-python/graphene/pull/645 solves that so lets follow up there

**Comment by syrusakbary** [comment]
This is now fixed by #701 .
