### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mandx** [graphql-python/graphene#614]
This isn't really an issue; in the spirit of [jhund/filterrific#147](https://github.com/jhund/filterrific/issues/147), I just wanted to say thanks to @syrusakbary for creating/maintaining this library (or libraries) because this:
* Has saved me a lot of time when working on frontend projects (Thanks to Relay, use of Redux and manual state management is minimal).
* Allows me to keep working with Python.
* Allows me to learn how to do async programing with Python 3.6!

(Edit: Typo)

**Comment by syrusakbary** [comment]
Thanks a lot for this token of appreciation, it really helps me to continue pushing forward.

I'm super happy that you find Graphene useful in your day to day... and I will make sure this remains true for the next years to come (lots of exciting stuff to come in next releases!).

Best,
Syrus Akbary
