### ISSUE TITLE
Difference between graphene.List(X) vs graphene.List(lambda: X)

### ISSUE THREAD

**Issue by pedroabi** [graphql-python/graphene#617]
Is there any difference between these two declarations?

**Comment by mjtamlyn** [comment]
As far as I'm aware, not really. The advantage of the latter is that it can be used when X has not yet been defined, allowing circular references. For example:

```py
class A(ObjectType):
    children = graphene.List(lambda: B)

class B(ObjectType):
    parent = graphene.Field(A)
```

**Comment by jkimbo** [comment]
@mjtamlyn is right, it's to allow circular references when defining your schema.
