### ISSUE TITLE
ObjectType resets existing attributes to None in __init__

### ISSUE THREAD

**Issue by tomas-sk** [graphql-python/graphene#619]
Call to ```super().__init__``` of ObjectType resets all previously set field attributes to None.

This behavior was introduced by fix of issue #585.

```python

from graphene import ObjectType, String, Field, Schema


def test_objecttype_reset_attribute():
    class User(ObjectType):
        name = String(required=True)

        def __init__(self, *args, **kwargs):
            self.name = 'Default Name'
            super().__init__(*args, **kwargs)

    class Query(ObjectType):
        user = Field(User)

        def resolve_user(self, info):
            return User()

    schema = Schema(query=Query)
    result = schema.execute(''' query basequery {
        user {
            name
        }
    }
    ''')
    assert not result.errors
    assert result.data == {
        'user': {
            'name': 'Default Name',
        }
    }
```

**Comment by nparrish** [comment]
Wouldn't it make more sense to invoke the base class constructor before performing any derived-class initialization?

**Comment by tomas-sk** [comment]
Prior to version v2.0.1, it was possible to set attributes before invoking the base class init. So it is sort of a "breaking change" for people who assumed it is a "feature" and used it in existing code bases. It luckily was discovered as a failing test.

I think it would be better to keep previous behavior or produce some warning on misuse or at least put it in upgrade notices/docs.

The cause is the added default argument to pop call in [objecttype.py:84](https://github.com/graphql-python/graphene/commit/3ee94131ae511d2d83116730dcc4a50258ced5af#diff-48527f4d25710bdc0eb833a3b936167b). As it is now, the surrounding try block looks unnecessary to me. That makes me think this code will benefit from another review.
