### ISSUE TITLE
Problem with Data Loader and Promise resolve

### ISSUE THREAD

**Issue by nykolaslima** [graphql-python/graphene#625]
I have a simple one-to-many relationship that I wanna to solve using the Data Loader approach:
```
class PointOfConsuming(graphene.ObjectType):
    id = graphene.String()
    name = graphene.String()
    products = graphene.List(lambda: Product)

    def resolve_products(self, info):
        context = info.context
        return context['data_loaders'].point_of_consuming_product_loader.load(self.id)
```
The `point_of_consuming_product_loader` `load` method return a list of `Product`. But in Graphene I'm getting and error:
```
AssertionError: User Error: expected iterable, but did not find one for field PointOfConsuming.products.
```

Looks like Graphene can't handle the promise with a list of products. How can I solve this issue?

**Comment by frsv** [comment]
You have to register a success callback for your promise which will return a data. So your return should be like
```
return context['data_loaders'].point_of_consuming_product_loader.load(self.id).then(lambda response: response)
```

**Comment by jkimbo** [comment]
@nykolaslima did @frsv 's solution fix things for you?

**Comment by jkimbo** [comment]
Closing until more information is provided
