### ISSUE TITLE
Add GeoJSON types

### ISSUE THREAD

**Issue by syrusakbary** [graphql-python/graphene#63]
Add GeoJSON types (`graphene.geo`) and the mapping from Django Geo fields to it.

**Comment by syrusakbary** [comment]
Not relevant right now. It could be useful create a custom package `graphene-geojson`.

**Comment by Virako** [comment]
Hello @syrusakbary, if I want to use graphql with the geodjango, is possible? I'm newby with graphql, but when i want to try add models.PointField to graphql, I obtain Exception: Don't know how to convert the Django field player.Player.pos (<class 'django.contrib.gis.db.models.fields.PointField'>). Do you know how to resolve this problem? Is easy or i should create a graphene-geojson package first? Thanks you very much

**Comment by Mhs-220** [comment]
same problem here,
how can i solve it?

**Comment by farnoodma** [comment]
+1

**Comment by zbyte64** [comment]
This guy is working on one: https://github.com/flavors/django-graphql-geojson/
