### ISSUE TITLE
String Scalar (extra arguments) 

### ISSUE THREAD

**Issue by weiztech** [graphql-python/graphene#631]
how to pass extra arguments on string scalar ? 
ex `String(min_length=xx, other_args)`

**Comment by jkimbo** [comment]
@weiztech you should be able to just pass any arguments you want as kwargs. E.g.:

```python
class Query(graphene.Object):
	my_field = graphene.String(min_length=xx, some_arg=graphene.String(), another_arg=graphene.Int())

	def resolve_my_field(root, info, some_arg, another_arg):
		pass
```

**Comment by weiztech** [comment]
@jkimbo , got error
`TypeError: __init__() got an unexpected keyword argument 'min_length'`

so i actually want to make a custom scalar that can add `min_length` as the arguments. but get error like above.  is there any way to do something that ?

**Comment by jkimbo** [comment]
@weiztech can you give a me a bit more context on the code that you're having trouble with? Also make sure you're on the latest version of graphene. The following definitely works:

```python
class Query(graphene.Object):
	my_field = graphene.String(min_length=graphene.Int())

	def resolve_my_field(root, info, min_length):
		pass
```

If you would like to make a custom scalar you can follow the example of the `Date` scalar: https://github.com/graphql-python/graphene/blob/5df134e096f4ac839331d9aa6bfcc2bd50affa95/graphene/types/datetime.py#L18-L41

**Comment by weiztech** [comment]
@jkimbo , im using graphene2.0 
is it possible to add extra arguments on the custom scalar 

    class CustomString(Scalar):

       def __init__(self, *args, **kwargs):
        super(CustomString, self).__init__(*args, **kwargs)

      @staticmethod
      def serialize(dt):
          return dt

      @classmethod
      def parse_literal(self, node):
          if isinstance(node, ast.StringValue):
              return node.value

      @classmethod
      def parse_value(self, value):
          return value

 
    class testMutate(graphene.Mutation):
        class Arguments:
            str = CustomString(max_length=10, min_length=5)

        string = graphene.String()


could you let me know how to access attr `max_length` and `min_length` inside the `CustomString` class. ?
currently its show error `TypeError: __init__() got an unexpected keyword argument 'max_length'`

**Comment by jkimbo** [comment]
I'm still not sure I'm understanding your issue properly. From the code you've included I assume you want to apply some kind of validation to the input argument `str` in your mutation? If that is the case you can do that in the `mutate` method of the Mutation. That will allow you to return an accurate error message to the user.

E.g.:

```python
class TestMutate(graphene.Mutation):
	class Arguments:
		str = graphene.String(required=True)
	
	error_message = graphene.String()
	ok = graphene.Boolean(required=True)
	
	def mutate(root, info, str):
		# validate str
		try:
			validate_str(str)
			return TestMutate(ok=True)
		except StrTooLong:
			return TestMutate(error_message="Input string is too long", ok=False)
		except StrTooShort:
			return TestMutate(error_message="Input string is too short", ok=False)

```

**Comment by weiztech** [comment]
@jkimbo , i actually dont want validate inside the mutation class  because i'm afraid  need to repeat the validation code for other mutation class.

i think its better if i can catch/validate it inside the `CustomScalar` class if this case is possible.

**Comment by jkimbo** [comment]
@weiztech I don't think it's possible since the argument types use classmethods to parse and serialise values so they don't contain any actual state (which you would need to have to validate values)

I would suggest creating some helper functions/classes to validate inputs that can then be called in the `mutate` function. I actually think that is a better solution anyway since it allows you to return accurate error messages to the client.

**Comment by weiztech** [comment]
Thanks @jkimbo , yes i agree

i also found some good example at issue [456](https://github.com/graphql-python/graphene/issues/456)
