### ISSUE TITLE
Revising how __repr__ on SubclassWIthMeta_Meta works

### ISSUE THREAD

**Issue by dfee** [graphql-python/graphene#632]
This implementation is quite problematic, especially for abstract types. Perhaps some conditional logic could be applied, such as:

```python
class SubclassWithMeta_Meta(InitSubclassMeta):
    def __repr__(cls):
        if not hasattr(cls, '_meta'):
            return type.__repr__(cls)
        return "<class '{}.{}' as {}>".format(
            cls.__module__,
            cls.__name__,
            cls._meta.name,
        )
```

Without this, we get into AttributeError issues where a class doesn't necessarily have a `_meta`, and it's a bit unclear what we're actually looking at. I agree that sharing the graphql name is nice, so we oughta retain that.

I'd be happy to submit a PR with tests if @syrusakbary agrees.

https://github.com/graphql-python/graphene/blob/0b92d3dba64f438e97a955d13f2ec542705d1e5e/graphene/utils/subclass_with_meta.py#L11

**Comment by syrusakbary** [comment]
This is now fixed in `master` (and graphene `2.1.0`).
Please reopen the issue if is not working as expected.
