### ISSUE TITLE
Requesting schema for external URL

### ISSUE THREAD

**Issue by akshaybabloo** [graphql-python/graphene#639]
Does graphene provide any way to request external URL's schema for example, if I want to request total releases from GitHub's graphql I would do something like this with `requests`

```python
import requests

url = 'https://api.github.com/graphql'
json = {"query": "{ repository(owner:\"akshaybabloo\", name:\"gollahalli-com\") { releases{ totalCount } } }"}
api_token = "my token"
headers = {'Authorization': 'token %s' % api_token}

r = requests.post(url=url, json=json, headers=headers)
print(r.text)
```

Is there a way I could do this with graphene?

**Comment by abawchen** [comment]
@akshaybabloo : Dose this one help? https://github.com/graphql-python/graphene/issues/399

**Comment by jkimbo** [comment]
@akshaybabloo graphene is a server side implementation of graphql, not a client. You probably should post this under https://github.com/graphql-python/gql

Also, the example there should be more than enough to get you there anyway:
https://github.com/graphql-python/gql/blob/3653bb5260b60a6c72d0bb0137874fb40969a826/tests/test_transport.pyr

**Comment by styk-tv** [comment]
@jkimbo @abawchen @akshaybabloo : fair, but in case of server that HAS to implement its own method/query level authentication (or populate query variables based on token details) AND let's say neo4j/graphql endpoint all and ready what will most likely have to happen is that new auth api will have both server (relay-compliant) as well as direct client access to already implemented graphql. yes? would you then recommend using graphene or move directly into something like graphql-relay-py+gql?
