### ISSUE TITLE
Custom Node type

### ISSUE THREAD

**Issue by miracle2k** [graphql-python/graphene#640]
I have some trouble with creating a custom node type, as described here:

http://docs.graphene-python.org/en/latest/relay/nodes/#custom-nodes

The error I am seeing is:

`AssertionError: Found different types with the same name in the schema: Node, Node.`

As far as I can tell, I would say the problem here for me is a combination of:

- A lot of the node implementation is not in `AbstractNode`, but in `Node`, so I can't just easily implement by own `AbstractNode` subclass without copying a lot of code.
- The fact that `NodeField` has a dependency on `Node` further requires me to re-implement that one too.

Can we move most of the node implementation into `AbstractNode` instead?

**Comment by jkimbo** [comment]
@miracle2k it looks like the issue is that you have two types which are both called `Node` in the schema. This can happen if you are using `relay.Node` as an interface anywhere as well as your custom Node implementation.

**Comment by jkimbo** [comment]
Closing this since I haven't heard anything back from you @miracle2k . Please comment with more information if you are still having an issue.
