### ISSUE TITLE
[Feature request] Support for query complexity analysis

### ISSUE THREAD

**Issue by fishy** [graphql-python/graphene#642]
(I plan to implement it in the coming days if there's no strong objection/concern, this issue is mainly for discussion purpose)

Sangria has implemented a query complexity analysis, which is described here: http://sangria-graphql.org/learn/#query-complexity-analysis. We would like to implement something similar with Graphene.

We were able to implement a simple version (every node counts as 1) without modifying graphene code. But in order to implement a more complex and realistic version, some works need to be done inside Graphene.

The main problem we are facing is that we cannot figure out a way to add a custom property to nodes defined in our schema, something like:

```python
class Query(graphene.ObjectType):
  my_field = graphene.Field(
    MyType,
    description='some description',
    resolver=my_func,
    complexity=2,
  )
```

Even if we can overload `graphene.Field` to accept the complexity parameter in the constructor, we don't really get `Query` or `graphene.Field` back in the schema. Instead, we get `GraphQLField` or `GrapheneObjectType`, which already filtered that out.

There are a few different ways to make it possible:

1. Allow users to add custom properties to schema definitions (kind of like how we do `args` in `graphene.Field`), which will be kept in the schema. So the user could call `graphql.parse`, and then calculate the complexity with parsed AST and complexity info from the schema.

2. Add a `complexity` property to `graphene.Field`, which is default to `1` and could be either a number or a callable with parameter `args` that returns a number. Then, when we parse the query in `graphql-core`, pass in a `max_complexity` or something similar, calculate the complexity of the query, and reject the query if calculated complexity exceeds it.

Please do let me know if you have any concerns or suggestions. Thanks!

**Comment by fishy** [comment]
Actually never mind. We figured out a way to go Route 1 without modifying graphene code (and Route 2 will change a lot of APIs, which will be very risky).

The basic idea is, you can use a private field in the type (we use `_complexity`), something like:

```python
class MyType(graphene.ObjectType):
    field1 = ...
    field2 = ...
    ...

    _complexity = {
        'field1': 2,
    }
```

Then, in the complexity analysis code, you can get that map back from the schema by something like `schema.get_query_type().fields['fieldName'].graphene_type._complexity`.

**Comment by patrick91** [comment]
Thanks @fishy do you have any example for this? Maybe it could be nice to write some docs/tips for it.

**Comment by cantino** [comment]
@fishy Any chance you could share your complexity analysis code?

**Comment by YejuAhn** [comment]
@fishy Would you mind sharing your implementation??

**Comment by Checho3388** [comment]
Hey everyone 👋 — for those still looking for a solution here:

I’ve been working on [`graphql-complexity`](https://github.com/Checho3388/graphql-complexity), a Python library to compute and limit GraphQL query complexity. It’s built on top of `graphql-core`, so it works with Graphene today.

-----

**Install**

```bash
pip install graphql-complexity
```

-----

**Basic example**

```python
from graphql_complexity import get_complexity, SimpleEstimator

complexity = get_complexity(
    query=query,
    schema=schema.graphql_schema,
    estimator=SimpleEstimator(complexity=1)
)

if complexity > 10:
    raise Exception(f"Query too complex ({complexity}). Max allowed: 10")
```

-----

**Per-field control with `@complexity` directive**

```python
schema_str = """
    directive @complexity(value: Int!) on FIELD_DEFINITION

    type Query {
        me: User @complexity(value: 1)
    }

    type User {
        name: String!
        friends: [User!] @complexity(value: 5)  # expensive field
    }
"""

complexity = get_complexity(
    query=query,
    schema=schema_str,
    estimator=DirectivesEstimator(schema_str)
)
```

-----

Happy to prioritize any gaps for Graphene users — issues and PRs welcome 🙏
