### ISSUE TITLE
Missing deprecated fields in __type query

### ISSUE THREAD

**Issue by Speedy1991** [graphql-python/graphene#646]
Hi!
I found a bug, or i don't know the right query:
If i check for deprecation with a __type query, the deprecated field is not shown.
But the documentation on GraphiQL shows it. (renamedField)

<a href="https://ibb.co/nzMxhR"><img src="https://thumb.ibb.co/nzMxhR/deprecated_bug.png" alt="deprecated_bug" border="0"></a>

**Comment by zanchi** [comment]
I came across the same thing, it looks like deprecated fields are not included by default but can be included with an `includeDeprecated` arg

```graphql
{
  __type(name: "YourType") {
    fields(includeDeprecated: true) {
      isDeprecated
      name
    }
  }
}
```

**Comment by Speedy1991** [comment]
Is there aneasy way to add the _includeDeprecated_ flag to graphene?

**Comment by zanchi** [comment]
I have no idea, I don't actually use graphene, I just found this when I was having the same issue and thought that might be useful!

**Comment by jkimbo** [comment]
@Speedy1991 you can just add the `includeDepreacted` flag to your query and it should work. The reason it's showing up in graphiql is because the introspection query it uses has it included: https://github.com/graphql-python/graphql-core/blob/v2.0.0/graphql/utils/introspection_query.py#L24
