### ISSUE TITLE
Sharing input and output schemas

### ISSUE THREAD

**Issue by joetempleman** [graphql-python/graphene#647]
I'm trying to do a basic CRUD API using graphene and I can't seem to get it working without duplicating huge amounts of the schema for input vs output. This is a simplified version of what I'm trying to achieve:

```python
from graphene import ObjectType, Schema, String, Int, Field, Mutation

data = {}


class NestedObject(ObjectType):
    nested_field = Int()


class Object(ObjectType):
    name = String()
    field1 = String()
    nested_object = Field(NestedObject)


class CreateObject(Mutation):
    Input = Object
    Output = Object

    def mutate(cls, info, input_object):
        global data
        data[input_object.name] = input_object


class QueryRoot(ObjectType):
    object_by_name = Field(ObjectType, name=String())


class MutationRoot(ObjectType):
    create_object = CreateObject.Field()

schema = Schema(query=QueryRoot, mutation=MutationRoot)
```

The problem is that I can't use an ObjectType as an input so this is thrown:
`ValueError: Expected nested_object to be Argument, but received Field. Try using Argument(NestedObject).`

Is there a way that I can do this in graphene without having to duplicate the entire object schema? If I have to have the input and output as separate it is destined to be bug prone as people update one side and not the other and descriptions etc all have to be duplicated.

**Comment by joetempleman** [comment]
Circling back to answer my own question, it is an intentional limitation of the graphQL spec that means Input and Output types are different. Quoting the spec: 
```
Fields can define arguments that the client passes up with the query, to configure their behavior. These inputs can be Strings or Enums, but they sometimes need to be more complex than this.

The Object type defined above is inappropriate for re‐use here, because Objects can contain fields that express circular references or references to interfaces and unions, neither of which is appropriate for use as an input argument. For this reason, input objects have a separate type in the system.

An Input Object defines a set of input fields; the input fields are either scalars, enums, or other input objects. This allows arguments to accept arbitrarily complex structs.
```
http://facebook.github.io/graphql/October2016/#sec-Input-Objects

**Comment by ProjectCheshire** [comment]
It appears this is resolved. Please let me know if otherwise.
