### ISSUE TITLE
Does graphene support remote schemas and stitching? 

### ISSUE THREAD

**Issue by valentinradu** [graphql-python/graphene#649]
This is more of a question or feature request than issue, but, does it? I didn't found any initializer/method to init my local schema from the remote introspected one.

**Comment by lucas-bremond** [comment]
Did you find an answer to that question?

**Comment by valentinradu** [comment]
Nobody answered for a long time so I assumed: no. End up using an Apollo JS gateway able to stitch multiple Graphene powered microservices.

**Comment by lucas-bremond** [comment]
That's what I guessed... Thanks for your answer!

**Comment by jkimbo** [comment]
Sorry no one got back to you @valentinradu . As you guessed though, currently Graphene doesn't support remote schemas or stitching.

**Comment by kigen** [comment]
@valentinradu  Were you able to get Apollo JS gateway to load your graphene-based schema implementations?

**Comment by RoySegall** [comment]
Hi, I'm coming back to this issue since I did not find a solution for that, I have a couple of microservices, most of them are in apollo server, and one written in python. I did not found a way to stitch schema of my python grpahql and the apollo server.

Any ideas?

**Comment by ProjectCheshire** [comment]
@RoySegall I've been playing with the implementation of a registry, much as neomodel (neo4j graph db specific ogm) uses for models, so one idea would be to post an introspection to your apollo server, and register the received types with a registry. Then in your middleware or such, you can check the registry, if the type is found there, delegate and route the graphql request and all the args

It feels kludgy atm, but still poking it as I have time.

**Comment by ItamarGronich** [comment]
@RoySegall I have that also, 

I have a ApolloServer gateway and trying to stitch a couple of graphene services, but apollo server doesn't seem to be able to receive the schema properly from graphene.

@valentinradu How'd you manage to accomplish this ?
