### ISSUE TITLE
Generator resolver treated as asyncio coroutine

### ISSUE THREAD

**Issue by Lucretiel** [graphql-python/graphene#655]
Currently, generator resolvers are interpreted as asyncio coroutines. This makes sense for compatibility with Python 3.3 and 3.4, but it would be nice if there was a way to tag a generator as "definitely not a coroutine", so that it'd be possible to to do something like this:

```
class Query:
    players = graphene.List(lambda: PlayerObject)
    def resolve_players(self, info):
        links = PlayerLink.objects.all()
        for link in links:
            player = link.player
            player.field = link.field
            yield player
```

For now, I sadly to manually unroll the generator into a list. In order to preserve backwards compatibility, my proposal is to create a `graphene.not_async` or `graphene.list_generator` decorator that can be applied to generator resolvers to tag them as definitely not async.

**Comment by DrPyser** [comment]
That's weird behavior. Generator shouldn't be assumed to be coroutines. From what I understand, generator-based coroutines should be explicitly annotated with [`@asyncio.coroutine`](https://docs.python.org/3/library/asyncio-task.html#asyncio.coroutine), and can then be found using [`asyncio.is_coroutine`](https://docs.python.org/3/library/asyncio-task.html#asyncio.iscoroutine).

**Comment by DrPyser** [comment]
@Lucretiel Has this issue been resolved?
This should be simple to fix(given both proposed solutions), but after looking through the code, I can't find where the resolvers are extracted.
