### ISSUE TITLE
Automatic escape utf-8 character in JSONString?

### ISSUE THREAD

**Issue by luvwinnie** [graphql-python/graphene#658]
Hi, I'm newly with graphQL and graphene.
I have a JSONField of data in my postgresql database. I'm trying to implement graphql in order to get result from postgresql. It's seems like JSONField will automatic convert to JSONString in graphene.However If I do so , my Japanese character will not be decode. Is it possible to decode the JSONString automatically?

**Comment by abawchen** [comment]
@luvwinnie : Could you provide you input, currently output and expected output? It will help a lot to understand you question (at least for me :p).

**Comment by jkimbo** [comment]
@luvwinnie do you have any more information on this issue so that we can try and help?

**Comment by jkimbo** [comment]
Closing until more information provided

**Comment by luvwinnie** [comment]
sorry for late reply, my input is a speech recognition result of Japanese like below.
`{
    "recognition_result": {
      "tri4": [
        {
          "utterance_id": "new_processing_0000158_0000381",
          "result": "歌詞+名詞 前面+名詞 に+助詞/格助詞 い+感動詞 突っ張り+動詞/ラ行五段/連用形 感+名詞 が+助詞/格助詞 ある+動詞/ラ行五段/連体形 そう+名詞 です+助動詞/終止形",
          "start_time": 1.58,
          "end_time": 3.81
        },
        {
          "utterance_id": "new_processing_0000426_0000688",
          "result": "<sp> 今回+名詞 歩行+名詞 訓練+名詞 を+助詞/格助詞 実施+名詞 し+動詞/サ行変格/連用形 まし+助動詞/連用形 た+助動詞/終止形",
          "start_time": 4.26,
          "end_time": 6.88
        }
      ],
      "dnn": [
        {
          "utterance_id": "new_processing_0000158_0000381",
          "result": "か+助詞/終助詞 自然+形状詞 面+名詞 に+助詞/格助詞 突っ張り+動詞/ラ行五段/連用形 感+名詞 が+助詞/格助詞 ある+動詞/ラ行五段/連体形 そう+名詞 です+助動詞/終止形",
          "start_time": 1.58,
          "end_time": 3.81
        },
        {
          "utterance_id": "new_processing_0000426_0000688",
          "result": "回+名詞 歩行+名詞 訓練+名詞 を+助詞/格助詞 実施+名詞 し+動詞/サ行変格/連用形 まし+助動詞/連用形 た+助動詞/終止形",
          "start_time": 4.26,
          "end_time": 6.88
        }
      ]
    }
  }`

and this data is use to save to my database. And I Wish to get the result like below query.
`
query{
          data{
                   recognition_result
           }
}
`

however when I can get the result. My Japanese character are all encoded in Unicode.
For my solution now, I have to escape in my client side. Is there anyway to solve this problem?
I'm not in the control of my server, I would send my query result later on.

Thx!

**Comment by jkimbo** [comment]
The code for the `JSONField` type is pretty simple: https://github.com/graphql-python/graphene/blob/2594cdb61409f8ecedf0958ee959f8f8ded3efbc/graphene/types/json.py All it does to output the json string is call `json.dumps(dt)`. 

I would recommend you make a custom scalar type based on the `JSONField` to try and see if changing the `serialize` function solves your issue. If you do please comment on this issue with your solution.
