### ISSUE TITLE
How to generate documentation in GraphiQL?

### ISSUE THREAD

**Issue by alexisrolland** [graphql-python/graphene#660]
Hello,

I have not seen any material on the topic. Would you know if there is a documentation which explains how to generate descriptions / documentation in GraphiQL from the code directly?

Thanks

**Comment by jkimbo** [comment]
@alexisrolland for scalars you can add the `description` kwarg to specify a description and for `ObjectType` you can add a description field to the `Meta` class.

```python
class MyType(graphene.ObjectType):
	class Meta:
		description = "Some description for MyType"

	my_field = graphene.String(description="Some description for myField")
```

**Comment by alexisrolland** [comment]
Thank you @jkimbo 
I'm actually using Graphene-SQLAlchemy so I realize I might have not posted the question on the right repository. My `ObjectType` is actually defined like this:

```python
from graphene_sqlalchemy import SQLAlchemyObjectType
from database.model_people import ModelPeople
import graphene


class People(SQLAlchemyObjectType):
    """People node."""

    class Meta:
        model = ModelPeople
        interfaces = (graphene.relay.Node,)
```

My "People node." docstring get displayed properly in GraphiQL but I'm not able to get a description for the attributes of my node since they come from the `ModelPeople` class defined in SQLAlchemy.

I will check on the Graphene-SQLAlchemy side how this is managed.
Thanks

**Comment by alexisrolland** [comment]
@jkimbo one more question though. Do you know how to provide a description for the fields created for my `Mutation` class below?

```python
class Mutation(graphene.ObjectType):
    """Mutations which can be performed by this API."""
    createPerson = schema_people.CreatePerson.Field()
    updatePerson = schema_people.UpdatePerson.Field()
    createPlanet = schema_planet.CreatePlanet.Field()
    updatePlanet = schema_planet.UpdatePlanet.Field()
```

I've tried adding the `description` kwarg to the `Field()` method but it did not really work.
Thanks in advance.

**Comment by jkimbo** [comment]
Yep there seems to be several open issues/pull requests about not being able to define a description for a mutation (e.g. PRs: https://github.com/graphql-python/graphene/pull/618, https://github.com/graphql-python/graphene/pull/565 or https://github.com/graphql-python/graphene/pull/594 and issues: https://github.com/graphql-python/graphene/issues/634, https://github.com/graphql-python/graphene/issues/626 and https://github.com/graphql-python/graphene/issues/593 )

@syrusakbary any reason why one of the above PRs hasn't been merged yet?

**Comment by syrusakbary** [comment]
Yup, sorry for being silent about this.

The main reason this is not merged is because the provided solutions tried to get the description from the mutation output ObjectType, when actually the description is for the Field.

The best solution would be to allow `description` to be set directly in the `Field` function:
https://github.com/graphql-python/graphene/blob/master/graphene/types/mutation.py#L79

**Comment by alexisrolland** [comment]
Thanks for the answer.
But this is not supported at the moment (sorry I don't understand the code snippet you linked).
Is it?

**Comment by syrusakbary** [comment]
Just fixed this issue with commit: https://github.com/graphql-python/graphene/commit/a7a4ba62af4cb8b00ffa6a9f8cf79bd87dfb5e95

**Comment by alexisrolland** [comment]
@syrusakbary Thanks for committing this change. I have one more question. I'm installing graphene with pip. I have upgraded my graphene package to its last version:

`pip install graphene --upgrade`

But I don't think it already includes your last changes / commits to the master branch. I'm curious, what does it take to have your new version pushed to PyPi?

Thank you
Alexis

**Comment by elwoodxblues** [comment]
What are the plans for releasing a new version? I'd love to have this feature.
