### ISSUE TITLE
skip and include directives.

### ISSUE THREAD

**Issue by alexpantyukhin** [graphql-python/graphene#662]
According the http://graphql.org/learn/queries/#directives article each implementation of the GraphQL should has implemented `@skip` and `@include` directives.

**Comment by jkimbo** [comment]
@alexpantyukhin the `@skip` and `@include` directives are already available (they are implemented in the [graphql-core](https://github.com/graphql-python/graphql-core) library which graphene uses). Tests to show it working are here: https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/tests/test_directives.py

**Comment by alexpantyukhin** [comment]
@jkimbo thank you very much!

**Comment by japrogramer** [comment]
hello, the  ` @client` directive has become very popular
is there a way to have a list of directives that graphene should just ignore, since they are used client side.?

**Comment by alexpantyukhin** [comment]
@japrogramer Could you please clarify what is the `@client` directive? Couldn't find it.

**Comment by japrogramer** [comment]
@alexpantyukhin it is a directive used with the apollo client to reference its local cache.
