### ISSUE TITLE
Caching/Memoization of resolvers?

### ISSUE THREAD

**Issue by HeyHugo** [graphql-python/graphene#671]
I've tried adding memoization to a resolver and cache the result in redis using flask-caching, see http://pythonhosted.org/Flask-Caching/#memoization

However it does not work, result is calculated on the next requests still. (with same args of course)

Is this because of some resolver "magic" happening? How can I make this work, I really need to be able to use memoization on some queries for graphene to be feasible.

Any other ideas how to achieve this type of caching?

**Comment by HeyHugo** [comment]
Ah, got this working now. I think it might have been something with the info argument (timestamp or similar?). I solved it by calling another function with only the graphql variable arguments from the resolve.

**Comment by jcunhafonte** [comment]
How did you achieve the solution?
