### ISSUE TITLE
Error handling and errors property on graphql respons

### ISSUE THREAD

**Issue by gmetzker** [graphql-python/graphene#672]
I can't seem to find much documentation around error handling with Graphene.  If I raise an exception inside resolver methods these seem to be transformed into a `GraphQLLocatedError` in the result object of `schema.execute`.  

The problem I'm finding is that when doing a `json.dumps()` on the response `GraphQLLocatedError` is not JSON serializable.  I can implement the serialization but I wondered if there was any common schema in the GraphQL error object.  

The only documentation I've found on the `errors` property is in [Validation documentation](http://graphql.org/learn/validation/) but it doesn't appear to be very prescriptive.

**Comment by sf-sagarj** [comment]
You should  use json.dumps() on result.data instead of result object. 

You can check for errors before json.dumps() on result.data

**Comment by gmetzker** [comment]
@sf-sagarj My `result.data` serializes fine.  But I was asking, more specifically, about how to do the serialization when I do have results.errors present and I want to communicate those in the GraphQL response.  `GraphQLLocatedError` doesn't seem to serialize, and I can't find any documentation on what the format for `.errors` should be.

**Comment by jkimbo** [comment]
@gmetzker this the way that graphene-django handles it: https://github.com/graphql-python/graphene-django/blob/dbd3957a9f622573b2b106546f3accc48f5d5b41/graphene_django/views.py#L161-L163

Basically it calls `format_error` from `graphql.error` on each `GraphQLError`

**Comment by jkimbo** [comment]
Closing issue until there is more information
