### ISSUE TITLE
Document implementing custom Relay Connections

### ISSUE THREAD

**Issue by jkimbo** [graphql-python/graphene#674]
With [Relay Connections](http://docs.graphene-python.org/en/latest/relay/connection/) it's possible to almost completely customise the connection type by returning the connection type from the resolve function. This should be documented.

E.g. https://github.com/graphql-python/graphene/issues/307#issuecomment-250881176

**Comment by morenoh149** [comment]
I take it this does not mean the js lib relay, but a graphene concept of relay?

**Comment by jkimbo** [comment]
@morenoh149 correct it does. The whole Relay integration part of graphene needs a lot of attention from both a code standpoint and a documentation one. The Relay classic integration probably also needs to be dropped since it’s no longer supported by the Relay team.

**Comment by jkimbo** [comment]
@montemishkin for reference here is some example code on how you can customise Connections: https://github.com/graphql-python/graphene/issues/875#issuecomment-450738767

**Comment by montemishkin** [comment]
im assuming you meant to tag @morenoh149 instead of me :)

**Comment by jkimbo** [comment]
Apologies I did mean to tag @morenoh149 :)
