### ISSUE TITLE
Document reserved characters in argument names

### ISSUE THREAD

**Issue by ustun** [graphql-python/graphene#68]
I tried to run the following:

```python

import graphene


class Query(graphene.ObjectType):
    hello = graphene.String(firstName=graphene.String())

    def resolve_hello(self, args, info):
        return 'Hello ' + args.get('firstName')

schema = graphene.Schema(query=Query)

result = schema.execute("""
query foo($firstName:String)
{
        hello(firstName:$firstName)
}
""", args={"firstName": "Serkan"})

print result.data


```

It works. However, if I change all references to firstName to name, it stops working. Is this documented, or is it a bug?

```python

import graphene


class Query(graphene.ObjectType):
    hello = graphene.String(name=graphene.String())

    def resolve_hello(self, args, info):
        return 'Hello ' + args.get('name')

schema = graphene.Schema(query=Query)

result = schema.execute("""
query foo($name:String)
{
        hello(name:$name)
}
""", args={"name": "Serkan"})

print result.data
```

The stack trace is the following:

```
  File "test.py", line 18, in <module>
    """, args={"name": "Serkan"})
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphene/core/schema.py", line 122, in execute
    kwargs = dict(kwargs, request=request, root=root, args=args, schema=self.schema)
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphene/core/schema.py", line 85, in schema
    subscription=self.T(self.subscription))
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphene/core/schema.py", line 22, in __init__
    super(GraphQLSchema, self).__init__(*args, **kwargs)
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphql/core/type/schema.py", line 42, in __init__
    self._type_map = self._build_type_map()
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphql/core/type/schema.py", line 85, in _build_type_map
    type_map = type_map_reducer(type_map, type)
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphql/core/type/schema.py", line 117, in type_map_reducer
    field_map = type.get_fields()
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphql/core/type/definition.py", line 193, in get_fields
    self._field_map = define_field_map(self, self._fields)
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphql/core/type/definition.py", line 218, in define_field_map
    assert_valid_name(field_name)
  File "/Users/ustun/Projects/graphene_test/.venv/lib/python2.7/site-packages/graphql/core/type/definition.py", line 758, in assert_valid_name
    assert COMPILED_NAME_PATTERN.match(name), 'Names must match /{}/ but "{}" does not.'.format(NAME_PATTERN, name)
TypeError: expected string or buffer

```

**Comment by ustun** [comment]
Also, possibly related, underscores in field names do not work:

```

import graphene


class Query(graphene.ObjectType):
    hello = graphene.String(first_name=graphene.String())

    def resolve_hello(self, args, info):
        return 'Hello ' + args.get('first_name')

schema = graphene.Schema(query=Query)

result = schema.execute("""
query foo($first_name:String)
{
        hello(first_name:$first_name)
}
""", args={"first_name": "Serkan"})

print result.data
```

**Comment by ustun** [comment]
Incidentally, `from` argument name was the first thing I tried on the playground since it accepts an argument named `to` and it took me some time to remember that `from` is a keyword. Maybe the error message could be made better there too.

http://graphene-python.org/playground/?schema=import%2520graphene%250A%250Aclass%2520Query(graphene.ObjectType)%253A%250A%2520%2520%2520%2520hello%2520%253D%2520graphene.String()%250A%2520%2520%2520%2520ping%2520%253D%2520graphene.String(to%253Dgraphene.String()%252C%2520from%253Dgraphene.String())%250A%250A%2520%2520%2520%2520def%2520resolve_hello(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520%27World%27%250A%250A%2520%2520%2520%2520def%2520resolve_ping(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520%27Pinging%2520%257B%257D%2520%257B%257D%27.format(args.get(%27to%27)%252C%2520args.get(%27from%27))%250A%250Aschema%2520%253D%2520graphene.Schema(query%253DQuery)%250A&query=query%2520%257B%250A%2520%2520hello%250A%2520%2520ping(to%253A%2522Peter%2522%252C%2520FROM%253A%2520%2522Ustun%2522)%250A%257D%250A

**Comment by syrusakbary** [comment]
Hi @ustun,

I've fixed the name argument in Fields with this commit: https://github.com/graphql-python/graphene/commit/2eea03cb62f9c254792f066ca8b697060b2407ed

So the first code you wrote would work perfectly.

About the last code you wrote:
```python

import graphene


class Query(graphene.ObjectType):
    hello = graphene.String(first_name=graphene.String())

    def resolve_hello(self, args, info):
        return 'Hello ' + args.get('first_name')

schema = graphene.Schema(query=Query)

result = schema.execute("""
query foo($first_name:String)
{
        hello(first_name:$first_name)
}
""", args={"first_name": "Serkan"})

print result.data
```

Graphene, converts (by default, could be disabled) not only the field names in ObjectTypes/Interfaces, but also the argument names to be `camelCase`.
So if you use an argument for having a `first_name` name, you should query in the GraphQL query using: `firstName`.
Like:
```python
query foo($firstName:String)
{
        hello(firstName:$firstName)
}
""", args={"firstName": "Serkan"})
```

About the `from` error, it's a Python syntax error, so Graphene will not show any errors for that, as it will not be executed.

Hope it helps!
