### ISSUE TITLE
Query with "or" expression

### ISSUE THREAD

**Issue by bwanglzu** [graphql-python/graphene#681]
Hi everyone, maybe it's a stupid question, I'm new to graphene. Is it possible for me to query like this?
```python
query{
  things(type: "type_a" or "type_b"){
    edges{
      node{
        thing_id
      }
    }
  }
}
``` 
I mean the `type` argument could possibly  be a String or multiple Strings (or a list).. I figured out that Django has something called `django_filter`.. But I'm using Flask.

Thanks!

**Comment by jkimbo** [comment]
@bwanglzu as far as I'm aware there is no such ability in the graphql spec: http://facebook.github.io/graphql/October2016/ Graphene is just a framework to implement a graphql server and so it must conform to the specification.

If you want to allow your client to arbitrarily pass filters to your underlying data fetching method you could model it as a list argument as you suggested:

```python
class Query(graphene.ObjectType):
	things = relay.ConnectionField(ThingConnection, or_filters=graphene.List(graphene.String)
```

**Comment by jkimbo** [comment]
Great, glad I could help. Generally with graphql there is not a big overhead in having multiple ways to query the data since it's up the client to decide how to query. And it's usually better to be explicit with naming so what you've come up with looks great.

**Comment by bwanglzu** [comment]
In case you're using`SQLAlchemy`, please take a look at the latest comment [this](https://github.com/graphql-python/graphene-sqlalchemy/issues/27)
