### ISSUE TITLE
Enums return Meta enum value if Meta class is used

### ISSUE THREAD

**Issue by schrockn** [graphql-python/graphene#685]
If you have the following enum defined:

```python
class SomeEnumGraphQL(graphene.Enum):
    class Meta:
        name = 'SomeEnum'

    SOMEVALUE = 0
```

You end up getting the following during an introspection query such as:

```
{
  __schema {
    types {
      name
      enumValues{
        name
        description
      }
    }
  }
}
```
The relevant part of the result is:

```
"name": "SomeEnum",
"enumValues": [
  {
    "name": "Meta",
    "description": null
  },
  {
    "name": "SOMEVALUE",
    "description": null
  }
]
```

**Comment by schrockn** [comment]
Thanks so much for all the hard work on this project! If this is a new/unknown issue I could put together a PR. But before I did all that wanted to see if it was on someone's radar. Thanks!

**Comment by syrusakbary** [comment]
Good catch! Will fix soon :)

**Comment by syrusakbary** [comment]
This is now fixed in `master` :)

**Comment by schrockn** [comment]
Awesome! Thanks for the super fast fix.
