### ISSUE TITLE
AbstractType is shown in documentation, but raises Deprecation warning

### ISSUE THREAD

**Issue by saturdayplace** [graphql-python/graphene#690]
The [django/relay documentation](http://docs.graphene-python.org/projects/django/en/latest/tutorial-relay/) shows the use of `AbstractType`, but this raises a DeprecationWarning at runtime.

Additionally, the [URL provided](https://github.com/graphql-python/graphene/blob/2.0/UPGRADE-v2.0.md#deprecations) in the DeprecationWarning message returns a 404

**Comment by jkimbo** [comment]
@saturdayplace the graphene-django repo is here: https://github.com/graphql-python/graphene-django

I'm sure a PR to update the documentation would be appreciated.

**Comment by abawchen** [comment]
@jkimbo : I take this easy one in #692

**Comment by syrusakbary** [comment]
I just fixed this with https://github.com/graphql-python/graphene-django/commit/9cdd95c11436566d48b9b3e19aed9e648fcb3d76. Closing issue
