### ISSUE TITLE
Is it possible to group query/mutations and subscriptions

### ISSUE THREAD

**Issue by kavink** [graphql-python/graphene#693]
As I add more models to query/mutations and subscriptions, would be great to group them by tags or something, Same way as Swagger does.

Wondering if Graphql and by extension Graphene allows it to do ? And how to do it.

**Comment by jkimbo** [comment]
@kavink GraphQL doesn't specify any particular ways of grouping mutations or subscriptions. There is an interesting discussion on it here: https://github.com/facebook/graphql/issues/376

Generally it's not useful to try and map traditional CRUD api endpoints to a GraphQL api. Mutations end up being very specific to a particular use case and so are difficult to group anyway.
