### ISSUE TITLE
graphene.Int Scalars are not double-precision as documented

### ISSUE THREAD

**Issue by dkleissa** [graphql-python/graphene#698]
The docs currently list `graphene.Int` scalars as:

"Represents non-fractional signed whole numeric values. Int can represent values between -(2^53 - 1) and 2^53 - 1 since represented in JSON as double-precision floating point numbers specified by IEEE 754."

In our testing, `Int`s appear to be single precision, not double. Is this just a documentation issue, or something else we are missing?

**Comment by ProjectCheshire** [comment]
Fixed by #891
