### ISSUE TITLE
Executor Customization

### ISSUE THREAD

**Issue by jhgg** [graphql-python/graphene#7]
I think that it would be beneficial to be able to pass a custom executor to a Graphene schema, so that it can use it to `execute` the query.

I'm thinking either:
```python
schema = Schema(query=QueryRootType, executor=Executor(...))
```
OR
```python
schema = Schema(query=QueryRootType)
schema.set_executor(Executor(...))
```

By default it should use the default executor instance. I am going to expose an API for this in `core.graphql.execution`

```python
from core.graphql import execution
default_executor = execution.get_default_executor()
```

The default executor will be configured to be a synchronous executor. In addition, you will be able to set the default executor using:

```python
execution.set_default_executor(Executor(...))
```

**Comment by jhgg** [comment]
I've added the get/set default executors in `graphql-core`. https://github.com/graphql-python/graphql-core/commit/ad228f0087968d6e5706f4f90cd3a40e9c7de736

**Comment by syrusakbary** [comment]
I want to have automatic field ordering in graphene enabled as default, which is in contradiction with what graphql-core thinks it should be
However you should be still able to change it whenever you want. Going to merge the code soon.
Let me know your thoughts on that @jhgg
