### ISSUE TITLE
GenericIPAddressField support

### ISSUE THREAD

**Issue by lightning18** [graphql-python/graphene#70]
It has been in Django since 1.4 and can be converted to String. I can submit a PR but I don't know how you want it. Can it be done the same way as UUIDField?

**Comment by syrusakbary** [comment]
Yeah, any pull request will be more than welcome.
We only support Django 1.6+,  so only adding `models.GenericIPAddressField` into `convert_field_to_string` should work ;)

**Comment by lightning18** [comment]
No need for checks then. Submitted #71, added a test in it too.
