### ISSUE TITLE
`default_value=` doesn't work with NonNulls

### ISSUE THREAD

**Issue by ipmcc** [graphql-python/graphene#702]
There doesn't appear to be a way to specify default values when using `NonNull` (which, somewhat ironically, seems like the most obvious moment to want a default value.)

The following test shows what I've tried so far:

```
import unittest
import graphene
from collections import OrderedDict

class NonNullDefaultValueTestCase(unittest.TestCase):
    def test_default_value_as_kwarg_to_type(self):
        # This fails with:
        # NonNull could not have a mounted Boolean() as inner type. Try with NonNull(Boolean).
        class User(graphene.ObjectType):
            name = graphene.String()
            is_admin = graphene.NonNull(graphene.Boolean(default_value=False))

    def test_default_as_kwarg_to_NonNull(self):
        # In light of the previous error, I tried this, which also fails, but differently:
        # graphql.error.base.GraphQLError: Cannot return null for non-nullable field User1.isAdmin.
        class User(graphene.ObjectType):
            name = graphene.String()
            is_admin = graphene.NonNull(graphene.Boolean, default_value=False)

        class Query(graphene.ObjectType):
            user = graphene.Field(User)

            def resolve_user(self, *args, **kwargs):
                return User(name="foo")  # I expect the default value to be picked up for is_admin

        schema = graphene.Schema(query=Query)
        expected = OrderedDict([('user', OrderedDict([('name', 'foo'), ('isAdmin', False)]))])
        observed = schema.execute("{ user { name isAdmin } }")

        self.assertIs(observed.errors, None)
        self.assertEqual(observed.data, expected)
```

Stepping through it in the debugger, I see that `NonNull` tucks away its `args` and `kwargs` (presumably for later use) but I don't see them ever getting used. Am I missing something here?

**Comment by syrusakbary** [comment]
Thanks for the input.
I just checked and `default_value` was actually dismissed for fields. I've added a test case based on your example to avoid this repeating again in the future.

Thanks.

**Comment by jestevez-cds** [comment]
Shouldn't a `NonNull` field use it's default even when passed `None`?
For instance, I would expect the following to pass.

`def test_default_as_kwarg_to_NonNull():
    # Related to https://github.com/graphql-python/graphene/issues/702
    class User(ObjectType):
        name = String()
        is_admin = NonNull(Boolean, default_value=False)

    class Query(ObjectType):
        user = Field(User)

        def resolve_user(self, *args, **kwargs):
            return User(name="foo", is_admin=None) # <------------------------------------- 

    schema = Schema(query=Query)
    expected = {"user": {"name": "foo", "isAdmin": False}}
    result = schema.execute("{ user { name isAdmin } }")

    assert not result.errors
    assert result.data == expected`

**Comment by jkimbo** [comment]
@jestevez-cds `default_value` is passed as the 3rd param to `getattr` which is why it returns `None` even if you have a default value: https://github.com/graphql-python/graphene/blob/7ecb4e68ba03a65908752cb17de101dc51b3e220/graphene/types/resolver.py#L1-L2

You can override the default resolver if you like by using the [`set_default_resolver`](https://github.com/graphql-python/graphene/blob/7ecb4e68ba03a65908752cb17de101dc51b3e220/graphene/types/resolver.py#L17) function and change it to something like this:

```python
def attr_resolver(attname, default_value, root, info, **args):
	value = getattr(root, attname, default_value)
	if value is None:
		return default_value
	return value
```

You can also set the default resolver per object type by setting the `default_resolver` attribute on the `Meta` class: https://docs.graphene-python.org/en/latest/api/#object-types

**Comment by jestevez-cds** [comment]
@jkimbo That's super helpful. Thank you!
