### ISSUE TITLE
Support for Decimal type

### ISSUE THREAD

**Issue by picturedots** [graphql-python/graphene#703]
I've been using my own implementation of a Decimal type -- maybe it should be included as a standard type?

    from graphene.types import Scalar
    from graphql.language import ast

    class Decimal(Scalar):
        """
        The `Decimal` scalar type represents a python Decimal.
        """
        @staticmethod
        def serialize(dec):
            assert isinstance(dec, decimal.Decimal), (
                'Received not compatible Decimal "{}"'.format(repr(dec))
            )
            return str(dec)
        
        @staticmethod
        def parse_value(value):
            return decimal.Decimal(value)
        
        @classmethod
        def parse_literal(cls, node):
            if isinstance(node, ast.StringValue):
                return cls.parse_value(node.value)

**Comment by jkimbo** [comment]
Great idea! Would love to see a PR with this and some tests.

Also `parse_value` should probably return `None` if it's not a valid `Decimal` (like how it's done in the datetime types: https://github.com/graphql-python/graphene/blob/05d7e61b844b574f59d68ead86ed40431843d51d/graphene/types/datetime.py#L60-L64)

**Comment by jkimbo** [comment]
Decimal support has now been merged into master. Thanks @picturedots !

**Comment by iraj-jelo** [comment]
It's cool guys. I came across this issue now and I found I should update the Graphene to get new fields. actually I used to check [the document](https://docs.graphene-python.org/en/latest/types/scalars/) for new features but apparently **it isn't update**  though.

**Comment by jkimbo** [comment]
@iraj-jelo the documentation is a bit out of date 😞 We are accepting pull requests though if you'd like to update it?

**Comment by jkimbo** [comment]
(also it is there in the API documentation at least! https://docs.graphene-python.org/en/latest/api/#graphene-scalars)

**Comment by iraj-jelo** [comment]
@jkimbo  of course. I'll give a try
