### ISSUE TITLE
ImportError: cannot import name 'Model Name'

### ISSUE THREAD

**Issue by Allan-Nava** [graphql-python/graphene#705]
How can I fix the circular or cyclic imports in Python?

[circular or cyclic imports](https://stackoverflow.com/questions/744373/circular-or-cyclic-imports-in-python)

**Comment by jkimbo** [comment]
You can either pass a lambda to `graphene.Field` or a string import. e.g.:

```python
class Query(graphene.ObjectType):
	current_user = graphene.Field(lambda: User)
	favorite_pet = graphene.Field('mobileapi.definitions.pets.Pet')
```

**Comment by jkimbo** [comment]
@Allan-Nava did you get this working?

**Comment by jkimbo** [comment]
Closing issue until there is more information

**Comment by amaksymov** [comment]
Using string references does not appear to be support in Connection.Meta.Node
```python
class UserConnection(relay.Connection):
    class Meta:
        node = 'UserTypeObject'
```
What to do in this case?
