### ISSUE TITLE
Postgres Relay Cursor Support

### ISSUE THREAD

**Issue by Benjaminryejones** [graphql-python/graphene#708]
Hi there,

I've implemented pagination using Relay cursors, however I am having duplicate items returned from the server:
![image](https://user-images.githubusercontent.com/10845447/38403215-b4555724-3916-11e8-8626-2c4eb0887098.png)

I see the same id items returned in graphiql when I start querying object types and use the 'endCursor' field from pageInfo, which verifies that server is indeed returning duplicated items:
![image](https://user-images.githubusercontent.com/10845447/38403453-7cd343d6-3918-11e8-8e99-8e6bb25fae09.png)
![image](https://user-images.githubusercontent.com/10845447/38403467-8a810acc-3918-11e8-82f5-cd10379ceb7f.png)

As I understand from https://facebook.github.io/relay/graphql/connections.htm#sec-Pagination-algorithm, all edges should be pulled and ordered such that duplicates like this don't occur, but that doesn't seem to be the case. Help much appreciated!

Versions:
Python 3.5.2
Django (2.0.4)
django-filter (1.1.0)
graphene (2.1)
graphene-django (2.0.0)
graphql-core (2.0)
graphql-relay (0.4.5)
"apollo-cache-inmemory": "^1.1.5",
"apollo-client": "^2.2.0",
"apollo-client-preset": "^1.0.6",
"apollo-link": "^1.0.7",
"apollo-link-state": "^0.3.1",
"apollo-server-express": "^1.3.2"

**Comment by jkimbo** [comment]
@Benjaminryejones it looks like it's the node ID's that are duplicated not the cursor values. How are you generating the list of objects for the connection? And how are you generating their ID's?

**Comment by Benjaminryejones** [comment]
Thanks for the response, @jkimbo.

The objects are generated by the Django ORM and I'm using a sorted version of the Graphene DjangoFilterConnectionField:

GQL Card type:
```
class CardType(DjangoObjectType):
    class Meta:
        model = Card
        interfaces = (relay.Node, )
        filter_fields = {
            'id': ['exact'],
            'card_type': ['exact', 'icontains'],
            'feeds': ['exact']
        }
```

GQL Card query:
```
class CardQuery(graphene.ObjectType):
    card = relay.Node.Field(CardType)
    cards = OrderedDjangoFilterConnectionField(CardType, orderBy=List(String))
```

OrderedDjangoFilterConnectionField:
```
from graphene import relay, String, List, ObjectType
from graphene_django.filter import DjangoFilterConnectionField
from graphene_django.fields import DjangoConnectionField      
        
class OrderedDjangoFilterConnectionField(DjangoFilterConnectionField):
    @classmethod
    def connection_resolver(cls, resolver, connection, default_manager, max_limit,
                            enforce_first_or_last, filterset_class, filtering_args,
                            root, info, **args):
        filter_kwargs = {k: v for k, v in args.items() if k in filtering_args}
        qs = filterset_class(
            data=filter_kwargs,
            queryset=default_manager.get_queryset(),
            request=info.context
        ).qs
        order = args.get('orderBy', None)
        if order:
            qs = qs.order_by(*order)
        return super(DjangoFilterConnectionField, cls).connection_resolver(
            resolver,
            connection,
            qs,
            max_limit,
            enforce_first_or_last,
            root,
            info,
            **args
        )
```

(For reference, I also get dupes when I use DjangoFilterConnectionField).

I did a quick sanity check and I do not see any duplicate ids for the relevant table in postgres:
![image](https://user-images.githubusercontent.com/10845447/38579855-1fcf5686-3cbd-11e8-8ae9-f127bda2a4fa.png)

As I understand the node ids are generated from a hash of __typename + id, so I don't believe there should be any duplicate node ids.

Let me know if you have any other questions or if I can provide more context!

**Comment by Benjaminryejones** [comment]
Quick update:

After some testing yesterday, it looks like the `data` argument passed into `connection_from_list` in graphql-relay/connection/arrayconnection.py ([link](https://github.com/graphql-python/graphql-relay-py/blob/master/graphql_relay/connection/arrayconnection.py)) changes depending on the `first` and `after` arguments passed in in the GraphQL query.

As the function notes, it only works if the same array is static:
```
def connection_from_list(data, args=None, **kwargs):
    '''
    A simple function that accepts an array and connection arguments, and returns
    a connection object for use in GraphQL. It uses array offsets as pagination,
    so pagination will only work if the array is static.
    '''
```

Not sure where/how this is happening (must be in the DjangoFilterConnectionField resolver or something), I'll take a look later today.

**Comment by Benjaminryejones** [comment]
Looks like it was something to do with how Postgres returns data from queries with LIMITs and OFFSETs.

For reference, I was able to troubleshoot by installing the [Graphene Django debug middleware](http://docs.graphene-python.org/projects/django/en/latest/debug/) and ordering the results using a [modified version of the DjangoFilterFieldConnection that allows one to order the results](https://gist.github.com/ivlevdenis/3fb0ede89650889cc9f62a77770e7156).

**Comment by Benjaminryejones** [comment]
Also for reference: https://www.postgresql.org/docs/9.3/static/queries-limit.html
