### ISSUE TITLE
Version 2.1 has a bug in passing DateTime in variable_values

### ISSUE THREAD

**Issue by hornedbull** [graphql-python/graphene#712]
Previously, a datetime string used to work when passed to variable_values of execute function. However, with version 2.1 the function only accepts DateTime objects if the input type of a variable is DateTime. However, even after I changed the str to DateTime object, the execute function fails on .split as it can’t run split on a DateTime object. Seems like the validation was added for variable_values, however the internal methods weren’t change to suit DateTime objects and still only support DateTime Strings.

**Comment by jkimbo** [comment]
@hornedbull any updates?

**Comment by jkimbo** [comment]
Closing issue until there is more information

**Comment by goharyounas** [comment]
any update?
