### ISSUE TITLE
Capture exception when resolving

### ISSUE THREAD

**Issue by seansay** [graphql-python/graphene#715]
Hi guys,

Not sure this is possible now, right now it seems the resolving will 'eat' the eceptions in the resolve method, is there an way to I customized the resolve part .  I want to send the exception and detail trackback to sentry to monitor errror

**Comment by jkimbo** [comment]
The result object you get back from `execute` has an errors attribute that contains an array of errors that happened during the execute phase. You can use that to report errors to sentry. E.g.:

```python
for error in result.errors:
	# error is an instance of `GraphQLLocatedError` where the original error
	# is on the `original_error` attribute
	try:
    	raise error.original_error
    except Exception:
    	sentry_client.captureException()
```

Or you can configure your logging setup to propagate errors from `graphql.execution.executor` to sentry. They are logged out here: https://github.com/graphql-python/graphql-core/blob/b3a6bd0f89651af10a937e5270e46c696672a2e5/graphql/execution/executor.py#L314

**Comment by seansay** [comment]
thanks!
