### ISSUE TITLE
Calculated/computed Fields resolver calling order

### ISSUE THREAD

**Issue by j-robin-hunter** [graphql-python/graphene#717]
I'm working through providing a graphql source to an energy monitoring application. Total load for a premises is essentially the sum of all of the measured loads on each circuit.

The following is a trivial piece of the work where there are two measured load fields  and one total_load field

```
class Heating(graphene.ObjectType):
    total_load = graphene.Float()
    water_heater = graphene.Field(lambda: SensorReading,
                                  resolver=get_measurement,
                                  args={'id': graphene.String('Water Heater')})
    space_heater = graphene.Field(lambda: SensorReading,
                                      resolver=get_measurement,
                                      args={'id': graphene.String('Space Heater')})
```
I have tried to create a simple resolver to compute the total_load from water_heater and space_heater values but this total_load resolver always gets called first so both water_heater and space_heater are None, meaning I can't do the calculation.

Both water_heater and space_heater use a DataLoader, part of the get_measurement resolver. This is important as the time series database (InfluxDB) has a tendancy to return quite large amounts of data the I need to resolve from a cache and which need bulk loading.

I have thought about using a promise or middleware to get the total_load but wanted to get a steer as to the right way to resolve this type of timing related issue and more generally how to approach calculated/computed values using both GraphQL and Graphene as much seaching hasn't given me much luck so far.

**Comment by j-robin-hunter** [comment]
This is a good idea and not one I had thought of. I'm sure this will do what I'm after. Many thanks

**Comment by jkimbo** [comment]
@j-robin-hunter how did it go?

**Comment by jkimbo** [comment]
Closing issue because I think it's solved. Will reopen if it's still a problem.

**Comment by rarenatoe** [comment]
What if I need a dictionary that would be calculated based on a list, the dictionary containing several sums, such as:

{"mondayTotal": 45, "tuesdayTotal": 32, ... etc...}

Iterating the list to get the result for each day would cause me to iterate it 7 times.

Furthermore the ObjectType being returned sometimes is the outermost one and there is no way calculate this inside some resolver because there is no general resolver for the outermost objectType...

**Comment by jkimbo** [comment]
@rarenatoe in that case I would recommend abstracting the day calculation into a seperate function that you either cache or compute it at the level above the object type that needs the data.
