### ISSUE TITLE
Graphene as a validation library

### ISSUE THREAD

**Issue by ustun** [graphql-python/graphene#72]
This is probably not the best place to discuss this as it is not a bug report, but I was wondering how we should approach data validation with graphql and graphene, especially with its Django integration.

For example, should graphene replace the django forms layer as well? I believe it should and it can, since its validation capabilities are much richer. It is possible to validate if something is a string in django, but going beyond that, for example, ensuring a value is a list of strings is not possible without custom code.

We should discuss and document the best practices here.

I see graphene as ultimately replacing the urls, views and forms parts of django.

**Comment by syrusakbary** [comment]
@adamcharnock is working in #60, which apart of the main propose (filtering in django connections) provides a way for mapping also forms into Graphene types.

**Comment by syrusakbary** [comment]
Right now the code merged by #60 into master allows to convert any kind of form with its fields to a Graphene Type.

Closing this issue, please reopen if any questions or suggestions ;)
