### ISSUE TITLE
ImportError: Could not import 'cookbook.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField'.

### ISSUE THREAD

**Issue by samuelvillegas** [graphql-python/graphene#724]
Hi I just clone from the repository, execute the `python setup.py install`  and `pip install -r requirements.txt` in examples/cookbook
I followed the tutorial and didn't work ether 

Could not import 'cookbook.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField'.

**Comment by jkimbo** [comment]
@samuelvillegas did you mean to open this issue in the [graphene-django](https://github.com/graphql-python/graphene-django) repo?

**Comment by jkimbo** [comment]
Closing issue until there is more information
