### ISSUE TITLE
Problem with implementing 'non-null list of non-null Strings'

### ISSUE THREAD

**Issue by tivaliy** [graphql-python/graphene#733]
I have some problem with implementing **non-null list of non-null Strings**. Let's say we have a mutation:

```
class DeleteTasks(graphene.Mutation):

    class Arguments:
        tasks_ids = graphene.NonNull(graphene.List(graphene.NonNull(graphene.String)))

    ok = graphene.Boolean()

    def mutate(self, info, tasks_ids):
         ....
         ....
        return DeleteTasks(ok=True)
```

Now I want to play around with mutation entry point and use Apollo Client Developer Tools...
Here is a autogenerated documentation, that looks as expected:

`deleteTasks(taksIds: [String!]!): DeleteTasks`

The problem is that I can call mutation with an empty list of parameters (ids of the tasks), i.e. mutation request:

```
mutation{
  deleteCompanies(companiesIds: []){
    ok
  }
}
```
and here is a response:

```
{
  "data": {
    "deleteTasks": {
      "ok": true
    }
  }
}
```

So, the problem is that I have to make an extra validation on empty list, but as I expected this should be done by GraphQL itself.

**Comment by jkimbo** [comment]
This behaviour is correct according to the GraphQL docs: http://graphql.org/learn/schema/#lists-and-non-null

An empty list is a **non-null** value so it should be accepted by the schema definition you have.
