### ISSUE TITLE
Best way to work with relay

### ISSUE THREAD

**Issue by marcelombc** [graphql-python/graphene#739]
Hello, I started working with graphene recently and I decided to create a small API to learn the framework.
I have an external service that expose some functions, let's call them ```get_properties()``` and ```get_property_rooms(property_id)```. I started creating two ```DataLoader```, one to fetch the properties of the user and another to fetch the rooms of a specific property.

```python
class PropertiesLoader(DataLoader):
    def get_cache_key(self, key):
        return key['context'].user

    def batch_load_fn(self, keys):
        return Promise.resolve([get_properties() for key in keys])


class RoomsLoader(DataLoader):
    def get_cache_key(self, key):
        return key['context'].user + key['property_id']

    def batch_load_fn(self, keys):
        return Promise.resolve([get_property_rooms(key['property_id']) for key in keys])


properties_loader = PropertiesLoader()
rooms_loader = RoomsLoader()
```

Then I created two nodes and two connections, one for the properties and another for the rooms.

```python
class Room(graphene.ObjectType):
    class Meta:
        interfaces = (relay.Node, )

    name = graphene.String(description='The room name')


class RoomConnection(relay.Connection):
    class Meta:
        node = Room


class Property(graphene.ObjectType):
    class Meta:
        interfaces = (relay.Node, )

    name = graphene.String(description='The name of the property')
    rooms = relay.ConnectionField(RoomConnection, description='The rooms of the property')

    @staticmethod
    def resolve_rooms(root, info, **kwargs):
        return rooms_loader.load(root.id)

    @classmethod
    def get_node(cls, info, id):
        return properties_loader.load(
            {'context': info.context}
        ).then(lambda properties: [
            item for item in properties if item.id == int(id)
        ][0])


class PropertyConnection(relay.Connection):
    class Meta:
        node = Property


class RelayQuery(graphene.ObjectType):
    property = relay.Node.Field(Property)
    properties = relay.ConnectionField(PropertyConnection)
    room = graphene.Field(Room,
                          id=graphene.ID(required=True),
                          property_id=graphene.ID(required=True))
    rooms = relay.ConnectionField(RoomConnection,
                                  property_id=graphene.ID(required=True))

    @staticmethod
    def resolve_properties(root, info, **kwargs):
        return properties_loader.load({'context': info.context})

    @staticmethod
    def resolve_room(root, info, id, property_id, **kwargs):
        _, _id = relay.Node.from_global_id(id)
        _, _property_id = relay.Node.from_global_id(property_id)

        return rooms_loader.load(
            {'context': info.context, 'id': int(_property_id)}
        ).then(lambda rooms: [
            item for item in rooms if item.id == int(_id)
        ][0])

    @staticmethod
    def resolve_rooms(root, info, property_id, **kwargs):
        _, id = relay.Node.from_global_id(property_id)
        return rooms_loader.load({'context': info.context, 'property_id': int(id)})


schema = graphene.Schema(query=RelayQuery)
```

As you may notice from the ```RelayQuery```, I have a room field which accepts two ```graphene.ID()```. One for the room id and another for the property id.
I want to know if there is a better way to do this? It would be really nice if I could use a ```relay.Node.Field``` for the room field in the ```RelayQuery```, pass the property id as argument and implement the ```get_node``` method in the ```Room``` node like the following example:

```python
class Room(graphene.ObjectType):
    class Meta:
        interfaces = (relay.Node, )

    name = graphene.String(description='The room name')

    @classmethod
    def get_node(cls, info, id, property_id):
        return rooms_loader.load(
            {'context': info.context, 'property_id': int(property_id)}
        ).then(lambda rooms: [
            item for item in rooms if item.id == int(id)
        ][0])


class RelayQuery(graphene.ObjectType):
    ...
    room = relay.Node.Field(Room, property_id=graphene.ID(required=True))
    ...
```

Please let me know if there is a better approach to do this and if yes, could you update the documentation in the relay section? I want to be able to do the following queries:

```graphql
query {
  properties {
    edges {
      node {
        id, name,
        rooms {
          edges {
            node {
              id, name
            }
          }
        }
      }
    }
  }
}

query {
  rooms(propertyId: "UHJvcGVydHk6Mjg5Mg==") {
    edges {
      node {
        id, name
      }
    }
  }
}

query {
  property(id: "UHJvcGVydHk6Mjg5Mg==") {
    id, name,
    rooms {
      edges {
        node {
          id, name
        }
      }
    }
  }
}

query {
  room(id: "Um9vbTo2", propertyId: "UHJvcGVydHk6Mjg5Mg==") {
    id, name
  }
}
```

**Comment by jkimbo** [comment]
@marcelombc just to clarify you want to avoid having to do:

```python
_, _id = relay.Node.from_global_id(id)
_, _property_id = relay.Node.from_global_id(property_id)
```

inside your resolvers. Is that right?

At the moment there isn't a way in Graphene of defining an argument as specifically a Relay ID and getting it to decode the ID automatically. I don't really have to time now to figure out how to do it but if you would like to contribute one that would be great!

At my work we have found a work around using a decorator that cleans up our code a bit:

```python
def unmask(**config):
    def unmask_decorator(func):
        def unmask_wrapper(obj, info, **kwargs):
            for arg_name, kls in config.items():
                if kwargs[arg_name]:
                    schema_type, unmasked_id = relay.Node.from_global_id(kwargs[arg_name])

                    if schema_type != kls._meta.name:
                        kwargs[arg_name] = None

                    kwargs[arg_name] = unmasked_id
            return func(obj, info, **kwargs)
        return unmask_wrapper
    return unmask_decorator
```

You can then use it like this:

```python
@unmask(id=Room, property_id=Property)
def resolve_room(root, info, id, property_id, **kwargs):
	return rooms_loader.load(
    	{'context': info.context, 'id': int(property_id)}
    ).then(lambda rooms: [
    	item for item in rooms if item.id == int(id)
    ][0])
```

**Comment by jkimbo** [comment]
Btw you don't need to decorate your resolvers with `@staticmethod` either

**Comment by marcelombc** [comment]
Hi @jkimbo, the idea is to get rid of the ```resolve_room``` resolver and add the ```get_node``` method in the ```Room``` node. The idea is to pass an extra argument in the relay node field like this:

```python
class Room(graphene.ObjectType):
    class Meta:
        interfaces = (relay.Node, )

    name = graphene.String(description='The room name')

    @classmethod
    def get_node(cls, info, id, property_id):
        return rooms_loader.load(
            {'context': info.context, 'property_id': int(property_id)}
        ).then(lambda rooms: [
            item for item in rooms if item.id == int(id)
        ][0])


class RelayQuery(graphene.ObjectType):
    ...
    room = relay.Node.Field(Room, property_id=graphene.ID(required=True))
    ...
```

I know that this is not possible, that's why I created a graphene field for the room and get the id from global id.
Since I'm new with GraphQL and graphene I just want to understand if what I did is a good practice or not. Another question is why we should use relay in the server side? Shouldn't we use relay as client side? And should I use graphene relay to build my API if I'm not using React in the client side? I'm really confusing with this part since relay is a JavaScript framework for building data-driven React applications. What if I choose to use Apollo for the client side? Should I implement relay in the server side? It would be great to get a more complete documentation about graphene relay.

**Comment by jkimbo** [comment]
Ah ok sorry, I think I see where the misunderstanding comes from now.

Relay is only one option with working with GraphQL on the client (others include Apollo as you mentioned and even slimmer clients like [urql](https://formidable.com/blog/2018/introducing-urql/)). Graphene supports all of these options out of the box and it also provides several helper classes to support Relay specifically (everything in the `graphene.relay` namespace).

The bit thats probably confusing you is that in the old version of Relay (relay-classic) it assumed that your GraphQL schema was setup in a particular way. For example it assumed you had a `node` field in the root query that allowed relay-classic to refetch a particular node whenever it needed to. This is what `relay.Node.Field` is for (more information can be found on the [relay docs](https://facebook.github.io/relay/docs/en/graphql-server-specification.html#object-identification)). With the new version of Relay (relay-modern) most of this is **optional** so you don't have to implement any of it in your schema.

Having said that you might still want to implement some of the relay schema **patterns** such as the `node` field and the [`connections`](https://facebook.github.io/relay/docs/en/graphql-server-specification.html#connections) specification because they turn out to be very useful even if you are not using relay. If that is the case then you can use the `graphene.relay` part of the graphene library but it is not required to start using GraphQL on your client.

I hope that clears some things up 🙂

**Comment by marcelombc** [comment]
Thanks for the explanation @jkimbo it was very clear. Like you said, the relay-classic assumes that you have a ```node``` in the root query. I've tried to create a general ```node``` to refetch both ```Property``` and ```Room``` like the following:

```python
class RelayQuery(graphene.ObjectType):
    node = relay.Node.Field()
```

This way I could do the following queries to get a specific ```Property``` and ```Room```:

```graphql
query {
  node(id: "UHJvcGVydHk6Mjg5Mg==") {
    id
    ... on Property {
      id, name,
      rooms {
        edges {
          node {
            id, name
          }
        }
      }
    }
}
```

```graphql
query {
  node(id: "Um9vbTo2") {
    id
    ... on Room {
      id, name
    }
  }
}
```

But since my ```get_rooms``` method depends on the property id I can't do this, that's why I created a root node field for the ```Property``` only (```property = relay.Node.Field(Property)```) and a root graphene field (has two required ```graphene.ID()``` arguments, one for the room id and another for the property id) for the ```Room``` (```room = graphene.Field(Room, id=graphene.ID(required=True), property_id=graphene.ID(required=True))```). 
Do you think it's possible to create a workaround to set a generic root node field to refetch both ```Property``` and ```Room``` like the previous example? What is your opinion about this and if you need to implement something like this, how do you approach it? Sorry for all the questions, but I just want to understand the best way to work with graphene and graphene relay and follow good practices from the beginning.

**Comment by jkimbo** [comment]
I don't think you should try and overload the `graphene.relay.Node.Field` class to try and accept arbitrary arguments since the class is there for a specific purpose which is to implement the root node field.

If your data model is such that there is no way to get a room without going through a property then I would create a `room_by_id` field on the `Property` type and have a top level `property_by_id` field that fetches the room. The schema would look like this:

```graphql
type Query {
	propertyById(propertyId: ID!): Property!
}

type Property {
	roomById(roomId: ID!): Room!
}
```

**Comment by marcelombc** [comment]
Thanks for the idea @jkimbo but I see a problem with your approach. Since my method ```get_room``` accepts the room id and the property id, there is no need to fetch the property. All I need is to pass the property id and room id to my service to get the room details. Going through the property is an unnecessary job because it will pass in the ```get_node``` method from the ```Property``` node. Since I'm using ```DataLoader``` the data is in cache but even then I don't want my code to go through unnecessary methods to fetch the data.
I would prefer to use a room graphene field at root and translate the global id to proper id using the ```from_global_id``` method

**Comment by jkimbo** [comment]
Sure it's totally up to you. What I would say is that the best way to architect your schema is to think about what makes the most sense for how the front end client wants to use the data. You can always improve efficiency in the backend but if your client has to work around types or fields that don't make sense to how the data is actually being used then you might as well be using a traditional REST api.

Anyway I'm going to close this issue as it doesn't seem like there is anything that needs to change in Graphene.
