### ISSUE TITLE
Native SQLAlchemy integration/bindings

### ISSUE THREAD

**Issue by mekarpeles** [graphql-python/graphene#74]
See https://github.com/graphql-python/graphene/issues/51, similarly https://github.com/graphql-python/graphql-epoxy/issues/5

**Comment by mekarpeles** [comment]
I'm working on something with no security implications (all data is public), so s a make-shift solution (don't use in production), I'm registering (pseudo code) all models using the following approach crufty:

    import Base # = some declarative_base(cls=mixin), see [1]
    import graphene
    class Query(graphene.ObjectType): pass
    for k, v in Base._decl_class_registry.items():
        setattr(Query, k.lower(), v)
        setattr(Query, 'resolve_%s' % k, lambda self, args, info: v.get(args.get('id')).dict() #dict() coming from [1]

[1] see https://github.com/thegroovebox/api.groovebox.org/blob/master/groovebox/api/core.py#L33

Note: _decl_class_registry has some non-models registered with it (e.g. _sa_module_registry), so additional error handling / logic is required.

**Comment by syrusakbary** [comment]
@jfeinstein10 already did an amazing work trying to integrate `sqlalchemy` into `graphene`.

I'm going to fork its [sqlalchemy graphene branch](https://github.com/jfeinstein10/graphene/tree/sqlalchemy) and preserve his work updated with the recent changes of graphene.

**Comment by syrusakbary** [comment]
Work in progress pull request: #87

**Comment by gwind** [comment]
@jfeinstein10  I saw this [code](https://github.com/jfeinstein10/graphene/blob/sqlalchemy/graphene/contrib/sqlalchemy/types.py#L88)  : 

```python
class SQLAlchemyNode(BaseNode, SQLAlchemyInterface):
    id = GlobalIDField()

    @classmethod
    def get_node(cls, id, info=None):
        try:
            instance = cls._meta.model.filter(id=id).one()
            return cls(instance)
        except cls._meta.model.DoesNotExist:
            return None
```

In the `cls._meta.model.filter(id=id).one()` , I'm concern:

1. use a django like model query , not original sqlalchemy orm usage.
2. use id as id. Relay ID is a string, model id maybe integer always.

@syrusakbary I'm working on sqlalchemy backend, any progress would be interested.

**Comment by syrusakbary** [comment]
@gwind some code ported by @jfeinstein10 was not updated to reflect the SQLAlchemy nature, as you exposed.

However is actually fixed by some commits I did recently: https://github.com/graphql-python/graphene/blob/sqlalchemy/graphene/contrib/sqlalchemy/types.py#L122

2. The Relay ID field have to be a String, by spec. The field id in the SQLAlchemy model is mapped to an integer, but this query `.filter(id='1')` works also well in this cases.

Feel free to fork this work and do any improvements!

**Comment by gwind** [comment]
@syrusakbary  may be a `raise NotImplementedError()` would be a good choice.

I have a local sqlachemy binding, but it is very basic, and i am not family with graphql - relay.
Thanks,

**Comment by gwind** [comment]
@syrusakbary I've saw that `graphene.relay.NodeField` in root query would convert original id (int or string) to a uniq ID ( type + id => base64) .

So my concern about `instance = cls._meta.model.filter(id=id).one()` was wrong: id is the object id in table exactly now.

**Comment by syrusakbary** [comment]
Graphene is using `from_global_id` from `graphql_relay` right now.

However you can customize the `id_fetcher` function in `NodeField` (https://github.com/graphql-python/graphene/blob/master/graphene/relay/fields.py#L68)

**Comment by gwind** [comment]
I see, thanks :smile:

**Comment by syrusakbary** [comment]
SQLAlchemy support is now merged into master, closing the issue 😎
