### ISSUE TITLE
Relay filtering single object

### ISSUE THREAD

**Issue by impowski** [graphql-python/graphene#747]
For example I have this type, the model is `AbstractUser`
```
class UserType(DjangoObjectType):
    class Meta:
        model = UserModel
        interfaces = (graphene.relay.Node, )
        filter_fields = ['username']

class Query(graphene.ObjectType):
    user = graphene.relay.Node.Field(UserType)
    all_users = DjangoFilterConnectionField(UserType)
```

I want to be able to do this:
```
query {
    user(username: "Bob") {
        first_name
        last_name
    }
}
```

How I could implement this type of behaviour without using `get()` method?

**Comment by jkimbo** [comment]
@impowski the `relay.Node.Field` is meant to implement a field that you fetch by using the relay id. If you would like to be able to find a user using other criteria you will have to implement your own field resolver. For example:

```python
class Query(graphene.ObjectType):
    user = graphene.Field(UserType, username=graphene.String(required=True))
    all_users = DjangoFilterConnectionField(UserType)

	def resolve_user(root, info, username):
		return UserModel.objects.get(username=username)
```

**Comment by impowski** [comment]
@jkimbo Ok I see, I did something like that:
```
def resolve_user(self, args, ctx, info):
        username = args.get('username')
```
And it didn't work

**Comment by jkimbo** [comment]
@impowski what version of graphene are you using? The new api for resolvers is:

```python
def resolve_user(self, info, **args):
	username = args.get('username')
```

You can find more information here: https://github.com/graphql-python/graphene/blob/master/UPGRADE-v2.0.md

**Comment by impowski** [comment]
@jkimbo we use the latest version, but shouldn't it work just like that with `DjangoFilterConnectionField`? Or it will only work on `all_users`? I don't understand the point of it if I need to write my own resolvers or it should work like that?

**Comment by jkimbo** [comment]
@impowski I'm going to close this issue now. Please do post any updates you have here for posterity.
