### ISSUE TITLE
allow null in input list

### ISSUE THREAD

**Issue by altaurog** [graphql-python/graphene#749]
I would like to be able to create a range search parameter as a list of possibly null values, so I could do something like the following:

range | query
----- | -----
amps < 3 | `components (amps: [null, 3])`
1 < amps < 3 | `components (amps: [1, 3])`
1 < amps | `components (amps: [1, null])`

Input List type doesn’t seem to allow this.  I get an `Unexpected Name "null"` error

**Comment by altaurog** [comment]
In this case I could just use a string with comma-separated values:

range | query
----- | -----
amps < 3 | `components (amps: ",3")`
1 < amps < 3 | `components (amps: "1,3")`
1 < amps | `components (amps: "1,")`

but it seems to me that null would be useful as a legal value in any case.

**Comment by jkimbo** [comment]
@altaurog graphene is powered by [graphql-core](https://github.com/graphql-python/graphql-core) which is an almost direct port of the graphql-js library for node. graphql-core doesn't support `null` yet but there is an open issue (https://github.com/graphql-python/graphql-core/issues/118) and a potential pull request open (https://github.com/graphql-python/graphql-core/pull/172) for it.

I'm going to close this issue in favour of tracking progress in the graphql-core repo.

**Comment by altaurog** [comment]
@jkimbo thanks!  I’ll have a look there.

**Comment by antwan** [comment]
Aforementioned issues have been removed. Is it truly fixed?

**Comment by jkimbo** [comment]
@antwan Graphene v3 uses the new v3 version of graphql-core which has full support for nulls. We’re hoping to release the new version soon but in the meantime there is a beta version that you could use.
