### ISSUE TITLE
fragments

### ISSUE THREAD

**Issue by DrPyser** [graphql-python/graphene#755]
I can't find any documentation anywhere on support for fragments in graphene.

Is it possible to define fragments? If so, how?

Thanks.

**Comment by DrPyser** [comment]
I think I now understand that fragments are defined client-side. Closing.

**Comment by roelzkie15** [comment]
@DrPyser Hey hope you could share your solution or the link to a documentation so everyone could learn also!

**Comment by DrPyser** [comment]
https://graphql.org/learn/queries/#fragments

The fragments are defined by the client and sent along with the query. The server doesn't have to do anything special, the framework takes care of expanding the fragments into their component fields before passing the query to the application code.
