### ISSUE TITLE
Error from Apollo-codegen

### ISSUE THREAD

**Issue by ZZHHAANNGG** [graphql-python/graphene#759]
I create a basic graphene-django project. I can send queries on the GraphqlView. But Apollo-codegen always returns an error

```
apollo-codegen introspect-schema http://localhost:8000/graphql/ --output schema.json
```

error: Error while fetching introspection query result: invalid json response body at http://localhost:8000/graphql/ reason: Unexpected token < in JSON at position 1

**Comment by jkimbo** [comment]
@ZZHHAANNGG this looks like `http://localhost:8000/graphql` is returning html and not JSON which is what the `apollo-codegen` tool is expecting.

What happens if you run the following in a terminal?

```
curl --request POST http://localhost:8000/graphql/
```

**Comment by ZZHHAANNGG** [comment]
It complains about CSRF.


`<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    #info { background:#f6f6f6; }
    #info ul { margin: 0.5em 4em; }
    #info p, #summary p { padding-top:10px; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>


  <p>You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.</p>
  <p>If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for &#39;same-origin&#39; requests.</p>

</div>

<div id="info">
  <h2>Help</h2>

    <p>Reason given for failure:</p>
    <pre>
    CSRF cookie not set.
    </pre>


  <p>In general, this can occur when there is a genuine Cross Site Request Forgery, or when
  <a
  href="https://docs.djangoproject.com/en/2.0/ref/csrf/">Django's
  CSRF mechanism</a> has not been used correctly.  For POST forms, you need to
  ensure:</p>

  <ul>
    <li>Your browser is accepting cookies.</li>

    <li>The view function passes a <code>request</code> to the template's <a
    href="https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render"><code>render</code></a>
    method.</li>

    <li>In the template, there is a <code>{% csrf_token
    %}</code> template tag inside each POST form that
    targets an internal URL.</li>

    <li>If you are not using <code>CsrfViewMiddleware</code>, then you must use
    <code>csrf_protect</code> on any views that use the <code>csrf_token</code>
    template tag, as well as those that accept the POST data.</li>

    <li>The form has a valid CSRF token. After logging in in another browser
    tab or hitting the back button after a login, you may need to reload the
    page with the form, because the token is rotated after a login.</li>
  </ul>

  <p>You're seeing the help section of this page because you have <code>DEBUG =
  True</code> in your Django settings file. Change that to <code>False</code>,
  and only the initial error message will be displayed.  </p>

  <p>You can customize this page using the CSRF_FAILURE_VIEW setting.</p>
</div>

</body>
</html>`

**Comment by jkimbo** [comment]
Ok thats your issue then. You need to mark your `/graphql` endpoint as exempt of CSRF protection. You can do this by wrapping the view in the `csrf_exempt` function like this:

```python
# urls.py
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    url(r'^graphql$', csrf_exempt(GraphQLView.as_view(schema=schema))),
]
```

There is more information in the Django documentation: https://docs.djangoproject.com/en/2.0/ref/csrf/#module-django.views.decorators.csrf

**Comment by ZZHHAANNGG** [comment]
It works now. Django issue -_-. Have been struggling for days. Thank you.
