### ISSUE TITLE
Incorrect mutate document

### ISSUE THREAD

**Issue by youngking** [graphql-python/graphene#76]
[This page] (http://graphene-python.org/docs/mutations/)  has a mutate example,  but parameters of the  mutate method are incorrect, follow it will get an error:  `"mutate() takes exactly 3 arguments (4 given)" `

According to  to this [test](https://github.com/graphql-python/graphene/blob/master/graphene/core/tests/test_mutations.py), it should be like:

```python
    @classmethod
    def mutate(cls, instance, args, info):
        person = Person(name=args.get('name'))
        ok = True
        return CreatePerson(person=person, ok=ok)
```

**Comment by syrusakbary** [comment]
This is solved by #77.
