### ISSUE TITLE
how to fix Int type limit -2147483648(MIN_INT) ~ 2147483647(MAX_INT)

### ISSUE THREAD

**Issue by keyeMyria** [graphql-python/graphene#761]
How to fix the limit of Int type limit range  -2147483648(MIN_INT) ~ 2147483647(MAX_INT). Defined in file [scalars.py](https://github.com/graphql-python/graphene/blob/master/graphene/types/scalars.py).

**Comment by dan98765** [comment]
@keyeMyria what kind of fix are you hoping for? Are you asking for way to allow integers to take values below -2147483648 and above 2147483647? Or are you asking about something else?

**Comment by messa** [comment]
I've just noticed this issue in notifications, I will try to answer the question anyway :)

I think it's clearly explained in the comment:

```
# As per the GraphQL Spec, Integers are only treated as valid when a valid
# 32-bit signed integer, providing the broadest support across platforms.
#
# n.b. JavaScript's integers are safe between -(2^53 - 1) and 2^53 - 1 because
# they are internally represented as IEEE 754 doubles.
MAX_INT = 2147483647
MIN_INT = -2147483648
```

If you need to transfer integers outside this limit - or if you need to work with numbers with decimal or arbitrary precision - just put the number inside a string.
