### ISSUE TITLE
Tutorial on relay error

### ISSUE THREAD

**Issue by ccsv** [graphql-python/graphene#774]
I was doing the tutorial and found this error on the page with the custom filters  filters http://docs.graphene-python.org/projects/django/en/latest/filtering/#custom-filtersets

The example has:
```
class AnimalFilter(django_filters.FilterSet):
    # Do case-insensitive lookups on 'name'
    name = django_filters.CharFilter(lookup_type='iexact')

    class Meta:
        model = Animal
        fields = ['name', 'genus', 'is_domesticated']

    @property
    def qs(self):
        # The query context can be found in self.request.
        return super(AnimalFilter, self).qs.filter(owner=self.request.user)
```

The ` django_filters.CharFilter(lookup_type='iexact')` will give an `TypeError:__init__() got an unexpected keyword argument 'lookup_type'` it should be changed to:

`name = django_filters.CharFilter(lookup_expr=['iexact'])`

Second thing is the function qs  is not really clear on how you get `self.request.user` it mentions "set in context.user" that is not really clear what that is.

**Comment by jkimbo** [comment]
@ccsv can you raise this issue on https://github.com/graphql-python/graphene-django ? I'm sure a PR fixing the documentation error would be appreciated as well.
