### ISSUE TITLE
how to add totalcount with list type

### ISSUE THREAD

**Issue by xiaohanghang** [graphql-python/graphene#776]
e.g:
```
    allusers {
            totalcount
            [
				id,
             	name
            ]

	}
```

**Comment by jkimbo** [comment]
@xiaohanghang `List` types can only represent lists and can't have any other attributes so what you're trying to do in the example is not possible.

You could model it by using an `ObjectType` to store `totalCount` like this:

```
type Query {
	allUsers: AllUsersConnection
}

type AllUsersConnection {
	totalCount: Int!
	edges: [User]
}

type User {
	id: ID!
	name: String!
}
```

and so your query would look like this:
```
query {
	allUsers: {
		totalCount
		edges: {
			id
			name
		}
	}
}
```

The Graphene code to model the above would look like this:

```python
class User(graphene.ObjectType):
	id = graphene.ID(required=True)
	name = graphene.String(required=True)

class AllUsersConnection(graphene.ObjectType):
	total_count = graphene.Int(required=True)
	edges = graphene.List(User)

class Query(graphene.ObjectType):
	all_users = graphene.Field(AllUsersConnection)
```

I'll leave the implementation of the resolvers up to you.

Hope that helps! You might also want to look at the (Relay Connections Spec)[https://facebook.github.io/relay/graphql/connections.htm] which codifies a way of defining connections and is a good pattern to follow even if you don't use relay.

**Comment by xiaohanghang** [comment]
Hi，jkimbo   ，Thanks！！！

**Comment by jkimbo** [comment]
Glad I could help!
