### ISSUE TITLE
Issue with resolve_*() functions 

### ISSUE THREAD

**Issue by amitsaha** [graphql-python/graphene#78]
Consider this example (adapted from simple example in getting started):

```
amit@yosemite work $ cat hello_graphql.py
import graphene

class Query(graphene.ObjectType):
    hello_id = graphene.String()

    def resolve_hello_id(self, args, info):
        print 'Resolve called'
        return 'World'

schema = graphene.Schema(query=Query)
schema.execute('{ hello_id }')
```

On executing it, resolve function is not called. I have seen this is a generic issue when the field name is `*_id`.

**Comment by syrusakbary** [comment]
Hi @amitsaha, the "issue" is caused because `graphene` automatically maps `snake_case` field names and args to `camelCase` (as `camelCase` is the preferred way in js clients). So the good query will be
```python
schema.execute('{ helloId }`)
```

You can disable this auto camelCase behavior doing:
```python
schema = graphene.Schema(query=Query, auto_camelcase=False)
```
Related issue: #46 
Hope it helps.

**Comment by amitsaha** [comment]
Thank you @syrusakbary

**Comment by dgoldstein0** [comment]
I think I just wasted an hour or two (maybe more) because this behavior is not demonstrated in the examples - or if it is, it's extremely nonobvious.  This should really be better documented.

**Comment by amitsaha** [comment]
+1 @dgoldstein0 I think there could be a FAQ as a wiki page @syrusakbary ?

**Comment by gwind** [comment]
There is need a attention in `schema = graphene.Schema(query=Query, auto_camelcase=False)` , auto_camelcase would meet some issues in client-side which use React/Relay.

e.g

- clientMutationId
- pageInfo
