### ISSUE TITLE
Adding Query InputField examples to the docs

### ISSUE THREAD

**Issue by adamdavis40208** [graphql-python/graphene#780]
This page is the closest example for how to use an InputField:

http://docs.graphene-python.org/en/latest/types/mutations/

But it never shows how to also use it in a Query.

This example, however, does: https://github.com/graphql-python/graphene/blob/master/examples/complex_example.py#L18

It even shows how to query it. 

This seems useful enough to add to the docs.

**Comment by jkimbo** [comment]
That would be a great addition to the docs! https://github.com/graphql-python/graphene#documentation has some instructions on how to update the docs locally. Could you add something?

**Comment by adamdavis40208** [comment]
Sure thing, I'm no technical writer but I can take a swing at it.

**Comment by codeocelot** [comment]
Having just solved this last night, I appreciate the pain point.  I'm happy to write it up if @adamdavis40208 is busy.

**Comment by adamdavis40208** [comment]
@codeocelot Absolutely! I totally lost track of this.
