### ISSUE TITLE
Response deduplication

### ISSUE THREAD

**Issue by keeth** [graphql-python/graphene#782]
Does graphene have an equivalent to [graphql-crunch](https://github.com/banterfm/graphql-crunch) or [graphql-deduplicator](https://github.com/gajus/graphql-deduplicator)?

If I wanted to write a wrapper that emitted a deduplicated response from graphene, could anyone suggest a starting point?  Seems like a straightforward way to save a lot of bandwidth.

Thanks!

**Comment by jkimbo** [comment]
@keeth as far as I know there isn't a solution for response deduplication in the graphene ecosystem. I would love for someone to build one though!

It looks like you should be able to build something standalone that just takes the response from `execute`. 

E.g.:
```python
result = schema.execute('...')
deduped_data = deflate(result.data)
```

**Comment by keeth** [comment]
Thanks! I'll close this issue for now.

**Comment by jkimbo** [comment]
@keeth I've implemented both graphql-crunch (https://github.com/graphql-python/graphene/pull/787) and graphql-deduplicator (https://github.com/graphql-python/graphene/pull/786) in python. I didn't see any benefit on the queries we use at work but try them out and let me know if you see any benefits.
