### ISSUE TITLE
Assertions unsafe in production code

### ISSUE THREAD

**Issue by danpalmer** [graphql-python/graphene#784]
I've noticed while reading graphene and graphene-django that assertions are used frequently to protect from operations with undefined results or things that should be impossible (but might still happen if used incorrectly).

In Python, assertions are not safe to use for this in general. This is because they can be disabled, and often are in production.

Instead of:

```python
assert something is not None, "Something was unexpectedly None"
```

We should do this:

```python
if something is not None:
    raise AssertionError("Something was unexpectedly None")
```

This is the recommended best practice in Python development where assertions are being used.

**Comment by Kacppian** [comment]
Can I take this up?

**Comment by danpalmer** [comment]
Go for it. I’m happy to review the PRs if you do.

**Comment by jkimbo** [comment]
That would be great @Kacppian !

**Comment by Kacppian** [comment]
I've fixed this in #794

**Comment by Kacppian** [comment]
Sorry for the delay, was caught up. Here's a PR I raised, scraped the previous one - #808

**Comment by Kacppian** [comment]
Still awaiting for reviews on #808
