### ISSUE TITLE
Cannot implement optional argument for queries

### ISSUE THREAD

**Issue by wilk** [graphql-python/graphene#789]
I'm trying to define an optional argument for the following query:

```python
class Query(object):
  all_services = graphene.List(ServiceType, data=graphene.Argument(ServicesInput, required=False, default_value={}))
```

The associated query in GQL is this one:

```gql
{
      allServices() {
        id
      }
}
```

But I got the following error:

```bash
{'errors': [{'message': 'Syntax Error GraphQL request (2:19) Expected Name, found )\n\n1: {\n2:       allServices() {\n                     ^\n3:         id\n', 'locations': [{'line': 2, 'column': 19}]}]}
```

Passing an empty object to the query resolves the issue:

```gql
{
      allServices(data: {}) {
        id
      }
}
```

However, this is not what I'm expecting.
I don't want the user to set an empty `data`: instead, I want the user to call allServices without params at all.

How can I do that?
What's missing?

**Comment by jkimbo** [comment]
@wilk your query should look like this:

```gql
{
      allServices {
        id
      }
}
```

Notice the lack of `()`

**Comment by wilk** [comment]
Yep, it was a GQL issue, my bad, sorry.

Thanks 💪 

I'm closing this issue.
