### ISSUE TITLE
Monitoring in Graphene Middleware

### ISSUE THREAD

**Issue by danpalmer** [graphql-python/graphene#792]
Apologies if this is a bit of a rookie question, but I'm unfamiliar with Graphene's middleware system and its reliance on promises, and attempting to make them play nicely with existing Python concepts.

I'd like to wrap Graphene operations with monitoring. What I'd like to do is something like...

```python
class MonitoringMiddleware(object):
    def resolve(self, next_, obj, info, **kwargs):
        with metrics.monitor():
            return next_(obj, info, **kwargs)
```

However, if I do this, I get unexpected or empty results. For example, our monitoring for number of database queries made is 0, even though data is returned. I think the reason for this is that the `next_` function resolves to a promise, so no work is actually done inside the `metrics.monitor` context manager.

I'd appreciate any help or feedback on how best to structure this. Is there anything simple that can be done here to wrap the execution of the promise – I need to do work before and after because it the monitoring needs to know initial and end states, and I also need to guarantee that the monitoring is called at the end to cleanup any mutated state.

The monitoring function is roughly:

```python
from contextlib import contextmanager

@contextmanager
def monitor():
    setup()
    try:
        yield
    finally:
        teardown()
```

Side note: I debated posting this on https://github.com/syrusakbary/promise, but decided to post it here as I think the solution might end up being a bit more tied to the middleware structure. Happy to repost on that repo if people think it appropriate.

**Comment by keeth** [comment]
@danpalmer did you figure out a solution to this?

**Comment by dvndrsn** [comment]
You can chain a function to be called after the promise by calling `result.next(callback_fn)`.

See the promise docs here: https://github.com/syrusakbary/promise/blob/master/README.md#promisethendid_fulfill-did_reject
