### ISSUE TITLE
AbstractType is deprecated but still in the documentaiton

### ISSUE THREAD

**Issue by alexpirine** [graphql-python/graphene#795]
Hi,

The documentation — http://docs.graphene-python.org/en/latest/types/abstracttypes/ — shows that you have to use `graphene.AbstractType` but this way of doing seems to be deprecated: https://github.com/graphql-python/graphene/blob/master/UPGRADE-v2.0.md#deprecations

Is the official documentation out-of-date?

Thanks

**Comment by jkimbo** [comment]
@manesioz @alexpirine https://github.com/graphql-python/graphene/pull/1053 should fix this.
