### ISSUE TITLE
ObjectType resolving fields from dicts or objects

### ISSUE THREAD

**Issue by ilyakitaev** [graphql-python/graphene#798]
Hi! There is an example code:

 
```
class Photo(graphene.ObjectTypet):
  
      id = graphene.ID()
      url = graphene.String()
      fileName = graphene.String()
      extension = graphene.String()
  
  
class User(graphene.ObjectTypet):
  
      _id = graphene.ID()
      name = graphene.String()
      photos = graphene.List(Photo)

class Query(graphene.ObjectType):
      user = graphene.Field(User, dict(_id=graphene.String(required=True)))
  
      async def resolve_user(self, info, _id):
          user = await db.users.find_one(dict(_id=_id))
          # do the simple filted
          resolved_fileds = {f: user[f]
                           for f in User._meta.fields}
          user = User(**resolved_fileds) if user else None
          return user
```
The result is

```
{
  "data": {
    "user": {
      "Id": "1",
      "name": "Test User",
      "photos": [
        {
          "id": null,
          "fileName": null
        }        
      ]
    }
  }
}
```

Field "photos" not initialized in __init__. In argument "photos" I got just list with dicts. I know  that I can to this serialization by myself, but maybe it's already implemented?

**Comment by jkimbo** [comment]
What does the `photos` field that you get back from `db.users.find_one(dict(_id=_id))` look like? By default Graphene uses `getattr` to pick off fields from a data object.

**Comment by ilyakitaev** [comment]
@jkimbo as I say it's a list of dicts. I can convert it to list of Photos() manually, but the question is there any already implemented way to fill ObjectType with nested fields from dictionary or I have to implement it by myself.

**Comment by jkimbo** [comment]
You could change the default resolver on the `Photo` Object type like this:

```python
from graphene.types.resolver import dict_resolver

class Photo(graphene.ObjectType):
	class Meta:
		default_resolver = dict_resolver
      
	id = graphene.ID()
    url = graphene.String()
    fileName = graphene.String()
    extension = graphene.String()

**Comment by ilyakitaev** [comment]
Thanks, @jkimbo. That's what I was looking for. I think that it would be in docs.

**Comment by jkimbo** [comment]
Also I have a PR #638 which should mean by default graphene would handle dicts and objects transparently

**Comment by saffrydaffry** [comment]
I'm surprised this wasn't in the docs, i'd spent so much unnecessary effort explicitly resolving dicts... please update the docs, this is an expected behavior of graphql.  thanks

**Comment by y0urself** [comment]
Is it correct, that the `class Meta:` "feature" is only for Python 2?

Is there any other workaround to set the `default_resolver` when using Python 3?
