### ISSUE TITLE
Errors upon execution

### ISSUE THREAD

**Issue by amitsaha** [graphql-python/graphene#80]
I see that when a query is executed via the ``execute()`` method, the result object has `errors` - a list of errors. My questions are:

- Why do we have a list of errors?
- If we must have a list of errors, is there any recommended way to report these to a HTTP client? a list of serialized messages?

**Comment by syrusakbary** [comment]
@amitsaha the errors field in the response is implemented following the `GraphQL` spec:
https://facebook.github.io/graphql/#sec-Errors

This field (`errors`) will be added if any exception occurs while processing the query (validation or field retrieving).

The errors will be written in the response as a field in the json, however you can always wrap the response checking if any errors and changing the HTTP status code accordingly.

**Comment by amitsaha** [comment]
@syrusakbary Thanks for your clarification. I am pondering how to best return the error messages in a single HTTP response, in case there is more than one.
