### ISSUE TITLE
Docs should be readable on small monitor at 200% zoom

### ISSUE THREAD

**Issue by thedailyshow** [graphql-python/graphene#800]
Ideally documentation should be readable at max zoom, but there are guidelines that indicate they should at least work well at 200% zoom.

Currently, on a 13" monitor, with 200% zoom, sidebar on left takes up lots of room, and even if scrolled horizontally, text goes off visible display.

I believe CSS should not have fixed width, but rather max width, and possibly sidebar should move from left when zoomed in. Consider also some may want to read documentation in browser with half of screen.

**Comment by syrusakbary** [comment]
This is a great suggestion. I would love to merge any PRs fixing this.

You can find in the repo https://github.com/graphql-python/graphene-python.org the necessary instructions to set the docs layout locally, and submit a PR once the fix is done :)
