### ISSUE TITLE
Is there anyway to do subquery?

### ISSUE THREAD

**Issue by xiaohanghang** [graphql-python/graphene#801]
e.g:
{
finduser{
   username
   email
   posts(title:"***"){
     title
     body
}
}
Your prompt reply will be much appreciated.Thanks！！！！

**Comment by tomateos** [comment]
Yes, just add it as an argument to the resolver

**Comment by xiaohanghang** [comment]
can you give a example？it will helpful

**Comment by tomateos** [comment]
Just define a new variable in your resolver and pass it in as a variable value when executing the query. This is a trivial example from the docs, but it should give you a good idea of how to create your resolver:
https://github.com/graphql-python/graphene/blob/master/docs/quickstart.rst#creating-a-basic-schema

**Comment by jkimbo** [comment]
@xiaohanghang did you resolve your issue?

**Comment by xiaohanghang** [comment]
yes. thanks发自我的华为手机-------- 原始邮件 --------主题：Re: [graphql-python/graphene] Is there anyway to do subquery? (#801)发件人：Jonathan Kim 收件人：graphql-python/graphene 抄送：hangzaizai <479135798@qq.com>,Mention @xiaohanghang did you resolve your issue?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/graphql-python/graphene","title":"graphql-python/graphene","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/graphql-python/graphene"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jkimbo in #801: @xiaohanghang did you resolve your issue?"}],"action":{"name":"View Issue","url":"https://github.com/graphql-python/graphene/issues/801#issuecomment-473532352"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/graphql-python/graphene/issues/801#issuecomment-473532352",
"url": "https://github.com/graphql-python/graphene/issues/801#issuecomment-473532352",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
