### ISSUE TITLE
Cannot Use Top-Level Fragment in Mutation

### ISSUE THREAD

**Issue by lgants** [graphql-python/graphene#805]
I'm unable to use fragments on the top-level of a mutation. I could be mistaken, but seems like a bug - I'm porting an working graphql schema from node.js into graphene (without relay). Anyone know if this is correct/desired behavior?

For example, the following mutation works:
```
fragment CommentInfo on Comment {
  id
  content
}

mutation addPost($input: AddPostInput!) {
  addPost(input: $input) {
    title
    content
    comments {
      ...CommentInfo
    }
  }
}
```

However, the following mutation doesn't:
```
fragment PostInfo on Post {
  id
  title
  content
}

mutation addPost($input: AddPostInput!) {
  addPost(input: $input) {
    ...PostInfo
  }
}
```

The failed mutation prints the following:
```
{
  "errors": [
    {
      "message": "Fragment PostInfo cannot be spread here as objects of type AddPost can never be of type Post",
      "locations": [
        {
          "line": 9,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by jkimbo** [comment]
@lgants sorry for not getting back to you sooner on this. Can you include the python code for your `addPost` mutation? It looks like the output of that mutation is not a `Post` type which is why your fragment is failing.

**Comment by jkimbo** [comment]
@lgants I'm going to close this issue since you haven't responded to it so I'm going to assume it's been resolved. If it is still an issue then please reply with more information and I'll reopen this.
