### ISSUE TITLE
Field description not defaulting to object docstring

### ISSUE THREAD

**Issue by charlesverdad** [graphql-python/graphene#809]
I'm using version `2.1.3` and whenever I create a field in my mutation or query, I have to manually pass on the description argument like so:

```py
class Mutation(graphene.ObjectType):
    create_user = CreateUser.Field(description=CreateUser.__doc__)
```
Otherwise, the description doesn't show up in GraphiQL. Is this the intended behavior? I was under the impression that the Field's description should automatically be set to the object's docstring.

For reference, the mutation is defined as:
```py
class CreateUser(graphene.Mutation):
    """Create a user given an email and [encrypted] password."""

    email = graphene.String()
    user_id = graphene.Int()

    class Arguments:
        email = graphene.String(required=True)
        password = graphene.String(required=True)

    def mutate(self, info, **fields):
        print(fields)
        user = User.objects.create_user(**fields)
        return CreateUser(
            email=user.email,
            password=password
        )
```

**Comment by shifqu** [comment]
I had the problem about the docs not being updated as well. Current workaround is to have the local graphiql bookmarked without any arguments. 
I **think** that when you run a query, the docs get cached, so by removing the `?query=` part of the url, you force graphiql to refetch the doc-strings.

**Comment by jkimbo** [comment]
@charlesverdad I think you're right but I don't have time to verify it right now. The place to fix it would be here: https://github.com/graphql-python/graphene/blob/c40ce98bb8a82a73d673e5d14bb5ccd2ccdfb1a6/graphene/types/mutation.py#L88

That line probably needs to become:

```python
description=description or cls.__doc__
```

Could you create a PR with the change and some tests to go along with it? There is also a `trim_docstring` utility function that you might find useful: https://github.com/graphql-python/graphene/blob/master/graphene/utils/trim_docstring.py

**Comment by jkimbo** [comment]
Closing since this is resolved now (thanks @cherls !)
