### ISSUE TITLE
Comparison issue for Enum

### ISSUE THREAD

**Issue by Fity** [graphql-python/graphene#811]
Since `Enum` use `is` operator to check equality, it will fail if the other value is not the same object as `Enum.value`.

Code:

```
from graphene import Enum

big_value = 99999999999999
big_string = 'hello' * 100


class MyEnum(Enum):
    TypeA = 99999999999999
    TypeB = 'hello' * 100

assert MyEnum.TypeA == big_value
assert MyEnum.TypeB == big_string
```

Expect result:
Everything works fine.

Result:

assertion failed for both.

**Comment by Fity** [comment]
@jkimbo  why not update `Enum.__eq__` function to use `==` for non-enum object values?
It is weird that `MyEnum.TypeA == small_value` works and `MyEnum.TypeB == big_value` not.
IMO, `graphene` should support these two cases or, just remove this feature and users should only use `MyEnum.TypeA.value`.

**Comment by jkimbo** [comment]
@Fity I think the graphene Enum follows the same behaviour as the Python Enum class (https://docs.python.org/3/library/enum.html#comparisons)

```python
from enum import Enum as PyEnum

big_value = 99999999999999
big_string = 'hello' * 100

class MyEnum(PyEnum):
	TypeA = 99999999999999
    TypeB = "hello" * 100

assert MyEnum.TypeA == big_value
assert MyEnum.TypeB == big_string
```

The assertions in the above code will also fail. I think it would be more confusing if the Graphene Enum didn't behave in a similar way to the Python Enum don't you agree?

Also I'm not sure what you mean when you say `MyEnum.TypeA == small_value` works? What is `small_value`?

**Comment by jkimbo** [comment]
Ah I didn't know about that. Thanks!
