### ISSUE TITLE
Commercial support?

### ISSUE THREAD

**Issue by leebenson** [graphql-python/graphene#813]
I love this lib - thanks so much for your hard work, @syrusakbary!

With that said, I'd happily contribute to paying for more of your time to extend Graphene, and fill in a few missing pieces that would make it more viable to use in production.

Namely:

- Error catching, per https://github.com/graphql-python/graphql-core/issues/177, and https://github.com/graphql-python/graphql-core/issues/202. System exceptions bubble up to user output by default, which a dangerous default IMO. I'd love to see a cleaner way of logging exceptions and controlling error output that could be defined in one place, rather than defensive `try/except` blocks in every mutation.

- Core improvements / re-factoring. Thread safety (#43), resolving promise issues (https://github.com/syrusakbary/promise/issues/57), moving to `async/await` per [your comment](https://github.com/graphql-python/graphene/issues/612#issuecomment-347066815), etc. There are a few core things that are beyond my immediate experience with how things work under the hood, that seem like they have some potential to throw weird/unexpected issues that are hard to diagnose.

- Documented subscription support/patterns, per #781.

- Docs synced with releases. There have been a few occasions where trying doc examples has thrown errors, such as #812 today or https://github.com/graphql-python/flask-graphql/issues/52 which I ran into a few days ago. When this happens, monkey-patched workarounds are usually suggested by the community, which makes for brittler code.

- Some more tooling to provide official solutions for #772, etc. Calculating the cost of queries, parsing the AST tree and preempting query joins that might be necessary, etc. Outside the purview of the core, perhaps, but necessary stuff at scale that would save devs reinventing the wheel.

- Closing issues faster. This is just a general thing, but there are issues going back 2-3 years that would be good to get unstuck. Much of it might even be redundant now or have other solutions, but clearing the backlog would make a clearer case for using the lib in production, knowing those same issues are unlikely to resurface.

Obviously, your time is valuable and the fact that you've put together _anything_ at all - let alone something as cool as Graphene - is amazing, so thank you.

But perhaps there's a way, as a community, we could buy more of your time to address some of the above? I'd happily chuck in a few bucks on the reg to keep this lib up-to-date.

**Comment by patrick91** [comment]
I'd love to support Graphene too, both with money and with my personal time, I'm not working much on Python right now, but I'm sure I will in future.

@syrusakbary what do you think of a Kickstarter campaign or, maybe, a patreon?

**Comment by syrusakbary** [comment]
Hi @leebenson , @patrick91.

Thanks a lot for chiming in for Commercial support, this is something I've been thinking for a while.
T might permit me to open-source (with license) Quiver, so more companies can have access to it.

As a way of organizing the different tiers for contributing into the project, I was thinking on doing similarly to [Vue.js in patreon](https://www.patreon.com/evanyou).
* **Backer**
  $10 or more per month
  Your name will be put in backers.md in the Graphene repository.
* **Generous Backer**
  $50 or more per month
  Your name will be put at the top of backers.md in the Graphene repository.
* **Bronze Sponsor**
  $100 or more per month
  Your name or company logo (small) will be put in backers.md in the Graphene repository.
* **Silver Sponsor**
  $250 or more per month
  Your name or company logo (medium) will be put at
  - the top of backers.md in the Graphene repository;
  - on a dedicated sponsors page on graphene-python.org.
* **Gold Sponsor**
  $500 or more per month
  A job post on every documentation page
  Your name or company logo (big) will be put at
  - The homepage of graphene-python.org; (50k+ impressions per month)
  - The top of the project repo's README. (~6k+ unique visitors per month)
* **Platinum Sponsor**
  $2,000 or more per month
  A job post on every documentation page
  Your name and company logo will be put on:
  - The top left of every documentation page on graphene-python.org
  - The homepage of graphene-python.org (at the top of the sponsors section)
  - The top of the project repo's README.

Thoughts?

**Comment by leebenson** [comment]
I think that's a great idea.

For me personally, it's not so much about the reward scheme/publicity link-back, as it is the time investment in features (although I'm sure other/bigger companies would be interested.)

If I knew that, say, 50 people paying $50/mo would yield 20 hours of dedicated focus each month and increased traction against bug reports/feature requests, I'd be very happy to contribute. It's specifically about the code, for me. I'd like to know the back-bone of my API server is being supported by someone with a commercial incentive to keep it going.

**Comment by codeocelot** [comment]
I love these ideas. A few more things that could be accomplished with sponsorship that could increase visibility and promote graphql in python: 

- Graphene's documentation can be fleshed out to make it more attractive to less-ambitious developers.  There's a fair bit of digging needed to get up and running with the current documentation.
- Increased support for authentication, security and establishment of reasonable best-practices to remove doubt and instill the confidence to drive adoption through to production.
- Support for community led initiatives, like developing ports for different python frameworks/servers ([like my beloved tornado!](https://github.com/dronedeploy/graphene-tornado/))
- Establish best practices in testing.  I think Python has all the tools to do this, we just need to document the best practices so testing becomes intuitive to newly onboarded developers.

I'm ready and able to pitch in and make contributions to make this a reality, because I really think GraphQL in python has a ton of potential for a thriving ecosystem.

**Comment by syrusakbary** [comment]
I'm working towards what we talked here 😊

These are the most recent changes:
* Added ROADMAP file in the project repo (and link it from the README)
  https://github.com/graphql-python/graphene/blob/master/ROADMAP.md
* Added TEAM page in Graphene website (so it's easier to see main contributors of the community)
  https://graphene-python.org/team/
* Added a support page in Graphene (is hidden right now, will be enabled once we are all happy with the current framework)
  https://graphene-python.org/support-graphene/
* Created Patreon page 
  https://www.patreon.com/syrusakbary

If you could visit the [Patreon page](https://www.patreon.com/syrusakbary), the [Graphene support page](https://graphene-python.org/support-graphene/) and write here your feedback, it would be highly appreciated!
@codeocelot @leebenson @patrick91 

*PS: I will update the ROADMAP with your suggestions towards specific issues / features you would like to see in the GraphQL Python community moving forward, so we make sure the funding will enable those*

**Comment by leebenson** [comment]
Thanks @syrusakbary. I've kick-started your Patreon with $50/mo. Once I get my current project off the ground and funding is a little less tihgt, I'll be happy to bump this up to a higher tier.

Hope you reach your goals!

**Comment by leebenson** [comment]
Can we help @syrusakbary drum up a bit more support?

This thread has a bunch of upvotes, but no additional contributions so far. Would be awesome if we could collectively buy a realistic chunk of time to devote to smashing through Syrus's to-do list.

**Comment by gotexis** [comment]
Hmmmmm....

**Comment by tobiasfeil** [comment]
Is Graphene dead?

**Comment by jkimbo** [comment]
@tobiasfeil no Graphene is not dead. There are still a few contributors maintaining the different projects under the graphql-python org. Unfortunately commercial support didn't pan out though.
