### ISSUE TITLE
Cannot deprecate variables in InputObjectType

### ISSUE THREAD

**Issue by mzins** [graphql-python/graphene#816]
Hi graphene community!

I am trying to deprecated input variables in my schema. I add the deprecated_reason tag to the variable but it does not appear to be deprecated in GraphiQL (still shows in the docs, autofill, and does not have a deprecation warning). Here is what I have

```
class NameArgs(InputObjectType):
    firstname = List(String, description="query by a list of first names")
    lastname = List( String, description="query by a list of last names" )

class PersonQuery(ObjectType):
    person = List(PersonType, input_args=NameArgs())
    
    def resolve_person( self, info, input_args ):
        return back_end_query(**input_args)
 
```

I am wanting to deprecate the first name field/variable. My understanding is I can just set the deprecation_reason tag and that is all. 

```
class NameArgs(InputObjectType):
    firstname = List(String, description="query by a list of first names")
    lastname = List( String, description="query by a list of last names",
                     deprecation_reason="last name is no longer supported by database")
```

However, the last name is not showing that it is deprecated. Is this a bug or am I not using the deprecation feature correctly?

Thank you!

**Comment by jkimbo** [comment]
It doesn't look like this is supported in the spec: https://github.com/facebook/graphql/issues/197

I'll close this issue for now but we can revisit it once the spec is updated.
