### ISSUE TITLE
Search by docs

### ISSUE THREAD

**Issue by alxpy** [graphql-python/graphene#818]
Hello! Could you please enable search by documentation?

**Comment by syrusakbary** [comment]
I'm working on this right now. Waiting for Algolia to approve the application for the docsearch application:

https://community.algolia.com/docsearch/

**Comment by syrusakbary** [comment]
Algolia just approved the application and docsearch is now live in all Graphene pages :)

<img width="1087" alt="screen shot 2018-09-06 at 12 06 46 pm" src="https://user-images.githubusercontent.com/188257/45151026-8609c780-b1cd-11e8-8213-691820a70853.png">

**Comment by alxpy** [comment]
thx!
