### ISSUE TITLE
Sharing result of one field as an input to another

### ISSUE THREAD

**Issue by dwiel** [graphql-python/graphene#82]
I've modified the toy example on the graphene playground to express the kind of thing I would like to be able to do.  I want to have fields which depend on the output of other fields (on that object as well as potentially other connected objects).  Right now I can make get the value for fields on a particular class by calling resolve_*() methods from within other resolve methods, but the result is not kept and so duplicate computation is done.  Is there a different way to do this that doesn't result in duplicate computation?  Is there a way to do this across object boundaries?  For example defining a field which depends on summing the values of a field of an object in a has_many relation?

http://graphene-python.org/playground/?schema=import%2520graphene%250A%250Aclass%2520Query(graphene.ObjectType)%253A%250A%2520%2520%2520%2520hello%2520%253D%2520graphene.String()%250A%2520%2520%2520%2520ping%2520%253D%2520graphene.String(to%253Dgraphene.String())%250A%250A%2520%2520%2520%2520def%2520resolve_hello(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520%27World%2520%257B%257D%27.format(id(self))%250A%250A%2520%2520%2520%2520def%2520resolve_ping(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520h%2520%253D%2520self.resolve_hello(args%252C%2520info)%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520%27Pinging%2520%257B%257D%2520%253A%2520%257B%257D%27.format(args.get(%27to%27)%252C%2520h)%250A%250Aschema%2520%253D%2520graphene.Schema(query%253DQuery)%250A&query=query%2520%257B%250A%2520%2520hello%250A%2520%2520ping(to%253A%2522Peter%2522)%250A%257D%250A

**Comment by Globegitter** [comment]
@dwiel 
That does of course depend on the actual use-case, but one way is to just group them together into an ObjectType and then you can have something as follows:

http://graphene-python.org/playground/?schema=import%2520graphene%250A%250Aclass%2520HelloPing(graphene.ObjectType)%253A%250A%2520%2520%2520%2520hello%2520%253D%2520graphene.String()%250A%2520%2520%2520%2520ping%2520%253D%2520graphene.String()%250A%250Aclass%2520Query(graphene.ObjectType)%253A%250A%2520%2520%2520%2520hello%2520%253D%2520graphene.String()%250A%2520%2520%2520%2520ping%2520%253D%2520graphene.String(to%253Dgraphene.String())%250A%2520%2520%2520%2520hello_ping%2520%253D%2520graphene.Field(HelloPing%252C%2520to%253Dgraphene.String())%250A%250A%2520%2520%2520%2520def%2520resolve_hello(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520%27World%2520%257B%257D%27.format(id(self))%250A%250A%2520%2520%2520%2520def%2520resolve_ping(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520h%2520%253D%2520self.resolve_hello(args%252C%2520info)%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520%27Pinging%2520%257B%257D%2520%253A%2520%257B%257D%27.format(args.get(%27to%27)%252C%2520h)%250A%2520%2520%2520%2520%250A%2520%2520%2520%2520def%2520resolve_hello_ping(self%252C%2520args%252C%2520info)%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520h%2520%253D%2520%27World%2520%257B%257D%27.format(id(self))%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520HelloPing(ping%253D%27Pinging%2520%257B%257D%2520%253A%2520%257B%257D%27.format(args.get(%27to%27)%252C%2520h)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520hello%253Dh)%250A%250Aschema%2520%253D%2520graphene.Schema(query%253DQuery)%250A&query=query%2520%257B%250A%2520%2520hello%250A%2520%2520ping(to%253A%2522Peter%2522)%250A%2520%2520helloPing(to%253A%2522Peter%2522)%2520%257B%250A%2520%2520%2520%2520hello%250A%2520%2520%2520%2520ping%250A%2520%2520%257D%250A%257D%250A

**Comment by dwiel** [comment]
The problem is that even with this solution, resolve_hello will be run 3 separate times.  This can be a problem if that function is slow or depended on by multiple other fields in the query.

**Comment by syrusakbary** [comment]
@dwiel if you wrap your fields with common attributes to a `ObjectType`, as @Globegitter suggested, the resolver for this `ObjectType` will be only called once.

So yes, resolving field would be called 3 times.

1. The parent resolver (`helloPing`)
2. The hello field in `HelloPing`
3. The ping field in `HelloPing`

However, as `GraphQL` (and `graphene` as well) is prepared to run the resolving fields asynchronously, this is how the nature of resolving queries should look like (as defined by the Spec, when querying we cannot assure that the fields would resolved in order, hence we cannot depend on other fields resolve value in the same type level).

**Comment by dwiel** [comment]
I see that makes sense.  Thanks for the detailed answer

**Comment by syrusakbary** [comment]
No problem! Closing the issue
