### ISSUE TITLE
Defining cross-references between objects

### ISSUE THREAD

**Issue by romaia** [graphql-python/graphene#828]
This is more of a question than a issue.

Suppose the following example:

```python
class Sale(ObjectType):
   pass

class SaleItem(ObjectType):
    sale = Field(Sale)
```

How can I proceed to add a new field on Sale that references SaleItem, like:

```python
class Sale(ObjectType):
    items = List(SaleItem)
```

**Comment by jkimbo** [comment]
@romaia you can lazily reference other types by using a lambda function like this:

```python
class Sale(ObjectType):
	items = List(lambda: SaleItem)

class SaleItem(ObjectType):
    sale = Field(Sale)
```

You can also specify a full import path as a string (like Django):

```python
# This file is api/definitions/sale.py
class Sale(ObjectType):
	items = List('api.definitions.sale.SaleItem')

class SaleItem(ObjectType):
    sale = Field(Sale)
```

**Comment by mikebobadilla** [comment]
@jkimbo Thanks so much. I came from JavaScript and completely forgot that arrow functions are just lambda functions 😛

**Comment by jkimbo** [comment]
You're welcome @mikebobadilla . Glad I could help!
