### ISSUE TITLE
Django: Make m2m through table fields available on edges

### ISSUE THREAD

**Issue by adamcharnock** [graphql-python/graphene#83]
When a `DjangoConnectionField` traverses a many-to-many field it would be nice to have the option to expose the fields of any through-table on the edges of the relationship.

[As much a note for myself as a feature request]

**Comment by syrusakbary** [comment]
Never thought about that but makes sense :+1:

**Comment by matclayton** [comment]
We'd also love to see this, an example of using m2m relationships would also be fantastic.

**Comment by adamcharnock** [comment]
@matclayton FWIW I'm currently treating the through table as simply another node. It makes the GraphQL somewhat nested, but it works for now.

**Comment by tom-zeit** [comment]
We would also like to see this feature :)

**Comment by jkimbo** [comment]
Hi @adamcharnock . We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 6 months) to try and clean up the issue tracker. If this is still important to you please comment and we'll re-open this.

Thanks!

**Comment by syrusakbary** [comment]
Reopening the issue as it might be useful to have

**Comment by McPo** [comment]
Is it possible to keep this on the radar? It would be a very nice feature (And its how I assume it would work)

**Comment by Eraldo** [comment]
@McPo  What would it take for graphene to automatically add the through model fields?

**Comment by Eraldo** [comment]
Any updates on this?
Still looking forward to automatic through edges. :)

**Comment by tony** [comment]
@syrusakbary Can you reopen and move this to a discussion?
