### ISSUE TITLE
Error : just first start

### ISSUE THREAD

**Issue by ParkDyel** [graphql-python/graphene#836]
cause wrong code.

try start graphene with flask( python 3.7 or 3.6)
but can't run with this error. what is wrong from me?
```
 File "C:\Users\blue\AppData\Local\Programs\Python\Python36\lib\site-packages\graphene\types\field.py", line 53, in __init__
    self.args = to_arguments(args or OrderedDict(), extra_args)
  File "C:\Users\blue\AppData\Local\Programs\Python\Python36\lib\site-packages\graphene\types\argument.py", line 41, in to_arguments
    extra_args = sorted(extra_args.items(), key=lambda f: f[1])
TypeError: '<' not supported between instances of 'String' and 'SubclassWithMeta_Meta
```

**Comment by jckw** [comment]
How did you solve this @ParkDyel?

**Comment by art1415926535** [comment]
> How did you solve this @ParkDyel?

Maybe you specify a class as an argument instead of an instance.

**Comment by jckw** [comment]
In my case I was using a custom field, so a work around was to just add a `__le__` method to that type, i.e.:

```
class MyCustomField(WhateverClass):
    ...

    def __lt__(self, other):
        return True
```

Not the best, but a quick workaround since it seems that Graphene isn't doing anything massively important with it.

**Comment by art1415926535** [comment]
In your case, maybe `WhateverClass` is not a subclass of `graphene.InputObjectType`.
