### ISSUE TITLE
What's the best way to do dependency injection?

### ISSUE THREAD

**Issue by robhobbes** [graphql-python/graphene#837]
It seems like it would be really useful to be able to pass in whatever database handle you want to the your Query class for example so that you can mock your database when writing tests.

I'm ignorant to the internals of the ObjectType class and what `Schema()` does when passed the query class, but it would be nice to be able to do something similar to:
```
class Query(graphene.ObjectType):
    person = graphene.Field(Person, person_id=graphene.Int())

    def __init__(db, *args, **kwargs):
    	super().__init__(*args, **kwargs)
    	self.db = db

db = get_database_handle()
query = Query(db)
return graphene.Schema(query=query)
```

Is there already a recommended way of doing this?

**Comment by johnnymetz** [comment]
I'm have the same question.

**Comment by ekampf** [comment]
Use the `context` - https://docs.graphene-python.org/en/latest/execution/execute/

**Comment by jkimbo** [comment]
@robhobbes @johnnymetz : @ekampf is correct. `context` is the way to inject data that each resolver can access.
