### ISSUE TITLE
Setting a schema name different than class name

### ISSUE THREAD

**Issue by zhammer** [graphql-python/graphene#839]
Is it possible to do something like:
```py
class MyGraphQlSong(graphene.ObjectType):
  __name__ = 'Song'

  id = graphene.String()
  artist = graphene.String()
  album = graphene.String()
```
So that `MyGraphQlSong` is created in the schema just as `Song`, such as:
```graphql
type Song {
  id: String
  artist: String
  album: String
}
```

**Comment by jkimbo** [comment]
@zhammer does that not work? I would expect it to work.

**Comment by zhammer** [comment]
Didn't work for me.

**Comment by zhammer** [comment]
Seems like this is where the name is set: `'_meta': <ObjectTypeOptions name='GraphQlSong'>,`

**Comment by helloqiu** [comment]
According to the source:
https://github.com/graphql-python/graphene/blob/master/graphene/types/base.py#L6
You can customize the type name like this:
``` python
class MyGraphQlSong(graphene.ObjectType):
  class Meta:
    name = 'Song'
```
@zhammer

**Comment by zhammer** [comment]
thanks @helloqiu. i'm going to try this out tomorrow when i have some time.

also thanks for linking this to #823. graphene is cool but is in dire need of improved documentation.
