### ISSUE TITLE
how can i get info arg from outside an executing query ..

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/graphene#840]
im storing object ids in a db model, and i would like to use get node method to get an instance of the object refrenced by that id as a class method to the model .. but that method requires an info arg ... how can i get that info arg ..  does the schema have such a method?

**Comment by jkimbo** [comment]
@japrogramer the `info` arg is part of the execution context and is created when the schema is executed. The object is defined here in graphql-core: https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/base.py#L66
