### ISSUE TITLE
Is there anyone use graphene and react-relay build a real app?

### ISSUE THREAD

**Issue by gwind** [graphql-python/graphene#85]
I'm working on build a app, tools:

- Backend

   - Tornado
   - SQLAlchemy
   - graphene

- Frontend

   - React/Relay

GraphQL used in Relay schema has restriction:
  
- [Relay Global Object Identification Specification](https://facebook.github.io/relay/graphql/objectidentification.htm)
- [GraphQL Relay Specification
Getting Started](https://facebook.github.io/relay/docs/graphql-relay-specification.html)

graphene have docs: [Walkthrough - Relay](http://graphene-python.org/docs/relay/)

there is a example and test:
- [starwars_relay examples](https://github.com/graphql-python/graphene/blob/master/examples/starwars_relay/schema.py)
- [test_mutation.py](https://github.com/graphql-python/graphene/blob/master/examples/starwars_relay/tests/test_mutation.py)

In client-side, relay sendMutation query like this:

```
{"query":"mutation Signin($input_0:SignInMutationInput!){signin(input:$input_0){clientMutationId}}","variables":{"input_0":{"username":"gwind","password":"ffffff","clientMutationId":"1"}}}
```

How to return a session object from a successful signin, since there is just a `clientMutationId` queried by client-side ? 

What's the relationship between `clientMutationId` and my object id?

Any help would be appriciate!
Thanks

**Comment by syrusakbary** [comment]
Hi @gwind, in the mutation in relay (in the client) you have to specify the output you want when you do the `signin` mutation ([example](https://github.com/graphql-python/graphene/blob/master/examples/starwars_relay/tests/test_mutation.py#L11-L25))

The `clientMutationId` output field is automatically added by relay, however you must add the data you want to get to.

Right now you seem to do something like that in the client
```graphql
mutation Signin {
    signin(input:$input_0)
}
```
when you should do:

```graphql
mutation Signin {
    signin(input:$input_0) {
        session {
             id
        }
    }
}
```

Or something like that... does that makes sense?

**Comment by gwind** [comment]
@syrusakbary , thanks for you fast reply!

In fact, I've submit a communication at `github.com/facebook/relay` - [How to get full mutation response?](https://github.com/facebook/relay/issues/166)

because relay has restriction itself, the default behavior can not execute a mutation like:

```
mutation Signin {
    signin(input:$input_0) {
        session {
             id
        }
    }
}
```

So, I've interest about `is there anyone use graphene and react-realy build a real app?`

Thanks again.

**Comment by syrusakbary** [comment]
@gwind as far as I know there are some companies playing with `graphene` for usage in production. And I have few projects too ;)
The main question should be directed to Relay, I guess... as the problems that could emerge by `graphene` are also in the principal `graphql-js` implementation.

**Comment by gwind** [comment]
@syrusakbary yes, Relay is base on GraphQL, but have restrictions extremely. May be it is in progress more than a product solution.

But I'm very like the GraphQL, Relay, React, it is a very important thing after REST. :smile:

**Comment by Globegitter** [comment]
@gwind We are using graphene + relay in our app that we'll release in closed beta by beginning of march.

**Comment by gwind** [comment]
@Globegitter :+1: 

I'm working on it. Although many issues with relay in practice, I'm love it so much!

**Comment by syrusakbary** [comment]
Closing this issue, please reopen if the same question arises.
