### ISSUE TITLE
[Q] How does a request for file upload look like ?

### ISSUE THREAD

**Issue by jakubczaplicki** [graphql-python/graphene#853]
I found the server-side code for handling image upload on https://github.com/graphql-python/graphene/blob/1b746e64609e4bc9d9baf880954415452b476812/docs/relay/mutations.rst

But how should the mutation request look like ?

**Comment by jakubczaplicki** [comment]
I'll reply myself:

* Python server code:

```
class UploadImage(graphene.Mutation):
    class Arguments(object):
        file = graphene.String(required=True)

    status = graphene.Boolean()

    def mutate(self, info, file):
        img = info.context.files[file].read()
        # more stuff
        return UploadImage(status=True)
```


* Curl request:

```
curl -X POST http://localhost:5001/graphql \
             -H 'content-type: multipart/form-data; boundary=----GraphQlFileUpload' \
             -F 'query=mutation {uploadImage(file: "photo") {status}}' \
             -F 'photo=@selfie.jpg'
```

**Comment by abdelhalimresu** [comment]
@jakubczaplicki  I think the request should respect the [Multipart Request Spec](https://github.com/jaydenseric/graphql-multipart-request-spec), because many client libraries use it for files upload.

**Comment by gt-novelt** [comment]
FYI, I opened an issue to ask for _multipart request spec_ implementation: #1052
