### ISSUE TITLE
schema_printer should include descriptions

### ISSUE THREAD

**Issue by avivey** [graphql-python/graphene#865]
The schema objcet `__str__` produces a nice SDL of the schema, but it should also include the description strings, because "Documentation is first‐class feature of GraphQL type systems" ([from the spec](https://facebook.github.io/graphql/June2018/#sec-Descriptions)).

**Comment by avivey** [comment]
oh, it's from an external lib. never mind.

**Comment by tony** [comment]
@avivey I would still be interested in having descriptions as an option, esp. when using graphql doc tools
