### ISSUE TITLE
Cannot add integral value to Timestamp without freq.

### ISSUE THREAD

**Issue by F-Chaudhry** [graphql-python/graphene#866]
I have a date column as `dtype('<M8[ns]')` which was converted from string type.
i want to add some number of days to this TIMESTAMP type.
doing something like this:
`data['dATE'].min()+6)` but getting the error

`Cannot add integral value to Timestamp without freq.`

how can i use arithmetic operation on date?

**Comment by jkimbo** [comment]
@F-Chaudhry this looks like an issue with datetimes and not a Graphene issue. I would recommend asking this question on StackOverflow.
