### ISSUE TITLE
Documentation for Dynamic? Examples of it with graphene.List?

### ISSUE THREAD

**Issue by tony** [graphql-python/graphene#871]
(Coming from https://github.com/graphql-python/graphene/issues/522#issuecomment-322322090)

I am having a difficult time getting `graphene.Dynamic` set up.

I'd submit something in more detailed - but to begin, I'm not sure if I'm using it the way it should be.

When using the example, I get `AttributeError: 'Dynamic' object has no attribute 'name'`.

What is the difference between `graphene.Dynamic` and passing a lambda?

(I'm happy to add tests / documentation, but I'm in a temporary position where I'm not sure if I'm reporting a feature request, bug, or a question)

**Comment by tony** [comment]
What I want to do: I want to see if I can resolve the type of a field when metaclass stuff is done. But, I'd like to have access to other object information for the parent type, and possibly the schema implementing it (lambda isn't enough in this case).

**Comment by jcockhren** [comment]
I came across this thread when trying to use Dynamic as well. From #725 it looks like Dynamic Fields are are only partially implemented.
