### ISSUE TITLE
Should every column be selected for calculating pagination?

### ISSUE THREAD

**Issue by ahokinson** [graphql-python/graphene#875]
Shouldn't the selected node elements be sent with the pagination request and not every column defined?

If this is not the expected behavior of GraphQL, can someone point me to the code that does pagination so that I may alter it within my own project? I'm not sure how the process of querying flows and could use some help. 

Thanks!

**Comment by dvndrsn** [comment]
@ahokinson - graphene provides `ConnectionField` to implement pagination using the relay compliant connection API.

There's a code sample here (tho its bare bones and might need a little elaboration):
https://docs.graphene-python.org/en/latest/relay/connection/

To page forward, we use `cursor` value from `pageInfo` or `edge` as `after` argument to the connection field and `first` as the pagesize in our query.

Here's an example query:
```
query connectionStuff($cursor: String, $pageSize: int) {
  posts(first: $pageSize, after: $cursor) {
    pageInfo { pageEnd hasNextPage }
    edges {
       cursor
       node {
         id
         title
       }
    }
}
```

**Comment by ahokinson** [comment]
When using a connection field, you do a count(*) on a subselection which includes every column in the table. That seems unnecessary. 

It's a particular issue for me because I am dealing with massive amounts of data using https://www.snowflake.com/. The metadata query for pagination details is actually super expensive in this situation because it has to move all the data just to get a row count. 

Would it not suffice to only use the node selections in the count?

**Comment by jkimbo** [comment]
@ahokinson you can pick apart and customise exactly how to get the page info by returning an instance of the `relay.Connection` type in the connection resolver. A `relay.Connection` is just an extended `ObjectType`. So for example (carrying on with @dvndrsn 's example):

```python
import graphene
from graphene import relay

class Post(graphene.ObjectType):
    id = graphene.ID()
    title = graphene.String()

class PostConnection(relay.Connection):
    class Meta:
        node = Post

class Query(graphene.ObjectType):
    posts = relay.Connection(PostConnection)

    def resolve_posts(_, info, **args):
        first = args.get('first')
        last = args.get('last')
        after = args.get('after')
        before = args.get('before')

        # Get relevant posts using the pagination info above
        posts = get_posts(first, last, after, before)

        edges = [
            PostConnection.Edge(
                node=node,
                cursor=cursor_string_from_node(node)
            )
            for node in edges
        ]

        total_length = get_posts_count()  # Here you can optimise how you get the count

        page_info = relay.PageInfo(
            has_next_page=(total_length > first),
            has_previous_page=False,  # This can be quite hard to determine so you can just ignore it
            start_cursor=edges[0].cursor,
            end_cursor=edges[-1].cursor,
        )

        return PostConnection(
            edges=edges,
            page_info=page_info,
        )
```

You'll have to build your own functions for `get_posts`, `get_posts_count` and `cursor_string_from_node` but that should mean that you can start optimising exactly how the connection gets the page info.

**Comment by jkimbo** [comment]
@ahokinson did my answer resolve your question?

**Comment by jkimbo** [comment]
@ahokinson I'm going to close this issue since there hasn't been any activity on it for a couple of months. Feel free to comment if this is still a problem and I'll reopen it.
