### ISSUE TITLE
CIText column in SQLAlchemy model not recognized

### ISSUE THREAD

**Issue by antoine-gallix** [graphql-python/graphene#876]
I want to create an ObjectType from one of my SQLAlchemy model (User) that contains a column (email) whose type in our database (Postgres) is CIText. Python Graphene doesn't know what to do with this type of column. Any idea how I can solve this?

My idea was that I could override the automatic creation of an ObjectType field from the SQLAlchemy model, and explicitely define the field as being a `graphene.String` type and manually define the resolver. But I can't figure out how to.

python-graphene error message: `Exception: Don't know how to convert the SQLAlchemy field user.email (<class 'sqlalchemy.sql.schema.Column'>)`

[Postgres doc on CIText](https://www.postgresql.org/docs/9.1/citext.html)
[python package for citext type: sqlalchemy-citext](https://pypi.org/project/sqlalchemy-citext/)

**Comment by jkimbo** [comment]
@antoine-gallix you might want to submit this issue to the [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy) repo. Otherwise if it's not specific to that library can you please include a way to reproduce the issue?

**Comment by antoine-gallix** [comment]
Thanks @jkimbo , that was it. I finally found the answer to my question in an example of the `readme` file of the `graphene-sqlalchemy` project. There is a system of include/exclude fields from the conversion from SQLAlchemy model to Graphene `ObjectType`. In [this example section](https://github.com/graphql-python/graphene-sqlalchemy#examples) it's written that one can do the following:

```python
class User(SQLAlchemyObjectType):
    class Meta:
        model = UserModel
        # only return specified fields
        only_fields = ("name",)
        # exclude specified fields
        exclude_fields = ("last_name",)
```
I think the main thing that blocked me from finding this was that it was not clear to me that the sqlalchemy integration was developed in another project and that there were some additional documentation to be found in the readme of the project, not in a static documentation page.
To avoid such issues in the future, my suggestion would be to link to this page from the python-graphene documentation to make that information more discoverable.

**Comment by jkimbo** [comment]
There is a link to the sqlalchemy project in the README: https://github.com/graphql-python/graphene#integrations

I'm not sure it can be much more prominent than that 🙂 Anyway I'm glad you solved your issue.
