### ISSUE TITLE
Does Graphene plan to create a client query tools?

### ISSUE THREAD

**Issue by gwind** [graphql-python/graphene#88]
Hi, guys

I'm working on a `python3/tornado/sqlalchemy/graphene + React + Graphql/Relay` solution.

Usually, we use js to run query/mutation on a backend GraphQL schema server.

But use python as client-side is usual. such as: 

```
query Root{
  account{...F0}
}
fragment F0 on AccountApi{
  group(id:"R3JvdXA6Mw=="){
    id
    name
  }
  me{
    lastName
    username
  }
}
```

the group id - `R3JvdXA6Mw==` can be replace by mako template, string format, ...
does graphene plan to supply a more nice query ?

example:

```python
from graphene.client import gq
q = gq(root='''
query Root{
  account
}
''')

f1 = q.fragment("AccountApi", '''
group(id:{group_id}){
    id
    name
  }
  me{
    lastName
    username
  }
''', group_id="R3JvdXA6Mw==")

print(f1.json())
```

**Comment by syrusakbary** [comment]
Thanks for asking about that.

A GraphQL Python client is planned in the roadmap, however we're waiting until Facebook isolates the Relay-core from Relay React so porting Relay-core client to Python will be quite easy.

**Comment by syrusakbary** [comment]
Going to close it until Facebook releases relay-core :)

**Comment by gwind** [comment]
:+1:

**Comment by syrusakbary** [comment]
@gwind Quick note, we released the `gql` package that intends to be a Python client for GraphQL servers. Now is super basic, but it's worth to take a look!
https://github.com/graphql-python/gql
