### ISSUE TITLE
Cannot pickle graphene.Enum 

### ISSUE THREAD

**Issue by kazhuravlev** [graphql-python/graphene#881]
# Environment

Mac OS

```bash
$ sw_vers -productVersion 
10.14

$ python -V
Python 3.6.3

$ python -c 'import graphene; print(graphene.__version__)'
2.1.3
```

# Reproduce

```python
import graphene
import pickle

class ExampleEnum(graphene.Enum):
    CAT = 1
    DOG = 2

print(pickle.dumps(ExampleEnum.CAT))
```

```
Traceback (most recent call last):
  File "/Users/exanpleuser/scratches/scratch.py", line 9, in <module>
    print(pickle.dumps(ExampleEnum.CAT))
_pickle.PicklingError: Can't pickle <enum 'EnumMeta'>: attribute lookup ExampleEnum on graphene.types.enum failed
```

# Expected

Pickle can perform `dumps` and `loads` on `graphene.Enum` objects

**Comment by avivey** [comment]
(I think #879 also makes this stuff work)

**Comment by senseysensor** [comment]
any fix for this...?

**Comment by senseysensor** [comment]
Don't have idea why this gets closed and won't be fixed,
however, fix is very small. This can be both fixed in library source code or if create enums using custom metaclass.

```
from graphene.types.enum import EnumMeta as GrEnumMeta
import graphene.types.enum


class MyMeta(GrEnumMeta):
    def __new__(cls, name_, bases, classdict, **options):
        obj = super().__new__(cls, name_, bases, classdict, **options)
        setattr(graphene.types.enum, name_, obj.__enum__)
        return obj


class MyEnum(GrEnum, metaclass=MyMeta):
    A = 'a'
    B = 1


gr_enum = MyEnum.B
pickled = pickle.dumps(gr_enum)
restored = pickle.loads(pickled)
assert type(gr_enum) is type(restored)
assert gr_enum == restored
```

**Comment by erikwrede** [comment]
@senseysensor nice fix, if you send in a PR including tests I can review & test 🙂

**Comment by senseysensor** [comment]
Sorry, unfortunately that solution above appeared to have some limitations. In order `pickle.dumps()` works fine with such approach, declared Enum names in runtime must be unique, otherwise pickle fails with another error. It's easy to submit similar fix for library code (my first commit in PR), at least that will resolve part of cases (which in case of our project will be acceptable).
