### ISSUE TITLE
Supporting remote schemas

### ISSUE THREAD

**Issue by DrPyser** [graphql-python/graphene#882]
Hi. 

Is there any plan to support some way of linking multiple schemas together, such as referring to types defined in another schema(potentially remote, network accessible)? For example, in apollo server: https://www.apollographql.com/docs/apollo-server/features/remote-schemas.html.

There are two paradigm I can see for this:
* "Importing"(i.e. reconstructing) the external schema, via an introspection query.
  * https://www.prisma.io/blog/how-do-graphql-remote-schemas-work-7118237c89d7
* Using some kind of "proxy" type to refer to types defined in another schema, given the type name and remote endpoint URL. Introspection queries could either resolve dynamically, always querying the remote schema, or only querying it once and storing the result with the proxy types.

For the second approach, [linked data and json-ld](https://json-ld.org/) comes to mind, where types from different schemas can be used, by specifying the namespace where those types are defined, as URLs from where the actual type definitions(schemas) can be retrieved.

I wouldn't mind working on implementing some of this myself, but it seems graphene lacks a documented extension api, which makes this task difficult. Any advice of what to subclass and which methods to implement would be welcomed.

Thanks!

**Comment by jkimbo** [comment]
@DrPyser there aren't any plans at the moment as far as I'm aware. I would be interested to see any solution that you come up with though!

**Comment by nikordaris** [comment]
Personally, I'd like to see graphene support Apollo Federation. That would be really powerful to be able to integrate into that

**Comment by DrPyser** [comment]
Yup, this seems like a perfectly sensible approach.
At a highlevel

- [ ] Support "importing" schemas from other apis(by using introspection query to reconstruct the schema)
- [ ] Support creating "extension" types that represent entities from defined in remote schemas, potentially defining additional fields. A set of fields has to be declared as a key that can be used to resolve matching entities across schemas.
- [ ] Support creating a federated schema by providing urls to graphql apis, as well as local schema objects.

**Comment by nikordaris** [comment]
So I started looking at Apollo Federation spec and it seems pretty straight forward to implement. All you really need to do is define some directives and a couple root queries that will inspect your schema for the Federation Gateway. The question is what should that API look like in graphene for registering and resolving entities.
