### ISSUE TITLE
Integrating different data sources

### ISSUE THREAD

**Issue by chirag-shah1** [graphql-python/graphene#885]
Is there anyway to query data from different sources in a single query?
Suppose I've Mysql and Elastic, how can i create a single resolver to get the data from both sources in a single query?

**Comment by jkimbo** [comment]
@chirag-shah1 yes definitely! Graphene (and a core part of and GraphQL server) is that it is agnostic to where the data underlying each field lives and how it is fetched. So for example say we have the following schema:

```
type Post {
	title: String!
	content: String!
	relatedPosts: [Post]
}

type Query {
	searchPosts(searchTerm: String!): [Post]
}
```

and say that to search for posts you are using Elasticsearch but the actual posts are stored in Mysql with Django. You could build your server like this:

```python
import graphene

from blog.models import Post as DjangoPost  # your Django model

class Post(graphene.ObjectType):
	title = graphene.String(required=True)
	content = graphene.String(required=True)
	date_published = graphene.DateTime(required=True)
	related_posts = graphene.List(Posts)
	
	def resolve_related_posts(post, info):
		related_posts = get_related_posts(post.id)  # Query Elasticsearch for related posts
		return related_posts

class Query(graphene.ObjectType):
	search_posts = graphene.List(Post, search_term=graphene.String(required=True))

	def resolve_search_posts(_, info, search_term):
		relevant_posts = find_posts(search_term)  # Get all the relevant posts from Elasticsearch
		post_ids = [post['id'] for post in relevant_posts]
		posts = DjangoPost.objects.filter(id__in=post_ids)
		return posts
```

As you can see the graphql server is querying multiple data sources and even combining multiple data sources into one to satisfy a client query.

Hope that helps!
