### ISSUE TITLE
What structure does the info object have?

### ISSUE THREAD

**Issue by hannes-petri-maxiv-lu-se** [graphql-python/graphene#889]
Is there any documentation on what the info object that's passed to each resolver function actually contains? Various examples indicate that I can expect the properties "context" and "field_name" to be present, but that's the only thing I can find.

**Comment by ktosiek** [comment]
I haven't seen any documentation on that, but it's an instance of `ResolveInfo`: https://github.com/graphql-python/graphql-core/blob/v2.1.0/graphql/execution/base.py#L66

**Comment by ProjectCheshire** [comment]
@hannes-petri-maxiv-lu-se You can find the ResolveInfo object at https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/base.py
