### ISSUE TITLE
Is there any way to name field on the ObjectTypes keyword?

### ISSUE THREAD

**Issue by nkg168** [graphql-python/graphene#894]
I want to define Type as follows.
```
type Edge {
  from: Int
  to: Int
}
```

But,Python give me a syntax error because `from` is keyword
```
class Edge(graphene.ObjectType):
    from = graphene.Int()
    to = graphene.Int()
```

Can't I define this Type?

**Comment by jkimbo** [comment]
@nkjmr you can use the `name` attribute to override the name of the field. So:

```python
class Edge(graphene.ObjectType):
    _from = graphene.Int(name='from')
    to = graphene.Int()
```

**Comment by nkg168** [comment]
@jkimbo that works as expected. Thanks a lot.
