### ISSUE TITLE
How to access a parameter of one resolver in another?

### ISSUE THREAD

**Issue by pawarchinmay27** [graphql-python/graphene#897]
```python
class Product(graphene.ObjectType):
	productName=graphene.String()
	productDependecies=graphene.List(ProductDependency)


'''
I wish to access the instanceName here in this class How Can I do it 
'''

class Instance(graphene.ObjectType):
	instanceName=graphene.String()
	products=graphene.List(Product)
	
	def resolve_products(self,info):
    	#some code that follows

```

**Comment by jkimbo** [comment]
@pawarchinmay27 can you provide a more complete example of what you are trying to do?

**Comment by pawarchinmay27** [comment]
@jkimbo I have a use case where instance will have a list of products 
 I want to access the instanceName property of the class Instance in the product class.
The Instance class has the resolve method for products I 
the structure is more like this
```
instance123:{
     products:['abc','def']
}
```

**Comment by jkimbo** [comment]
So the output of the resolve method is passed to the next level down in the tree and it can be of any shape as long as the next level understands it. So in your case you can do:

```python
class Instance(graphene.ObjectType):
	products = graphene.List(Product)
	
	def resolve_products(instance, info):
		# instance looks like:
		# {
		#   'products': ['abc', 'def'],
		#   'name': 'Instance name',
		# }
    	return [
			{
				'productName': product,
				'instanceName': instance['name'],
			} for product in instance['products']
		]


class Product(graphene.ObjectType):
	productName=graphene.String()
	productDependecies=graphene.List(ProductDependency)

	def resolve_productDependencies(product, info):
		instance_name = product['instanceName']
```

**Comment by pawarchinmay27** [comment]
@jkimbo 

```
class Instance(graphene.ObjectType):
	products = graphene.List(Product)
	instanceName=graphene.String()
	def resolve_products(instance, info):
    	  return [Product(productName,[ProductDependency()])]


class Product(graphene.ObjectType):
	productName=graphene.String()
	productDependecies=graphene.List(ProductDependency)

	def resolve_productDependencies(product, info):
		instance_name = product['instanceName']
                print(instance_name)
```

I tried with this approach and got an error message **'Product' object is not subscriptable**

**Comment by jkimbo** [comment]
@pawarchinmay27 it would help if you could give me a way to reproduce your error. Also did you try and use the code that I suggested? Did it not work?

**Comment by pawarchinmay27** [comment]
```
class Product(graphene.ObjectType):
	productName=graphene.String()
	productDependencies=graphene.List(ProductDependency)
	def resolve_productDeproductDependencies(self,info):
		print(self['instanceName'])


class Instance(graphene.ObjectType):
	instanceName=graphene.String()
	products=graphene.List(Product)
	def resolve_products():
		return [Product("xyz")]

	

```


@jkimbo  this is the code I tried and ended up getting that 'Product' object is not subscriptable

**Comment by pawarchinmay27** [comment]
@jkimbo  could you help with this

**Comment by jkimbo** [comment]
@pawarchinmay27 you're returning a `Product` object at the end of your `resolve_products` function. That object is then being passed as the `self` parameter to the `resolve_productDeproductDependencies` function and so when you try and print `self['instanceName']` it's not working because `self` is an object and not a dict. You can change the code to:

```python
	def resolve_productDeproductDependencies(self,info):
		print(self.instanceName)
```

To debug issues like this I would recommend using something like [pdbpp](https://pypi.org/project/pdbpp/) to debug what values you are getting in the resolver function.

Also in future it would help if you could provide a full working example of your issue (maybe in the form of a github repo) or just try the solution that I provided to you first.
