### ISSUE TITLE
Extend root response object

### ISSUE THREAD

**Issue by sebastiandev** [graphql-python/graphene#901]
@syrusakbary We are currently implementing a public API and we need to return some metadata for the whole request (like request id, user quota, etc).

We have implemented in a way we use a base object type for every query and mutation output, but when multiple operations are triggered the metadata would be duplicated.

Is there a way to extend the root response, so we could add our custom metadata in there, instead of as fields on every operation output type?

**Comment by sebastiandev** [comment]
While implementing this approach for error handling I have also found an issue when resolving the error field. I have a base class that extends `ObjectType` by iterating over the resolvers and wrapping them to n catch any errors and setting an `errors` dict in the `info.context`.
Problem is that when resolving a type field that throws an exception, I do catch it and set the error, but the error field was already processed/resolved.  Is there a way to force a particular field to be processed at the end or to force it to update? I need to make sure every resolver runs before the error field is resolver so I make sure all errors are caught.

```python
class BaseObjectType(graphene.ObjectType):

    class Meta:
        abstract = True

    @classmethod
    def __init_subclass_with_meta__(
        cls,
        interfaces=(),
        possible_types=(),
        default_resolver=None,
        _meta=None,
        **options
    ):
        super().__init_subclass_with_meta__(
            interfaces, possible_types, default_resolver, _meta, **options)

        for f in cls._meta.fields:
            if f in ['errors']:
                continue

            resolver_name = "resolve_{}".format(f)
            if hasattr(cls, resolver_name):
                setattr(cls, resolver_name, catch_errors(getattr(cls, resolver_name)))


class BaseResponse(BaseObjectType):

    class Meta:
        abstract = True

    errors = graphene.String()

    @staticmethod
    def resolve_errors(root, info, **kwargs):
        operation_name = info.path[0]
        error_key = f"{operation_name}_errors"
   
        if not root.errors and error_key in info.context.errors:
            root.errors = ",".join(info.context.errors[error_key])

        return root.errors
```

**Comment by norman-thomas** [comment]
Would inheriting from `graphene.ObjectType` and using the inherited class as parent for all others not solve the issue?

i.e.

```python
class ObjectWithQuota(graphene.ObjectType):
    quota = graphene.Int()

    def resolve_quota(self, info):
        remaining_quota = determine_quota(...)
        return remaining_quota

class Message(ObjectWithQuota):
    pass  # TODO fields and resolvers
```

All `Message` objects would then have the `quota` field with a default implementation of how to calculate it.

**Comment by sebastiandev** [comment]
Yeah I already did that, but if the users make more than one query for example, quota would be present on both query results. I was thinking about something that is at a higher level, like the `errors` and `data` fields from the response payload.

**Comment by ekampf** [comment]
@sebastiandev the [GraphQL spec](https://graphql.github.io/graphql-spec/June2018/#sec-Response-Format) allows adding an `extensions` key to the response to return metadata:

> The response map may also contain an entry with key extensions. This entry, if set, must have a map > as its value. This entry is reserved for implementors to extend the protocol however they see fit, and > hence there are no additional restrictions on its contents.

You can see vendors, like [Apollo Tracing](https://github.com/apollographql/apollo-tracing) using this:
```
{
  "data": <>,
  "errors": <>,
  "extensions": {
    "tracing": {
        ... tracing data ...
     }
   }
}
```

I think the best way to do what you're asking is to collect all the data throughout the GraphQL execution step and then add it to the response.
When you execute a GraphQL query you can provide a custom `context` object (usually a `dict` but can be whatever you want) that'll be available to all resolvers as `info.context`.
You can use the context object to collect data, then after the query finished executing add it to the response as an extension.

**Comment by reubenosborne1** [comment]
@ekampf I have been looking everywhere for an explaination on this. So thank you! Glad I found this thread. How do I "add it to the response as an extension"?
