### ISSUE TITLE
mutate_and_get_payload method does not resolve Node ID

### ISSUE THREAD

**Issue by arielnmz** [graphql-python/graphene#908]
# Steps to reproduce

1. Create a simple type implementing the `Node` interface
2. Create a mutation for said type that subclasses `relay.ClientIDMutation`
3. Inspect the `**kwargs` of the `mutate_and_get_payload` method

# Expected results

That the `client_mutation_id` param contains the resolved ID of the node rather than the global ID, i.e. if the provided global ID is `TXlUeXBlOjEK` (`MyType:1`), then `client_mutation_id` should contain the value `1` (as happens with the `get_node` method of the type)

# Actual results

`client_mutation_id` contains the provided Node ID, i.e. `TXlUeXBlOjEK` (`MyType:1`) instead of `1`

Python 3.7.2, Graphene 2.1.3

**Comment by episodeyang** [comment]
@patrick91 @dan98765 Can someone comment on this issue? We can create a PR if this indeed is considered something that we want.

**Comment by arielnmz** [comment]
After doing some research I learned that that field's actual purpose is so the client can keep track of the mutations it sends to the backend (i.e. for Apollo or similar), that's why it's a `String` and not an ID or GlobalID, so perhaps it is indeed desired behaviour. Anyway, you still have to manually  add an ID field to the input (and resolve it afterwards) if your goal is to mutate an object referenced by a `GlobalID`, maybe the problem is that I expected a bit more from `ClientIDMutation`s, so I came up with a crude solution in the form of Mixins and some helper functons to make them a bit more useful. Maybe I can create a PR when I'm done with this sprint, or at least link to a gist...

**Comment by episodeyang** [comment]
yeah that's right! Was just about to post too.

Spec file see: https://facebook.github.io/relay/graphql/mutations.htm
