### ISSUE TITLE
How can I test a InputObjectType class?

### ISSUE THREAD

**Issue by claradaia** [graphql-python/graphene#917]
Hello,

Is there a way to test the validation of input with InputObjectType classes?

I come from Django with DRF and with serializers I was able to test validation logic instantiating the serializer class with my data and calling the `is_valid` method:

```
data = {
    'some': 'data',
    'more': 'data'
}
self.assertTrue(MySerializer(data=data).is_valid())
```

I expected the InputObjectType class to have something like that, but I could not find it.
I saw #600 and understand custom validation logic should be done in a property method (which I could then call in the test), but right now I'm looking at **basic schema validation** such as missing required fields or unexpected fields.

(I also looked at #556 and tried using that particular way of instantiating the class, but found nothing useful. Looking at the source code for the InputObjectType base class did not help either.)

This is important to me because my data structure is somewhat complex, with embedded documents that have their own embedded documents, all of them associated with InputObjectType classes. The whole thing is created at once, and the input can get pretty big. I would rather not have to write a full valid input for each test if I'm only testing the validation of a small portion of it.

**Comment by jkimbo** [comment]
@claradaia unfortunately it doesn't look like this is possible. Graphene delegates the actual validation part to the graphql-core and I'm not sure exactly where the validation happens. I'll do some more digging but I'm pretty sure at the moment what you're asking for is not possible.

One workaround would be to test the schema with your input type to check if it works. For example:

```python
from mytypes import MyInputType  # <- this is the input type you want to test

class TestMutation(graphene.Mutation):
    class Arguments:
        input = MyInputType()

    ok = graphene.Boolean()

    def mutate(root, info, **args):
        return TestMutation(ok=True)

class TestQuery(graphene.ObjectType):
    name = graphene.String(default_value="Dave")

class MyMutations(graphene.ObjectType):
    input_type_test = TestMutation.Field()

schema = graphene.Schema(query=TestQuery, mutation=MyMutations)

def test_input_type():
	query_string = """
    mutation testMutate($input: MyInputType!) {
        inputTypeTest(input: $input) {
            ok
        }
    }
    """

    result = schema.execute(query_string, variables={
		'input': {
			'some': 'data',
			'more': 'data',
		}
	})

    assert not result.errors
```

You can probably abstract most of that code into a test helper.

**Comment by claradaia** [comment]
Thank you, @jkimbo, I will try that.

**Comment by tahakhan0** [comment]
You could write type asserts if you're using something such as

```python
class SomeMutation(graphene.relay.ClientIDMutation):
    class Input:
           some_input = graphene.Field(types.MyinputType)
           some_reference = graphene.String()


assert SomeMutation.Input.some_reference._meta.name == "String"

# Note: Mounting it as a field allows us to access it's type.
assert SomeMutation.Input.some_input.type._meta.name == "MyInputType"
```
