### ISSUE TITLE
Media path for files

### ISSUE THREAD

**Issue by michelecocuccio** [graphql-python/graphene#918]
Hello everyone.
I am not expert with Python and I am just trying to do everything myself as our backend developer is sick at the moment. I successfully setup Graphene and everything works fine, I am using graphQL from my React app with success. Although I noticed that the files have now lost the /media/ path that was previously set in the urls.py file. 

This is what I have now

```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # The following are for GraphQL
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```
but it doesn't work. How can I have my Media files to be prefixes with /media/ as it was before?

Thanks

**Comment by jkimbo** [comment]
@michelecocuccio this issue doesn't seem related to graphene. Are you sure that adding the path for `graphql/` is the reason your static assets are missing the `/media/` path?
