### ISSUE TITLE
[docs] Code overflows the parent container

### ISSUE THREAD

**Issue by shaminmeerankutty** [graphql-python/graphene#924]
In documentation page https://docs.graphene-python.org/en/latest/types/enums/
code overflows the parent container and causes horizontal scrolling. 

![image](https://user-images.githubusercontent.com/8272719/54694334-15fdd600-4b4e-11e9-907d-efcf493b65b2.png)

Caused by the long code in `Usage with Python Enums` section
https://docs.graphene-python.org/en/latest/types/enums/#usage-with-python-enums

**Comment by ekampf** [comment]
Fixed
