### ISSUE TITLE
Async DataLoader

### ISSUE THREAD

**Issue by jamesstidard** [graphql-python/graphene#926]
Hi,

I have a async database connection and am using async/await syntax to query the database. I was wondering if it's possible to use the DataLoader with async.

I've been able to do async resolve functions, however I've not been able to do it with the DataLoader subclasses. I don't know if this is because it's not supported or if I've done something wrong.

I get this error when I make the `batch_load_fn` async:

```
Traceback (most recent call last):
  File ".../python3.7/site-packages/promise/promise.py", line 842, in handle_future_result
    resolve(future.result())
  File ".../query.py", line 11, in resolve
    return info.context.request.app.dataloaders[cls].load(uuid)
  File ".../python3.7/site-packages/promise/dataloader.py", line 97, in load
    cached_promise = self._promise_cache.get(cache_key)
graphql.error.located_error.GraphQLLocatedError: 'RedisLoader' object has no attribute '_promise_cache'
```

Thanks

**Comment by dan98765** [comment]
Have you checked out https://github.com/syrusakbary/aiodataloader ? I wonder if it takes care of the cache in an asyncio context.

**Comment by jamesstidard** [comment]
@dan98765 oh great, looks very promising. I didn't even think of a third party library as thought it would be too tightly coupled with the framework.

I'll check this out, cheers.

**Comment by dvndrsn** [comment]
@dan98765 I wonder if this library should be brought under the `graphql-python` umbrella along with `promise` (for non-async DataLoaders). Both libraries' primary use case is with GraphQL, as far as I know.

**Comment by dan98765** [comment]
@dvndrsn I think that makes a lot of sense, @syrusakbary what do you think? (Syrus is the owner of that repo, so he'll have to make the decision).
