### ISSUE TITLE
Fetching the schema from client?

### ISSUE THREAD

**Issue by BramKaashoek** [graphql-python/graphene#929]
I would like to use interfaces. In order to properly save the fetched data to the store in my apollo client, my client will need to query some schema information. I'm trying to fetch the schema as described on https://www.apollographql.com/docs/react/advanced/fragments#fragment-matcher, but this method of fetching the schema does not seem to be supported. 

Any advice on how to get the required information?

I'm using the script as provided:

```
const fetch = require('node-fetch');
const fs = require('fs');

fetch(`http://localhost:8000/graphql`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    variables: {},
    query: `
      {
        __schema {
          types {
            kind
            name
            possibleTypes {
              name
            }
          }
        }
      }
    `,
  }),
})
  .then(result => result.json())
  .then(result => {
    // here we're filtering out any type information unrelated to unions or interfaces
    const filteredData = result.data.__schema.types.filter(
      type => type.possibleTypes !== null,
    );
    result.data.__schema.types = filteredData;
    fs.writeFile('./fragmentTypes.json', JSON.stringify(result.data), err => {
      if (err) {
        console.error('Error writing fragmentTypes file', err);
      } else {
        console.log('Fragment types successfully extracted!');
      }
    });
  });
```

gives me `{"__schema":{"types":[]}}`

So there is no specific error, but my types are empty.

**Comment by jkimbo** [comment]
@BramKaashoek introspecting the schema is supported out of the box with Graphene so the guide you've linked to should work. Can you provide any error messages that you are seeing when you try and introspect the schema?

**Comment by BramKaashoek** [comment]
Turns out I'm an idiot and forgot to build my changes introducing the interfaces before fetching the schema. Now I have `{"__schema":{"types":[{"kind":"INTERFACE","name":"Lot","possibleTypes":[{"name":"OwnLot"},{"name":"NotOwnLot"}]}]}}`, which is exactly what I would expect. Sorry for wasting your time.

**Comment by jkimbo** [comment]
No worries, glad you fixed the issue!
