### ISSUE TITLE
Support deprecation

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#93]
It seems that deprecation of fields is not supported either in graphene or graphql-core. It seems to be explained here: https://github.com/facebook/graphql/blob/d8a52f1fb70a61ceb13dd49292b74b58d894a074/spec/Section%204%20--%20Introspection.md#deprecation

I would expect to be able to use it as follows:

```py
class User(relay.Node):
    billing_address = graphene.String(
        isDeprecated=True,
        deprecationReason='Selecting your billing address is not supported anymore',
        description='Selected billing address.')
```

**Comment by jhgg** [comment]
This is already supported in core. Just pass a `deprecation_reason` to the underlying `GraphQLField`. 
There is no `is_deprecated` as a non-null value for `deprecation_reason` implies `is_deprecated ` for the purpose of schema introspection.

**Comment by Globegitter** [comment]
Ok will have a look - thanks for the quick response :)

**Comment by syrusakbary** [comment]
@Globegitter You can now use `graphene.String(..., deprecation_reason='Deprecated since 1.0')` :wink:

**Comment by Globegitter** [comment]
@syrusakbary Thank you for the quick turnaround :)
