### ISSUE TITLE
How to have URL redirection

### ISSUE THREAD

**Issue by subokita** [graphql-python/graphene#931]
How can one have URL redirection inside a mutation code?
Here's a sample of my code
```
from sanic import response

class CreateSample( Mutation ):
    class Arguments:
        input = SampleInputType()

    Output = SampleSchema

    async def mutate( self, info, input ):
        return response.redirect( 'https://www.google.com' )
```

what happens is that it will always try to return the Output type, thus trying to wrapped whatever being returned from response.redirect with SampleSchema instance.

Is it even possible to have an URL redirection within a GraphQL mutation?

**Comment by ekampf** [comment]
You're not supposed to have redirections in GraphQL because GraphQL is not tied to HTTP (and should always return status `200` according to spec)
If you want to tell the client to redirect somewhere tell it in the mutation response.
```
class CreateSample(graphene.Mutation):
    class Arguments:
        foo = graphene.String()

    ok = graphene.Boolean()
    sample = graphene.Field(lambda: Person) 
    next_url = graphene.String()

    def mutate(self, info, foo):
        sample = Sample(foo=foo)
        ok = True
        return CreateSample(sample=person, ok=ok, next_url="... whatever ...")
```
