### ISSUE TITLE
Int range correction per graphql spec

### ISSUE THREAD

**Issue by crawfordleeds** [graphql-python/graphene#933]
The docs currently state that the scalar Int can represent values between -2^53-1 and 2^53, as seen [here](https://docs.graphene-python.org/en/latest/types/scalars/).

This seems to conflict with my experience and the [graphql docs](https://graphql.org/learn/schema/) which state Int is a signed 32-bit integer. 

I may be missing something with the graphene implementation, but I have been unable to use Int's greater than 32-bit. 

Would appreciate feedback on if this is an issue on my end or if it's a documentation issue. If indeed it is a documentation issue I'm happy to make PR. Cheers!

**Comment by ProjectCheshire** [comment]
@crawfordleeds we merged a pr regarding that but are having some issues getting the docs to properly update
https://github.com/graphql-python/graphene/pull/891/files

**Comment by crawfordleeds** [comment]
Sorry about that, didn't notice it. Thanks!
