### ISSUE TITLE
Incompatibility with Python 2.7 version

### ISSUE THREAD

**Issue by sulabhjain** [graphql-python/graphene#936]
https://github.com/graphql-python/graphene/blob/7b6dae7fa3bf8d2e066e92e730c8a9740656a448/graphene/types/uuid.py#L15

This fails occasionally on python 2.7, most likely pointed by my colleague due to it sending uuid in unicode string. 

Suggested fix:
import six
and then replace if condition
 if isinstance(uuid, six.string_types):

**Comment by ekampf** [comment]
Fixed
