### ISSUE TITLE
Authorization in Django

### ISSUE THREAD

**Issue by defrex** [graphql-python/graphene#94]
Graphene has been amazing to use so far. Great work.

By default it seems to make all data available to everyone, which I can't go to production with for obvious reasons. There are really two things I'd like. They may already be possible, I just don't see how from the documentation.

**Queryset Filtering**
I'd love to be able to access the `request` object and a queryset at the same time to I can limit the data returned that way. For example, something like this.

```Python
class PostNode(DjangoNode):
    class Meta:
        model = Post
    
    @classmethod
    def get_queryset(Cls, request):
        return Post.objects.filter(owner=request.user)
```

**Limiting Field Access**
Every field on the model is exposed by default. There are lots of docs on adding filters, but I'm not sure how to whitelist the fields returned. I'd love something like this.

```Python
class PostNode(DjangoNode):
    class Meta:
        model = Post
        fields = ('title', 'description', 'created')
```

**Comment by gwind** [comment]
Use `only_fields`   -  [code](https://github.com/graphql-python/graphene/blob/master/graphene/contrib/django/types.py#L17-L32)

```python
class PostNode(DjangoNode):
    class Meta:
        model = Post
        only_fields = ('title', 'description', 'created')
```

**Comment by syrusakbary** [comment]
For limiting field access you can use @gwind suggestion.
About filtering depending on the context, is quite easy:

```python
class PostNode(DjangoNode):
    class Meta:
        model = Post
        only_fields = ('title', 'description', 'created')

class Query(graphene.ObjectType):
    posts = PostNode.List() # You can also use DjangoConnectionField(PostNode)
    resolve_posts(self, args, info):
        # If you are using graphql-django-view, the request_context is the Django request
        request = info.request_context
        return Post.objects.filter(owner=request.user)
```

Hope it helps!

**Comment by syrusakbary** [comment]
Feel free to reopen if any question! ;)

**Comment by defrex** [comment]
Thanks for the help!

**Comment by bradreardon** [comment]
Hi @syrusakbary, I'm either mistaken or the docs on this are out of date. It appears that even when using `graphql-django-view`, `request_context` is not an attribute passed on the `info` parameter of resolve functions.

Am I doing something wrong? Perhaps you could help me out here. It seems the documentation on this is pretty vague. Thanks!

**Comment by jameswyse** [comment]
@bradreardon I had the same issue, it seems to be a recent change. Try using the `with_context` decorator:

```python
from graphene.utils import with_context

@with_context
def resolve_current_user(self, args, context, info):
    if context.user.is_authenticated:
        return context.user
```

**Comment by syrusakbary** [comment]
@bradreardon the example @jameswyse pointed should solve the problem.
When `with_context` was released in `graphene` `v.0.9.0` it was not documented at all, so was easy to run into this problem.
We solved this with better documentation. But let me know if you run into more issues.
