### ISSUE TITLE
What is to good way to manage large queries with pytest and graphene test client?

### ISSUE THREAD

**Issue by anudeepsamaiya** [graphql-python/graphene#942]
Should this queries be defined as pytest fixtures?
Or should this be stored in seperate text files, and then be read inside the test function?

The reason to ask this is because, test functions gets very big if queries are defined inside the function?

Please express your opinions on which of the three is better approach.

**Comment by ekampf** [comment]
Whatever you find most comfortable working with.
Personally I usually inline my GraphQLs...
