### ISSUE TITLE
Dynamically generate graphene object types

### ISSUE THREAD

**Issue by arindam04** [graphql-python/graphene#945]
I am looking for example of how to generate graphene.ObjectType or relay.Node/Connection subclasses dynamically instead of having to define a type statically? Something along the lines of how we can use GraphQLObjectType(name=, fields=,) Basically I have some data from which I need to construct my class hierarchy types rather than defining them apriori. Currently graphql-core lets be create classes using meta types, like below. I am looking for graphene/relay way of doing it
 timeseries = GraphQLObjectType("Timeseries", OrderedDict([("date", GraphQLField(GraphQLString, resolver=resolvers.generic_resolver('date'))),
                                                  ("reportDate", GraphQLField(GraphQLString, resolver=resolvers.generic_resolver('reportDate'))),
                                                  ("value", GraphQLField(GraphQLFloat, resolver=resolvers.generic_resolver('value')))
                                                  ]))

Can someone provide an example?

**Comment by dsanders11** [comment]
If anyone has a better way I'd love to hear it, but this is how I've been accomplishing this:

```python
timeseries = type('timeseries', (graphene.ObjectType,), {
    'date': graphene.String(resolver=resolvers.generic_resolver('date')),
    'report_date': graphene.String(resolver=resolvers.generic_resolver('reportDate')),
    'value': graphene.Float(resolver=resolvers.generic_resolver('value'))
})
```

**Comment by ekampf** [comment]
@arindam04 @dsanders11 it sounds to me like `graphene` is too high level for your needs and you're actually better off using its underlying [graphql-core](https://github.com/graphql-python/graphql-core) library.

Your time series would look something like this:
```
schema = GraphQLSchema(
  query= GraphQLObjectType(
    name='RootQueryType',
    fields={
      'timeseries': GraphQLField(
        type= GraphQLObjectType(
            name='TimeSeriesType',
            field={
              'date': GraphQLString(...),
              ...
            }
        ),
        resolver=lambda *_: 'world'
      )
    }
  )
)
```

**Comment by dsanders11** [comment]
@ekampf, thanks for the example. Unfortunately I still need the `graphene-django` integration, and the scalars implemented in `graphene` (like `DateTime`), etc. While not idea, the meta programming lets me retain access to those features while dynamically creating schema.

**Comment by arindam04** [comment]
@ekampf , thanks for the graphql-core example. I am also trying to use graphene for its conveniences like relay integration & dataloader and simplified syntax and hence wanted to get a way to create these objects on the fly.
