### ISSUE TITLE
Execute without case convertions

### ISSUE THREAD

**Issue by yardensachs** [graphql-python/graphene#948]
I am trying to execute a query without having the result be turned into camel case and enums turn into upper case. I was able to write a utility for keys conversion back to snake case, but that I can't do the same for enums, since I would not know what is an enum and what is not.

Is there a way to execute a query without getting those case conversions string? (This would be just for some queries, not for all)
Another options is somehow feeding the query result to some case "restorer", but I looked into the code and could not find a good example of that.

**Comment by ekampf** [comment]
@yardensachs when you create your `Schema` object its constructor accepts `auto_camelcase` which is `True` by default by you can change it to `False`.

**Comment by changeling** [comment]
@yardensachs, You can simply use aliases in your query, by prefixing elements with your preferred key followed by a colon. For example:

Query:
```
{
  allPlaces{
    id:pkId
    date
    date_sort:dateSort
    parent_place:parentPlaceId
    name
  }
}
```

Result:
```
{
  "data": {
    "allPlaces": [
      {
        "id": 2,
        "date": null,
        "date_sort": null,
        "parent_place": null,
        "name": "Mobile, Mobile, Alabama, United States"
      },
      {
        "id": 580,
        "date": null,
        "date_sort": null,
        "parent_place": null,
        "name": "Skowhegan, Somerset, Maine, United States"
      }
    ]
  }
}
```

Is this what you're looking for?

**Comment by yardensachs** [comment]
Did not look for that, but we decided to go another way.

**Comment by japrogramer** [comment]
> @yardensachs when you create your `Schema` object its constructor accepts `auto_camelcase` which is `True` by default by you can change it to `False`.

Im trying to create a schema were some of my fields are camel case and others aren't.
Is there a way to hint that the field should not be auto camel cased on a field by field or type by type bases?
