### ISSUE TITLE
Need to support JOIN like logic in GraphQL

### ISSUE THREAD

**Issue by ethe** [graphql-python/graphene#949]
For example, if I want to get all users' role of each user group, then I need a query maybe like this:
```
{
  groups {
    userRole(group: $groups.id) {
      user_id
      roles
    }
  }
}
```

In current, there is no way to get parent node attribute in child node.

**Comment by ekampf** [comment]
@ethe  your query should be:
```
{
  groups {
    userRole {
      user_id
      roles
    }
  }
}
```

By definition the `userRole` resolver is called for each relevant group (the resolver is *in the Group* object):
```
class UserRole(ObjectType)
  ...

class Group(ObjectType):
  user_roles = List(UserRole)

  def resolve_user_role(self, info):
    group_id = self.id
    user_role = ... fetch user role using group_id ...
    return user_role

class Query(ObjectType):
  groups = List(Group)
  
  def resolve_groups(self, info):
    groups = ... fetch groups from somewhere ...
    return groups
```

**Comment by ekampf** [comment]
Also, you seem to be including relational DB schema in your GraphQL structure rather than making it about the data you really want to represent.
Your ideal structure seems to be:
```
{
  groups {
    roles {
      id
      name
    }
  }
}
```
The fact that you have a UserRole table somewhere that connects groups to roles is an implementation detail the caller doesn't care about

**Comment by ethe** [comment]
@ekampf  I think it is not a good resolution, yeah, if there are only dual nodes We can use defining resolve_user_role in group query class. But if there are more than triple nodes, and want to get root nodes attribute in leaf node, it doesn't work I think.
