### ISSUE TITLE
FilterSet typed filter input

### ISSUE THREAD

**Issue by Eraldo** [graphql-python/graphene#958]
Currently I am very happy with the django-filter integration: https://docs.graphene-python.org/projects/django/en/latest/filtering/

I am especially making good use of "Custom Filtersets".
However the docs only show how to use `django_filters.CharFilter`.
I am wondering how I can make it so that my gql expects a custom type instead of a string filter input.

So far, I found `get_filtering_args_from_filterset` method and suspect that is the place to hook/register my filter type into somehow.

Did I miss how to do it? Any instructions/examples/ideas/pointers?

**Comment by Eraldo** [comment]
Found it! :)

For future people running into this:
```python
@convert_form_field.register(CustomFormField)
def convert_form_field_to_string(field):
    return CustomType(description=field.help_text, required=field.required)
```

**Comment by rcrogers** [comment]
Here's a complete example of registering custom types (in this case a Graphene enum used in conjunction with a multiple-choice field):
```
class EnumMultipleChoiceField(MultipleChoiceField):
    def __init__(self, enum, **kwargs):
        choices = [(e.name, e.name) for e in enum]
        self.graphene_enum = graphene.Enum(enum.__name__, choices)
        super().__init__(choices=choices, **kwargs)


@convert_form_field.register(EnumMultipleChoiceField)
def convert_field_to_graphene_type(field):
    return graphene.List(field.graphene_enum)


class EnumMultipleChoiceFilter(MultipleChoiceFilter):
    field_class = EnumMultipleChoiceField

    def __init__(self, enum, **kwargs):
        super().__init__(enum=enum, **kwargs)

        
class MyModelFilter(FilterSet):
    foo = EnumMultipleChoiceFilter(Enum("AnEnumObject", [("A", "A"), ("B", "B"), ("C", "C")]))
