### ISSUE TITLE
Nested Mutations

### ISSUE THREAD

**Issue by Rafik-Belkadi** [graphql-python/graphene#964]
Hi everyone,

im facing a problem where i have nested mutations, i want to execute  a mutation like this : 

``` 
mutation {
    createUser(input: {
        firstname : "test"
        product : createProduct(input...)
    }    
    )
}
```

**Comment by ekampf** [comment]
There's no way to do this in GraphQL. You'd have to execute it as 2 separate calls or code a mutation that does both.
