### ISSUE TITLE
Issue installing dependencies (promise)

### ISSUE THREAD

**Issue by SioKCronin** [graphql-python/graphene#965]
Hi there,

I'm trying to deploy a Graphene/Flask API on AWS ElasticBeanstalk, and am getting the following build error from the dependency `promise`'s setup:

```
  Downloading/unpacking promise>=2.1,<3 (from graphene==2.1.3->-r /var/app/requirements.txt (line 16))
    Downloading promise-2.2.1.tar.gz
    Running setup.py (path:/var/app/build/promise/setup.py) egg_info for package promise
      error in promise setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
      Complete output from command python setup.py egg_info:
      error in promise setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```
Has anyone else found a way around this?

I thought perhaps this might have to do with the edit I found on [#72](https://github.com/syrusakbary/promise/pull/72) (Promise PR)

**Comment by SioKCronin** [comment]
Resolved. Issue was EB defaulting to Python 3.4 for package installs. Specified 3.6 which fixed it.

**Comment by MesquitaEngineer** [comment]
Sorry, I dont understand EB. What's it?
