### ISSUE TITLE
Exposing Mypy-compatible type information

### ISSUE THREAD

**Issue by ktosiek** [graphql-python/graphene#966]
I'd like to use Mypy for checking a Graphene-based app. Is anyone working on stubs, or even better - a Mypy plugin?

What I imagine is writing:
```
class Me(ObjectType[User]):
    full_name = graphene.String()
    def resolve_full_name(self, info):
        return self.get_full_name()
```

And getting a guarantee that User.get_full_name() returns something assignable to Optional[String].

**Comment by ktosiek** [comment]
Looks like this might not be possible - `Plugin.get_function_hook` can override the type of full_name, and `Plugin.get_subclass_hook` can look at types of actual methods, but I haven't found a way to make those two communicate.

An approach closer to https://github.com/graphql-python/graphene/issues/729#issuecomment-457988621 seems to make more sense - this way everything to know about a resolver lives in one place.

**Comment by dvndrsn** [comment]
From my understanding, much (if not all) of the Graphene and graphql-core codebase is type hinted with Python 2.7 style annotations, but all of the user generated types have attributes through some metaprogramming, which can be a challenge to generate stubs for. There's a mypy issue here discussing a similar topic:

https://github.com/python/mypy/issues/1310

**Comment by ktosiek** [comment]
Those type hints are not exported, see [this PEP-561 section](https://www.python.org/dev/peps/pep-0561/#packaging-type-information). And as you've noted, they don't cover that much of user's code.

For the metaprogramming part a plugin would be needed. I've looked into it, but I'm not sure how to tie field declarations with types of resolvers (maybe we'll need a new mypy hook?).

**Comment by ckarnell** [comment]
Hi all, I created a repo for stubs for this library and wrote a plugin for it to match resolver function definitions to their corresponding `Field` attributes. Feel free to use / file issues / contribute!

https://github.com/trialspark/graphene-stubs/pulls

**Comment by PureTryOut** [comment]
That packages hasn't seen an update since March 2020, only 2 months after it was announced here. It would be great if mypy itself can export type hints, can this issue be re-opened?

**Comment by ryanovas** [comment]
Would also like to see this re-opened

**Comment by lotusmana** [comment]
Bump.  This is still a problem.
