### ISSUE TITLE
Standardize relay element import statements in the documentation.

### ISSUE THREAD

**Issue by changeling** [graphql-python/graphene#967]
There should be some consistency in documentation across the ecosystem here regarding `import` statements for `relay` elements. Either `from graphene.relay import`, to highlight that they are, in fact, `relay`-related, or `from graphene import` works, but there is confusion among users and IMHO it gives a bit of a sloppy perception/introduction to the libraries.

On a personal note, I took unnecessary time tracking down the references with the uncertainty that the code base might have diverged during this transitionary period and resulted in two groups of definitions. Not a lot of time, of course, but not needed, and with an uncomfortable feeling about the code consistency.

Given that the primary `relay` components are imported in `graphene/__init__.py` with `from .relay import (Node, is_node, GlobalID, ClientIDMutation, Connection, ConnectionField, PageInfo)`, personally I'd suggest using the `from graphene import Node` syntax as canon, but the consistency is the big thing here. As mentioned, I had some confusion myself, and I see the question arise with others.

For an example, see: https://stackoverflow.com/questions/56117612/what-is-the-difference-between-graphene-node-and-graphene-relay-node

**Comment by dvndrsn** [comment]
This is a great idea. I think the Relay support in Graphene is awesome, but understanding what it is and how to use it needs improvement.
