### ISSUE TITLE
Docs: Burger menu not working

### ISSUE THREAD

**Issue by joshprice** [graphql-python/graphene#97]
Burger menu not opening on site http://graphene-python.org/, tried in Chrome, Safari, Firefox, Mobile Safari.

The `translate3d(-100%,... )` inline style isn't changed/removed even though the `isOpen` state of the is correct.

I noticed when debugging in Chrome that the inline styles had `-webkit-` prefixes applied but couldn't see why, so suspecting an interaction with another library perhaps.

**Comment by syrusakbary** [comment]
Thanks for pointing this out!
Probably this could be fixed by using a newer version of `react-burger-menu`.
