### ISSUE TITLE
Drop python 2.x in 3.x

### ISSUE THREAD

**Issue by dulmandakh** [graphql-python/graphene#972]
I think graphene should drop python 2.x support in 3.x release, and it's unnecessary to maintain compatibility. https://github.com/graphql-python/graphene/blob/master/ROADMAP.md

**Comment by iashraful** [comment]
Totally agreed at this point. :)

**Comment by ekampf** [comment]
That's the goal we agreed on. We'll update the roadmap document very soon
FYI @mvanlonden

**Comment by ProjectCheshire** [comment]
This is resolved in master/next.
