### ISSUE TITLE
Circular ObjectType reference requires full path

### ISSUE THREAD

**Issue by mfrlin** [graphql-python/graphene#974]
Opening new issue because I can't reopen the old one.

> Hi @imranolas,
> 
> You can achieve this by using String references (ala Django):
> 
> ```python
> # category_type.py
> @schema.register
> class Category(graphene.ObjectType):
>     Post = graphene.List('Post')
> 
> # post_type.py
> @schema.register
> class Post(graphene.ObjectType):
>     category = graphene.Field('Category')
> ```

This does not work anymore. Just tested like this:

```
class Webhook(ModelObjectType):
  triggered_by = graphene.Field('WebhookEventType')

class WebhookEventType(ModelObjectType):
  ...
```

This raises ImportError from here: https://github.com/graphql-python/graphene/blame/master/graphene/utils/module_loading.py#L39

If I change string to `mymodule.WebhookEventType` then it works but this is not ideal.

_Originally posted by @mfrlin in https://github.com/graphql-python/graphene/issues/110#issuecomment-494761345_

**Comment by waxisien** [comment]
It may be a regression, but you could also achieve this by using `lambda`:

```
@schema.register
class Category(graphene.ObjectType):
    Post = graphene.List(lambda: Post)

# post_type.py
@schema.register
class Post(graphene.ObjectType):
    category = graphene.Field(lambda: Category)
```

**Comment by japrogramer** [comment]
I agree that the string type shouldn't have to be the full path.
reason, the types should be unique so .. problem shouldn't be.

**Comment by yakovlevkll** [comment]
Not elegant but working solution (in case of one-to-many relation)

```python
# api/models/post.py
import graphene

from api.models import category

class Post(graphene.ObjectType):

    category = graphene.Field(
        lambda: category.Category,
        description='Category associated with the post'
    )
```

```python
# api/models/category.py
import graphene

from api.models import post

class Category(graphene.ObjectType):

    posts = graphene.List(
        lambda: post.Post,
        description='Posts associated with the category'
    )
```
