### ISSUE TITLE
JSONString return backslashes

### ISSUE THREAD

**Issue by dhelbegor** [graphql-python/graphene#976]
I'm trying to use graphene JSONString to query/mutate a django jsonfield, but in the both cases I receive/send this: 
```
{
  "data": {
    "TitleType": [
      {
        "id": "1",
        "name": "My First Title",
        "fields": "{\"a\": \"b\"}"
      }
    ]
  }
}
```

can you guys tell me how can I avoid the backslashes in both cases?

**Comment by ekampf** [comment]
You can't avoid backlashes because that how JSON strings look.
According to JSON spec, JSON values have to use double quotes - "
So if you have a JSON value inside a a string value that's in a JSON, you cant use the inner " chars will break the outer JSON, you have to backslash them.

An alternative would be to use `GenericScalar` instead of `JSONString`. In that case your value will be returned as a JSON object and not a string, like this:
```
{
  "data": {
    "TitleType": [
      {
        "id": "1",
        "name": "My First Title",
        "fields": {"a": "b"}
      }
    ]
  }
}
```

**Comment by ekampf** [comment]
`from graphene.types.generic import GenericScalar`

**Comment by dhelbegor** [comment]
Thank you very much @ekampf

**Comment by dhelbegor** [comment]
in my mutation I'm getting this error, do you know why?
`{
  "errors": [
    {
      "message": "Syntax Error GraphQL (5:7) Expected Name, found String \"a\"\n\n4:     fields: {\n5:       \"a\": \"b\"\n         ^\n6:     }\n",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ]
    }
  ]
}`

my mutation:
`mutation{
  lastroTypeCreate(
    name: "My First Title",
    fields: {"a": "b"}
  ) {
    id
    name
    fields
  }
}`

**Comment by changeling** [comment]
Can you post your schema? For one thing, your syntax is incorrect.

I _believe_ you want to do something like, but this is off-the-cuff:

```
 mutation{
  lastroTypeCreate( name: "My First Title", fields: ["a", "b"] ) {
    id
    name
    fields
  }
}
```

**Comment by EliasOPrado2** [comment]
This is how you can implement GenericScalar().

Basically you have to get the field that is JSONString() (that is a JSONField) in django model and switch to GenericScalar to make it normal JSON again. Very simple.

```python
class ApplicantPersonalDataSchema(DjangoObjectType):

    # the JSONField that needs to be threated.
    address = GenericScalar()
    class Meta:
        model = ApplicantPersonalData
        interfaces = (Node,)
        fields = [
            "id",
            "applicant_id",
            "name",
            "document_type",
            "document_code",
            "address",
            "marital_status",
        ]
```
