### ISSUE TITLE
Bad hyperlink on documentation

### ISSUE THREAD

**Issue by Ambro17** [graphql-python/graphene#978]
NonNull reference under required field from this page https://docs.graphene-python.org/en/latest/types/scalars/ redirects to an inexistent page, namely: 
`https://docs.graphene-python.org/en/latest/types/scalars/list-and-nonnull/#nonnull`
The correct link is
`https://docs.graphene-python.org/en/latest/types/list-and-nonnull/#nonnull`

**Comment by ekampf** [comment]
Can you PR it?

**Comment by Ambro17** [comment]
Inspecting the element with chrome debugger i see that the href points to
 `./list-and-nonnull.html#nonnull` with `/types/scalars/` as working directory.

Changing it to `../list-and-nonnull.html#nonnull` makes the link works as expected, resolving to `https://docs.graphene-python.org/en/latest/types/list-and-nonnull/#nonnull`

Strangely, what works for the online version (double dot) doesn't resolve locally. And viceversa, single dot works locally with make docs but fails on the page.. 
I've opened a pr for you to check this behaviour #980
