### ISSUE TITLE
Example for UnionType

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#98]
We have just been trying to use `UnionType` but with very little success, all throwing some error message that is hard to identify/debug.

This is a simplified example of what we have been trying, using the latest version `0.7.0`:

```py
from graphene.core.classtypes.uniontype import UnionType
from graphene import ObjectType, String, Field, Schema

class Human(ObjectType):
    some_field = String()
    other_field = String()

class Pet(ObjectType):
    yet_another_field = String()

class Thing(UnionType):
    '''Thing union description'''
    class Meta:
        types = [Human, Pet]

class Query(ObjectType):
    thing = Field(Thing)

    def resolve_thing(self, args, info):
        return Thing(some_field='test') # or Human(some_field='test')

schema = graphene.Schema(query=Query)
```

There are a few more variations that we have tried as well, but didn't work. So how does a full example of using `UnionType` look like?

CC @imranolas

**Comment by syrusakbary** [comment]
@Globegitter You can use the way you mentioned, or using inheritance:

```python
    class Human(ObjectType):
        name = String()

    class Pet(ObjectType):
        name = String()

    class Thing(Human, Pet):
        '''Thing union description'''
        my_attr = True
```
Example taken from [the objecttype tests](https://github.com/graphql-python/graphene/blob/master/graphene/core/classtypes/tests/test_objecttype.py#L81)

However I feel this current approach (the one I wrote) is not the best one so I was thinking about deprecating taking the following:

```python
class Thing(Union(Human, Pet)):
    '''Thing union description'''
```

PS: the one you mentioned that would be still valid.

Thoughts?

**Comment by imranolas** [comment]
@syrusakbary: Any chance you could release these changes?

**Comment by syrusakbary** [comment]
@imranolas Sure! A new version will be pushed to PyPI soon! :)

**Comment by syrusakbary** [comment]
Just published a new version to PyPI with this fix and other features 
`pip install graphene==0.7.1`

Release notes: https://github.com/graphql-python/graphene/releases/tag/v0.7.1

**Comment by alex-wilmer** [comment]
Hi, I wasn't able to figure this out from the docs... does it even currently address union types? Do I need to include `from graphene.core.classtypes.uniontype import UnionType`?
