### ISSUE TITLE
Mutation argument `interfaces` does not work

### ISSUE THREAD

**Issue by dvndrsn** [graphql-python/graphene#994]
Mutations implement the same options as ObjectType (because they create ObjectType under the hood), but using `interfaces` meta argument does not have the expected effect of applying the GraphQL Interfaces to the Mutation Payload ObjectType.

Mutation should be able to apply `interfaces` Meta argument to have the payload object type implement the desired interfaces.

See this thread for more discussion:

_Originally posted by @jkimbo in https://github.com/graphql-python/graphene/pull/971_

**Comment by Nta1e** [comment]
I will take this on @dvndrsn
