### ISSUE TITLE
Data lake hadoop HDFS connection examples?

### ISSUE THREAD

**Issue by scheung38** [graphql-python/graphene#997]
"Data agnostic: Graphene supports any kind of data source: SQL (Django, SQLAlchemy), NoSQL, custom Python objects, etc. We believe that by providing a complete API you could plug Graphene anywhere your data lives and make your data available through GraphQL."

Anyone worked with Hadoop HDFS as I have a data lake that I want to use GraphQL to query from. thanks

**Comment by dvndrsn** [comment]
Hi @scheung38, thanks for your question!

I've not worked with Hadoop HDFS with Graphene, but it seems like it would be a simple to perform some kind of method call to fetch data from HDFS when resolving the field. You would need to use some kind of Python-based library to fetch data from HDFS, parse it and return it to the Graphene Schema.

As your schema grows, it may be necessary to consider other patterns like DataLoader to batch requests to HDFS, but this should be enough to get you started.

```
from graphene import ObjectType, String, Field, ID


def get_person_from_hdfs(id):
  person = ... # do HDFS things here to fetch data by ID
  # person is data in the shape {'first_name': 'Bob', 'last_name': 'Burgers'}
  return person

class Person(ObjectType):
  first_name = String()
  last_name = String()

class Query(ObjectType):
  person = Field(Person, id=ID())
  
  def resolve_person(root, info, id):
    return get_person_from_hdfs(id) 
```
