### ISSUE TITLE
Add GraphiQL Explorer to default instance on GraphiQL

### ISSUE THREAD

**Issue by three60five** [graphql-python/graphene#998]
GraphiQL is one of the tools that make the developer experience of GraphQL so great. The GraphiQL Explorer package takes the developer experience to another level. It allows users to visually build GraphQL queries. They just released a [2.0 version](https://www.onegraph.com/blog/2019/05/30/GraphiQL_Explorer_2_0_A_Power_User_Release.html). It has been incorporated into many projects including Apollo Client devtools, Hasura, PostGraphile, etc.

Github:
https://github.com/OneGraph/graphiql-explorer

See the demo here:
https://www.onegraph.com/graphiql

It would be a great improvement to the graphene project to incorporate GraphiQL Explorer into the default instance of GraphiQL.

**Comment by Cito** [comment]
I agree that it would be nice to have the latest version. But GraphiQL support is added by the server middleware, i.e. a concern of projects like Graphene-Django, not of Graphene itself. You should post the issue there. Maybe also request that other tools such as Playground and Voyager are added as well :)
